### ISSUE TITLE
Error in NavigationView implemented with Fragment

### ISSUE THREAD

**Issue by gmorenope** [mapbox/mapbox-navigation-android#1001]
Hi, I'm testing the app and I get this error with  NavigationView implemented with Fragment option. 
Thank you for your help!

E/AndroidRuntime: FATAL EXCEPTION: main
                  android.content.res.Resources$NotFoundException: File res/drawable/ic_arrow_head.xml from drawable resource ID #0x7f0800b0. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
                      at android.content.res.Resources.loadDrawable(Resources.java:2842)
                      at android.content.res.Resources.getDrawable(Resources.java:1521)
                      at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:360)
                      at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addArrowHeadIcon(NavigationMapRoute.java:516)
                      at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.initializeUpcomingManeuverArrow(NavigationMapRoute.java:479)
                      at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.initialize(NavigationMapRoute.java:861)
                      at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:264)
                      at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:239)
                      at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.initializeRoute(NavigationMapboxMap.java:139)
                      at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.<init>(NavigationMapboxMap.java:69)
                      at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationMapboxMap(NavigationView.java:550)
                      at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigation(NavigationView.java:542)
                      at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:343)
                      at com.mapbox.services.android.navigation.testapp.activity.navigationui.fragment.NavigationFragment.startNavigation(NavigationFragment.java:147)
                      at com.mapbox.services.android.navigation.testapp.activity.navigationui.fragment.NavigationFragment.access$000(NavigationFragment.java:26)
                      at com.mapbox.services.android.navigation.testapp.activity.navigationui.fragment.NavigationFragment$1.onResponse(NavigationFragment.java:136)
                      at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:167)
                      at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
                      at android.os.Handler.handleCallback(Handler.java:725)
                      at android.os.Handler.dispatchMessage(Handler.java:92)
                      at android.os.Looper.loop(Looper.java:176)
                      at android.app.ActivityThread.main(ActivityThread.java:5365)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
                      at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:917)
                      at android.graphics.drawable.Drawable.createFromXml(Drawable.java:858)
                      at android.content.res.Resources.loadDrawable(Resources.java:2839)
                      at android.content.res.Resources.getDrawable(Resources.java:1521) 
                      at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:360) 
                      at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addArrowHeadIcon(NavigationMapRoute.java:516) 
                      at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.initializeUpcomingManeuverArrow(NavigationMapRoute.java:479) 
                      at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.initialize(NavigationMapRoute.java:861) 
                      at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:264) 
                      at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.<init>(NavigationMapRoute.java:239) 
                      at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.initializeRoute(NavigationMapboxMap.java:139) 
                      at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.<init>(NavigationMapboxMap.java:69) 
                      at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationMapboxMap(NavigationView.java:550) 
                      at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigation(NavigationView.java:542) 
                      at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:343) 
                      at com.mapbox.services.android.navigation.testapp.activity.navigationui.fragment.NavigationFragment.startNavigation(NavigationFragment.java:147) 
                      at com.mapbox.services.android.navigation.testapp.activity.navigationui.fragment.NavigationFragment.access$000(NavigationFragment.java:26) 
                      at com.mapbox.services.android.navigation.testapp.activity.navigationui.fragment.NavigationFragment$1.onResponse(NavigationFragment.java:136) 
                      at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:167) 
                      at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70) 
                      at android.os.Handler.handleCallback(Handler.java:725) 
                      at android.os.Handler.dispatchMessage(Handler.java:92) 
                      at android.os.Looper.loop(Looper.java:176) 
                      at android.app.ActivityThread.main(ActivityThread.java:5365) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by Guardiola31337** [comment]
Hey @gmorenope 👋 thanks for reaching out and report your issue.

This should be fixed with https://github.com/mapbox/mapbox-navigation-android/pull/1067 which landed last week and was included in the latest release [`0.16.0-beta.1`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.16.0-beta.1). Please feel free to re-open if you still experience this issue.

Thanks for checking out the SDK!
