### ISSUE TITLE
MapWayname#updateLayerWithRoadLabelFeatures NullPointerException

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1029]
Run into the following 💥 while testing

```
06-14 20:34:26.537 31220-31220/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.services.android.navigation.testapp, PID: 31220
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.google.gson.JsonElement.getAsString()' on a null object reference
        at com.mapbox.geojson.Feature.getStringProperty(Feature.java:324)
        at com.mapbox.services.android.navigation.ui.v5.map.MapWayname.updateLayerWithRoadLabelFeatures(MapWayname.java:74)
        at com.mapbox.services.android.navigation.ui.v5.map.MapWayname.updateWaynameWithPoint(MapWayname.java:43)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.updateMapWaynameWithLocation(NavigationMapboxMap.java:217)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.updateLocation(NavigationMapboxMap.java:94)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.updateNavigationMap(NavigationView.java:330)
        at com.mapbox.services.android.navigation.ui.v5.NavigationPresenter.onNavigationLocationUpdate(NavigationPresenter.java:67)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewSubscriber$3.onChanged(NavigationViewSubscriber.java:43)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewSubscriber$3.onChanged(NavigationViewSubscriber.java:39)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel$1.onProgressChange(NavigationViewModel.java:251)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:145)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:113)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:92)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5312)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
```

**Comment by danesfeder** [comment]
I think this may be an issue with the MAS.  We are checking for an empty list of features [here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/MapWayname.java#L73-L74) before trying to get the `String` property `"name"`.  

In the MAS [`Feature#getStringProperty`](https://github.com/mapbox/mapbox-java/blob/master/services-geojson/src/main/java/com/mapbox/geojson/Feature.java#L323-L325) you can see we are trying to get the property via the key provided, but not checking if it's `null` before calling `getAsString()`.

I'm also seeing [this convenience method](https://github.com/mapbox/mapbox-java/blob/master/services-geojson/src/main/java/com/mapbox/geojson/Feature.java#L400-L402).  Maybe the best practice here is to use this before trying to get the String property from our side.

cc @osana @tobrun @LukasPaczos

**Comment by Guardiola31337** [comment]
> I'm also seeing [this convenience method](https://github.com/mapbox/mapbox-java/blob/master/services-geojson/src/main/java/com/mapbox/geojson/Feature.java#L400-L402).  Maybe the best practice here is to use this before trying to get the String property from our side.

Yeah, I think so because as documented in [`Feature#getStringProperty`](https://github.com/mapbox/mapbox-java/blob/master/services-geojson/src/main/java/com/mapbox/geojson/Feature.java#L323-L325) the property could be `null`.

LOL you're fast @danesfeder 😂 https://github.com/mapbox/mapbox-navigation-android/pull/1031
