### ISSUE TITLE
NavigationService#endNavigation NullPointerException

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1030]
Run into the following 💥 while testing

```
java.lang.RuntimeException: Unable to stop service com.mapbox.services.android.navigation.v5.navigation.NavigationService@d28320: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mapbox.android.core.location.LocationEngine.removeLocationEngineListener(com.mapbox.android.core.location.LocationEngineListener)' on a null object reference
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3706)
        at android.app.ActivityThread.access$1600(ActivityThread.java:197)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6642)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mapbox.android.core.location.LocationEngine.removeLocationEngineListener(com.mapbox.android.core.location.LocationEngineListener)' on a null object reference
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.endNavigation(NavigationService.java:175)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onDestroy(NavigationService.java:85)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3686)
        at android.app.ActivityThread.access$1600(ActivityThread.java:197) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1670) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6642) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by danesfeder** [comment]
Closed via #1026
