### ISSUE TITLE
MapMatching Issue

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1034]
I Was Originally Using `NavigationRoute.Builder` to plot my navigation and then using `NavigationLauncher`.

I've now switched to MapMatching as I plan to get a more accurate route from a KML file.

**Gradle Configuration**
```java
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.14.0') {
        transitive = true
        changing = true
    }
```

**Map Matching Code**
```java
private List<Point> coordinatePoints;
private String RouteURL;

protected void onCreate(Bundle savedInstanceState) {
	// Place All Coordinates Into Point List.
	RouteURL = "53.70783,-2.68767/53.717877,-2.671947/53.073331,-2.410982/52.523454,-1.882268/51.525444,0.275767/51.532722,0.109229/51.5175,0.0671"

	coordinatePoints = new ArrayList<>();
	for (String s: Arrays.asList(RouteURL.split("/"))){
		  Double latitude = Double.valueOf(s.split(",")[0]);
		  Double longitude = Double.valueOf(s.split(",")[1]);
		  coordinatePoints.add(Point.fromLngLat(longitude, latitude));
	 }

	Timber.tag(TAG).d(coordinatePoints.toString());
	// Above Timber Output: 
	// [Point{type=Point, bbox=null, coordinates=[-2.68767, 53.70783]}, Point{type=Point, bbox=null, coordinates=[-2.671947, 53.717877]}, Point{type=Point, bbox=null, coordinates=[-2.410982, 53.073331]}, Point{type=Point, bbox=null, coordinates=[-1.882268, 52.523454]}, Point{type=Point, bbox=null, coordinates=[0.275767, 51.525444]}, Point{type=Point, bbox=null, coordinates=[0.109229, 51.532722]}, Point{type=Point, bbox=null, coordinates=[0.0671, 51.5175]}]

}

@SuppressLint("MissingPermission")
private void buildRoute() {

	// Used to prevent route being built twice
	// If location changes inbetween building.
	routeBuildStarted = true;

	// Show Loading Spinner.
	loading.setVisibility(View.VISIBLE);


	// Build Route.
	Timber.tag(TAG).d( "buildRoute();");
	Timber.tag(TAG).d( "Create navigationRoute");

	if (useCurrentAsOrigin) {
		// Add Current Position To Beginning Of ArrayList.
		
		// Get Current Location
		lastLocation = locationEngine.getLastLocation();
		if (lastLocation != null) {
			// Set Current Position.
			currentPosition = Point.fromLngLat(lastLocation.getLongitude(), lastLocation.getLatitude());
		}					
		coordinatePoints.add(0, Point.fromLngLat(currentPosition.latitude(), currentPosition.latitude()));
	}

	MapboxMapMatching.Builder mapMatchingBuilder = MapboxMapMatching.builder()
			.accessToken(Mapbox.getAccessToken())
			.coordinates(coordinatePoints)
			.steps(true)
			.voiceInstructions(true)
			.bannerInstructions(true)
			.profile(DirectionsCriteria.PROFILE_DRIVING);

	if (coordinatePoints.size() > 0){
		mapMatchingBuilder.build().enqueueCall(this);
	}else{
		Snackbar.make(findViewById(R.id.mapView), "Unable to create Navigation Route.", Snackbar.LENGTH_SHORT).show();
	}
}

@Override
public void onResponse(Call<MapMatchingResponse> call, Response<MapMatchingResponse> response) {
	if (response.isSuccessful()){
		hideLoading();
		mapMatchingDirectionsRoute = response.body().matchings().get(0).toDirectionRoute();

		populateRouteInformation(mapMatchingDirectionsRoute);
		drawRoute(mapMatchingDirectionsRoute);
		boundCameraToRoute();
	}else{
		RelativeLayout relativeMainView = findViewById(R.id.relativeMainView);
		Timber.tag(TAG).e("No Valid Route Has Been Found!");
		Snackbar.make(relativeMainView, "No Valid Route Has Been Found!", BaseTransientBottomBar.LENGTH_SHORT).show();
	}
}
    
@Override
public void onFailure(Call<MapMatchingResponse> call, Throwable throwable) {
	Timber.e(throwable);
}

private void drawRoute(DirectionsRoute route) {
	// Check If Existing Route Is Plotted And Remove.
	if (navigationMapRoute != null) {
		Timber.tag(TAG).d( "Remove Old Route");
		navigationMapRoute.removeRoute();
	}

	Timber.tag(TAG).d( "Create NavigationMapRoute();");
	navigationMapRoute = new NavigationMapRoute(mapView, this.mapboxMap, "admin-3-4-boundaries-bg");

	if (route != null) {
		// Display Loading Spinner.
		loading.setVisibility(View.VISIBLE);

		// Draw the route on the map
		Timber.tag(TAG).d( "Draw Route On MapView.");
		navigationMapRoute.addRoute(route);

		createMarkers();
		hideLoading();
	} else {
		Timber.tag(TAG).e( "Unable to draw route, route object is null.");
	}
}
```
However, when attempting to plot the route above it doesn't seem to be working, with `NavigationRoute.Builder this worked fine with the First Coordinate as the `Origin`, the Last Coordinate as the `Destination` and the ones inbetween set as `WayPoints`.

**See Below Screenshot of Plotted MapMatching Route.**
![screenshot_20180618-125304_route info 1](https://user-images.githubusercontent.com/32104383/41535107-a3fab87e-72f0-11e8-9df0-da8017dabf39.jpg)

![screenshot_20180618-125314_route info 1](https://user-images.githubusercontent.com/32104383/41535121-ab278064-72f0-11e8-95b4-d232ff2f204a.jpg)

**See Below Same Route Working with NavigationRoute.Builder**
![screenshot_2018-06-18-13-11-12](https://user-images.githubusercontent.com/32104383/41535496-0f6a45a6-72f2-11e8-973a-c613f15b1f5c.png)

**Other Information**
I have another route I am trying to plot but getting an error, the CoOrdinates i'm trying to plot, which work with the `NavigationRoute.Builder` are below.
```
53.70783,-2.68767/53.717685,-2.670658/53.116686,-2.335651/50.91766,-1.45926

[Point{type=Point, bbox=null, coordinates=[-2.68767, 53.70783]}, Point{type=Point, bbox=null, coordinates=[-2.670658, 53.717685]}, Point{type=Point, bbox=null, coordinates=[-2.335651, 53.116686]}, Point{type=Point, bbox=null, coordinates=[-1.45926, 50.91766]}]
```

However this gives me the following **Error**
```java
06-18 12:53:40.960 20563-20563/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: main
    Process: uk.co.ainscough.routeinfo, PID: 20563
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at uk.co.ainscough.routeinfo.ActivityNavigationMap.onResponse(ActivityNavigationMap.java:360)
        at com.mapbox.api.matching.v5.MapboxMapMatching$1.onResponse(MapboxMapMatching.java:150)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
Which relates to the following line
```
mapMatchingDirectionsRoute = response.body().matchings().get(0).toDirectionRoute();
```

**Comment by danesfeder** [comment]
@Danny-James `MapMatching` is not going to work the same as `NavigationRoute`.  The API is designed to take coordinates that are pretty close in proximity and not "waypoints" of a route.  It looks like the exception you're seeing is a result of no matches found by the map matching API.

**Comment by Danny-James** [comment]
@danesfeder is this how Map Matching converted to Directions Route works, See video: https://youtu.be/8sJt4hdNrSM

Also, it looks like the voice instructions say you have arrived at your 7th/8th etc destination but the instructions only ever say 1st Destination.

This isn't practical as our drivers would throw the device through the window as it's speaking at least once per second.

**Comment by Danny-James** [comment]
**Attached GEOJson**
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -2.6488384841151173,
            53.59325702160693
          ],
          [
            -2.6494875786967213,
            53.594275842955646
          ],
          [
            -2.6496806977457936,
            53.594240821379486
          ],
          [
            -2.6499381898112233,
            53.59422808625369
          ],
          [
            -2.650142037696355,
            53.594234453817066
          ],
          [
            -2.6503297923273976,
            53.594250372721305
          ],
          [
            -2.6503297923273976,
            53.5943490697937
          ],
          [
            -2.6503566144175465,
            53.59442548027209
          ],
          [
            -2.650415623015874,
            53.59448597180278
          ],
          [
            -2.650496089286321,
            53.59453691197199
          ],
          [
            -2.650565826720708,
            53.59458148456966
          ],
          [
            -2.6506516574091847,
            53.59461968961598
          ],
          [
            -2.650742852515691,
            53.59467062962394
          ],
          [
            -2.650817954368108,
            53.59471520208056
          ],
          [
            -2.6510271666712697,
            53.59484573543299
          ],
          [
            -2.651214921302312,
            53.59499218700686
          ],
          [
            -2.6513758538432057,
            53.59510998464357
          ],
          [
            -2.648999416656011,
            53.59565121280723
          ],
          [
            -2.6486078141398366,
            53.59574672293993
          ],
          [
            -2.648302042312139,
            53.59587725310539
          ],
          [
            -2.646794640845769,
            53.59633888094334
          ],
          [
            -2.646150910682195,
            53.59653308149198
          ],
          [
            -2.6456359265513356,
            53.59661903882685
          ],
          [
            -2.6446703313059743,
            53.59676548425386
          ],
          [
            -2.6436469077060565,
            53.59693739780304
          ],
          [
            -2.643512797255312,
            53.596988335016576
          ],
          [
            -2.6434484242389544,
            53.5970774749925
          ],
          [
            -2.6433411358783587,
            53.597153880536496
          ],
          [
            -2.6432284830997332,
            53.59720800104651
          ],
          [
            -2.6430246352146014,
            53.59724302016315
          ],
          [
            -2.6428744315097674,
            53.59723983660827
          ],
          [
            -2.642112684149538,
            53.597252570826214
          ],
          [
            -2.6419034718463763,
            53.59725575438015
          ],
          [
            -2.6410290717075213,
            53.59720800104651
          ],
          [
            -2.6401975869129046,
            53.597153880536496
          ],
          [
            -2.6399996307055744,
            53.59717760078724
          ],
          [
            -2.6394202735583576,
            53.59726037325746
          ],
          [
            -2.6391466882388386,
            53.59729857588133
          ],
          [
            -2.6387048565302393,
            53.597368613935345
          ],
          [
            -2.638361533776333,
            53.597371797480505
          ]
        ]
      },
      "properties": {}
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            -2.638340076104214,
            53.59734314556552
          ],
          [
            -2.638066490784695,
            53.59735587975237
          ],
          [
            -2.637868007317593,
            53.597324044278025
          ],
          [
            -2.63769098152261,
            53.59720306925692
          ],
          [
            -2.63719209064584,
            53.596690513350474
          ],
          [
            -2.6370579801950953,
            53.59663002497614
          ],
          [
            -2.6364464365397,
            53.59658863814379
          ],
          [
            -2.6355757174096652,
            53.59653879272791
          ],
          [
            -2.634379452189023,
            53.59634777582785
          ],
          [
            -2.6351948437295505,
            53.59503928684178
          ],
          [
            -2.6357902941308566,
            53.59395044029782
          ],
          [
            -2.6357956585488864,
            53.59366389706976
          ],
          [
            -2.6357473787866183,
            53.59340600650297
          ],
          [
            -2.6355703529916354,
            53.59295393313922
          ],
          [
            -2.6356132683358737,
            53.592746980566346
          ],
          [
            -2.6357634720407077,
            53.59230760097424
          ],
          [
            -2.636353558023984,
            53.590718791710124
          ],
          [
            -2.636401837786252,
            53.5898781951101
          ],
          [
            -2.636283820589597,
            53.58944515397209
          ],
          [
            -2.636278456171567,
            53.5889898191659
          ],
          [
            -2.6364179310403415,
            53.58824153103092
          ],
          [
            -2.6364876684747287,
            53.58766518092403
          ],
          [
            -2.6367934403024264,
            53.58725440726594
          ],
          [
            -2.6370938477120944,
            53.586900947666656
          ],
          [
            -2.6372976955972262,
            53.58663027840726
          ],
          [
            -2.6373727974496432,
            53.58635005428888
          ],
          [
            -2.637404983957822,
            53.586158991324694
          ],
          [
            -2.6373674330316134,
            53.58610804105504
          ],
          [
            -2.637329882105405,
            53.586076197105314
          ],
          [
            -2.637329882105405,
            53.58604435313158
          ],
          [
            -2.637378161867673,
            53.58600614033145
          ],
          [
            -2.6374425348840304,
            53.5859647430923
          ],
          [
            -2.637474721392209,
            53.58589787054343
          ],
          [
            -2.6374693569741794,
            53.58580552256387
          ],
          [
            -2.6377429422936984,
            53.5851558965917
          ],
          [
            -2.6378395018182345,
            53.584477599994564
          ],
          [
            -2.637807315310056,
            53.583882091191555
          ],
          [
            -2.637759035547788,
            53.583840691871956
          ],
          [
            -2.6377161202035495,
            53.58380884621389
          ],
          [
            -2.637651747187192,
            53.583796107943925
          ],
          [
            -2.637555187662656,
            53.58378018510111
          ],
          [
            -2.6364930328927585,
            53.58362414092395
          ],
          [
            -2.635307496508176,
            53.58353815715159
          ],
          [
            -2.6344438252053805,
            53.5835477109127
          ],
          [
            -2.633934205492551,
            53.58355726467166
          ],
          [
            -2.6330222544274875,
            53.583461726984844
          ],
          [
            -2.6322444138131686,
            53.58351268044468
          ],
          [
            -2.63170797201019,
            53.5836336946656
          ],
          [
            -2.631289547403867,
            53.58380247707943
          ],
          [
            -2.630790656527097,
            53.58399355069667
          ],
          [
            -2.6304473337731906,
            53.58407634899594
          ],
          [
            -2.629991358240659,
            53.58413685534278
          ],
          [
            -2.6297016796670505,
            53.58417506983302
          ],
          [
            -2.6288755592904635,
            53.58414003988498
          ],
          [
            -2.628312295397336,
            53.584063610806574
          ],
          [
            -2.627496903856809,
            53.58390756767579
          ],
          [
            -2.626912182291562,
            53.583764262252274
          ],
          [
            -2.625817841013486,
            53.583461726984844
          ],
          [
            -2.6247127708993503,
            53.583273835570836
          ],
          [
            -2.6235057768426486,
            53.583598664268926
          ],
          [
            -2.623044436892087,
            53.58381839991382
          ],
          [
            -2.6222665962777682,
            53.584031765316475
          ],
          [
            -2.62122589917999,
            53.58417188529351
          ],
          [
            -2.620496338327939,
            53.58423557603856
          ],
          [
            -2.6201691088281222,
            53.584251498709825
          ],
          [
            -2.619380539377744,
            53.58408908718138
          ],
          [
            -2.6176371035180636,
            53.58341077346359
          ],
          [
            -2.617277687510068,
            53.58317511262872
          ],
          [
            -2.616950458010251,
            53.58274837209757
          ],
          [
            -2.6168217119775363,
            53.58199360404221
          ],
          [
            -2.616827076395566,
            53.581445831444206
          ],
          [
            -2.6164247450433322,
            53.581468124653625
          ],
          [
            -2.614885157068784,
            53.581595514196174
          ],
          [
            -2.6141502317987033,
            53.581535004211325
          ],
          [
            -2.613613789995725,
            53.581519080516706
          ],
          [
            -2.612932508905942,
            53.58142035347618
          ],
          [
            -2.6122512278161593,
            53.58130888718556
          ],
          [
            -2.6108511147103854,
            53.58110506235113
          ],
          [
            -2.6099445280633517,
            53.580971301769424
          ],
          [
            -2.608640974482114,
            53.58064008326923
          ],
          [
            -2.6037593540750094,
            53.5803534497801
          ],
          [
            -2.6026060041986056,
            53.580375743565625
          ],
          [
            -2.601425832232053,
            53.58049995158402
          ],
          [
            -2.5986416992745944,
            53.581509526297054
          ],
          [
            -2.598480766733701,
            53.581528634734205
          ],
          [
            -2.5982930121026584,
            53.58153818894953
          ],
          [
            -2.5981964525781222,
            53.58148723310948
          ],
          [
            -2.59650129648071,
            53.57976425261546
          ],
          [
            -2.596410101374204,
            53.57961456337896
          ],
          [
            -2.5961418804727145,
            53.57948079808084
          ],
          [
            -2.5948436913095065,
            53.578968027183635
          ],
          [
            -2.5942643341622897,
            53.57875463621974
          ],
          [
            -2.594103401621396,
            53.57869730712053
          ],
          [
            -2.5939692911706515,
            53.578579463727955
          ],
          [
            -2.5939210114083835,
            53.57837881070908
          ],
          [
            -2.5940175709329196,
            53.57820363666003
          ],
          [
            -2.594881242235715,
            53.576662073729054
          ],
          [
            -2.594881242235715,
            53.5766302226626
          ],
          [
            -2.5948919710717746,
            53.576528299088636
          ],
          [
            -2.5951226410470553,
            53.57616837950227
          ],
          [
            -2.5952192005715915,
            53.57608875086128
          ],
          [
            -2.5952943024240085,
            53.57603778845233
          ],
          [
            -2.5952674803338595,
            53.5759581595654
          ],
          [
            -2.595176285227353,
            53.575881715692816
          ],
          [
            -2.592236584147031,
            53.574101171393174
          ],
          [
            -2.5917430576882907,
            53.57381130824751
          ],
          [
            -2.589693850000913,
            53.57276332491105
          ],
          [
            -2.588969653566892,
            53.572368333570424
          ],
          [
            -2.5884493050180026,
            53.571896887462756
          ],
          [
            -2.5875319895349093,
            53.5708456711343
          ],
          [
            -2.5870277342401095,
            53.57029775408186
          ],
          [
            -2.5861855206094333,
            53.5692337553414
          ],
          [
            -2.586088961084897,
            53.56917959900092
          ],
          [
            -2.585820740183408,
            53.56886421658136
          ],
          [
            -2.585622256716306,
            53.568784574184264
          ],
          [
            -2.585493510683591,
            53.56876545998663
          ],
          [
            -2.585316484888608,
            53.568708117341934
          ],
          [
            -2.585321849306638,
            53.56864440320106
          ],
          [
            -2.585348671396787,
            53.568574317535244
          ],
          [
            -2.5853754934869357,
            53.56848511742897
          ],
          [
            -2.58527356954437,
            53.568239816166525
          ],
          [
            -2.58502144189697,
            53.56799132772278
          ],
          [
            -2.584694212397153,
            53.56768867956924
          ],
          [
            -2.584340160807187,
            53.56750071804682
          ],
          [
            -2.5840826687417575,
            53.56740195826805
          ],
          [
            -2.583894914110715,
            53.56732868473479
          ]
        ]
      },
      "properties": {}
    }
  ]
}
```

**Comment by danpat** [comment]
@Danny-James I would do two things to get this working:

  1.  Simplify your trace using something like https://github.com/mapbox/geosimplify-js or an equivalent.  You don't need all those points to get it working, and they'll cause you to hit coordinate limits quickly if your traces are long.
  2. Use the `waypoints=0,<last coord>` parameter to the Matching API to avoid all the legs in the matching response

The reason that (1) works is that your trace has lots of redundant points in it.  The matching algorithm will still work with a lot fewer points, and reducing the point count will help keep you under the maximum coordinate limits for the API.

For (2), this will cause the Matching API to behave more like the Directions API - all the intermediate points along the route will be suppressed as leg start/ends.

Making these two changes to your approach should simplify things a lot for you.

**Comment by Danny-James** [comment]
@danpat do you know if the `geosimplify` is available in the Android SDK? Also, how would I add `waypoints=0,<last coord>` to the MapMatching API Call?

**Comment by Danny-James** [comment]
@danpat @danesfeder Can you shed some light on this please;

```java
Position[] before = new Position[points.size()];
for (int i = 0; i < points.size(); i++) before[i] = points.get(i);

Position[] after = PolylineUtils.simplify(before, tolerance, quality);

```
What is `tolerance` and what is `quality`?

**Comment by Danny-James** [comment]
@danpat @danesfeder I think I have worked it out.

```java
        List<Point> simplifiedPoints;
        simplifiedPoints = PolylineUtils.simplify(coordinatePoints, 0.001, true);

        // Split Out CoOrdinates In To
        int simplifiedPointsSize = simplifiedPoints.size();
        if (simplifiedPoints.size() > 100){
            simplifiedPointsSize = 100;
        }

        List<Point> subList = simplifiedPoints.subList(0, simplifiedPointsSize);

        //Timber.tag(TAG).d( )
        MapboxMapMatching.Builder mapMatchingBuilder = MapboxMapMatching.builder()
                .accessToken(Mapbox.getAccessToken())
                .coordinates(subList)
                .steps(true)
                .tidy(false)
                .waypoints(0, (simplifiedPointsSize - 1))
                .voiceInstructions(true)
                .bannerInstructions(true)
                .language(Locale.UK.getLanguage())
                .voiceUnits(DirectionsCriteria.IMPERIAL)
                .profile(DirectionsCriteria.PROFILE_DRIVING);

        if (simplifiedPointsSize > 0){
            mapMatchingBuilder.build().enqueueCall(this);
        }else{
            Snackbar.make(findViewById(R.id.mapView), "Unable to create Navigation Route.", Snackbar.LENGTH_SHORT).show();
        }
```

I will then remove the hundred which have already been used, and when reaching the last point run another `MapMatching` call to get the next route for the Remaining points.

@danesfeder does this sound the correct way of doing it?

**Comment by Danny-James** [comment]
@danesfeder @danpat removing the `simplifiedPoints` and using `coordinatePoints` the line plots correctly.

**Comment by danpat** [comment]
> What is tolerance and what is quality?

These control how much simplification happens on the line.  You should read up on the [Ramer-Douglas-Peucker](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm) algorithm to understand what these do.  Basically the bigger the numbers you supply, the more points will be removed, and the rougher the simplification will appear.  How much simplification is appropriate depends on your situation, you'll have to tune it for your data.

For drawing the routeline, don't use the simplified geometry - it will have exactly what you've observed - lots of points missing.  Instead, you should use the matched geometry returned by the Map Matching API.

I'm not super familiar with the Java wrappers - I work on the backend REST API for this service.

**Comment by Danny-James** [comment]
@danpat The images you can see above are the `NavigationLauncher.startNavigation();` I did pass in the `mapMatchingDirectionsRoute`, not sure why this didn't plot correctly.

I have now created a new activity which I pass through the Coordinates where all the `MapMatching` takes place, the reason for this is the sheer amount of coordinates the KML will contain, I will have the ability to MapMatch on 100 Coordinates and just before reaching the end of the route MapMatch the next set of 100 Coordinates this was I can ensure i have a replica of the KML file.

What I am thinking of doing is the following, 

1.

**Comment by Danny-James** [comment]
@danpat @danesfeder Ok Guys, here is where I am at the minute, I am now using `NavigationView` instead of `NavigationLauncher`, I am now plotting 100 Coordinates and then doing the following to plot the next 99 Coordinates, leaving the last one to be the first one in the next call.

```java
    @Override
    public void onArrival() {
        if (!points.isEmpty()) {
            fetchRoute(points, false);
        }
    }

private void fetchRoute(List<Point> coordinates, boolean showProgress) {

        if (coordinates.size() > 0){
            // Split Out CoOrdinates In To
            pointsSize = coordinates.size();
            if (coordinates.size() > 100) {
                pointsSize = 100;
            }

            List<Point> subList = coordinates.subList(0, pointsSize);

            if (showProgress) {
                // Display Progress Window For Map Matching.
                mProgressDialog = new ProgressDialog(ActivityNavigation.this);
                mProgressDialog.setCancelable(false);
                //progressDialog.setIcon(R.mipmap.ic_launcher);
                mProgressDialog.setMessage("Building Navigation Route...");
                mProgressDialog.setTitle("Please wait");
                mProgressDialog.setIndeterminate(true);
                mProgressDialog.show();
            }

            MapboxMapMatching.Builder mapMatchingBuilder = MapboxMapMatching.builder()
                    .accessToken(Mapbox.getAccessToken())
                    .coordinates(subList)
                    .steps(true)
                    .tidy(false)
                    .waypoints(0, (pointsSize - 1))
                    .voiceInstructions(true)
                    .bannerInstructions(true)
                    .language(Locale.UK.getLanguage())
                    .voiceUnits(DirectionsCriteria.IMPERIAL)
                    .profile(DirectionsCriteria.PROFILE_DRIVING);

            if (pointsSize > 0) {
                mapMatchingBuilder.build().enqueueCall(new Callback<MapMatchingResponse>() {
                    @Override
                    public void onResponse(Call<MapMatchingResponse> call, Response<MapMatchingResponse> response) {
                        if (response.isSuccessful()) {
                            Timber.tag(TAG).d(response.message());
                            if (response.body().matchings().size() > 0) {
                                if (mProgressDialog.isShowing()){
                                    mProgressDialog.dismiss();
                                }
                                startNavigation(response.body().matchings().get(0).toDirectionRoute());

                                // Remove Navigated Points From Array.
                                points.subList(0, pointsSize - 1).clear();
                            }else{
                                showUnableToRouteDialog();
                                Timber.tag(TAG).e("No Matching Available");
                            }
                        }else{
                            showUnableToRouteDialog();
                            Timber.tag(TAG).e(response.message());
                        }
                    }

                    @Override
                    public void onFailure(Call<MapMatchingResponse> call, Throwable t) {
                        showUnableToRouteDialog();
                        Timber.tag(TAG).e(t);
                    }
                });
            }
        }else{
            Timber.tag(TAG).e("No Coordinates Passed Into Navigation.");
            showUnableToRouteDialog();
        }
    }

private void showStartOfJourneyDialog() {
        AlertDialog alertDialog = new AlertDialog.Builder(this).create();
        alertDialog.setMessage("Would you like to start this journey part way through the route?");
        alertDialog.setCancelable(false);
        alertDialog.setButton(AlertDialog.BUTTON_POSITIVE, "Yes",
                (dialogInterface, in) -> {
                    // Do nothing
                    Point currentLocation = ActivityNavigationSummary.getCurrentPosition();

                    Timber.tag(TAG).d("Array Size: %s", points.size());

                    double lastCheckDistance = -1;
                    double currentCheckdistance;
                    Point nearestPoint = null;
                    int count = 0;
                    for (Point p : points){
                            count++;
                            currentCheckdistance = Math.acos(
                                    Math.cos(
                                            Math.toRadians(90 - currentLocation.latitude())
                                    )
                                            * Math.cos(
                                            Math.toRadians(90 - p.latitude())
                                    )
                                            + Math.sin(
                                            Math.toRadians((90 - currentLocation.latitude()))
                                    )
                                            * Math.sin(
                                            Math.toRadians(90 - p.latitude())
                                    )
                                            * Math.cos(
                                            Math.toRadians(currentLocation.longitude() - p.longitude())
                                    )
                            ) * 6371;


                        Timber.tag(TAG).d("Distance: %s", currentCheckdistance);

                        if (lastCheckDistance == -1) {
                            lastCheckDistance = currentCheckdistance;
                            nearestPoint = p;
                        }else if( currentCheckdistance < lastCheckDistance){
                            lastCheckDistance = currentCheckdistance;
                            nearestPoint = p;
                        }else{
                            //points.remove(p);
                            break;
                        }
                    }

                    // Remove Points Upto and Including Nearest Point
                    points.subList(0, count - 1).clear();

                    Timber.tag(TAG).d("Array Size: %s", points.size());
                    Timber.tag(TAG).d("Nearest Point: %s", nearestPoint.toString());

                    // Fetch Route.
                    fetchRoute(points, true);

                    Timber.tag(TAG).d("Array Size: %s", points.size());
                });
        alertDialog.setButton(DialogInterface.BUTTON_NEGATIVE, "No",
                (dialogInterface, in) -> fetchRoute(points, true));

        alertDialog.show();
    }

    private NavigationViewOptions setupOptions(DirectionsRoute directionsRoute) {
        NavigationViewOptions.Builder options = NavigationViewOptions.builder();
        options.directionsRoute(directionsRoute)
                .navigationListener(this)
                .progressChangeListener(this)
                .routeListener(this)
                .shouldSimulateRoute(true);
        return options.build();
    }

```

However, what seems to be annoying is when arriving at the end of each set of 100 Coordinates, the user hears the following `You have arrived at your destination` - is their anyway I can have the MapMatching regenerate the route before this? is their any flags I can check for in the `onProgressChange` method?

```java
@Override
    public void onProgressChange(Location location, RouteProgress routeProgress) {
        lastKnownLocation = location;
    }
```

What i would like to do is the following, the navigation has 100 Points to start with, if we say at point 82 the instruction is going to be "In 2 miles you will arrive at your destination" i would then before this announcement regenerate a new MapMatching Call using 18 Points From the previous call and 82 New points from my list.

Let me know if you don't understand this, what I would need to do this would be to capture every point completed on the route so I can add this to a `completedPoints` List and then remove these from my Master list of Points, Can you help with this?

**Comment by Danny-James** [comment]
@danesfeder do you have any input on this?

**Comment by danesfeder** [comment]
@Danny-James you would be able to check `RouteProgress#distanceRemaining()` and then regenerate your route given some arbitrary value like `100m` remaining as you explained?

**Comment by Danny-James** [comment]
@danesfeder Is their no way to read the Instruction to check if it contains `Arrive at Destination` and if the next instruction is that then run a new `MapMatching` call?

**Comment by Danny-James** [comment]
@danesfeder I am now listening for the event `onMilestoneEvent`

```java
    @Override
    public void onMilestoneEvent(RouteProgress routeProgress, String instruction, Milestone milestone) {
        Timber.tag(TAG).d(instruction);
        Timber.tag(TAG).d("distance Remaining: %s", routeProgress.distanceRemaining());
        Timber.tag(TAG).d("routeProgress > currentLeg() > summary(): %s", routeProgress.currentLeg().summary());
        //Timber.tag(TAG).d("milestone > getInstruction() > buildInstruction(): %s", milestone.getInstruction().buildInstruction(routeProgress));
    }
```

Which is outputing the following;

```java
06-26 17:35:03.016 21227-21227/uk.co.ainscough.routeinfo D/ainscough.routeinfo: Turn right onto St John's (A44), then turn left onto Malvern Road (B4485)
    distance Remaining: 1858.4007517435416
    routeProgress > currentLeg() > summary(): Henwick Road, Malvern Road


06-26 17:36:42.266 21227-21227/uk.co.ainscough.routeinfo D/ainscough.routeinfo: In a quarter mile, you will arrive at your destination
06-26 17:36:42.267 21227-21227/uk.co.ainscough.routeinfo D/ainscough.routeinfo: distance Remaining: 544.2869099118316
    routeProgress > currentLeg() > summary(): Henwick Road, Malvern Road
```

However, this is only the current milestone/instruction how could I access the Next instruction before it speaks it out? I would then like to see how far I am away from that instruction being spoken and then run the MapMatching Call.

**Comment by Danny-James** [comment]
In reality i would like it never to say `In a quarter mile, you will arrive at your destination` as I think our drivers will become confused and not know the next section of journey will start (Additional 100 Points).

**Comment by Danny-James** [comment]
@danesfeder I'm looking for a little help on the `onProgressChange` method.

**See Below My Code**
```java
@Override
    public void onProgressChange(Location location, RouteProgress routeProgress) {
        lastKnownLocation = location;

        List<Point> currentPoints = routeProgress.currentStepPoints();
        Point currentPoint = currentPoints.get(0);
```

What I'm trying to do is get the current point, I'm passing in 100 Points to the Map Matching API, and what i'm trying to do is to build up the Logic to prevent the user from hearing `In a quarter mile, you will arrive at your destination` - What i'm doing is the following;

```java
 public void onMilestoneEvent(RouteProgress routeProgress, String instruction, Milestone milestone) {
        Timber.tag(TAG).d(instruction);
        Timber.tag(TAG).d("distanceRemaining(): %s", routeProgress.distanceRemaining());
        Timber.tag(TAG).d("currentLeg().summary(): %s", routeProgress.currentLeg().summary());

        List<BannerInstructions> routeProgressBannerInstruction = routeProgress.currentLegProgress().currentStep().bannerInstructions();
        BannerInstructions bIM = null;
        if ((routeProgressBannerInstruction != null ? routeProgressBannerInstruction.size() : 0) > 0) {
            bIM = routeProgressBannerInstruction.get(0);
        }
        if (bIM != null) {
            if (bIM.primary().type().equals("arrive")){
                Timber.tag(TAG).d("Next Step Is Arrival");
                fetchRoute(points, false);
            }
        }
}
```

As you can see from above i'm checking the current step to see if it's a type of `arrive`, if so i  would like to rerun `fetchRoute(List<Points>, boolean ShowProgress)` - What I plan on doing is passing in a Points List of all the points that have been completed, hopefully building this list up in the `onProgressChange`

I will then pass this through to `fetchRoute()` and remove those Points from the master list. Do you know how I can get the current point and possibly the next point?

```                 
X----------C------->-----N-----------X
           ^ Current Point             
                   ^ Current Position
                         ^ Next Point
```
**Key:**
**X** = Points
**C** = Current Point
**N** = Next Point
**>** = Current Position

The current point will always be the last one you passed until reaching the next point.

**Comment by Danny-James** [comment]
@danesfeder Change of mind with this one, What I believe would be the better option would be to Suppress the voice instruction and banner instruction of `Turn Right, and you will arrive at your destination` to `Turn Right` if `points.size() > 0` << This means only supress the instruction if their are more points to be loaded in.

Another example is, `In a quarter mile, you will arrive at your destination` we could possibly replace this Voice Instruction with `In a quarter mile, Continue.` and the BannerInstruction to `Continue`.

If `points.Size()` contains more points their is another MapMatching response required so the user actually isn't arriving at the destination.

Would this be possible?

**Comment by Danny-James** [comment]
@danesfeder Any chance of some input on this or have i posted the above in the wrong section?

**Comment by jackhd1** [comment]
@Danny-James Before you pass your DirectionsRoute to navigation you can modify it's route legs' steps to exclude the arrive instruction.

**Comment by danesfeder** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/1107 is also moving to let you override the current banner instruction.  `if instruction contains "arrive" don't update`

**Comment by Danny-James** [comment]
@danesfeder will i need to do a combination of @jackhd1 soluton and #1107 or is it just #1107 i can do when released.

**Comment by Danny-James** [comment]
@danesfeder Any Chance you can take alook at [#1107](https://github.com/mapbox/mapbox-navigation-android/pull/1107) I'm having trouble updating the banner instruction.

And would like to know how to update the instructions list of upcoming instructions.

**Comment by Danny-James** [comment]
@danesfeder As a workaround for the time being how would i prevent the instruction list from being shown when the user touches the `bannerText`? Is their something available already?

**Comment by danesfeder** [comment]
Hey @Danny-James given the convo in #1378, I'm going to go ahead and close here
