### ISSUE TITLE
Null Reference in NavigationInstructionPlayer

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#1052]
**Android API:** 8.1
**Mapbox Navigation SDK version:** 0.15.0

### Steps to trigger behavior

 1. Use a language that isn't supported by mapbox (I thought I was using English, but that's a separate issue...)
 2. Run library normally, such that it calls onOffRoute(), setMuted(), or onDestroy()

### Expected behavior

Nothing unusual

### Actual behavior

Null Reference Exception - mapboxSpeechPlayer will not have been initialised

**Comment by Guardiola31337** [comment]
Hey @richjhart 👋 thanks for reaching out and reporting your problem.

Could you add some more information for reproducing the crash (minimal example) or any other specifics around your test setup? Are you able to provide any logs? Do you have some more information on used device? If there is any sample or pseudo code you can provide, that would be really helpful.

**Comment by richjhart** [comment]
I can provide more information if needed, but basically it seems to be impossible to make it NOT happen if you use Map Matching for the request.

When this happens, converting the response to a DirectionsRoute using toDirectionRoute() leave voiceLanguage as null.

When this is ultimately passed to NavigationInstructionPlayer, languageSupportedByMapboxSpeech will be false (line 25).

Therefore when initInstructionPlayers is called, line 91 will not be executed, and so mapboxSpeechPlayer will not be initialised - which is the only place is could be initialised.

From that point on, any calls to setMuted, onOffRoute, or onDestroy will crash.

**Comment by richjhart** [comment]
Here is a full stack trace of the crash

06-22 12:26:28.577 15491-15491/com.bynd.looper E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bynd.looper, PID: 15491
    java.lang.RuntimeException: Unable to destroy activity {com.bynd.looper/com.bynd.looper.ActivityNavigation}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.onDestroy()' on a null object reference
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4555)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4573)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.onDestroy()' on a null object reference
        at com.mapbox.services.android.navigation.ui.v5.voice.NavigationInstructionPlayer.onDestroy(NavigationInstructionPlayer.java:60)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.deactivateInstructionPlayer(NavigationViewModel.java:349)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.onDestroy(NavigationViewModel.java:94)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.shutdown(NavigationView.java:522)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.onDestroy(NavigationView.java:161)
        at com.bynd.looper.FragmentNavigation.onDestroyView(FragmentNavigation.java:422)
        at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2565)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1512)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3235)
        at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:265)
        at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
        at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
        at android.app.Activity.performDestroy(Activity.java:7254)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1266)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4542)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4573) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1748) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by richjhart** [comment]
To fix it for now, when I "extract" the route, instead of calling:

return matchings.get(0).toDirectionRoute();

I do:

            DirectionsRoute route = matchings.get(0).toDirectionRoute();
            return route.toBuilder()
                    .voiceLanguage(route.routeOptions().language())
                    .build();

That should really be done in toDirectionRoute(), and obviously still doesn't fix the main issue that if the language is not a supported one, it will still crash (we only support English)

**Comment by danesfeder** [comment]
Hey @richjhart you're correct here, this is an oversight on our part.  We will look into the issues with the map matching conversion to `DirectionsRoute`, as well as accounting for no `voiceLanguage` provided in the SDK.  

Your fix will work for now - stay tuned, as soon as these fixes land, we will try to push a patch release next week.  Thank you for your patience here.

**Comment by danesfeder** [comment]
@richjhart PRs moving #1054 and https://github.com/mapbox/mapbox-java/pull/847 to address this
