### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by paqio** [mapbox/mapbox-navigation-android#1112]
Is there a way to use this SDK with AndroidX instead of Support?

**Comment by paqio** [comment]
Adding 
```
android.useAndroidX=true
android.enableJetifier=true
```
to gradle.properties solves conflicts

**Comment by richjhart** [comment]
Has anyone had any luck using the NavigationView element with AndroidX? After migrating - and with those flags one, adding:

    <com.mapbox.services.android.navigation.ui.v5.NavigationView
        android:id="@+id/navigation_view"
        android:layout_width="match_parent"
        android:layout_height="0dp"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        app:navigationDarkTheme="@style/NavigationViewDarkModified"
        app:navigationLightTheme="@style/NavigationViewLightModified" />

To my view results in an InflationException

**Comment by danesfeder** [comment]
@richjhart we still need to update / address conflicts should they arise (looks like they are from your comment here) - do you mind cutting a new ticket with your exception and this code?  Thanks!

**Comment by richjhart** [comment]
@danesfeder Will do - still just doing some investigation to try to get more info in a clean project (currently the error I get is maddeningly unhelpful). Will post something later today or tomorrow at the latest.

**Comment by danesfeder** [comment]
Thanks for the help as always @richjhart

**Comment by kkalera** [comment]
Hi, I'm experiencing some issues with the NavigationView when using androidx aswell. 
I'm using the example code found at the [mapbox examples page](https://docs.mapbox.com/android/navigation/examples/navigationview-with-fragment/)

For testing purposes I started out with 2 clean projects, one using androidx and one without androidx. 
The project without runs fine, while the project with androidx gives the following error:

>`2019-03-03 21:48:37.779 22059-22059/com.example.navigationfragmenttest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.navigationfragmenttest, PID: 22059
    java.lang.ClassCastException: com.example.navigationfragmenttest.MainActivity cannot be cast to androidx.lifecycle.LifecycleOwner
        at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.subscribe(InstructionView.java:181)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.subscribeViewModels(NavigationView.java:702)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigation(NavigationView.java:632)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:394)
        at com.example.navigationfragmenttest.NavigationFragment.startNavigation(NavigationFragment.kt:149)
        at com.example.navigationfragmenttest.NavigationFragment.access$startNavigation(NavigationFragment.kt:28)
        at com.example.navigationfragmenttest.NavigationFragment$fetchRoute$1.onResponse(NavigationFragment.kt:131)
        at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:170)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

Any ideas on how we could solve this? Besides changing my entire project back from androidx :P
