### ISSUE TITLE
Errors occur after navigation

### ISSUE THREAD

**Issue by wbearand** [mapbox/mapbox-navigation-android#1116]
**Android API:** N/A
**Mapbox Navigation SDK version:** 0.16.0-SNAPSHOT

### Steps to trigger behavior

 1. I am using an activity with navigationView for several cycles / routes, I am starting the next part some metres before the end of the current route. (I have to admit I have not figured out the best way to do that, I am having issues especially with listeners not triggering because my starting the next part is not smooth, tips concerning that are also appreciated.)
 2. After stopping the navigation sometimes errors occur. I can't really provide a definite guide to reproduce them.

### Expected behavior
No errors
### Actual behavior
Sometimes this crash occurs:
```
2018-07-17 22:50:10.792 29855-29855/com.................................. E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.................................., PID: 29855
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.mapbox.services.android.navigation.v5.navigation.notification.NavigationNotification.updateNotification(com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress)' on a null object reference
        at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.updateNavigationNotification(NavigationNotificationProvider.java:21)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onNewRouteProgress(RouteProcessorThreadListener.java:33)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback$1.run(RouteProcessorHandlerCallback.java:97)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

that one occurs more often, but the app does not crash at least:

```
2018-07-18 17:00:42.271 3918-3918/com.mapbox.services.android.navigation.testapp E/MapboxSpeechPlayer: java.lang.IllegalStateException
        at android.media.MediaPlayer.isPlaying(Native Method)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.stopMediaPlayerPlaying(MapboxSpeechPlayer.java:141)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.onDestroy(MapboxSpeechPlayer.java:95)
        at com.mapbox.services.android.navigation.ui.v5.voice.SpeechPlayerProvider.onDestroy(SpeechPlayerProvider.java:68)
        at com.mapbox.services.android.navigation.ui.v5.voice.NavigationSpeechPlayer.onDestroy(NavigationSpeechPlayer.java:81)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.deactivateInstructionPlayer(NavigationViewModel.java:364)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.onDestroy(NavigationViewModel.java:97)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.shutdown(NavigationView.java:574)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.onDestroy(NavigationView.java:169)
        at com.mapbox.services.android.navigation.testapp.activity.navigationui.EmbeddedNavigationActivity.onDestroy(EmbeddedNavigationActivity.java:147)
        at android.app.Activity.performDestroy(Activity.java:6881)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1153)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4190)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4221)
        at android.app.ActivityThread.-wrap6(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by Guardiola31337** [comment]
Hey @wbearand 👋 thanks for reaching out and report these crashes.

Quick question, are you using `NavigationLauncher` or `MapboxNavigationActivity` by any chance?

I run into the second crash you mentioned when testing the [`NavigationLauncherActivity`](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java) from the test app (after closing the app completely) 👀 

```
07-18 18:44:25.179 20393-20393/com.mapbox.services.android.navigation.testapp E/MapboxSpeechPlayer: java.lang.IllegalStateException
        at android.media.MediaPlayer.isPlaying(Native Method)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.stopMediaPlayerPlaying(MapboxSpeechPlayer.java:145)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.onDestroy(MapboxSpeechPlayer.java:99)
        at com.mapbox.services.android.navigation.ui.v5.voice.SpeechPlayerProvider.onDestroy(SpeechPlayerProvider.java:68)
        at com.mapbox.services.android.navigation.ui.v5.voice.NavigationSpeechPlayer.onDestroy(NavigationSpeechPlayer.java:81)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.deactivateInstructionPlayer(NavigationViewModel.java:360)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.onDestroy(NavigationViewModel.java:98)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.shutdown(NavigationView.java:574)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.onDestroy(NavigationView.java:169)
        at com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity.onDestroy(MapboxNavigationActivity.java:90)
        at android.app.Activity.performDestroy(Activity.java:6407)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
        at android.app.ActivityThread.-wrap5(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

cc @devotaaabel

**Comment by danesfeder** [comment]
We should open a new ticket for the silent speech player crash (if one isn't opened already).  I cut #1118 to address this.

**Comment by Guardiola31337** [comment]
> We should open a new ticket for the silent speech player crash (if one isn't opened already).

Tracking in #1119 

cc @wbearand

**Comment by wbearand** [comment]
Thanks for your quick response.

@Guardiola31337 : 
I am basically using [EmbeddedNavigationActivity](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/EmbeddedNavigationActivity.java) from master branch an 10th of July.

I slightly modified that sample adding milestones and listener as mentioned here [Feature request - allow custom voice instructions with navigationView #947](https://github.com/mapbox/mapbox-navigation-android/issues/947)

The other real crash is more worrisome though:
`java.lang.NullPointerException: Attempt to invoke interface method 'void com.mapbox.services.android.navigation.v5.navigation.notification.NavigationNotification.updateNotification(com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress)' on a null object reference`
