### ISSUE TITLE
OffRoute#isUserOffRoute NullPointerException

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1139]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mapbox.services.android.navigation.v5.offroute.OffRoute.isUserOffRoute(android.location.Location, com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress, com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationOptions)' on a null object reference
        at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.isUserOffRoute(NavigationHelper.java:478)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback.determineUserOffRoute(RouteProcessorHandlerCallback.java:74)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback.handleRequest(RouteProcessorHandlerCallback.java:51)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback.handleMessage(RouteProcessorHandlerCallback.java:33)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:193)
        at android.os.HandlerThread.run(HandlerThread.java:65)
```

**Comment by danesfeder** [comment]
@Guardiola31337 do you remember / have any context on how you produced this?

**Comment by Guardiola31337** [comment]
Nope 😥
I was driving when the app suddenly crashed and afterwards I connected the device and luckily the log trace was still available. Will report extra info if seen again.

**Comment by danesfeder** [comment]
@Guardiola31337 there wasn't any lifecycle changes from what you could remember?
