### ISSUE TITLE
Mapbox navigation launcher add waypoints names

### ISSUE THREAD

**Issue by praveenposwal** [mapbox/mapbox-navigation-android#1160]
We are creating a navigation by using mapbox navigation launcher, it is working fine untill we have added the waypoints names. After adding waypoints name application started to crash randomly (some time at 1st waypoint, some time at another). Every time erorr is same "Number of waypoint names must match  the number of waypoints provided "

Here is our code : 

         List<TourDetailResponse.TourDetailsPoi> pois = tourDetailResponse.getPois();

        Point origin = Point.fromLngLat(currentLongitude, currentLatitude);

        Point destination = Point.fromLngLat(pois.get(pois.size()-1).getLongitude(), pois.get(pois.size()-1).getLatitude());

        NavigationRoute.Builder  builder = NavigationRoute.builder(coreActivity)
                .accessToken(Mapbox.getAccessToken())
                .origin(origin)
                .destination(destination)

        .profile(DirectionsCriteria.PROFILE_WALKING);

        StringBuilder sb = new StringBuilder();

        sb.append("origin##");

            for(int q=0;q<pois.size()-1;q++)
        {
            Point point = Point.fromLngLat(pois.get(q).getLongitude(), pois.get(q).getLatitude());

            builder.addWaypoint(point);
            sb.append(pois.get(q).getName()+"##");
        }

        builder.language(Locale.getDefault());

        sb.append(pois.get(pois.size()-1).getName()+"##");

        sb.setLength(sb.length()-2);

        try
        {
           builder.addWaypointNames(sb.toString().split("##"));
        }catch (Exception e)
        {
            e.printStackTrace();
        }

In Debug mode we have checked that Number of waypoint names are same as the number of waypoints 

Stack trace : Fatal Exception: com.mapbox.core.exceptions.ServicesException: Number of waypoint names must match  the number of waypoints provided.
       at com.mapbox.api.directions.v5.MapboxDirections$Builder.build(MapboxDirections.java:757)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRoute$Builder.build(NavigationRoute.java:558)
       at com.mapbox.services.android.navigation.v5.route.RouteFetcher.executeRouteCall(RouteFetcher.java:120)
       at com.mapbox.services.android.navigation.v5.route.RouteFetcher.findRouteFromRouteProgress(RouteFetcher.java:72)
       at com.mapbox.services.android.navigation.ui.v5.route.ViewRouteFetcher.fetchRouteFromOffRouteEvent(ViewRouteFetcher.java:65)
       at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.sendEventOffRoute(NavigationViewModel.java:410)
       at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.access$600(NavigationViewModel.java:47)
       at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel$2.userOffRoute(NavigationViewModel.java:274)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onUserOffRoute(NavigationEventDispatcher.java:150)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onUserOffRoute(RouteProcessorThreadListener.java:57)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback$1.run(RouteProcessorHandlerCallback.java:99)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6123)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by danesfeder** [comment]
Hey @praveenposwal this looks like an issue on our end.  As a multi-waypoint route progresses, we remove way points that are completed - we track this to make proper re-route requests should an off-route event occur.  We are not, though, taking the same into account for way point names, which must be removed as well.  

Thank you for bringing this to our attention, we will work it into our current pipeline.

**Comment by praveenposwal** [comment]
Thank you @danesfeder , we are looking forward for the new version.
