### ISSUE TITLE
NavigationViewEventDispatcher#onBannerDisplay NullPointerException

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1189]
Run into the following 💥 while testing

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.api.directions.v5.models.BannerInstructions com.mapbox.services.android.navigation.ui.v5.NavigationViewEventDispatcher.onBannerDisplay(com.mapbox.api.directions.v5.models.BannerInstructions)' on a null object reference
  at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.updateBannerInstruction(NavigationViewModel.java:376)
  at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.access$800(NavigationViewModel.java:47)
  at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel$3.onMilestoneEvent(NavigationViewModel.java:283)
  at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onMilestoneEvent(NavigationEventDispatcher.java:137)
  at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onMilestoneTrigger(RouteProcessorThreadListener.java:46)
  at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback$1.run(RouteProcessorHandlerCallback.java:98)
  at android.os.Handler.handleCallback(Handler.java:873)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:193)
  at android.app.ActivityThread.main(ActivityThread.java:6669)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by danesfeder** [comment]
Addressed in #1152
