### ISSUE TITLE
NPE MapWayname#updateWaynameLayerWithNameProperty

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#1227]
Run into the following 💥 while testing https://github.com/mapbox/mapbox-navigation-android/pull/1156

```
08-20 13:14:02.849 15537-15537/com.mapbox.services.android.navigation.testapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.services.android.navigation.testapp, PID: 15537
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mapbox.geojson.Feature.hasNonNullValueForProperty(java.lang.String)' on a null object reference
        at com.mapbox.services.android.navigation.ui.v5.map.MapWayname.updateWaynameLayerWithNameProperty(MapWayname.java:140)
        at com.mapbox.services.android.navigation.ui.v5.map.MapWayname.updateLayerWithRoadLabelFeatures(MapWayname.java:108)
        at com.mapbox.services.android.navigation.ui.v5.map.MapWayname.updateWaynameWithPoint(MapWayname.java:59)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.updateMapWaynameWithLocation(NavigationMapboxMap.java:268)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.updateLocation(NavigationMapboxMap.java:89)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.updateNavigationMap(NavigationView.java:331)
        at com.mapbox.services.android.navigation.ui.v5.NavigationPresenter.onNavigationLocationUpdate(NavigationPresenter.java:66)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewSubscriber$3.onChanged(NavigationViewSubscriber.java:43)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewSubscriber$3.onChanged(NavigationViewSubscriber.java:39)
        at android.arch.lifecycle.LiveData.considerNotify(LiveData.java:109)
        at android.arch.lifecycle.LiveData.dispatchingValue(LiveData.java:126)
        at android.arch.lifecycle.LiveData.setValue(LiveData.java:282)
        at android.arch.lifecycle.MutableLiveData.setValue(MutableLiveData.java:33)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel$1.onProgressChange(NavigationViewModel.java:267)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:144)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onNewRouteProgress(RouteProcessorThreadListener.java:34)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback$1.run(RouteProcessorHandlerCallback.java:97)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by danesfeder** [comment]
@Guardiola31337 this looks like an error resulting from the filter changes in the PR and not an issue with `master` ([code here](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/map/MapWayname.java#L82-L85)).

We are checking for an empty list and, if not empty, getting the first `Feature`.  So I don't see a case where this logic could result in a `null` `Feature`.  Going to close and comment on the PR that this needs to be addressed before merging.

**Comment by Guardiola31337** [comment]
@danesfeder 

I've reported as a new ticket because that part of the code was untouched.

> We are checking for an empty list and, if not empty, getting the first `Feature`.  So I don't see a case where this logic could result in a `null` `Feature`.

`empty` doesn't mean (`!=`) `null`

> Going to close and comment on the PR that this needs to be addressed before merging.  

We could fix it as part of that PR but it's an unrelated issue.

**Comment by Guardiola31337** [comment]
@danesfeder 

> but it's an unrelated issue.

My bad, I was looking at PR's branch code 🤦‍♂️ 

Thanks for clarifying in https://github.com/mapbox/mapbox-navigation-android/pull/1156#issuecomment-414659621

All clear now 🚀
