### ISSUE TITLE
Error using SNAPSHOT.

### ISSUE THREAD

**Issue by mecoFarid** [mapbox/mapbox-navigation-android#126]
```
07-10 23:37:55.176 11649-11649/com.tayqa.tms E/AndroidRuntime: FATAL EXCEPTION: main
                                                               Process: com.tayqa.tms, PID: 11649
                                                               java.lang.NoSuchMethodError: No interface method requestLocationUpdates(Lcom/mapzen/android/lost/api/LocationRequest;Lcom/mapzen/android/lost/api/LocationListener;)V in class Lcom/mapzen/android/lost/api/FusedLocationProviderApi; or its super classes (declaration of 'com.mapzen.android.lost.api.FusedLocationProviderApi' appears in /data/app/com.tayqa.tms-1/base.apk)
                                                                   at com.mapbox.services.android.location.LostLocationEngine.requestLocationUpdates(LostLocationEngine.java:123)
                                                                   at com.mapbox.services.android.navigation.v5.NavigationService.onConnected(NavigationService.java:224)
                                                                   at com.mapbox.services.android.location.LostLocationEngine.activate(LostLocationEngine.java:51)
                                                                   at com.mapbox.services.android.navigation.v5.NavigationService.startRoute(NavigationService.java:147)
                                                                   at com.mapbox.services.android.navigation.v5.MapboxNavigation$NavigationServiceConnection.onServiceConnected(MapboxNavigation.java:505)
                                                                   at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1320)
                                                                   at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1337)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:145)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6939)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by cammace** [comment]
This sounds more like an issue with the Map SDK rather than the navigation SDK since we aren't directly using LOST in this project. Try adding this snippet inside your `build.gradle` file:
```groovy
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.0@aar') {
  transitive = true
  exclude module: 'lost'
}
```
