### ISSUE TITLE
baseUrl: rerouting -> services exception

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#1268]
**Android API: 8.0**
**Mapbox Navigation SDK version: 0.18.0**

### Steps to trigger behavior

 1. Set NavigationRoute.builder(contex).baseUrl(myBaseUrl)
 2. Use NavigationLauncher.startNavigation with NavigationLauncherOptions 
 3. Force a off route location

### Expected behavior
Call baseUrl for rerouting... but my baseUrl (a php script) is never called)

### Actual behavior
```
com.mapbox.core.exceptions.ServicesException: An origin and destination are required before making the directions API request.
        at com.mapbox.api.directions.v5.MapboxDirections$Builder.build(MapboxDirections.java:751)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationRoute$Builder.build(NavigationRoute.java:558)
        at com.mapbox.services.android.navigation.v5.route.RouteFetcher.executeRouteCall(RouteFetcher.java:120)
        at com.mapbox.services.android.navigation.v5.route.RouteFetcher.findRouteFromRouteProgress(RouteFetcher.java:72)
        at com.mapbox.services.android.navigation.ui.v5.route.ViewRouteFetcher.fetchRouteFromOffRouteEvent(ViewRouteFetcher.java:65)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.sendEventOffRoute(NavigationViewModel.java:435)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.access$600(NavigationViewModel.java:51)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel$2.userOffRoute(NavigationViewModel.java:289)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onUserOffRoute(NavigationEventDispatcher.java:150)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onUserOffRoute(RouteProcessorThreadListener.java:57)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback$1.run(RouteProcessorHandlerCallback.java:99)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

I don't know where to set origin/destination to avoid this exception. If I don't set baseUrl everything works fine.

**Comment by P-Zenker** [comment]
```
NavigationRoute.builder(activityNavigation)
                .accessToken(Mapbox.getAccessToken())
                .origin(Point.fromLngLat(10.697726, 53.836667))
                .destination(Point.fromLngLat(10.701127, 53.837471))
                .voiceUnits(DirectionsCriteria.METRIC)
                .language(Locale.GERMAN)
                .baseUrl(myBaseUrl)
                .build()
                .getRoute(new Callback<DirectionsResponse>() {
                    @Override
                    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                        directionsRoute = response.body().routes().get(0);

                        NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                                .directionsRoute(directionsRoute)
                                .shouldSimulateRoute(false)
                                .enableOffRouteDetection(true)
                                .waynameChipEnabled(true)
                                .build();

                        NavigationLauncher.startNavigation(getActivity(), options);
                    }

                    @Override
                    public void onFailure(Call<DirectionsResponse> call, Throwable t) {
                        // ...
                    }
                });
```
If you need 'myBaseUrl' too, I write you a email

**Comment by P-Zenker** [comment]
Any updates to this issue? :)

**Comment by danesfeder** [comment]
@P-Zenker would you be able to test with `0.21.0`?  

On a second look here, this actually doesn't look related to the base URL.

From [this code](https://github.com/mapbox/mapbox-java/blob/master/services-directions/src/main/java/com/mapbox/api/directions/v5/MapboxDirections.java#L750-L753):

```
      if (coordinates.size() < 2) {
        throw new ServicesException("An origin and destination are required before making the"
          + " directions API request.");
      }
```

Something may be incorrect regarding our remaining way point calculation, thanks!

**Comment by P-Zenker** [comment]
Hey @danesfeder, you're right. In 0.21.0 the exception isn't thrown anymore.
