### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1309]
I've come across this error in my Fabric.io Crashlytics.

```
Fatal Exception: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1037880 bytes
       at android.app.NotificationManager.notifyAsUser(NotificationManager.java:342)
       at android.app.NotificationManager.notify(NotificationManager.java:292)
       at android.app.NotificationManager.notify(NotificationManager.java:276)
       at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.updateNotificationViews(MapboxNavigationNotification.java:152)
       at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.updateNotification(MapboxNavigationNotification.java:73)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.updateNavigationNotification(NavigationNotificationProvider.java:23)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onNewRouteProgress(RouteProcessorThreadListener.java:33)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback$1.run(RouteProcessorHandlerCallback.java:97)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)


Caused by android.os.TransactionTooLargeException: data parcel size 1037880 bytes
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:628)
       at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:899)
       at android.app.NotificationManager.notifyAsUser(NotificationManager.java:336)
       at android.app.NotificationManager.notify(NotificationManager.java:292)
       at android.app.NotificationManager.notify(NotificationManager.java:276)
       at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.updateNotificationViews(MapboxNavigationNotification.java:152)
       at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.updateNotification(MapboxNavigationNotification.java:73)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.updateNavigationNotification(NavigationNotificationProvider.java:23)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onNewRouteProgress(RouteProcessorThreadListener.java:33)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback$1.run(RouteProcessorHandlerCallback.java:97)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
```

**Gradle**
```
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.18.0') {
        transitive = true
        changing = true
    }
```

**Comment by Guardiola31337** [comment]
Hey @Danny-James 👋 thanks for reporting.

That one is being tracked in https://github.com/mapbox/mapbox-navigation-android/issues/1188

Closing here as duplicate.

As always, let us know if you find any other bugs. Thanks again!
