### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start activity

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1322]
I've come across an unusual error in my crashlytics dashboard - http://crashes.to/s/fe95199c795

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{uk.co.ainscough.routeinfo/uk.co.ainscough.routeinfo.ActivityNavigation}: android.view.InflateException: Binary XML file line #9: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2108)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2133)
       at android.app.ActivityThread.access$600(ActivityThread.java:142)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4895)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)

Caused by com.mapbox.mapboxsdk.exceptions.MapboxConfigurationException: 
Using MapView requires calling Mapbox.getInstance(Context context, String accessToken) before inflating or creating the view. The access token parameter is required when using a Mapbox service.
Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
       at com.mapbox.mapboxsdk.Mapbox.validateMapbox(Mapbox.java:131)
       at com.mapbox.mapboxsdk.Mapbox.getAccessToken(Mapbox.java:69)
       at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.<init>(NavigationViewModel.java:83)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.arch.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:199)
       at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:134)
       at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:102)
       at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationViewModel(NavigationView.java:425)
       at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeView(NavigationView.java:407)
       at com.mapbox.services.android.navigation.ui.v5.NavigationView.<init>(NavigationView.java:89)
       at com.mapbox.services.android.navigation.ui.v5.NavigationView.<init>(NavigationView.java:83)
       at java.lang.reflect.Constructor.constructNative(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
       at android.view.LayoutInflater.createView(LayoutInflater.java:587)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:687)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:746)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
       at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
       at uk.co.ainscough.routeinfo.ActivityNavigation.onCreate(ActivityNavigation.java:107)
       at android.app.Activity.performCreate(Activity.java:5042)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2072)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2133)
       at android.app.ActivityThread.access$600(ActivityThread.java:142)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4895)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

```java
@SuppressLint("MissingPermission")
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {

        if (getScreenOrientation() == Configuration.ORIENTATION_LANDSCAPE) {
            this.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);
        } else {
            this.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
        }

        setTheme(R.style.Theme_AppCompat_NoActionBar);
        super.onCreate(savedInstanceState);

        // Create CrashLytics.
        final Fabric fabric = new Fabric.Builder(this)
                .kits(new Crashlytics())
                .debuggable(true)
                .build();
        Fabric.with(fabric);

        // Retrieve Coordinates From File.
        getCoordinatesData();

        setContentView(R.layout.activity_navigation);

        navigationView = findViewById(R.id.navigationView);
        navigationView.onCreate(savedInstanceState);
        navigationView.initialize(this);

        // Log CrashLytics Event.
        Answers.getInstance().logContentView(new ContentViewEvent()
                .putContentName("RouteInfo Navigation")
                .putContentType("Android Activity")
                .putContentId("ActivityNavigation"));

    }
```

**Comment by Guardiola31337** [comment]
Hey 👋 @Danny-James Thanks for reaching out and report your issue as always 🙇 

This seem because the access token wasn't set up properly on your end. I recommend you to place the access token inside of your application's `onCreate()` method.

```java
public class MyApplication extends Application {

  @Override
  public void onCreate() {
    super.onCreate();

    // Mapbox Access token
    Mapbox.getInstance(getApplicationContext(), "YOUR_MAPBOX_ACCESS_TOKEN_GOES_HERE");
  }
}
```

and then retrieve it using `Mapbox.getAccessToken()` e.g.

```java
MapboxNavigation navigation = new MapboxNavigation(<Context>, Mapbox.getAccessToken());
```

Hope this helps. Thanks again!

Closing as answered.

**Comment by Danny-James** [comment]
@Guardiola31337 i've never had this issue before this is in my NavigationView which I am getting the error.

Everything seems to have always worked and i've never need to include `Mapbox.getInstance();`

**Comment by Guardiola31337** [comment]
That's weird then... Wondering if this is a specific device issue somehow 🤔 

Keep us posted. Thanks 🙏
