### ISSUE TITLE
FATAL EXCEPTION: GLThread 21502

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1326]
Hi Guys, I've just come across when starting my Navigation, I've tried to reproduce this and i'm not able to do so.

```
09-27 11:38:48.801 8930-10471/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: GLThread 21502
    Process: uk.co.ainscough.routeinfo, PID: 8930
    java.lang.Error: unknown pbf field type exception
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.nativeRender(Native Method)
        at com.mapbox.mapboxsdk.maps.renderer.MapRenderer.onDrawFrame(MapRenderer.java:74)
        at com.mapbox.mapboxsdk.maps.renderer.glsurfaceview.GLSurfaceViewMapRenderer.onDrawFrame(GLSurfaceViewMapRenderer.java:57)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1571)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
```

**Comment by Danny-James** [comment]
Crashlytics - http://crashes.to/s/614e14337a5

**Comment by Guardiola31337** [comment]
This seems an issue from the Maps SDK so I went ahead and created a ticket in `mapbox-gl-native` https://github.com/mapbox/mapbox-gl-native/issues/12984

BTW have you ever 👀 this before @mapbox/maps-android?

Closing as non actionable here.
