### ISSUE TITLE
CI crash

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-navigation-android#1327]
When updating something unrelated, CI failed with a native crash:

<img width="1022" alt="screen shot 2018-09-27 at 12 40 41" src="https://user-images.githubusercontent.com/2151639/46140901-a9ff7c80-c252-11e8-9a4b-815f41aafcc4.png">

@mapbox/navigation-android is this a known issue?
Out of x amount of runs, how many times is this run flaky?

**Comment by Guardiola31337** [comment]
Yeah that's being tracked in 👉 https://github.com/mapbox/mapbox-navigation-android/issues/1209

The flaky test is `NavigationViewOrientationTest` which throws 👇 

```
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): Exception in MapView.OnMapChangedListener
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source mapbox-location-source already exists
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddSource(Native Method)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.maps.NativeMapView.addSource(NativeMapView.java:782)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.maps.MapboxMap.addSource(MapboxMap.java:428)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.addLocationSource(LocationLayer.java:246)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.initializeComponents(LocationLayer.java:86)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.<init>(LocationLayer.java:81)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.initialize(LocationLayerPlugin.java:770)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.<init>(LocationLayerPlugin.java:226)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.<init>(LocationLayerPlugin.java:206)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.initializeLocationLayer(NavigationMapboxMap.java:408)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.<init>(NavigationMapboxMap.java:92)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationMap(NavigationView.java:265)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.services.android.navigation.ui.v5.NavigationView.onMapReady(NavigationView.java:208)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1235)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapChanged(MapView.java:1220)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:911)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.os.MessageQueue.next(MessageQueue.java:325)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at java.lang.reflect.Method.invoke(Native Method)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.support.test.espresso.base.Interrogator.getNextMessage(Interrogator.java:199)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.support.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:140)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.support.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:462)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.support.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:384)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.support.test.espresso.ViewInteraction$2.call(ViewInteraction.java:268)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.support.test.espresso.ViewInteraction$2.call(ViewInteraction.java:265)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.os.Handler.handleCallback(Handler.java:789)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.os.Handler.dispatchMessage(Handler.java:98)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.os.Looper.loop(Looper.java:164)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at java.lang.reflect.Method.invoke(Native Method)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
09-10 00:19:55.808: E/Mbgl-NativeMapView(9685): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
09-10 00:19:55.820: W/ProxyAndroidLoggerBackend(9130): Too many Flogger logs received before configuration. Dropping old logs.
09-10 00:19:55.821: I/chatty(9130): uid=10040(u0_a40) AsyncTask #1 identical 1 line
09-10 00:19:55.822: W/ProxyAndroidLoggerBackend(9130): Too many Flogger logs received before configuration. Dropping old logs.
09-10 00:19:55.841: I/TTS(10225): Creating Google TTS service, version 3.14.12
09-10 00:19:55.848: I/TTS(10225): Loading library tts_android_neon
09-10 00:19:55.853: I/Icing(8925): Post-init done
09-10 00:19:55.907: W/ProxyAndroidLoggerBackend(9130): Too many Flogger logs received before configuration. Dropping old logs.
09-10 00:19:55.918: I/dex2oat(10248): /system/bin/dex2oat --dex-file=/data/data/com.google.android.googlequicksearchbox/files/velour/verified_jars/JxbdCNCcyvM5PJutYFWEdDQ_1.jar --output-vdex-fd=89 --oat-fd=90 --oat-location=/data/data/com.google.android.googlequicksearchbox/files/velour/verified_jars/oat/arm64/JxbdCNCcyvM5PJutYFWEdDQ_1.odex --compiler-filter=quicken
09-10 00:19:55.918: I/dex2oat(10248): --------- beginning of crash
09-10 00:19:55.925: A/libc(9685): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x6f66200c3e092f in tid 9685 (igation.testapp)
09-10 00:19:55.937: I/zygote64(8889): Compiler allocated 5MB to compile void blcl.a(java.lang.Object, bleo)
09-10 00:19:55.947: W/ProxyAndroidLoggerBackend(9130): Too many Flogger logs received before configuration. Dropping old logs.
09-10 00:19:55.984: I/RequestAddCookies(9130): Cookie store not available in HTTP context
09-10 00:19:56.023: I/crash_dump64(10295): obtaining output fd from tombstoned
09-10 00:19:56.024: I//system/bin/tombstoned(690): received crash request for pid 9685
09-10 00:19:56.024: I/crash_dump64(10295): performing dump of process 9685 (target tid = 9685)
09-10 00:19:56.025: A/DEBUG(10295): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-10 00:19:56.025: A/DEBUG(10295): Build fingerprint: 'google/sailfish/sailfish:8.0.0/OPR3.170623.013/4397526:user/release-keys'
09-10 00:19:56.025: A/DEBUG(10295): Revision: '0'
09-10 00:19:56.025: A/DEBUG(10295): ABI: 'arm64'
09-10 00:19:56.025: A/DEBUG(10295): pid: 9685, tid: 9685, name: igation.testapp  >>> com.mapbox.services.android.navigation.testapp <<<
09-10 00:19:56.025: A/DEBUG(10295): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x6f66200c3e092f
09-10 00:19:56.025: A/DEBUG(10295):     x0   0000000000000000  x1   00000070a4ad5900  x2   0000000000000000  x3   00000070a490f41a
09-10 00:19:56.025: A/DEBUG(10295):     x4   0000007ff19d53a0  x5   00000070a4a0d688  x6   0000007088740400  x7   00000070a4ae65a0
09-10 00:19:56.025: A/DEBUG(10295):     x8   000000708bf79380  x9   726f66200c3e0927  x10  00000070a4ad5900  x11  0000000000000005
09-10 00:19:56.025: A/DEBUG(10295):     x12  27bc47bf3fe516d3  x13  0000007088856aa0  x14  00000000ffffffff  x15  0000000000056a80
09-10 00:19:56.025: A/DEBUG(10295):     x16  000000708b9eb768  x17  00000070a7fc8d1c  x18  0000000000000000  x19  000000708899f530
09-10 00:19:56.025: A/DEBUG(10295):     x20  00000070a9256a48  x21  00000070a9256a48  x22  00000070888ce1e0  x23  000000708849258c
09-10 00:19:56.025: A/DEBUG(10295):     x24  00000070a9256a48  x25  0000000000000000  x26  0000000000000000  x27  0000000000000001
09-10 00:19:56.025: A/DEBUG(10295):     x28  0000000000000026  x29  0000007ff19d5530  x30  000000708b659f5c
09-10 00:19:56.025: A/DEBUG(10295):     sp   0000007ff19d5460  pc   000000708b659f64  pstate 0000000060000000
09-10 00:19:56.026: D/VoldConnector(874): SND -> {20 volume mkdirs /storage/emulated/0/Android/data/com.google.android.tts/files/download_cache/}
09-10 00:19:56.028: D/VoldConnector(874): RCV <- {200 20 Command succeeded}
09-10 00:19:56.037: I/ResponseProcessCookies(9130): Cookie store not available in HTTP context
09-10 00:19:56.075: W/ProxyAndroidLoggerBackend(9130): Too many Flogger logs received before configuration. Dropping old logs.
09-10 00:19:56.075: I/chatty(9130): uid=10040(u0_a40) AsyncTask #1 identical 1 line
09-10 00:19:56.077: W/ProxyAndroidLoggerBackend(9130): Too many Flogger logs received before configuration. Dropping old logs.
09-10 00:19:56.090: I/TTS(10225): Voice download for es-us-x-sfb-lstm-embedded dispatched
09-10 00:19:56.090: W/TTS(10225): There is no local voice that can handle this request.
09-10 00:19:56.091: W/TTS(10225): Could not find voice for es
09-10 00:19:56.100: W/ProxyAndroidLoggerBackend(9130): Too many Flogger logs received before configuration. Dropping old logs.
09-10 00:19:56.102: D/DownloadManager(8681): [59] Starting
09-10 00:19:56.120: W/ProxyAndroidLoggerBackend(9130): Too many Flogger logs received before configuration. Dropping old logs.
09-10 00:19:56.217: I/chatty(9130): uid=10040(u0_a40) AsyncTask #1 identical 13 lines
09-10 00:19:56.217: W/ProxyAndroidLoggerBackend(9130): Too many Flogger logs received before configuration. Dropping old logs.
09-10 00:19:56.219: D/NetworkSecurityConfig(8681): No Network Security Config specified, using platform default
09-10 00:19:56.295: W/ProxyAndroidLoggerBackend(9130): Too many Flogger logs received before configuration. Dropping old logs.
09-10 00:19:56.301: A/DEBUG(10295): backtrace:
09-10 00:19:56.301: A/DEBUG(10295):     #00 pc 000000000017df64  /data/app/com.mapbox.services.android.navigation.testapp--OoIvEZudEkUF068uedRmg==/lib/arm64/libmapbox-gl.so
09-10 00:19:56.301: A/DEBUG(10295):     #01 pc 000000000017eb6c  /data/app/com.mapbox.services.android.navigation.testapp--OoIvEZudEkUF068uedRmg==/lib/arm64/libmapbox-gl.so
09-10 00:19:56.301: A/DEBUG(10295):     #02 pc 000000000009f278  /data/app/com.mapbox.services.android.navigation.testapp--OoIvEZudEkUF068uedRmg==/lib/arm64/libmapbox-gl.so
09-10 00:19:56.301: A/DEBUG(10295):     #03 pc 000000000004730c  /data/app/com.mapbox.services.android.navigation.testapp--OoIvEZudEkUF068uedRmg==/lib/arm64/libmapbox-gl.so
09-10 00:19:56.301: A/DEBUG(10295):     #04 pc 00000000000474b8  /data/app/com.mapbox.services.android.navigation.testapp--OoIvEZudEkUF068uedRmg==/lib/arm64/libmapbox-gl.so
09-10 00:19:56.301: A/DEBUG(10295):     #05 pc 0000000000044b28  /data/app/com.mapbox.services.android.navigation.testapp--OoIvEZudEkUF068uedRmg==/lib/arm64/libmapbox-gl.so
09-10 00:19:56.301: A/DEBUG(10295):     #06 pc 0000000000015f1c  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+808)
09-10 00:19:56.301: A/DEBUG(10295):     #07 pc 0000000000015b6c  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+108)
09-10 00:19:56.301: A/DEBUG(10295):     #08 pc 0000000000110e6c  /system/lib64/libandroid_runtime.so (_ZN7androidL38android_os_MessageQueue_nativePollOnceEP7_JNIEnvP8_jobjectli+44)
09-10 00:19:56.301: A/DEBUG(10295):     #09 pc 00000000007ce3ac  /system/framework/arm64/boot-framework.oat (offset 0x5ea000) (android.app.NativeActivity.onWindowFocusChangedNative [DEDUPED]+140)
09-10 00:19:56.301: A/DEBUG(10295):     #10 pc 000000000002c598  /dev/ashmem/dalvik-jit-code-cache (deleted)
```

Thanks for flagging @tobrun 🙏 

Closing here as duplicated.
