### ISSUE TITLE
Navigation Launcher crashes

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-navigation-android#1349]
While testing out https://github.com/mapbox/mapbox-navigation-android/commit/772ea4a0282d0a9d96e049ff6746cfc67ec0c953 with https://github.com/mapbox/mapbox-navigation-android/pull/1348. I'm often, not always, hitting the following crash after clicking `Launch Navigation` in `Navigation Launcher`:

```
2018-09-29 14:53:03.425 27999-28782/com.mapbox.services.android.navigation.testapp E/AndroidRuntime: FATAL EXCEPTION: mapbox_navigation_thread
  Process: com.mapbox.services.android.navigation.testapp, PID: 27999
  java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.location.Location.mProvider' on a null object reference
  at android.location.Location.set(Location.java:166)
  at android.location.Location.<init>(Location.java:159)
  at com.mapbox.services.android.navigation.v5.snap.SnapToRoute.buildSnappedLocation(SnapToRoute.java:23)
  at com.mapbox.services.android.navigation.v5.snap.SnapToRoute.getSnappedLocationWith(SnapToRoute.java:18)
  at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable.findSnappedLocation(RouteProcessorRunnable.java:84)
  at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable.process(RouteProcessorRunnable.java:61)
  at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable.run(RouteProcessorRunnable.java:44)
  at android.os.Handler.handleCallback(Handler.java:789)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:164)
  at android.os.HandlerThread.run(HandlerThread.java:65)
```

Tested on Samsung s9 running Android 8.0.0

**Comment by tobrun** [comment]
Can't think of a valid reason why this crash occurs, this could be a potential device specific issue. Only workarounds I'm currently seeing is to use the `Location(String provider)` constructor instead and provide the location data, that is currently provided by the constructor, with `Location#set(Location location)` instead.

**Comment by tobrun** [comment]
misread the stacktrace, it seems that provided Location object is null. Suggestion from https://github.com/mapbox/mapbox-navigation-android/issues/1349#issuecomment-425644097 won't change this.
