### ISSUE TITLE
Mute click crash beta.1

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-navigation-android#1368]
Crash when clicking mute button:

```
'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.20.0-beta.1'
```

>  Process: com.mapbox.logistics_example, PID: 14239
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.setMuted(boolean)' on a null object reference
        at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView$5.onClick(InstructionView.java:541)
        at com.mapbox.services.android.navigation.ui.v5.MultiOnClickListener.onClick(MultiOnClickListener.java:30)
        at android.view.View.performClick(View.java:6296)
        at android.view.View$PerformClick.run(View.java:24781)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by Guardiola31337** [comment]
@tobrun 
Could you retest this with the final release version [`v0.20.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.20.0)? Should be fixed by https://github.com/mapbox/mapbox-navigation-android/pull/1362

**Comment by tobrun** [comment]
It doesn't crash but it's not muting atm

**Comment by Guardiola31337** [comment]
Note that the APIs usage changed, won't do anything until you subscribe to `NavigationViewModel` or add a listener explicitly 👀 https://github.com/mapbox/mapbox-navigation-android/blob/f26de52248478824e94de1142f880d1902ca7b54/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/RerouteActivity.java#L93-L95

**Comment by tobrun** [comment]
just found: 

```
        // TODO get fix from SDK
//    val soundButton = instructionView.retrieveSoundButton()
//    soundButton.addOnClickListener { presenter.onSoundButtonClick(it as SoundButton) }
```

closing
