### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1413]
I've noticed the below crash in my crashlytics - http://crashes.to/s/7b7f531f9e1

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 4, size is 3
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
       at java.util.ArrayList.get(ArrayList.java:304)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.updateSteps(NavigationRouteProcessor.java:236)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.processNewIndex(NavigationRouteProcessor.java:186)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.advanceIndices(NavigationRouteProcessor.java:160)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.checkManeuverCompletion(NavigationRouteProcessor.java:145)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.buildNewRouteProgress(NavigationRouteProcessor.java:82)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback.handleRequest(RouteProcessorHandlerCallback.java:49)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorHandlerCallback.handleMessage(RouteProcessorHandlerCallback.java:33)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Comment by Guardiola31337** [comment]
Hey @Danny-James 👋 thanks for reaching out and report your issue.

Could you add some more information about the Mapbox Navigation SDK version used here? This will give us better insight into your implementation and what could be causing your problem.

**Comment by Danny-James** [comment]
@Guardiola31337 Sorry I forgot to include that.

```java
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.20.0') {
        transitive = true
        changing = true
    }
```

**Comment by Guardiola31337** [comment]
Current release version is [`0.21.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.21.0). To confirm that the issue is still present in the latest version, would you mind retesting it using `0.21.0` version?

**Comment by Danny-James** [comment]
@Guardiola31337 I will give that ago and report back to you.

**Comment by Guardiola31337** [comment]
> I will give that ago and report back to you.

Thanks a lot @Danny-James 🙏

**Comment by danesfeder** [comment]
@Danny-James noting here that the code that this is crashing on no longer exists in `0.20.0` or `0.21.0`. 

I can't see the release version in Crashlytics, but maybe it's a version of the app using an older version of the SDK.  Thanks for testing out the newest version!

**Comment by Danny-James** [comment]
@danesfeder, I believe the error was coming from Version `18.0`.

I'm now using version `21.0` so will let you know of any issues :) Thanks for the fast response guys as always

**Comment by Danny-James** [comment]
@danesfeder This issue is still present using `Version 21.0`

http://crashes.to/s/4aa54a6fe99

**Comment by danesfeder** [comment]
@Danny-James where does it indicate `0.21.0`?  Sorry I don't see it in the dashboard

**Comment by Danny-James** [comment]
@danesfeder this crash happened on Version 1.3.3 of my app which was pushed yesterday with `version 21.0` of the SDK.

**Comment by danesfeder** [comment]
@Danny-James got it, thank you 

Updated crash relevant to current code:
```

java.util.ArrayList.throwIndexOutOfBoundsException (ArrayList.java:251)
--
  | java.util.ArrayList.get (ArrayList.java:304)
  | com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.updateSteps (NavigationRouteProcessor.java:105)
  | com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.buildRouteProgressFrom (NavigationRouteProcessor.java:64)
  | com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.buildNewRouteProgress (NavigationRouteProcessor.java:42)
  | com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable.process (RouteProcessorRunnable.java:58)
  | com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable.run (RouteProcessorRunnable.java:44)


```
