### ISSUE TITLE
FATAL EXCEPTION: main java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1422]
I'm using the `Motorola TC55` and i'm coming across lots of `OutOfMemoryError `

I get this error regular, how i get this is;

If I call my `fetchRoute` method shown below and I don't receive a `successful match` I remove the last coordinate in my points list and then recall `fetchRoute`, this continues until I find a valid route, I believe this worked in `v-18.0`

```java
    private void fetchRoute(boolean showProgress, boolean routeFromCurrentLocation) {

        Log.d(TAG, "Start fetchRoute();");
        mIsFetchingRoute = true;

        if (routeFromCurrentLocation && getLastKnownLocation() != null){
            points.add(0, getLastKnownLocation());
        }

        pointsSize = points.size();
        if (pointsSize > 1){
            // Split Out CoOrdinates In To
            if (pointsSize > MAPMATCHING_LIMIT) {
                pointsSize = MAPMATCHING_LIMIT;
            }

            List<Point> subList = points.subList(0, pointsSize);

            if (showProgress) {
                Log.d(TAG, "Show Progress Dialog - Building Navigation Route.");
                // Display Progress Window For Map Matching.
                mProgressDialog = new ProgressDialog(ActivityNavigation.this);
                mProgressDialog.setCancelable(false);
                //progressDialog.setIcon(R.mipmap.ic_launcher);
                mProgressDialog.setMessage("Building Navigation Route...");
                mProgressDialog.setTitle("Please wait");
                mProgressDialog.setIndeterminate(true);
                mProgressDialog.show();
            }



            MapboxMapMatching.Builder mapMatchingBuilder = MapboxMapMatching.builder()
                    .accessToken(Mapbox.getAccessToken())
                    .coordinates(subList)
                    .steps(true)
                    .tidy(false)
                    .voiceInstructions(true)
                    .bannerInstructions(true)
                    .language(Locale.getDefault().getLanguage())
                    .voiceUnits(DirectionsCriteria.IMPERIAL)
                    .waypoints(0, (pointsSize - 1))
                    .profile(DirectionsCriteria.PROFILE_DRIVING);

            // Calculate Reroute Coordinate
            if (pointsSize == MAPMATCHING_LIMIT){
                Point mReRouteCoordinate = subList.get(REROUTE_COORDINATE);
                Point lastCoordinate = subList.get((pointsSize - 1));
                REROUTE_DISTANCE = distance(mReRouteCoordinate.latitude(), mReRouteCoordinate.longitude(), lastCoordinate.latitude(), lastCoordinate.longitude());
            }


            if (pointsSize > 1) {
                mapMatchingBuilder.build().enqueueCall(new Callback<MapMatchingResponse>() {
                    @Override
                    public void onResponse(Call<MapMatchingResponse> call, Response<MapMatchingResponse> response) {
                        if (response.isSuccessful()) {
                            Log.d(TAG,response.message());
                            if (response.body().matchings().size() > 0) {

                                Log.d(TAG,"MapMatching Completed Successfully.");

                                // Reset firstFetch
                                firstFetch = false;

                                if (mProgressDialog.isShowing()){
                                    mProgressDialog.dismiss();
                                }
                                startNavigation(response.body().matchings().get(0).toDirectionRoute());

                                // Add Current Route Points To List, Used For OffRoute Logic
                                if (currentRoutePoints.size() > 0){
                                    currentRoutePoints.clear();
                                }

                                // Remove Navigated Points From Array.
                                // At This Point, Remove All Passed Coordinates From Master List.
                                if (pointsSize == MAPMATCHING_LIMIT) {
                                    //currentRoutePoints.addAll(points.subList(0, REROUTE_COORDINATE));
                                    points.subList(0,  REROUTE_COORDINATE).clear();
                                }else{
                                    //currentRoutePoints.addAll(points.subList(0, pointsSize - 1));
                                    points.subList(0, pointsSize).clear();
                                }

                            }else{
                                // Used To Remove First or Last Coordinate TO Enable FetchRoute To Run Again.
                                // Used For When MapMatching Has Issue Plotting Route Because Of An Off Coordinate.
                                if (points.size() > 1) {
                                    if (firstFetch) {
                                        Log.d(TAG, "Remove First Point: " + points.get(0));
                                        points.remove(0);
                                    } else {
                                        Log.d(TAG, "Remove Last Point: " + points.get(points.size() - 1));
                                        points.remove(points.size() - 1);
                                    }
                                    Log.d(TAG,"Attempting To Get Route Again...");
                                    fetchRoute(false, false);
                                }else {
                                    showUnableToRouteDialog("Unable to plot route. \n\n Issue with MapMatching Request.");
                                    Log.e(TAG,"No Matching Available");
                                }
                            }
                        }else{
                            showUnableToRouteDialog("Unable to plot route. \n\n Unsuccessful Response. ");
                            Log.e(TAG,response.message());
                        }
                    }

                    @Override
                    public void onFailure(Call<MapMatchingResponse> call, Throwable t) {
                        showUnableToRouteDialog("Unable to plot route. \n\n" + t.getMessage());
                        //navigationView.stopNavigation();
                        Log.e(TAG, t.getMessage());
                    }
                });
            }
        }else{
            Log.e(TAG,"No Coordinates Passed Into Navigation.");
            showUnableToRouteDialog("Unable to plot route.");
        }

        mIsFetchingRoute = false;
    }
```

Error Log

```
10-16 13:10:36.586 13532-13532/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.OutOfMemoryError
        at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:94)
        at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:132)
        at java.lang.StringBuilder.append(StringBuilder.java:124)
        at okhttp3.HttpUrl$Builder.toString(HttpUrl.java:1291)
        at okhttp3.HttpUrl.<init>(HttpUrl.java:351)
        at okhttp3.HttpUrl$Builder.build(HttpUrl.java:1256)
        at retrofit2.RequestBuilder.build(RequestBuilder.java:193)
        at retrofit2.ServiceMethod.toCall(ServiceMethod.java:113)
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:184)
        at retrofit2.OkHttpCall.enqueue(OkHttpCall.java:95)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.enqueue(ExecutorCallAdapterFactory.java:62)
        at com.mapbox.api.matching.v5.MapboxMapMatching.enqueueCall(MapboxMapMatching.java:142)
        at uk.co.ainscough.routeinfo.ActivityNavigation.fetchRoute(ActivityNavigation.java:624)
        at uk.co.ainscough.routeinfo.ActivityNavigation.access$900(ActivityNavigation.java:57)
        at uk.co.ainscough.routeinfo.ActivityNavigation$1.onResponse(ActivityNavigation.java:668)
        at com.mapbox.api.matching.v5.MapboxMapMatching$1.onResponse(MapboxMapMatching.java:152)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:615)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4895)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
        at dalvik.system.NativeStart.main(Native Method)

```

**Comment by danesfeder** [comment]
This looks like an issue when building the URL to make the map-matching request (which I believe we've discussed earlier).  

Let's continue to track in https://github.com/mapbox/mapbox-java/issues/893 as this code is not actionable within this repository.  We will talk to the rest of the team about `893` and see where it fits in our current pipeline of work.  Thanks for your patience @Danny-James.

**Comment by Danny-James** [comment]
@danesfeder i have not got anywhere with this issue is their any chance you could chase the guys on your side please?
