### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Receiver not registered

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1439]
Hi Guys, Forgive me if this isn't anything to do with Mapbox however, I've come across the below Crash, I'm not using receivers in my application so i'm not sure why I've come across this fatal error.

**My App Details**
```
AppVersionCode | 6
AppVersionName | 1.3.3
MapboxNavgigationSDK | mapbox-navigation-android/0.21.0
```

**Crash Log** - http://crashes.to/s/4dd27cccddf
```
Fatal Exception: java.lang.IllegalArgumentException: Receiver not registered: android.support.v7.app.AppCompatDelegateImplV14$AutoNightModeManager$1@41ac5ef0
       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:654)
       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1370)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:452)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:452)
       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:452)
       at android.support.v7.app.AppCompatDelegateImplV14$AutoNightModeManager.cleanup(AppCompatDelegateImplV14.java:371)
       at android.support.v7.app.AppCompatDelegateImplV14.onStop(AppCompatDelegateImplV14.java:135)
       at android.support.v7.app.AppCompatDialog.onStop(AppCompatDialog.java:123)
       at android.app.Dialog.dismissDialog(Dialog.java:326)
       at android.app.Dialog.dismiss(Dialog.java:302)
       at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:170)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4895)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by Danny-James** [comment]
@danesfeder do i need to make any changes to my code when I move to `0.21.0`?
