### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Duration must be greater than zero.

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#1449]
I've come across another Fatal Exception. - If you require anymore information do let me know - http://crashes.to/s/d4461ae59e6

```
Fatal Exception: java.lang.IllegalArgumentException: Duration must be greater than zero.
       at com.mapbox.services.android.navigation.v5.utils.time.TimeFormatter.formatTimeRemaining(TimeFormatter.java:36)
       at com.mapbox.services.android.navigation.ui.v5.summary.SummaryModel.<init>(SummaryModel.java:25)
       at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel$1.onProgressChange(NavigationViewModel.java:301)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:144)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onNewRouteProgress(RouteProcessorThreadListener.java:34)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable$1.run(RouteProcessorRunnable.java:119)
       at android.os.Handler.handleCallback(Handler.java:615)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4895)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by danesfeder** [comment]
Hey @Danny-James this should be fixed on our part - you can confirm with `0.22.0-SNAPSHOT` https://github.com/mapbox/mapbox-navigation-android/pull/1425/
