### ISSUE TITLE
TurfException during navigation with mock position app 

### ISSUE THREAD

**Issue by nicomazz** [mapbox/mapbox-navigation-android#149]
During a navigation, after short time, the following exception is always thrown. It seems this problem always occurs immediately before a turn.
I'm using version 0.4.0 and an app to simulate navigation path (not MockLocationEngine)
```
 EXCEPTION: main
com.mapbox.services.api.utils.turf.TurfException: Start and stop points in Turf lineSlice cannot equal each other.
    at com.mapbox.services.api.utils.turf.TurfMisc.lineSlice(TurfMisc.java:58)
    at com.mapbox.services.android.navigation.v5.routeprogress.RouteStepProgress.getDistanceRemaining(RouteStepProgress.java:71)
    at com.mapbox.services.android.navigation.v5.milestone.TriggerProperty.getSparseArray(TriggerProperty.java:77)
    at com.mapbox.services.android.navigation.v5.milestone.StepMilestone.isOccurring(StepMilestone.java:32)
    at com.mapbox.services.android.navigation.v5.NavigationEngine.onLocationChanged(NavigationEngine.java:102)
    at com.mapbox.services.android.navigation.v5.NavigationService.onLocationChanged(NavigationService.java:243)
    at com.mapbox.services.android.location.LostLocationEngine.onLocationChanged(LostLocationEngine.java:145)
    at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.reportLocation(FusedLocationProviderApiImpl.java:121)
    at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:134)
    at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:297)
    at android.location.LocationManager$ListenerTransport.-wrap0(LocationManager.java)
    at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:242)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6776)

                                                                                 at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by samvgorode** [comment]
The same for me 
```
E/UncaughtException: com.mapbox.services.api.utils.turf.TurfException: Turf lineSlice requires a LineString made up of at least 2 coordinates.
                                                                        at com.mapbox.services.api.utils.turf.TurfMisc.lineSlice(TurfMisc.java:56)
                                                                        at com.mapbox.services.android.navigation.v5.NavigationEngine.calculateSnappedDistanceToNextStep(NavigationEngine.java:214)
                                                                        at com.mapbox.services.android.navigation.v5.NavigationEngine.onLocationChanged(NavigationEngine.java:94)
                                                                        at com.mapbox.services.android.navigation.v5.NavigationService.onLocationChanged(NavigationService.java:243)
                                                                        at com.mapbox.services.android.location.LostLocationEngine.onLocationChanged(LostLocationEngine.java:145)
                                                                        at com.mapzen.android.lost.internal.FusedLocationProviderApiImpl.reportLocation(FusedLocationProviderApiImpl.java:121)
                                                                        at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:134)
                                                                        at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:285)
                                                                        at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:214)
                                                                        at android.location.LocationManager$ListenerTransport$1.handleMessage(LocationManager.java:230)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
```

**Comment by samvgorode** [comment]
**nicomazz**, man, what app do you use for the fake navigation? I use "Lockito".

**Comment by nicomazz** [comment]
I use "Mock Locations (fake GPS path)"

**Comment by samvgorode** [comment]
Today I've noticed that crashes are almost before rotaries on the road, like a circle traffic. What do you think? Do you have the same situation?

**Comment by nicomazz** [comment]
Yes, same situation! I've the same problem with some gpx "running" on the emulator. I'll try soon if with the real GPS signal the problem persist.Il 03 ago 2017 11:56, Eugene <notifications@github.com> ha scritto:Today I've noticed that crashes are almost before rotaries on the road, like a circle traffic. What do you think? Do you have the same situation?

**Comment by nicomazz** [comment]
I have tested the navigator with a real gps signal in the car (with a passenger).
Initially, for the first half hour, as long as I was on the highway, no crash.
Exiting the highway, near a few turns the problem reappeared.

**Comment by cammace** [comment]
I'm thinking I might have fixed this issue in https://github.com/mapbox/mapbox-navigation-android/pull/151 but to confirm, could either of you guys provide the rotary/circle location coordinates so I can write some test?

**Comment by samvgorode** [comment]
Do we need to add another version of 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.4.0'? what version is actual for now?

**Comment by samvgorode** [comment]
LAT 48.620852692441055 LON 22.28801448740184 here I have the crash.
`java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.services.api.directions.v5.models.StepManeuver com.mapbox.services.api.directions.v5.models.LegStep.getManeuver()' on a null object reference` 
That happens when I use 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.4.0-SNAPSHOT'

**Comment by samvgorode** [comment]
For '**com.mapbox.mapboxsdk:mapbox-android-navigation:0.4.0**' (without SNAPSHOT) I have this:
```
E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Number com.google.gson.JsonElement.getAsNumber()' on a null object reference
                                                                        at com.mapbox.services.commons.geojson.Feature.getNumberProperty(Feature.java:231)
                                                                        at com.mapbox.services.api.utils.turf.TurfMisc.lineSlice(TurfMisc.java:58)
                                                                        at com.mapbox.services.android.navigation.v5.NavigationEngine.calculateSnappedDistanceToNextStep(NavigationEngine.java:214)
                                                                        at com.mapbox.services.android.navigation.v5.NavigationEngine.onLocationChanged(NavigationEngine.java:94)
                                                                        at com.mapbox.services.android.navigation.v5.NavigationService.forceLocationUpdate(NavigationService.java:168)
                                                                        at com.mapbox.services.android.navigation.v5.NavigationService.startRoute(NavigationService.java:156)
                                                                        at com.mapbox.services.android.navigation.v5.MapboxNavigation$NavigationServiceConnection.onServiceConnected(MapboxNavigation.java:485)
                                                                        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1225)
                                                                        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1242)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by nicomazz** [comment]
Steps to reproduce my problem (0.4.0-SNAPSHOT):

1. Get the route 
   from: LatLng [latitude=45.649085, longitude=12.309151, altitude=0.0] 
   to: LatLng [latitude=45.6108265, longitude=12.4517827, altitude=0.0]
2. mockLocationEngine.setRoute(route)
3. start navigation

Once started, it immediately crash with 
```
FATAL EXCEPTION: main
com.mapbox.services.api.utils.turf.TurfException: Turf lineSlice requires a LineString made up of at least 2 coordinates.
    at com.mapbox.services.api.utils.turf.TurfMisc.lineSlice(TurfMisc.java:56)
    at com.mapbox.services.android.navigation.v5.NavigationEngine.calculateSnappedDistanceToNextStep(NavigationEngine.java:214)
    at com.mapbox.services.android.navigation.v5.NavigationEngine.onLocationChanged(NavigationEngine.java:94)
    at com.mapbox.services.android.navigation.v5.NavigationService.onLocationChanged(NavigationService.java:243)
    at com.mapbox.services.android.location.MockLocationEngine$LocationUpdateRunnable.run(MockLocationEngine.java:370)
    at android.os.Handler.handleCallback(Handler.java:751)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:154)
    at android.app.ActivityThread.main(ActivityThread.java:6776)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

My start navigation:
```
        navigation.addNavigationEventListener(this)
        navigation.addProgressChangeListener(this)
        navigation.addMilestoneEventListener(this)
        navigation.addOffRouteListener(this)
        navigation.setLocationEngine(mockLocationEngine)
        navigation.setSnapToRoute(true)
        navigation.startNavigation(route)
```

**Comment by davols** [comment]
Started to get this issue as well. 

Using 0.4 snapshot. Yesterday I did around 20 plays in Lockito with a route and it never crashed. However that route in lockito got bugged so I create a new one, that is the same street and length wise it have started to crash. Seems to be related to the path and lockito for me.

**Comment by mKenfenheuer** [comment]
same problem here 


`FATAL EXCEPTION: main
                                                                                 Process: com.kenfenheuer.whereismydevice, PID: 26704
                                                                                 com.mapbox.services.api.utils.turf.TurfException: Start and stop points in Turf lineSlice cannot equal each other.
                                                                                     at com.mapbox.services.api.utils.turf.TurfMisc.lineSlice(TurfMisc.java:58)
                                                                                     at com.mapbox.services.android.navigation.v5.NavigationEngine.calculateSnappedDistanceToNextStep(NavigationEngine.java:214)
                                                                                     at com.mapbox.services.android.navigation.v5.NavigationEngine.onLocationChanged(NavigationEngine.java:94)
                                                                                     at com.mapbox.services.android.navigation.v5.NavigationService.onLocationChanged(NavigationService.java:243)
                                                                                     at com.mapbox.services.android.location.MockLocationEngine$LocationUpdateRunnable.run(MockLocationEngine.java:370)
                                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)`

**Comment by nicomazz** [comment]
With 0.5.0-SNAPSHOT I've never run into the problem again

**Comment by samvgorode** [comment]
**nicomazz**, I can't find `navigation.getRoute` method with callback,  in the new `0.5.0-SNAPSHOT` , could you please help me with this? Also, I can't find `NavigationMapRoute` and `LocationLayer`, do you use smth esle instead of this? How do you draw your route on map? With polyline?

**Comment by samvgorode** [comment]
Oh, I've found an answer for `navigation.getRoute`, this is it
```
private void getRoute(Position origin, Position destination) {
        NavigationRoute navigationRoute = NavigationRoute.builder()
                .origin(origin)
                .destination(destination)
                .accessToken(Mapbox.getAccessToken())
                .build();
        navigationRoute.getRoute(this);
    }
```
But, still question about `NavigationMapRoute` and `LocationLayer`, does anyone know how to import these classes?

**Comment by samvgorode** [comment]
I still have a crash in the finish of the navigation in **0.5.0-SNAPSHOT**
```
E/UncaughtException: java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
                                                                        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                        at java.util.ArrayList.get(ArrayList.java:308)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.DefaultMilestones$2.buildInstruction(DefaultMilestones.java:59)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.buildInstructionString(NavigationHelper.java:61)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onMilestoneTrigger(NavigationService.java:197)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:79)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by cammace** [comment]
@samvgorode, you shouldn't be getting a crash when using the `NavigationRoute` builder, can you post a logcat output here so I can troubleshoot this. Essentially the `NavigationRoute` class is a wrapper around the MapboxDirections ensuring some of the parameters are setup correctly.

**Comment by samvgorode** [comment]
Now everything is good with `NavigationRoute`. Problem dissapeared by itself.
