### ISSUE TITLE
Running real machine, The console prints the following information

### ISSUE THREAD

**Issue by giantss** [mapbox/mapbox-navigation-android#1512]
```
11-09 14:29:30.648 11921-11921/com.mapbox.services.android.navigation.testapp E/Mbgl-NativeMapView: Exception in MapView.OnMapChangedListener
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at java.util.ArrayList.get(ArrayList.java:413)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addDirectionWaypoints(NavigationMapRoute.java:453)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.onMapChanged(NavigationMapRoute.java:1019)
        at com.mapbox.mapboxsdk.maps.MapView$6.onMapChanged(MapView.java:334)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:917)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:999)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:328)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6802)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```
Running real machine, The console prints the following information
```11-09 14:21:22.389 11473-11473/com.mapbox.services.android.navigation.testapp W/RenderThread: type=1400 audit(0.0:9164): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
11-09 14:21:22.893 11473-11473/com.mapbox.services.android.navigation.testapp W/RenderThread: type=1400 audit(0.0:9165): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
11-09 14:21:23.393 11473-11473/com.mapbox.services.android.navigation.testapp W/RenderThread: type=1400 audit(0.0:9166): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
11-09 14:21:23.893 11473-11473/com.mapbox.services.android.navigation.testapp W/RenderThread: type=1400 audit(0.0:9167): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
11-09 14:21:24.401 11473-11473/com.mapbox.services.android.navigation.testapp W/RenderThread: type=1400 audit(0.0:9168): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
11-09 14:21:24.897 11473-11473/com.mapbox.services.android.navigation.testapp W/RenderThread: type=1400 audit(0.0:9169): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
11-09 14:21:25.397 11473-11473/com.mapbox.services.android.navigation.testapp W/RenderThread: type=1400 audit(0.0:9170): avc: denied { read } for name="boot_mode" dev="sysfs" ino=5287 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0```

**Comment by Guardiola31337** [comment]
Hey @giantss 👋 Thanks for reaching out and report your problem.

Could you add some more information for reproducing the crash (minimal example) or any other specifics around your test setup? What version of the SDK are you using? Do you have some more information on used device? If there is any sample or pseudo code you can provide, that would be really helpful and it'll give us better insight into your implementation and what could be causing your problem.

**Comment by Guardiola31337** [comment]
Thanks for your response @giantss 🙏 

As commented above, could you describe your use case in detail?

> Could you add some more information for reproducing the crash (minimal example) or any other specifics around your test setup? What version of the SDK are you using? If there is any sample or pseudo code you can provide, that would be really helpful and it'll give us better insight into your implementation and what could be causing your problem.

**Comment by danesfeder** [comment]
Hey @giantss 👋 thanks for reporting this.  The exception looks to be cause by [this code](https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/route/NavigationMapRoute.java#L453), where we are assuming the `featureCollection` list always contains a value.  It looks like in map reload scenarios, this may not always be the case.

I will make sure to address this ticket as a part of #1387 if it hasn't been addressed already.  Please stay tuned for that PR landing and thanks for your patience!

**Comment by danesfeder** [comment]
Hey @giantss, thanks for the steps - we are able to reproduce and will check in a fix soon / update this ticket after.  Thank you for your patience.

**Comment by Guardiola31337** [comment]
#1539 was opened to address OP.
