### ISSUE TITLE
Can’t start turn-by-turn navigation within custom NavigationViewActivity/NavigationViewFragment

### ISSUE THREAD

**Issue by JaninaMattes** [mapbox/mapbox-navigation-android#1524]
Hey, I implemented the custom NavigationActivity following part of the example in the Mapbox documentation and can show the navigation UI as map so far but can't start the navigation itself nor show the user’s location. The same problem exists when implementing it via a NavigationFragment. How can I pass the missing information when I call my NavigationActivity/NavigationFragment from my MainActivity and start the navigation correctly? Thanks a lot for any help!

I create the directionsRoute and call navigationView.startNavigation(options) with NavigationViewOptions.builder() like this:

```
fun onNavigationReady(isRunning: Boolean) {
...
calculateRoute(origin, destination)
} 
private fun calculateRoute(origin: Point , destination: Point) {
       NavigationRoute.builder(this.context)
               .accessToken(Mapbox.getAccessToken()!!)
               .origin(origin)
               .destination(destination)
               .build()
               .getRoute( object : Callback<DirectionsResponse> {
                   // Send request to Direction API
                   override fun onFailure(call: Call<DirectionsResponse>? , t: Throwable?) {
                   }
                   override fun onResponse(call: Call<DirectionsResponse>? ,
                                           response: Response<DirectionsResponse>?) {
                       if (response?.body() == null || response.body()?.routes()?.size!! < 1) {
                           return
                       }
                       directionsRoute = response.body()!!.routes()[0]
                       startNavigation()
                   }
               })
   }

private fun startNavigation() {
       if (directionsRoute == null) return
       val options = NavigationViewOptions.builder()
               .directionsRoute(directionsRoute)
               .shouldSimulateRoute(true)
               .navigationListener(this)
               .build()

       navigationView.startNavigation(options)
   }
```

**Comment by danesfeder** [comment]
Hey @JaninaMattes 👋 I don't see anything immediately wrong with this code.  Which version of the SDK are you using?  

> but can't start the navigation itself nor show the user’s location

Would can you post a screenshot or gif of the behavior you're seeing?  This will help us debug, thanks!

**Comment by danesfeder** [comment]
Hey @JaninaMattes 👋 it looks like the SDK version you're using is pretty dated (`0.15.0`).  Would you mind updating to `0.23.0` and giving this another shot?  Is there anything blocking you from updating to `0.23.0`?

**Comment by JaninaMattes** [comment]
Hi, yes actually I tried to update all versions and run into an issue with
gradle.build file mainly caused by the appcompat version I am implementing
in my dependencies. I will have another look into it.

**Comment by JaninaMattes** [comment]
adding url 'https://mapbox.bintray.com/mapbox' to my build.script helped and solved the above mentioned problem.
```
allprojects {
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url 'https://mapbox.bintray.com/mapbox' }
    }
}
```

But still I can't start turn-by-turn navigation in my NavigationFragment. 

`2018-11-13 15:28:03.704 3928-3928/com.app_map_box_map_nav E/Mbgl-NativeMapView: Exception in MapView.OnMapChangedListener
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at java.util.ArrayList.get(ArrayList.java:439)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addDirectionWaypoints(NavigationMapRoute.java:453)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.onMapChanged(NavigationMapRoute.java:1019)
        at com.mapbox.mapboxsdk.maps.MapView$6.onMapChanged(MapView.java:334)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:917)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:999)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
`

**Comment by danesfeder** [comment]
Hey @JaninaMattes yeah this was a good catch and a 🐛 on our part - we just merged #1530 to address this.  You can test this now by compiling a `SNAPSHOT` of our SDK https://github.com/mapbox/mapbox-navigation-android#using-snapshots

The fix is available in that version (`0.24.0-SNAPSHOT`).  If this fixes your issue, then I think we can go ahead and close here.

**Comment by JaninaMattes** [comment]
Hey @danesfeder 👍 thank you for the quick fix I added the `SNAPSHOT ` of your SDK but I am running into the same error again. 

I added the dependency to my project gradle.build file:

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://mapbox.bintray.com/mapbox' }
        maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    }
}
```
And into my app build.gradle file:

```
dependencies {
  implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.24.0-SNAPSHOT'
}
```

```
2018-11-14 10:09:43.943 29035-29035/com.bmwgroup.app_map_box_map_nav E/Mbgl-NativeMapView: Exception in MapView.OnMapChangedListener
    java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
        at java.util.ArrayList.get(ArrayList.java:413)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addDirectionWaypoints(NavigationMapRoute.java:453)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.onMapChanged(NavigationMapRoute.java:1019)
        at com.mapbox.mapboxsdk.maps.MapView$6.onMapChanged(MapView.java:334)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:917)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:999)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by danesfeder** [comment]
Hey @JaninaMattes 👋 the `ArrayIndexOutOfBoundsException` you're seeing was fixed by https://github.com/mapbox/mapbox-navigation-android/pull/1530.  Stay tuned for the upcoming release which should land this week.  You can also test this fix with the `SNAPSHOT`.  Thanks for your patience 👍

**Comment by Kbt1737** [comment]
Can we customize navigationlauncher.Startnavigation activity?

**Comment by Adityasai1431** [comment]
Hey @kbt77722 did you implement turn-by-turn navigation?
Please let me know, I can't complete mine.
Please help me.
