### ISSUE TITLE
I start a navigation UI on button click but it start and crash 

### ISSUE THREAD

**Issue by aecarlosae** [mapbox/mapbox-navigation-android#1528]
here is my code

```
>  new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                boolean simulateRoute = true;
                NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                        .directionsRoute(currentRoute)
                        .shouldSimulateRoute(simulateRoute)
                        .build();
                // Call this method with Context from within an Activity
                NavigationLauncher.startNavigation(DefaultHomeActivity.this, options);
            }
        }
```
on button click application crash and gives this error

11-13 13:07:03.413 14142-14142/com.exampledom.examplemapbox E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.exampledom.examplemapbox, PID: 14142
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Intent android.content.Intent.setPackage(java.lang.String)' on a null object reference
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.createPendingOpenIntent(MapboxNavigationNotification.java:147)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.initialize(MapboxNavigationNotification.java:93)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationNotification.<init>(MapboxNavigationNotification.java:63)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.buildNotificationFrom(NavigationNotificationProvider.java:40)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.<init>(NavigationNotificationProvider.java:14)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initializeNotificationProvider(NavigationService.java:107)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initialize(NavigationService.java:93)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.startNavigation(NavigationService.java:65)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.onServiceConnected(MapboxNavigation.java:724)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

kindly help on this issue

_Originally posted by @Meerz in https://github.com/mapbox/mapbox-navigation-android/issues/831#issuecomment-386513534_

**Comment by danesfeder** [comment]
Hey @aecarlosae this was previously caused by a naming clash.  The Navigation SDK includes a `NavigationActivity` in addition to the one that it looks like you're creating.  So `NavigationLauncher` is trying to launch your `NavigationActivity` causing the crash.  We have since updated to `MapboxNavigationActivity`.  Updating to `0.23.0` should help fix this.  

Here is the latest example code as well: https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationLauncherActivity.java#L334-L343

**Comment by aecarlosae** [comment]
@danesfeder I have the Updating 0.23.0 and the problem is there. Look, the NavigationLauncher.startNavigation(DefaultHomeActivity.this, options); launch the navigation but this crash immediately. I have renamed my Activity but the same problem

**Comment by jhoncho** [comment]
tengo el mismo inconveniente este es mi codigo.
 public void startNavigationBtnClick(View v)
    {
        boolean simulateRoute = false;
        NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                .directionsRoute(currentRoute)
                .shouldSimulateRoute(simulateRoute)
                .build();
        NavigationLauncher.startNavigation(MainActivity.this, options);
    }

-*-*-*-*
y este es el error que me arroja
2019-07-05 09:27:35.230 21699-21699/com.bayoex.navega E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bayoex.navega, PID: 21699
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:390)
        at android.view.View.performClick(View.java:6291)
        at android.view.View$PerformClick.run(View.java:24931)
        at android.os.Handler.handleCallback(Handler.java:808)
        at android.os.Handler.dispatchMessage(Handler.java:101)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385)
        at android.view.View.performClick(View.java:6291) 
        at android.view.View$PerformClick.run(View.java:24931) 
        at android.os.Handler.handleCallback(Handler.java:808) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921) 
     Caused by: java.lang.NullPointerException: Null directionsRoute
        at com.mapbox.services.android.navigation.ui.v5.AutoValue_NavigationLauncherOptions$Builder.directionsRoute(AutoValue_NavigationLauncherOptions.java:168)
        at com.bayoex.navega.MainActivity.startNavigationBtnClick(MainActivity.java:73)
        at java.lang.reflect.Method.invoke(Native Method) 
        at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:385) 
        at android.view.View.performClick(View.java:6291) 
        at android.view.View$PerformClick.run(View.java:24931) 
        at android.os.Handler.handleCallback(Handler.java:808) 
        at android.os.Handler.dispatchMessage(Handler.java:101) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
