### ISSUE TITLE
NavigationLauncherOptions

### ISSUE THREAD

**Issue by Anurag26** [mapbox/mapbox-navigation-android#1659]
**Android API: 
Target and compiled SDKversion:27
Min SDK:21**
**Mapbox Navigation SDK version:
Navigation and Navigation-ui: 0.13.0
SDK:6.0.1**

### Steps to trigger behavior

 1. After tracing the route, the Navigation provides a blank screen and crashes post clicking Recenter button.
 2. I have traced the log of NavigationLauncher 's object, my directionsRoute is empty. 

### Expected behavior
A navigation from source to destination

### Code
```
NavigationLauncherOptions options= NavigationLauncherOptions.builder().origin(originPosition).destination(destinationPosition).shouldSimulateRoute(true).build();
                Log.v(TAG,"Origin "+originPosition+"Destination "+destinationPosition);
                NavigationLauncher.startNavigation(MainActivity.this, options);
                Log.v(TAG,"Navigation Options"+options);
```
### Actual behavior
![screenshot 225](https://user-images.githubusercontent.com/16362654/50949126-05d0d700-14cb-11e9-990e-fda86df6ece9.png)
![bb874d63-20d4-46ea-b8f9-b97a034f65ae](https://user-images.githubusercontent.com/16362654/50949138-0cf7e500-14cb-11e9-9f7a-9a667023ebb8.jpg)
![b9200cd3-205d-4158-b59a-904d7f33f8d6](https://user-images.githubusercontent.com/16362654/50949139-0cf7e500-14cb-11e9-8287-e2fd1a0f68d9.jpg)

### Error Log:

```
01-10 11:29:14.997 22011-22011/com.bannuranurag.android.augv E/Mbgl-NativeMapView: Exception in MapView.OnMapChangedListener
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.setCameraEngine(com.mapbox.services.android.navigation.v5.navigation.camera.Camera)' on a null object reference
        at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.initialize(NavigationCamera.java:155)
        at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.<init>(NavigationCamera.java:57)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initNavigationCamera(NavigationView.java:574)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:377)
        at com.mapbox.services.android.navigation.ui.v5.NavigationActivity.onNavigationReady(NavigationActivity.java:115)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView$1.onStyleLoaded(NavigationView.java:226)
        at com.mapbox.mapboxsdk.maps.MapboxMap$1.onMapChanged(MapboxMap.java:1042)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:911)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6694)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

**Comment by Guardiola31337** [comment]
Hey @Anurag26 👋 thanks for reaching out and report your issue.

Current release version is [`0.26.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.26.0). To confirm that the issue is still present in the latest version, would you mind retesting it using `0.26.0` version? As you can imagine there have been a bunch of improvements and new features plus lots of bug fixes since `0.13.0`. Please consult the [migration guides](https://github.com/mapbox/mapbox-navigation-android/wiki#recent-migration-guides) for the necessary updates required and reach out to us if you have any questions or if you run into any issues. Thanks again!

**Comment by Anurag26** [comment]
Hello @Guardiola31337 thank you for your response. The reason why I am using ```0.13.0``` is because the version ```0.26.0```   throws the following ### Failed to resolve: com.mapbox.navigator:mapbox-navigation-native:3.4.11

**Comment by Guardiola31337** [comment]
As noted in all the release notes (starting in [`v0.20.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.20.0)) and in [Getting Started](https://github.com/mapbox/mapbox-navigation-android#getting-started) project's `README` section

> **Important Note**: With this release, you _must_ include the following snippet in your project’s `build.gradle`:
>```
>repositories {
>    maven { url 'https://mapbox.bintray.com/mapbox' }
>}
>```
>
>This will ensure the `mapbox` dependency is properly downloaded.

Have you added it to the root project's `build.gradle`?

**Comment by Anurag26** [comment]
@Guardiola31337  Yes I have.

![screenshot 226](https://user-images.githubusercontent.com/16362654/50967098-2b76d400-14fd-11e9-84fa-0405e4cb86d8.png)

**Comment by Guardiola31337** [comment]
It seems you have included it under the `buildscript` block. In order to get it working you should include it under the `allprojects` one. For reference you can check root's `build.gradle` file of `mapbox-navigation-android` https://github.com/mapbox/mapbox-navigation-android/blob/2f58fdb2a1983e5048a85a76bc3c9b280b099742/build.gradle#L35

**Comment by Anurag26** [comment]
@Guardiola31337 I am sorry, I had it under allprojects previously and that was not helping either. 

```
01-10 18:09:32.303 20461-20461/com.bannuranurag.android.augv E/SensorManager: sensor or listener is null
01-10 18:09:32.332 20461-20461/com.bannuranurag.android.augv E/Mbgl-NativeMapView: Exception in MapView.OnMapChangedListener
    com.mapbox.mapboxsdk.style.sources.CannotAddSourceException: Source mapbox-location-source already exists
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddSource(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.addSource(NativeMapView.java:788)
        at com.mapbox.mapboxsdk.maps.MapboxMap.addSource(MapboxMap.java:446)
        at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.addLocationSource(LocationLayer.java:246)
        at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.initializeComponents(LocationLayer.java:86)
        at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin$6.onMapChanged(LocationLayerPlugin.java:957)
        at com.mapbox.mapboxsdk.maps.MapView$6.onMapChanged(MapView.java:335)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:917)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1004)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:325)
        at android.os.Looper.loop(Looper.java:142)
        at android.app.ActivityThread.main(ActivityThread.java:6694)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
01-10 18:09:32.333 20461-20461/com.bannuranurag.android.augv A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8660090a in tid 20461 (ag.android.augv)
```

**Comment by Anurag26** [comment]
Hey @Guardiola31337 , thank you for your patience, in the end, I ended up switching from LocationLayerPlugin to LocationComponent and it solved the issue.

**Comment by Guardiola31337** [comment]
Awesome, glad to hear!

Yeah, I was going to ask if you were including the Location Layer Plugin because it's now deprecated and the `LocationComponent` from the Maps SDK should be used instead (to avoid issues / conflicts like the ones you saw).

Thanks for checking out the SDK!
