### ISSUE TITLE
Exception: addProgressChangeListener

### ISSUE THREAD

**Issue by TheTronuo** [mapbox/mapbox-navigation-android#1662]
Hi, what is it. How to fix it?
Version: 0.26.0.
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.addProgressChangeListener(com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation)' on a null object reference
       at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationListeners(NavigationView.java:684)
       at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigation(NavigationView.java:625)
       at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:387)
       at helper.truck.ati.screens.navigation.NavigationFragment.startNavigation(NavigationFragment.java:179)
       at helper.truck.ati.screens.navigation.NavigationFragment.access$100(NavigationFragment.java:38)
       at helper.truck.ati.screens.navigation.NavigationFragment$1.onResponse(NavigationFragment.java:161)
       at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:170)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:171)
       at android.app.ActivityThread.main(ActivityThread.java:6627)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:518)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by Guardiola31337** [comment]
Hey @TheTronuo 👋 thanks for reaching out and report your issue.

Could you add some more information for reproducing the issue (minimal example) or any other specifics around your test setup? If there is any sample or pseudo code you can provide, that would be really helpful. This will give us better insight into your implementation and what could be causing your problem.

**Comment by TheTronuo** [comment]
**NavigationFragment.java**
```
    private NavigationView navigationView;
    private DirectionsRoute directionsRoute;

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container,
                             @Nullable Bundle savedInstanceState) {
        return inflater.inflate(R.layout.navigation_view_fragment_layout, container, false);
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        navigationView = view.findViewById(R.id.navigation_view_fragment);
        navigationView.onCreate(savedInstanceState);
        navigationView.initialize(this);
    }

    @Override
    public void onStart() {
        super.onStart();
        navigationView.onStart();
    }

    @Override
    public void onResume() {
        super.onResume();
        navigationView.onResume();
    }

    @Override
    public void onSaveInstanceState(@NonNull Bundle outState) {
        navigationView.onSaveInstanceState(outState);
        super.onSaveInstanceState(outState);
    }

    @Override
    public void onViewStateRestored(@Nullable Bundle savedInstanceState) {
        super.onViewStateRestored(savedInstanceState);
        if (savedInstanceState != null) {
            navigationView.onRestoreInstanceState(savedInstanceState);
        }
    }

    @Override
    public void onPause() {
        super.onPause();
        navigationView.onPause();
    }

    @Override
    public void onStop() {
        super.onStop();
        navigationView.onStop();
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        navigationView.onLowMemory();
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        navigationView.onDestroy();
    }


    @Override
    public void onNavigationReady(boolean isRunning) {
        fetchRoute(((NavigationActivity)getActivity()).getOrigin(), ((NavigationActivity)getActivity()).getDestination());
    }

    @Override
    public void onCancelNavigation() {
        navigationView.stopNavigation();
        stopNavigation();
        getActivity().onBackPressed();
    }

    @Override
    public void onNavigationFinished() {
// no-op
    }

    @Override
    public void onNavigationRunning() {
// no-op
    }

    private void fetchRoute(Point origin, Point destination) {
        NavigationRoute.builder(getContext())
                .accessToken(Mapbox.getAccessToken())
                .origin(origin)
                .destination(destination)
                .build()
                .getRoute(new Callback<DirectionsResponse>() {
                    @Override
                    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                        directionsRoute = response.body().routes().get(0);
                        startNavigation();
                    }

                    @Override
                    public void onFailure(Call<DirectionsResponse> call, Throwable t) {

                    }
                });
    }

    private void startNavigation() {
        if (directionsRoute == null) {
            return;
        }
        NavigationViewOptions options = NavigationViewOptions.builder()
                .directionsRoute(directionsRoute)
                .navigationListener(NavigationFragment.this)
                .build();
        navigationView.startNavigation(options);
    }

    private void stopNavigation() {
        FragmentActivity activity = getActivity();
    }
}
```

**Comment by TheTronuo** [comment]
@danesfeder what I did wrong?

**Comment by danesfeder** [comment]
@TheTronuo does this crash happen every time you try to start the `Fragment`?

**Comment by danesfeder** [comment]
@TheTronuo can you provide more details as to when you experience this crash?  Thanks!

**Comment by danesfeder** [comment]
@TheTronuo going to go ahead and close here - we need a bit more detail / replication.  If you can provide the steps using that code snippet, we'd appreciate it.  Thanks!

**Comment by hosamJC** [comment]
@danesfeder it's happened in my code as well the same bug, it's not happening all the time but it comes almost times.
please can you provide me with a proper solution as I try many solutions without any fix

Thanks,
