### ISSUE TITLE
Instruction list IllegalArgumentException: Scrapped or attached views may not be recycled.

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#1711]
@Guardiola31337 found while testing:

```
2019-01-29 15:01:57.588 24575-24575/com.mapbox.services.android.navigation.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.services.android.navigation.app, PID: 24575
    java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true android.support.v7.widget.RecyclerView{4dbaf23 VFED..... .......D 0,0-1440,1972 #7f0900e4 app:id/rvInstructions}, adapter:com.mapbox.services.android.navigation.ui.v5.summary.list.InstructionListAdapter@f04b2e9, layout:android.support.v7.widget.LinearLayoutManager@cb95b6e, context:com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity@1cce10
        at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:6159)
        at android.support.v7.widget.RecyclerView$Recycler.recycleView(RecyclerView.java:6103)
        at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:293)
        at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
        at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
        at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:366)
        at android.support.v7.widget.GapWorker.run(GapWorker.java:397)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Guardiola31337** [comment]
@abhishek1508 @JunDai is this still an issue in the `1.0` UI SDK?

**Comment by abhishek1508** [comment]
Let's verify.
cc @JunDai @cafesilencio @langsmith

**Comment by cafesilencio** [comment]
From my experience this is caused by android:animateLayoutChanges=true on a RecyclerView.  I don't see any place in the 1.0 SDK where we have this configuration.  While researching this I also saw references to TransitionManager.beginDelayedTransition() causing this error if a RecyclerView is involved. While we call TransitionManager.beginDelayedTransition() in the InstructionView, the InstructionView doesn't have a RecyclerView in its layout and as far as I know the original issue described hasn't been experienced in our 1.0 code base.
