### ISSUE TITLE
MockNavigationActivity notification doesn't go back to activity when clicked, and also remains after navigation has completed.

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/mapbox-navigation-android#1745]
- [ ] MockNavigationActivity notification does not navigate to activity when clicked

- [ ] MockNavigationActivity notification doesn't go away at the end of navigation

- [ ] Crash when hitting back from the MockNavigationActivity during navigation:
```
2019-02-14 14:33:14.826 9622-9622/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.services.android.navigation.app, PID: 9622
    java.lang.RuntimeException: Unable to destroy activity {com.mapbox.services.android.navigation.app/com.mapbox.services.android.navigation.testapp.activity.MockNavigationActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.mapbox.services.android.navigation.testapp.activity.MockNavigationActivity$MyBroadcastReceiver@505c70
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4603)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4621)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.mapbox.services.android.navigation.testapp.activity.MockNavigationActivity$MyBroadcastReceiver@505c70
        at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1181)
        at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1456)
        at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:658)
        at com.mapbox.services.android.navigation.testapp.activity.notification.CustomNavigationNotification.onNavigationStopped(CustomNavigationNotification.java:70)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationNotificationProvider.shutdown(NavigationNotificationProvider.java:29)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.endNavigation(NavigationService.java:76)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.stopNavigation(MapboxNavigation.java:361)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.onDestroy(MapboxNavigation.java:172)
        at com.mapbox.services.android.navigation.testapp.activity.MockNavigationActivity.onDestroy(MockNavigationActivity.java:338)
        at android.app.Activity.performDestroy(Activity.java:7471)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1255)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4590)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4621) 
        at android.app.ActivityThread.-wrap5(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1757) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6938) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by Guardiola31337** [comment]
This example is not available anymore.

Closing here.

cc @abhishek1508
