### ISSUE TITLE
Crash Navigation View on intialization

### ISSUE THREAD

**Issue by Styvak** [mapbox/mapbox-navigation-android#1768]
I am trying to use Mapbox Navigation UI but when I create my activity with the NavigationView or with startNavigation with NavigatorLauncher I have this error :

> 2019-02-23 18:55:56.806 14570-14570/com.example.mapboxtestE/Mbgl-MapChangeReceiver: Exception in onDidFinishLoadingStyle
    java.lang.BootstrapMethodError: Exception from call site #0 bootstrap method
        at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager.<init>(AnnotationManager.java:88)
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:79)
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:56)
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:44)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.initializeNavigationSymbolManager(NavigationMapboxMap.java:583)
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.<init>(NavigationMapboxMap.java:92)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationMap(NavigationView.java:557)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.access$100(NavigationView.java:68)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView$1.onStyleLoaded(NavigationView.java:223)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:839)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:204)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1176)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:194)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1040)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.mapbox.mapboxsdk.plugins.annotation.AnnotationManager.<init>(AnnotationManager.java:88) 
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:79) 
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:56) 
        at com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.<init>(SymbolManager.java:44) 
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.initializeNavigationSymbolManager(NavigationMapboxMap.java:583) 
        at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.<init>(NavigationMapboxMap.java:92) 
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationMap(NavigationView.java:557) 
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.access$100(NavigationView.java:68) 
        at com.mapbox.services.android.navigation.ui.v5.NavigationView$1.onStyleLoaded(NavigationView.java:223) 
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:839) 
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:204) 
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1176) 
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:194) 
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1040) 
        at android.os.MessageQueue.nativePollOnce(Native Method) 
        at android.os.MessageQueue.next(MessageQueue.java:326) 
        at android.os.Looper.loop(Looper.java:160) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-02-23 18:55:56.819 14570-14570/com.example.mapboxtestEE/libc++abi: terminating with uncaught exception of type jni::PendingJavaException
2019-02-23 18:55:56.819 14570-14570/com.example.mapboxtestEA/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 14570 (le.mapboxtestE), pid 14570 (le.mapboxtestE)

I am using mapbox sdk 7.1.2and I tried the navigation-ui 0.30 and the new snapshot.
When I'm using the NavigationView I crash when I call navigationView?.initialize(myCallback)

Thank you

**Comment by Styvak** [comment]
It seems that the error is only in API 28, I tried an example project on GitHub it worked on API 26 emulator but not on 28

**Comment by danesfeder** [comment]
This looks to be similar to https://github.com/mapbox/mapbox-navigation-android/issues/1752#issuecomment-464746035.  Can you try adding Java 8 to your app project to resolve this?  Thanks!

**Comment by danesfeder** [comment]
Any updates here @Styvak?

**Comment by danesfeder** [comment]
Hey @Styvak going to go ahead and close here as https://github.com/mapbox/mapbox-navigation-android/issues/1768#issuecomment-467008734 should solve your issue I believe.  Please follow up if you find otherwise.
