### ISSUE TITLE
DafaultMilestones IndexOutOfBoundsException

### ISSUE THREAD

**Issue by samvgorode** [mapbox/mapbox-navigation-android#178]
I have a crash at the end of the navigation in `0.5.0-SNAPSHOT`
Mapbox team, please check `DafaultMilestones` line 37,
`int followUpStepIndex = routeProgress.currentLegProgress().stepIndex() + 2;`
For final step `followUpStepIndex` is not exist.
```
E/UncaughtException: java.lang.IndexOutOfBoundsException: Invalid index 3, size is 3
                                                                        at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                        at java.util.ArrayList.get(ArrayList.java:308)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.DefaultMilestones$2.buildInstruction(DefaultMilestones.java:59)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.buildInstructionString(NavigationHelper.java:61)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onMilestoneTrigger(NavigationService.java:197)
                                                                        at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:79)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
```

**Comment by mKenfenheuer** [comment]
I can confirm this. same here:

08-21 12:11:07.877 9541-9541/com.kenfenheuer.whereismydevice E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.kenfenheuer.whereismydevice, PID: 9541
                                                                               java.lang.IndexOutOfBoundsException: Index: 9, Size: 9
                                                                                   at java.util.ArrayList.get(ArrayList.java:411)
                                                                                   at com.mapbox.services.android.navigation.v5.navigation.DefaultMilestones$2.buildInstruction(DefaultMilestones.java:59)
                                                                                   at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.buildInstructionString(NavigationHelper.java:61)
                                                                                   at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onMilestoneTrigger(NavigationService.java:197)
                                                                                   at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:79)
                                                                                   at android.os.Handler.handleCallback(Handler.java:751)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                   at android.os.Looper.loop(Looper.java:154)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:6236)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by Grsmto** [comment]
This has already been PR there https://github.com/mapbox/mapbox-navigation-android/pull/171
As said in #175 they already know about this issue.

Again in the meanwhile you can use my fork using Jitpack like so:
`compile 'com.github.grsmto.mapbox-navigation-android:mapbox-android-navigation:fix-build-SNAPSHOT'`

**Comment by samvgorode** [comment]
It solved that problem, thenk you, @Grsmto !
