### ISSUE TITLE
Strictmode warning with OnSaveInstanceState

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-navigation-android#1875]
```
D/StrictMode: StrictMode policy violation; ~duration=17 ms: android.os.strictmode.CustomViolation: Compression of a bitmap is slow
        at android.os.StrictMode$AndroidBlockGuardPolicy.onCustomSlowCall(StrictMode.java:1513)
        at android.os.StrictMode.noteSlowCall(StrictMode.java:2455)
        at android.graphics.Bitmap.compress(Bitmap.java:1376)
        at com.mapbox.mapboxsdk.utils.BitmapUtils.getByteArrayFromDrawable(BitmapUtils.java:112)
        at com.mapbox.mapboxsdk.maps.UiSettings.saveCompass(UiSettings.java:177)
        at com.mapbox.mapboxsdk.maps.UiSettings.onSaveInstanceState(UiSettings.java:96)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onSaveInstanceState(MapboxMap.java:150)
        at com.mapbox.mapboxsdk.maps.MapView.onSaveInstanceState(MapView.java:337)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.onSaveInstanceState(NavigationView.java:151)
        at com.mapbox.services.android.navigation.testapp.activity.navigationui.fragment.NavigationFragment.onSaveInstanceState(NavigationFragment.java:75)
        at android.support.v4.app.Fragment.performSaveInstanceState(Fragment.java:2626)
        at android.support.v4.app.FragmentManagerImpl.saveFragmentBasicState(FragmentManager.java:2910)
        at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:2971)
        at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:134)
        at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:591)
        at android.support.v7.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:510)
        at com.mapbox.services.android.navigation.testapp.activity.navigationui.fragment.FragmentNavigationActivity.onSaveInstanceState(FragmentNavigationActivity.java:35)
        at android.app.Activity.performSaveInstanceState(Activity.java:2000)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1474)
        at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5099)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4427)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4391)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4466)
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1940)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7046)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)

```

**Comment by tobrun** [comment]
Actually hitting the following as well after:

```
2019-04-11 10:48:55.377 27208-27208/com.mapbox.services.android.navigation.app D/StrictMode: StrictMode policy violation; ~duration=9 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1546)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:232)
        at libcore.io.IoBridge.open(IoBridge.java:482)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1183)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1161)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1126)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.setDataSource(MapboxSpeechPlayer.java:182)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.setupMediaPlayer(MapboxSpeechPlayer.java:168)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.playInstruction(MapboxSpeechPlayer.java:160)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.playInstructionIfUpNext(MapboxSpeechPlayer.java:248)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.access$500(MapboxSpeechPlayer.java:28)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer$4.onFinishedDownloading(MapboxSpeechPlayer.java:235)
        at com.mapbox.services.android.navigation.v5.utils.DownloadTask.onPostExecute(DownloadTask.java:123)
        at com.mapbox.services.android.navigation.v5.utils.DownloadTask.onPostExecute(DownloadTask.java:17)
        at android.os.AsyncTask.finish(AsyncTask.java:748)
        at android.os.AsyncTask.access$900(AsyncTask.java:191)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:765)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7046)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
2019-04-11 10:48:55.379 27208-27208/com.mapbox.services.android.navigation.app D/StrictMode: StrictMode policy violation; ~duration=8 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1546)
        at libcore.io.BlockGuardOs.fstat(BlockGuardOs.java:157)
        at libcore.io.IoBridge.open(IoBridge.java:485)
        at java.io.FileInputStream.<init>(FileInputStream.java:159)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1183)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1161)
        at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1126)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.setDataSource(MapboxSpeechPlayer.java:182)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.setupMediaPlayer(MapboxSpeechPlayer.java:168)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.playInstruction(MapboxSpeechPlayer.java:160)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.playInstructionIfUpNext(MapboxSpeechPlayer.java:248)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.access$500(MapboxSpeechPlayer.java:28)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer$4.onFinishedDownloading(MapboxSpeechPlayer.java:235)
        at com.mapbox.services.android.navigation.v5.utils.DownloadTask.onPostExecute(DownloadTask.java:123)
        at com.mapbox.services.android.navigation.v5.utils.DownloadTask.onPostExecute(DownloadTask.java:17)
        at android.os.AsyncTask.finish(AsyncTask.java:748)
        at android.os.AsyncTask.access$900(AsyncTask.java:191)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:765)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7046)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
2019-04-11 10:48:55.478 27208-27239/com.mapbox.services.android.navigation.app E/MediaPlayerNative: error (1, -19)
2019-04-11 10:48:55.479 27208-27208/com.mapbox.services.android.navigation.app E/MediaPlayer: Error (1,-19)
2019-04-11 10:48:55.481 27208-27208/com.mapbox.services.android.navigation.app V/MediaPlayer: resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
2019-04-11 10:48:55.481 27208-27208/com.mapbox.services.android.navigation.app V/MediaPlayer: cleanDrmObj: mDrmObj=null mDrmSessionId=null
2019-04-11 10:48:55.492 27208-27208/com.mapbox.services.android.navigation.app D/StrictMode: StrictMode policy violation; ~duration=1 ms: android.os.strictmode.DiskWriteViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1502)
        at java.io.UnixFileSystem.delete(UnixFileSystem.java:304)
        at java.io.File.delete(File.java:1037)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.deleteLastInstructionPlayed(MapboxSpeechPlayer.java:215)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.onInstructionFinishedPlaying(MapboxSpeechPlayer.java:209)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.access$400(MapboxSpeechPlayer.java:28)
        at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer$3.onCompletion(MapboxSpeechPlayer.java:203)
        at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:3448)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7046)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
```

**Comment by Guardiola31337** [comment]
@abhishek1508 are these still reproducible in the `1.0` UI SDK?

**Comment by Guardiola31337** [comment]
cc @JunDai

**Comment by abhishek1508** [comment]
Let's verify.
cc @JunDai @cafesilencio @langsmith

**Comment by abhishek1508** [comment]
`StrictMode` warnings are everywhere in the `examples` test activities. They are not tied to any specific component as I am seeing it being generated from `onStyleLoaded`, `NavNativeImpl` and many others. We are enabling `strictMode` in `debug` mode inside `NavigationApplication.kt`. If we disable it, we don't get those warnings. Going to close it.
cc @Guardiola31337

**Comment by Guardiola31337** [comment]
@abhishek1508 
> `StrictMode` warnings are everywhere in the `examples` test activities. They are not tied to any specific component as I am seeing it being generated from `onStyleLoaded`, `NavNativeImpl` and many others. We are enabling `strictMode` in `debug` mode inside `NavigationApplication.kt`. If we disable it, we don't get those warnings. Going to close it.

This ticket was about investigating those warnings and fix them if any, especially if they were coming from the SDK 😅

**Comment by abhishek1508** [comment]
This would be very low in priority as we have major other issues we need to work on. We can revisit this later. 
cc @Guardiola31337
