### ISSUE TITLE
FATAL EXCEPTION mapbox_navigation_thread NumberFormatException s == null

### ISSUE THREAD

**Issue by GeordiRugenbrink** [mapbox/mapbox-navigation-android#1923]
``E/AndroidRuntime: FATAL EXCEPTION: mapbox_navigation_thread
    Process: project.name, PID: 20349
    java.lang.NumberFormatException: s == null
        at java.lang.Integer.parseInt(Integer.java:577)
        at java.lang.Integer.valueOf(Integer.java:801)
        at com.mapbox.services.android.navigation.v5.navigation.RouteRefresh.refresh(RouteRefresh.java:80)
        at com.mapbox.services.android.navigation.v5.navigation.RouteRefresh.refresh(RouteRefresh.java:74)
        at com.mapbox.services.android.navigation.v5.navigation.RouteRefresher.refresh(RouteRefresher.java:33)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable.process(RouteProcessorRunnable.java:66)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable.run(RouteProcessorRunnable.java:46)
        at android.os.Handler.handleCallback(Handler.java:874)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:198)
        at android.os.HandlerThread.run(HandlerThread.java:65)``

I got this error after upgrading to 0.36.0. It happened at the exact same moment when riding a route I made. After checking off like 6 steps it crashed and threw this error. What could it be?

**Comment by Guardiola31337** [comment]
The fix for OP was included in the recent release [`v0.37.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.37.0) 🎉 👀 https://github.com/mapbox/mapbox-navigation-android/pull/1909

I'm going to go ahead and closing here as fixed, if you re-test and still see issues, please feel free to cut a new ticket and we will continue to dig on this. Thanks for reporting the issue and checking out the SDK!
