### ISSUE TITLE
Error LocaleData for locate pt-pt

### ISSUE THREAD

**Issue by math77** [mapbox/mapbox-navigation-android#1929]
Hello,

I'm using the Navigation SDK and my app stopped and returned the following error:

`java.lang.AssertionError: couldn't initialize LocaleData for locale pt-pt
        at libcore.icu.LocaleData.initLocaleData(LocaleData.java:171)
        at libcore.icu.LocaleData.get(LocaleData.java:125)
        at java.text.NumberFormat.getNumberInstance(NumberFormat.java:468)
        at com.mapbox.services.android.navigation.v5.utils.DistanceFormatter.<init>(DistanceFormatter.java:74)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.establishDistanceFormatter(NavigationView.java:650)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.establish(NavigationView.java:642)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigation(NavigationView.java:617)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:381)
        at com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity.onNavigationReady(MapboxNavigationActivity.java:99)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView$1.onStyleLoaded(NavigationView.java:225)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:845)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:205)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1178)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:194)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1040)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:132)
        at android.os.Looper.loop(Looper.java:138)
        at android.app.ActivityThread.main(ActivityThread.java:5493)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1225)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1041)
        at dalvik.system.NativeStart.main(Native Method)
05-05 12:11:34.325 4948-4948/br.com.deliveryapp.deliveryapp A/libc: /usr/local/google/buildbot/src/android/ndk-release-r19/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:73: abort_message: assertion "terminating with uncaught exception of type jni::PendingJavaException" failed
05-05 12:11:34.335 4948-4948/br.com.deliveryapp.deliveryapp A/libc: Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 4948 (app.deliveryapp)
`

What could be causing the error?

**minSdkVersion: 17**
**compileSdkVersion: 28**
**com.mapbox.mapboxsdk:mapbox-android-navigation:0.37.0**

**Comment by danesfeder** [comment]
Hey @math77 👋 would you mind sending the `Locale` code you're using with `NavigationRoute` to generate the `DirectionsRoute` prior to navigation?  That will help us determine the localization issue here.  Thanks!

**Comment by math77** [comment]
@danesfeder 

`private void getRoute(Point origin, Point destination){
    	NavigationRoute.builder(this)
				.accessToken(Mapbox.getAccessToken())
				.origin(origin)
				.destination(destination)
				.language(new Locale("pt", "BR"))
				.build()
				.getRoute(new Callback<DirectionsResponse>() {
					@Override
					public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
						if (response.body() == null){
							Log.e("ERRO", "Rotas não encontradas, verifique a chave de acesso");
							return;
						}else if(response.body().routes().size() < 1){
							Log.e("ERRO", "Rotas não encontradas");
							return;
						}

						currentRoute = response.body().routes().get(0);

						if (navigationMapRoute != null) {
							navigationMapRoute.removeRoute();
						}else {
							navigationMapRoute = new NavigationMapRoute(null, mapView, mapboxMap, R.style.NavigationMapRoute);
						}
						navigationMapRoute.addRoute(currentRoute);
					}

					@Override
					public void onFailure(Call<DirectionsResponse> call, Throwable t) {
						Log.e("ERRO", "Error: "+t.getMessage());
					}
				});
	}
`
`
btnStartNavigation.setOnClickListener(new View.OnClickListener(){
        	@Override
        	public void onClick(View v){
        		NavigationLauncherOptions options = NavigationLauncherOptions.builder()
						.directionsRoute(currentRoute)
						.shouldSimulateRoute(true)
						.build();

        		NavigationLauncher.startNavigation(RegisterDeliveryActivity.this, options);
        	}
        });
`

**Comment by math77** [comment]
Hi,

This is the code I wrote

**Comment by danesfeder** [comment]
@math77 can you update the `Locale` instantiation to `new Locale("pt-BR")`?  Does this help?  We've seen some issues with localization similar to this in the past https://github.com/mapbox/mapbox-navigation-android/issues/1758

**Comment by math77** [comment]
Hello @danesfeder 

This worked for my code, thank you very much.

**Comment by danesfeder** [comment]
@math77 great, thank you!  Going to go ahead and close here as resolved.
