### ISSUE TITLE
ArrayIndexOutOfBoundsException MapRouteLine.drawWayPoints

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-navigation-android#1948]
### Description:
A crash happened for one of our users. Not sure how to reproduce but I copy pasted the content of the crash log below.

Cheers 

**Android API:**  7.0 Nougat
**Mapbox Navigation SDK version:** navigation-ui:0.36.0'

### Steps to trigger behavior
?
### Actual behavior
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
       at java.util.ArrayList.get(ArrayList.java:413)
       at com.mapbox.services.android.navigation.ui.v5.route.MapRouteLine.drawWayPoints(MapRouteLine.java:262)
       at com.mapbox.services.android.navigation.ui.v5.route.MapRouteLine.access$300(MapRouteLine.java:42)
       at com.mapbox.services.android.navigation.ui.v5.route.MapRouteLine$1.onRouteFeaturesProcessed(MapRouteLine.java:254)
       at com.mapbox.services.android.navigation.ui.v5.route.FeatureProcessingTask.onPostExecute(FeatureProcessingTask.java:49)
       at com.mapbox.services.android.navigation.ui.v5.route.FeatureProcessingTask.onPostExecute(FeatureProcessingTask.java:20)
       at android.os.AsyncTask.finish(AsyncTask.java:660)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

**Comment by Guardiola31337** [comment]
Hey @Christophe668 👋 friendly reminder that #1951 landed and OP should be fixed in the recent [`0.39.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.39.0) release version of the SDK 🎉 

Thanks for bringing this to us!
