### ISSUE TITLE
getWifiLevel : Fatal Exception: java.lang.SecurityException

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-navigation-android#1949]
### Description :
Crash during navigation

**Android API:** 28 Pie
**Mapbox Navigation SDK version:**
"com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.38.0"

### Steps to trigger behavior
? 
Crash log enclosed

### Actual behavior

[bike.cowboy.app_issue_crash_5CEC1EEC011E00011C2FD1C2A746AB0D_DNE_0_v2.txt](https://github.com/mapbox/mapbox-navigation-android/files/3226114/bike.cowboy.app_issue_crash_5CEC1EEC011E00011C2FD1C2A746AB0D_DNE_0_v2.txt)

**Comment by Guardiola31337** [comment]
Hey 👋 @Christophe668 thanks for reaching out and report your issue.

For easier visibility adding the crash Stack Trace here:

```
Fatal Exception: java.lang.SecurityException: WifiService: Neither user 10256 nor current process has android.permission.ACCESS_WIFI_STATE.
       at android.os.Parcel.createException(Parcel.java:1966)
       at android.os.Parcel.readException(Parcel.java:1934)
       at android.os.Parcel.readException(Parcel.java:1884)
       at android.net.wifi.IWifiManager$Stub$Proxy.getConnectionInfo(IWifiManager.java:1786)
       at android.net.wifi.WifiManager.getConnectionInfo(WifiManager.java:2060)
       at com.mapbox.services.android.navigation.ui.v5.ConnectivityStatusProvider.getWifiLevel(ConnectivityStatusProvider.java:50)
       at com.mapbox.services.android.navigation.ui.v5.ConnectivityStatusProvider.isConnectedFast(ConnectivityStatusProvider.java:29)
       at com.mapbox.services.android.navigation.ui.v5.voice.SpeechPlayerProvider.retrieveSpeechPlayer(SpeechPlayerProvider.java:57)
       at com.mapbox.services.android.navigation.ui.v5.voice.NavigationSpeechPlayer.play(NavigationSpeechPlayer.java:34)
       at bike.cowboy.app.features.map.navigation.MapboxNavigationFragment$startNavigation$1.onMilestoneEvent(MapboxNavigationFragment.java:103)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onMilestoneEvent(NavigationEventDispatcher.java:158)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onMilestoneTrigger(RouteProcessorThreadListener.java:46)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable$1.run(RouteProcessorRunnable.java:148)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

Caused by android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:1924)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1952)
	at com.android.server.wifi.WifiServiceImpl.enforceAccessPermission(WifiServiceImpl.java:1563)
	at com.android.server.wifi.WifiServiceImpl.getConnectionInfo(WifiServiceImpl.java:3626)
	at android.net.wifi.IWifiManager$Stub.onTransact(IWifiManager.java:341)
```

It seems that Android version 9 (Pie) changes require Location to be enabled (by the user), or the call to `getConnectioInfo()` will fail, even if your app has correct permissions 👀 this SO answer https://stackoverflow.com/questions/53005755/how-to-get-wifi-ssid-in-android-9-0pie#answer-54446042

We will keep investigating / trying to reproduce locally and then report back here on this ticket. Great catch by the way 💪

**Comment by Guardiola31337** [comment]
Could this still be an issue in 1.0 @mapbox/navigation-android?
