### ISSUE TITLE
Attempt to read from field 'double com.mapbox.mapboxsdk.camera.CameraPosition.zoom' on a null object reference com.mapbox.services.android.navigation.ui.v5.camera.DynamicCamera.createZoom

### ISSUE THREAD

**Issue by ben-j69** [mapbox/mapbox-navigation-android#1967]
**Android API:**
minSdkVersion 16
targetSdkVersion 28
**Mapbox Navigation SDK version:**
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.3.1'
    implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:4.6.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.6.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.35.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.35.0'

### Steps to trigger behavior

I don't know I just have this error fired by my app in prod. It append 45 times for over 30 users.

They are using Android 6,7,8,9.

The stack trace
````
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'double com.mapbox.mapboxsdk.camera.CameraPosition.zoom' on a null object reference
       at com.mapbox.services.android.navigation.ui.v5.camera.DynamicCamera.createZoom(DynamicCamera.java:110)
       at com.mapbox.services.android.navigation.ui.v5.camera.DynamicCamera.zoom(DynamicCamera.java:60)
       at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.adjustCameraFromLocation(NavigationCamera.java:534)
       at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.access$400(NavigationCamera.java:52)
       at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera$1.onProgressChange(NavigationCamera.java:97)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:165)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onNewRouteProgress(RouteProcessorThreadListener.java:34)
       at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable$1.run(RouteProcessorRunnable.java:142)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:171)
       at android.app.ActivityThread.main(ActivityThread.java:6638)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:907)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:797)
```

**Comment by Guardiola31337** [comment]
Hey @ben-j69 👋 thanks for reaching out and report your issue.

The fix for OP was included in the latest release [`v0.41.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v0.41.0) 🎉 👀 https://github.com/mapbox/mapbox-navigation-android/pull/1979

I'm going to go ahead and closing here as fixed, if you re-test and still see issues, please feel free to cut a new ticket and we will continue to dig on this. Thanks for reporting the issue and checking out the SDK!
