### ISSUE TITLE
Mapbox navigation crashes while navigating

### ISSUE THREAD

**Issue by kamleshsahu** [mapbox/mapbox-navigation-android#1991]
Error log :

07-09 20:19:49.548 12438-13404/com.mapbox.services.android.navigation.app E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #8
                                                                                            Process: com.mapbox.services.android.navigation.app, PID: 12438
                                                                                            java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                                                at android.os.AsyncTask$3.done(AsyncTask.java:353)
                                                                                                at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
                                                                                                at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
                                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:271)
                                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
                                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                                at java.lang.Thread.run(Thread.java:764)
                                                                                             Caused by: java.lang.Error: std::bad_alloc
                                                                                                at com.mapbox.navigator.Navigator.getHistory(Native Method)
                                                                                                at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigator.retrieveHistory(MapboxNavigator.java:73)
                                                                                                at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.retrieveHistory(MapboxNavigation.java:790)
                                                                                                at com.mapbox.services.android.navigation.testapp.activity.StoreHistoryTask.doInBackground(StoreHistoryTask.java:28)
                                                                                                at com.mapbox.services.android.navigation.testapp.activity.StoreHistoryTask.doInBackground(StoreHistoryTask.java:14)
                                                                                                at android.os.AsyncTask$2.call(AsyncTask.java:333)
                                                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
                                                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
                                                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
                                                                                                at java.lang.Thread.run(Thread.java:764) 
07-09 20:19:50.654 12438-13412/com.mapbox.services.android.navigation.app E/StrictMode: null
                                                                                        java.lang.Throwable: Untagged socket detected; use TrafficStats.setThreadSocketTag() to track all network usage
                                                                                            at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2010)
                                                                                            at com.android.server.NetworkManagementSocketTagger.tag(NetworkManagementSocketTagger.java:78)
                                                                                            at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:47)
                                                                                            at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:310)
                                                                                            at libcore.io.IoBridge.socket(IoBridge.java:667)
                                                                                            at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:116)
                                                                                            at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:98)
                                                                                            at java.net.Socket.createImpl(Socket.java:484)
                                                                                            at java.net.Socket.getImpl(Socket.java:547)
                                                                                            at java.net.Socket.setSoTimeout(Socket.java:1175)
                                                                                            at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:244)
                                                                                            at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:166)
                                                                                            at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
                                                                                            at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
                                                                                            at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
                                                                                            at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                            at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                            at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                            at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
                                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
                                                                                            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
                                                                                            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
                                                                                            at java.lang.Thread.run(Thread.java:764)

---------------------------------------------
Mapbox Navigation SDK version :
mapbox-android-navigation:0.41.0-SNAPSHOT

@langsmith @danesfeder need help

**Comment by LukasPaczos** [comment]
Hey @kamleshsahu, this looks like a strict mode violation, not a source of the crash. Are you sure this is the correct stack trace?

**Comment by kamleshsahu** [comment]
LukasPaczos , sorry my mistake, i have update the error log .please check sir.

**Comment by Guardiola31337** [comment]
Hey @kamleshsahu 👋 thanks for reaching out and report your issue.

It seems you were able to reproduce using the test app, right? Could you add some more information for reproducing consistently the issue? If you can provide the steps followed, which example from the test app you're 👀 and any changes you might have done, that would be really helpful. This will give us better insight into what could be causing your problem.

**Comment by andrlee** [comment]
@kamleshsahu please re-open with more details.
