### ISSUE TITLE
WayName is shown even when the text is empty after recentering

### ISSUE THREAD

**Issue by cmahopper** [mapbox/mapbox-navigation-android#2032]
**Android API:** 28
**Mapbox Navigation SDK version:** 0.41.0

The `WayName` view can become visible even when there's no text, resulting in a white bubble being shown.

Normally, this check is made in `NavigationPresenter`:
https://github.com/mapbox/mapbox-navigation-android/blob/f2a082cfd33792f2209c67979f615668d3f7a587/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationPresenter.java#L71-L75

However, when recentering, the check is not made:
https://github.com/mapbox/mapbox-navigation-android/blob/f2a082cfd33792f2209c67979f615668d3f7a587/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/NavigationPresenter.java#L24-L27

Thus, recentering causes the WayName view to always be shown.

**Comment by Guardiola31337** [comment]
Hey @cmahopper 👋 thanks for reaching out and report your issue.

That's a great catch! Are you able to reproduce that behavior in any of the examples of the [test app](https://github.com/mapbox/mapbox-navigation-android/tree/master/app)? That'd be really helpful to troubleshoot the problem described.

Also, friendly reminder that PRs are more than welcome 😅 It'd be awesome 💯 if you can submit a PR fixing this.

Thanks again!

**Comment by cmahopper** [comment]
@Guardiola31337 I can make a PR if you want, but I'd just add the same check as in the first code example. Maybe there's a better way to do it, so you don't have to remember to add the check again if the WayName visibility is changed somewhere else.

I can't start the test app, but the reproduction steps is to start the navigation on a road with no name, move the map, and press the recenter button. In my case, our work place is situated between a bunch of small roads (of a parking lot) with no names, so every time I test navigation, it happens.

For some reason I'm not able to start the test app. I get the following error:

```
    --------- beginning of crash
2019-08-26 09:10:53.376 31797-31797/com.mapbox.services.android.navigation.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.services.android.navigation.app, PID: 31797
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.services.android.navigation.app/com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity}: java.lang.RuntimeException: Cannot create an instance of class com.mapbox.services.android.navigation.testapp.example.ui.ExampleViewModel
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3047)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Cannot create an instance of class com.mapbox.services.android.navigation.testapp.example.ui.ExampleViewModel
        at android.arch.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:207)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:134)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:102)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$viewModel$2.invoke(ExampleActivity.kt:46)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$viewModel$2.invoke(ExampleActivity.kt:43)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.getViewModel(Unknown Source:7)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.access$getViewModel$p(ExampleActivity.kt:43)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$presenter$2.invoke(ExampleActivity.kt:49)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$presenter$2.invoke(ExampleActivity.kt:43)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.getPresenter(Unknown Source:7)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.setupWith(ExampleActivity.kt:292)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.onCreate(ExampleActivity.kt:55)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.arch.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:199)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:134) 
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:102) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$viewModel$2.invoke(ExampleActivity.kt:46) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$viewModel$2.invoke(ExampleActivity.kt:43) 
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.getViewModel(Unknown Source:7) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.access$getViewModel$p(ExampleActivity.kt:43) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$presenter$2.invoke(ExampleActivity.kt:49) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$presenter$2.invoke(ExampleActivity.kt:43) 
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.getPresenter(Unknown Source:7) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.setupWith(ExampleActivity.kt:292) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.onCreate(ExampleActivity.kt:55) 
        at android.app.Activity.performCreate(Activity.java:7149) 
        at android.app.Activity.performCreate(Activity.java:7140) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: com.mapbox.services.android.navigation.v5.exception.NavigationException: A valid access token must be passed in when first initializing MapboxNavigation
        at com.mapbox.services.android.navigation.v5.navigation.NavigationTelemetry.validateAccessToken(NavigationTelemetry.java:304)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationTelemetry.initialize(NavigationTelemetry.java:120)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.initializeTelemetry(MapboxNavigation.java:906)
2019-08-26 09:10:53.376 31797-31797/com.mapbox.services.android.navigation.app E/AndroidRuntime:     at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.initialize(MapboxNavigation.java:887)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.<init>(MapboxNavigation.java:118)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.<init>(MapboxNavigation.java:92)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleViewModel.<init>(ExampleViewModel.kt:64)
        	... 31 more
2019-08-26 09:10:53.377 31797-31797/com.mapbox.services.android.navigation.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.services.android.navigation.app, PID: 31797
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.services.android.navigation.app/com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity}: java.lang.RuntimeException: Cannot create an instance of class com.mapbox.services.android.navigation.testapp.example.ui.ExampleViewModel
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3047)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Cannot create an instance of class com.mapbox.services.android.navigation.testapp.example.ui.ExampleViewModel
        at android.arch.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:207)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:134)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:102)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$viewModel$2.invoke(ExampleActivity.kt:46)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$viewModel$2.invoke(ExampleActivity.kt:43)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.getViewModel(Unknown Source:7)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.access$getViewModel$p(ExampleActivity.kt:43)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$presenter$2.invoke(ExampleActivity.kt:49)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$presenter$2.invoke(ExampleActivity.kt:43)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.getPresenter(Unknown Source:7)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.setupWith(ExampleActivity.kt:292)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.onCreate(ExampleActivity.kt:55)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.arch.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:199)
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:134) 
        at android.arch.lifecycle.ViewModelProvider.get(ViewModelProvider.java:102) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$viewModel$2.invoke(ExampleActivity.kt:46) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$viewModel$2.invoke(ExampleActivity.kt:43) 
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.getViewModel(Unknown Source:7) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.access$getViewModel$p(ExampleActivity.kt:43) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$presenter$2.invoke(ExampleActivity.kt:49) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity$presenter$2.invoke(ExampleActivity.kt:43) 
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.getPresenter(Unknown Source:7) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.setupWith(ExampleActivity.kt:292) 
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleActivity.onCreate(ExampleActivity.kt:55) 
        at android.app.Activity.performCreate(Activity.java:7149) 
        at android.app.Activity.performCreate(Activity.java:7140) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3027) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3182) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1916) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: com.mapbox.services.android.navigation.v5.exception.NavigationException: A valid access token must be passed in when first initializing MapboxNavigation
        at com.mapbox.services.android.navigation.v5.navigation.NavigationTelemetry.validateAccessToken(NavigationTelemetry.java:304)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationTelemetry.initialize(NavigationTelemetry.java:120)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.initializeTelemetry(MapboxNavigation.java:906)
2019-08-26 09:10:53.377 31797-31797/com.mapbox.services.android.navigation.app E/AndroidRuntime:     at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.initialize(MapboxNavigation.java:887)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.<init>(MapboxNavigation.java:118)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.<init>(MapboxNavigation.java:92)
        at com.mapbox.services.android.navigation.testapp.example.ui.ExampleViewModel.<init>(ExampleViewModel.kt:64)
```

**Comment by gajdzik** [comment]
@cmahopper Did you change access token in mapbox-navigation-android\app\src\main\res\values\developer-config.xml ?

**Comment by cmahopper** [comment]
@gajdzik Ah, no, I didn't see I had to do that.

**Comment by gajdzik** [comment]
@cmahopper I am still not able to start test app, a lot of errors accur appear. @Guardiola31337 could you provide step by step instruction how to build it from the scratch?

**Comment by gajdzik** [comment]
It is hard to reproduce with these example apps, but I did this way: 
1. Run "NavigationView implemented with Fragment"
2. Cancel navigation
3. Start navigation
4. Move map
5. Click recenter

![device-2020-01-14-135317](https://user-images.githubusercontent.com/15325804/72348498-d9056000-36da-11ea-88d9-985975c24ebf.png)
![device-2020-01-14-135753](https://user-images.githubusercontent.com/15325804/72348517-e3275e80-36da-11ea-8fd8-d7afdcd46639.png)

**Comment by JunDai** [comment]
> In my case, our work place is situated between a bunch of small roads (of a parking lot) with no names, so every time I test navigation, it happens.

@cmahopper - your above comment gives me clue how to reproduce it. I will work on a fix of the issue.

![ezgif com-resize](https://user-images.githubusercontent.com/3918950/76369812-114ba800-62f2-11ea-97bb-582d6b6eb778.gif)
