### ISSUE TITLE
NavigationView startNavigation resulting in NullPointerException

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#2056]
**Android API:** 28
**Mapbox Navigation SDK version:** 0.41.0

### Steps to trigger behavior

 1. Open the test app
 2. Click on the settings icon on top left
 3. Click on View List of Navigation Examples
 4. Click on NavigationView implemented with Fragment. Immediately close it by pressing the device back button. Make sure that navigation doesn't start.

### Expected behavior
The example should close and the user should be taken back to the list

### Actual behavior
App crashes with NPE.

Crash Log:
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: net.fleat.driver.debug, PID: 6759
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.addProgressChangeListener(com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation)' on a null object reference
at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationListeners(NavigationView.java:678)
at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigation(NavigationView.java:619)
at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:381)
at net.fleat.driver.view.fragments.NavigationFragment.startNavigation(NavigationFragment.kt:322)
at net.fleat.driver.view.fragments.NavigationFragment.access$startNavigation(NavigationFragment.kt:45)
at net.fleat.driver.view.fragments.NavigationFragment$fetchRoute$1.onResponse(NavigationFragment.kt:307)
at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteCallback.onResponse(NavigationRouteCallback.java:30)
at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:185)
at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:6718)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/ApplicationCrashHandler: uncaughtException
```

Originally reported by @davelogan in (https://github.com/mapbox/mapbox-navigation-android/issues/2038)

**Comment by abhishek1508** [comment]
@davelogan Thank you for trying our SDK and reporting the issue. 
Apparently, this is something we could reproduce. We are having discussions on how to fix this. The fix is around `NavigationView` lifecycle and needs careful modification. Meanwhile we address this issue, it would be great if you could surround your call to `navigationView.startNavigation()` inside a try/catch. This way you will be unblocked.

**Comment by Guardiola31337** [comment]
@abhishek1508 could this be reproducible in `1.0`? Could you confirm?

**Comment by abhishek1508** [comment]
Let's verify this.
cc @JunDai @cafesilencio @langsmith

**Comment by cafesilencio** [comment]
I cannot reproduce this issue in our 1.0 version of the example app.
