### ISSUE TITLE
VoiceInstruction#getSsmlAnnouncement NPE switching online / offline + rerouting

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2060]
Found 👇 while testing

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mapbox.navigator.VoiceInstruction.getSsmlAnnouncement()' on a null object reference
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.retrieveSsmlAnnouncementInstruction(MapboxNavigation.java:802)
        at com.mapbox.services.android.navigation.ui.v5.VoiceInstructionCache.cache(VoiceInstructionCache.java:69)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel$2.onMilestoneEvent(NavigationViewModel.java:432)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onMilestoneEvent(NavigationEventDispatcher.java:158)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onMilestoneTrigger(RouteProcessorThreadListener.java:46)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable$1.run(RouteProcessorRunnable.java:148)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

This happened switching heavily between online and offline + in a rerouting scenario. It seems race condition, when asking to NN to retrieve the SSML announcement, it doesn’t have it anymore causing the 💥

**Comment by emilefleming** [comment]
I'm seeing a bunch of these in our crash reports. I'd be happy to provide any additional info that I have if it helps. This is our #1 navigation related crash.

**Comment by Guardiola31337** [comment]
@JunDai could we check if this would be an issue in `1.0`?

**Comment by abhishek1508** [comment]
Since it involves switching b/w online + offline, do we have offline capabilities ready in `1.0` @Guardiola31337 
I want to confirm if it is possible to confirm this issue with the state v1.0 is in?

**Comment by Guardiola31337** [comment]
This is now guarded by `?.` https://github.com/mapbox/mapbox-navigation-android/blob/94d886891aadee76b79f86b7c8db94fcac5c038e/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt#L383-L384 and it wasn't in the legacy.

Closing here.
