### ISSUE TITLE
FeedbackEvent screenshot IllegalArgumentException: Parameter specified as non-null is null

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2196]
Found a regression from https://github.com/mapbox/mapbox-navigation-android/pull/2151 conversion 👇 during testing.

```
10-10 23:18:22.449 30410-30410/com.mapbox.services.android.navigation.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.services.android.navigation.app, PID: 30410
    java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter <set-?>
        at com.mapbox.services.android.navigation.v5.internal.navigation.metrics.FeedbackEvent.setScreenshot(FeedbackEvent.kt)
        at com.mapbox.services.android.navigation.v5.internal.navigation.NavigationTelemetry.updateFeedbackEvent(NavigationTelemetry.java:255)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.updateFeedback(MapboxNavigation.java:763)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.updateFeedback(NavigationViewModel.java:169)
        at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.onFeedbackSelected(InstructionView.java:166)
        at com.mapbox.services.android.navigation.ui.v5.feedback.FeedbackBottomSheet.onFeedbackItemClick(FeedbackBottomSheet.java:119)
        at com.mapbox.services.android.navigation.ui.v5.feedback.FeedbackClickListener.onInterceptTouchEvent(FeedbackClickListener.java:35)
```

cc @Lebedinsky

**Comment by Guardiola31337** [comment]
Fixed via https://github.com/mapbox/mapbox-navigation-android/pull/2153

Closing.
