### ISSUE TITLE
Drop in navigation UI

### ISSUE THREAD

**Issue by johnwallco** [mapbox/mapbox-navigation-android#222]
I've had pretty good success with the iOS drop in navigation UI.

For Android, I'm using the Mapbox Optimization API to get a route. I'm able to get a route from the API, but I'm not sure how to start navigation with the route response. 

How do I start navigation once I have a route?

I'm using `'com.mapbox.mapboxsdk:mapbox-android-navigation:0.5.0'`

Thanks in advance.

**Comment by danesfeder** [comment]
Hey @johnwallco - glad to hear it! 

The Android drop-in UI landed in master last Friday https://github.com/mapbox/mapbox-navigation-android/pull/180, so it's actually not in `com.mapbox.mapboxsdk:mapbox-android-navigation:0.5.0`.

You can still start using it with:
`compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.0-SNAPSHOT'`
`compile 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.6.0-SNAPSHOT@aar' `

To launch the UI with a `DirectionsRoute`, you would need to call this in an `Activity`:
`NavigationLauncher.startNavigation(this, route, null, false);`

Stayed tuned for the javadocs we are working on in https://github.com/mapbox/mapbox-navigation-android/pull/221 and future coms around this.  Initially we won't be launching with the same functionality (as far as UI customization) that you see on iOS.  But, we are working to get that out asap.

**Comment by johnwallco** [comment]
Hey @danesfeder, thanks for the info.

I get the following error when trying to launch navigation UI from an activity:

`java.lang.NoSuchMethodError: No static method setAutoSizeTextTypeUniformWithConfiguration(Landroid/widget/TextView;IIII)V in class Landroid/support/v4/widget/TextViewCompat; or its super classes (declaration of 'android.support.v4.widget.TextViewCompat' appears in /data/app/com.cryptopinion.onitsway-MxAXcQDIcolVyceSGrKG6w==/split_lib_dependencies_apk.apk:classes24.dex)`

Here's the full stack trace:

`367/com.cryptopinion.onitsway E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.cryptopinion.onitsway, PID: 29367
                                                                           java.lang.NoSuchMethodError: No static method setAutoSizeTextTypeUniformWithConfiguration(Landroid/widget/TextView;IIII)V in class Landroid/support/v4/widget/TextViewCompat; or its super classes (declaration of 'android.support.v4.widget.TextViewCompat' appears in /data/app/com.cryptopinion.onitsway-OxOe4e_3KSCOKBi9t_tDJA==/split_lib_dependencies_apk.apk:classes24.dex)
                                                                               at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.initInstructionAutoSize(InstructionView.java:162)
                                                                               at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.bind(InstructionView.java:142)
                                                                               at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.onFinishInflate(InstructionView.java:76)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:876)
                                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                                                                               at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                               at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289)
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                               at com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(NavigationView.java:88)
                                                                               at android.app.Activity.performCreate(Activity.java:6975)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                               at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                               at android.os.Looper.loop(Looper.java:164)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
09-13 16:37:47.129 29367-29367/com.cryptopinion.onitsway E/UncaughtException: java.lang.NoSuchMethodError: No static method setAutoSizeTextTypeUniformWithConfiguration(Landroid/widget/TextView;IIII)V in class Landroid/support/v4/widget/TextViewCompat; or its super classes (declaration of 'android.support.v4.widget.TextViewCompat' appears in /data/app/com.cryptopinion.onitsway-OxOe4e_3KSCOKBi9t_tDJA==/split_lib_dependencies_apk.apk:classes24.dex)
                                                                                  at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.initInstructionAutoSize(InstructionView.java:162)
                                                                                  at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.bind(InstructionView.java:142)
                                                                                  at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.onFinishInflate(InstructionView.java:76)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:876)
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                                  at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
                                                                                  at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                                  at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                                  at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:289)
                                                                                  at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                                  at com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(NavigationView.java:88)
                                                                                  at android.app.Activity.performCreate(Activity.java:6975)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)`

**Comment by danesfeder** [comment]
@johnwallco We are using https://developer.android.com/guide/topics/ui/look-and-feel/autosizing-textview.html for the top instruction text, so your app will need to target API 26.  I'll be sure to specify that in the docs / javadoc

**Comment by johnwallco** [comment]
@danesfeder I hate to keep bugging you (thanks for all the help), but I believe I'm targeting API 26.

Here's my build.gradle:



```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.1"
    defaultConfig {
        applicationId "com.cryptopinion.onitsway"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 15
        versionName "2.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
repositories {
    mavenCentral()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.3@aar') {
        transitive = true
    }
    compile 'com.android.support:appcompat-v7:26.0.0-alpha1'
    compile 'com.android.support:design:26.0.0-alpha1'
    compile 'com.jakewharton:butterknife:8.8.1'
    compile 'com.android.volley:volley:1.0.0'
    compile 'com.google.code.gson:gson:2.8.1'
    compile 'com.google.android.gms:play-services-location:10.0.1'
    compile 'com.google.android.gms:play-services-places:10.0.1'
    compile 'com.android.support:percent:26.0.0-alpha1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.0-SNAPSHOT'
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.6.0-SNAPSHOT@aar'
    testCompile 'junit:junit:4.12'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'
}

configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '26.0.0-alpha1'
            }
        }
    }
}
apply plugin: 'com.google.gms.google-services'
```

**Comment by danesfeder** [comment]
@johnwallco No problem, I want to make sure this doesn't happen to everyone.

I believe forcing the support library to use `26.0.0-alpha1` is the issue. 

I have my `appcompat` dependency as:
`compile 'com.android.support:appcompat-v7:26.0.2'` 

Maybe change that and run a `./gradlew --refresh-dependencies`  If it's still crashing, I'll look into this a bit further.  Could be something on my end and how we are compiling the SDK.

**Comment by johnwallco** [comment]
@danesfeder It looks like 26.0.2 for `appcompat` did the trick on that error.

There's a new one. There's a NoClassDefFoundError for LocationLayerPlugin:

` java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin;`

<img width="756" alt="screen shot 2017-09-13 at 8 05 12 pm" src="https://user-images.githubusercontent.com/15603363/30406331-24f3ee1c-98bf-11e7-98f1-b164b727ef6f.png">
<img width="544" alt="screen shot 2017-09-13 at 8 05 15 pm" src="https://user-images.githubusercontent.com/15603363/30406335-292ff520-98bf-11e7-98f0-9a27c34f5a98.png">

**Comment by danesfeder** [comment]
@johnwallco Yeah that's on me, it looks like something is wrong with the dependencies compiling for the SNAPSHOT.  

I'll look into it tomorrow - in meantime, you can manually add the `LocationLayerPlugin` with:
`compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.1.0'`

It also looks like there's an issue compiling `MapView` XML attributes if you don't manually include the Map SDK.  I'll look into both.

**Comment by johnwallco** [comment]
Thanks, @danesfeder. Things are going in the right direction over here.

I have several other issues at the moment, but I'll try to make sure they're not my implementation mistakes before bugging you guys again.

**Comment by danesfeder** [comment]
@johnwallco no problem, happy to help

**Comment by danesfeder** [comment]
cc @johnwallco https://github.com/mapbox/mapbox-navigation-android/issues/229#issuecomment-330220064

**Comment by guraymumun** [comment]
@johnwallco can you share (copy/paste) your gradle here?
