### ISSUE TITLE
java.lang.OutOfMemoryError: Could not allocate JNI Env

### ISSUE THREAD

**Issue by tm355** [mapbox/mapbox-navigation-android#2245]
I am retrieving Lat Lng from firebase every second and changing marker positions according to lat lng it is basically like vehicle tracking. After changing Lat Lng App crashes within 30 secs i searched a lot on Internet and dint found anything. how to solve this issue?

2019-10-31 10:22:52.284 4356-4367/com.example.gradientpolyline I/art: Background partial concurrent mark sweep GC freed 87164(3MB) AllocSpace objects, 0(0B) LOS objects, 36% free, 7MB/11MB, paused 9.723ms total 83.063ms
2019-10-31 10:22:53.225 4356-5474/com.example.gradientpolyline E/art: ashmem_create_region failed for 'indirect ref table': Too many open files
2019-10-31 10:22:53.225 4356-5474/com.example.gradientpolyline W/art: Throwing OutOfMemoryError "Could not allocate JNI Env"
2019-10-31 10:22:53.228 4356-5474/com.example.gradientpolyline E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.example.gradientpolyline, PID: 4356
    java.lang.OutOfMemoryError: Could not allocate JNI Env
        at java.lang.Thread.nativeCreate(Native Method)
        at java.lang.Thread.start(Thread.java:745)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:941)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1359)
        at okhttp3.ConnectionPool.put(ConnectionPool.java:153)
        at okhttp3.OkHttpClient$1.put(OkHttpClient.java:167)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:266)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:776)

**Comment by Guardiola31337** [comment]
@abhishek1508 @cafesilencio could this be reproducible in `1.0`? Could you confirm?

**Comment by abhishek1508** [comment]
Let's verify this.
cc @JunDai @cafesilencio @langsmith

**Comment by cafesilencio** [comment]
This issue cannot be reproduced in 1.0. Please be on the lookout for our first public preview of UI SDK v1.0 coming soon. Feel free to create a new issue if you feel it still exists.

**Comment by neha4gupta** [comment]
Yes I am facing issue while getting the lat lng on map moving. Please help me also in this issue
