### ISSUE TITLE
Issue with onAnimationEnd method in FeedbackBottomSheet

### ISSUE THREAD

**Issue by cristiantorrado-endava** [mapbox/mapbox-navigation-android#2285]
Hello we have a blocked issue with the latest  navigation SDK i attached the entire information.
We catch the error with crashlytics in several devices. 

I hope you can fix it quickly.

Thanks a lot. 

Version of libraries used:
    
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.3'
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.3'
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.5.0'

Device 
Brand: samsung
Model: Galaxy Note8
Orientation: Vertical
RAM disponible: 1.1 GB
Sistema operativo
Versión: 9
Orientación: Vertical
Acceso de superadministrador: No

Trace: 

Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManagerImpl.checkStateLoss(FragmentManagerImpl.java:1536)
       at androidx.fragment.app.FragmentManagerImpl.enqueueAction(FragmentManagerImpl.java:1558)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:317)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:282)
       at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:250)
       at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:202)
       at com.google.android.material.bottomsheet.BottomSheetDialogFragment.dismiss(BottomSheetDialogFragment.java:48)
       at com.mapbox.services.android.navigation.ui.v5.feedback.FeedbackBottomSheet.onAnimationEnd(FeedbackBottomSheet.java:124)
       at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
       at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1232)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1474)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:984)
       at android.view.Choreographer.doCallbacks(Choreographer.java:764)
       at android.view.Choreographer.doFrame(Choreographer.java:696)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:965)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by Guardiola31337** [comment]
@abhishek1508 @JunDai is this still an issue in `1.0`? Could you check?

**Comment by abhishek1508** [comment]
Let's verify
cc @JunDai @cafesilencio @langsmith

**Comment by cafesilencio** [comment]
This issue cannot be reproduced in 1.0. Please be on the lookout for our first public preview of UI SDK v1.0 coming soon. Feel free to create a new issue if you feel it still exists.

**Comment by cafesilencio** [comment]
Reopening this. I figured out how to reproduce it.

**Comment by JunDai** [comment]
@cafesilencio - would you mind to record how to reproduce it?

**Comment by cafesilencio** [comment]
@JunDai  to reproduce:
1. open the feedback button example activity
2. set a route and start navigating.
3. press the feed back button and select one of the icons.
4. before the animation finishes put the app into the background.
5. wait and watch the log the exception will appear there after a few seconds.

**Comment by cafesilencio** [comment]
Fixed in PR #3360
