### ISSUE TITLE
Crash on NativeConnectivityListener initialization when updating to 0.42.4 from 0.42.3

### ISSUE THREAD

**Issue by clj0020** [mapbox/mapbox-navigation-android#2317]
I am getting a crash when I call Mapbox.getInstance at the NativeConnectivityListener initialization when updating to 0.42.4 from 0.42.3. Here is the stacktrace:

```
2019-12-13 14:59:10.889 11546-11546/com.routematch.driveby.dev E/tch.driveby.de: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
2019-12-13 14:59:10.892 11546-11546/com.routematch.driveby.dev D/AndroidRuntime: Shutting down VM
2019-12-13 14:59:10.953 11546-11546/com.routematch.driveby.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.routematch.driveby.dev, PID: 11546
    java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:67)
        at com.routematch.driveby.DriveByRoutematchApplication.onCreate(DriveByRoutematchApplication.kt:70)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by LukasPaczos** [comment]
Hey @clj0020 thanks for reporting the issue. Is it still reproducible when you clear your build folder and rebuild the project from scratch?

**Comment by Guardiola31337** [comment]
Closing as stale.

@clj0020 Feel free to open a new ticket if you can still reproduce OP. Thanks!
