### ISSUE TITLE
NavigationLauncher with custom style map

### ISSUE THREAD

**Issue by giudon010** [mapbox/mapbox-navigation-android#2319]
Hello,
I just want to know if it is possible to change the style (for example to Satellite) when we are in navigation mode.

Thank you in advance.

**Comment by LukasPaczos** [comment]
Hey @giudon010, you can change the style by retrieving the underlying `MapboxMap`:
```
navigationView.retrieveNavigationMapboxMap().retrieveMap().setStyle(Style.SATELLITE)
```

**Comment by P-Zenker** [comment]
Hey @LukasPaczos, 

this works, until I start the navigation:

```
@SuppressLint("MissingPermission")
@Override
public void onNavigationReady(boolean isRunning) {
    mapboxMap = navigationView.retrieveNavigationMapboxMap().retrieveMap();
    mapboxMap.setStyle(Style.SATELLITE);

    [...]

    navigationView.startNavigation(navigationViewOptions);
}
```

```
2020-02-28 16:01:13.536 java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List com.mapbox.mapboxsdk.maps.Style.getSources()' on a null object reference
2020-02-28 16:01:13.536     at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.initializeStreetsSource(NavigationMapboxMap.java:676)
2020-02-28 16:01:13.536     at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.initializeWayName(NavigationMapboxMap.java:668)
2020-02-28 16:01:13.536     at com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.addProgressChangeListener(NavigationMapboxMap.java:277)
2020-02-28 16:01:13.537     at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationListeners(NavigationView.java:691)
2020-02-28 16:01:13.537     at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigation(NavigationView.java:632)
2020-02-28 16:01:13.537     at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:394)
```

What am I doing wrong?
