### ISSUE TITLE
Crashes from the driver app

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#2321]
Our app crashes when attempting to navigate.

version
```
implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.4'
```

stack trace
```
 java.lang.Error: std::bad_alloc
     at com.mapbox.mapboxsdk.style.layers.Layer.nativeGetId(Native Method)
     at com.mapbox.mapboxsdk.style.layers.Layer.getId(Layer.java:69)
     at com.mapbox.services.android.navigation.ui.v5.route.MapRouteLine.updateAlternativeVisibilityTo(MapRouteLine.java:450)
     at com.mapbox.services.android.navigation.ui.v5.route.MapRouteLine.access$500(MapRouteLine.java:44)
     at com.mapbox.services.android.navigation.ui.v5.route.MapRouteLine$1.onRouteFeaturesProcessed(MapRouteLine.java:328)
     at com.mapbox.services.android.navigation.ui.v5.route.FeatureProcessingTask$1.run(FeatureProcessingTask.java:65)
     at android.os.Handler.handleCallback(Handler.java:883)
     at android.os.Handler.dispatchMessage(Handler.java:100)
     at android.os.Looper.loop(Looper.java:214)
     at android.app.ActivityThread.main(ActivityThread.java:7356)
     at java.lang.reflect.Method.invoke(Native Method)
     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by LukasPaczos** [comment]
This is most likely an issue similar to https://github.com/mapbox/mapbox-navigation-android/pull/2315 when Nav SDK accesses the cached layer while they are invalid. Are you able to reproduce with `0.43.0-SNAPSHOT`?

**Comment by kmadsen** [comment]
When I use that version it doesn't compile. There may be too many new changes in order to get it.

```
ERROR: Failed to resolve: com.mapbox.mapboxsdk:libnavigation-util:0.43.0-SNAPSHOT
Show in Project Structure dialog
Affected Modules: app


ERROR: Failed to resolve: com.mapbox.mapboxsdk:libnavigation-base:0.43.0-SNAPSHOT
Show in Project Structure dialog
Affected Modules: app


ERROR: Failed to resolve: com.mapbox.mapboxsdk:libnavigator:0.43.0-SNAPSHOT
Show in Project Structure dialog
Affected Modules: app
```

**Comment by ludovicroland** [comment]
@kmadsen : You should add this line to your repositories list : 

```
maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
```

**Comment by kmadsen** [comment]
> maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }

Thanks! It's added.

Also I think this was resolved by https://github.com/mapbox/mapbox-navigation-android/pull/2315. So I'm closing it
