### ISSUE TITLE
Fix flaky UI tests covering examples

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2403]
The `ui-tests` CI job is flaky and we should look into idling resources/view matchers to verify that views are available before interacting with them.

Example error:
```
com.schibsted.spain.barista.internal.failurehandler.BaristaException: View (with id: com.mapbox.driver.navigation.examples:id/notifyTextView) didn't match condition (is displayed on the screen to the user)
```

/cc @korshaknn

**Comment by Guardiola31337** [comment]
Noting 👇 from https://github.com/mapbox/driver/pull/358#issuecomment-576071031

> It seems `By.res` `BySelector` and using `wait(Until.hasObject())` helps with flakiness.
>
> Going to merge here as CI ✅ but we should keep an 👀 on these tests and adapt them based on ☝️ to make them more robust and deterministic.

**Comment by evabishchevich** [comment]
PR https://github.com/mapbox/mapbox-navigation-android/pull/2463

**Comment by Guardiola31337** [comment]
We're still seeing flakiness after #2463 and run sometimes into OP's exception e.g. https://github.com/mapbox/mapbox-navigation-android/pull/2462 👀 https://circleci.com/gh/mapbox/mapbox-navigation-android/16596?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link cc @evabishchevich

**Comment by Guardiola31337** [comment]
We've seen some `ui-tests-1_0` builds failing after this landed e.g. https://circleci.com/gh/mapbox/mapbox-navigation-android/19109?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link This particular run was observed in https://github.com/mapbox/mapbox-navigation-android/pull/2527

Re-opening 😞 cc @RingerJK

**Comment by RingerJK** [comment]
@Guardiola31337 imo issue appears only on low power devices, created [PR](https://github.com/mapbox/mapbox-navigation-android/pull/2590) where max timeout for view's appearance  increased to 10 sec. Lets merge and wait for results and how it works

**Comment by RingerJK** [comment]
Idling resources support issue https://github.com/mapbox/mapbox-navigation-android/issues/2767 (discussed https://github.com/mapbox/mapbox-navigation-android/pull/2590#discussion_r401254693)

**Comment by Guardiola31337** [comment]
`ui-tests-1_0` failed in https://circleci.com/gh/mapbox/mapbox-navigation-android/22193?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Wondering if it's a regression of https://github.com/mapbox/mapbox-navigation-android/pull/2590 or was just another flaky run (or both 😅) 🤔 

These are the stacktraces of the two tests that failed failed

`checkNotificationContent`

```com.schibsted.spain.barista.internal.failurehandler.BaristaException: View (with id: com.mapbox.navigation.examples:id/notifyTextView) didn't match condition (is displayed on the screen to the user)
at com.schibsted.spain.barista.internal.failurehandler.SpyFailureHandler.resendFirstError(SpyFailureHandler.kt:25)
at com.schibsted.spain.barista.internal.AssertAnyKt.assertAnyView(AssertAny.kt:42)
at com.schibsted.spain.barista.internal.AssertAnyKt.assertAny(AssertAny.kt:18)
at com.schibsted.spain.barista.assertion.BaristaVisibilityAssertions.assertDisplayed(BaristaVisibilityAssertions.kt:30)
at com.mapbox.navigation.examples.activity.TripServiceActivityKtTest.checkNotificationContent(TripServiceActivityKtTest.kt:68)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at com.schibsted.spain.barista.rule.cleardata.ClearFilesRule$apply$1.evaluate(ClearFilesRule.kt:25)
at com.schibsted.spain.barista.rule.cleardata.ClearDatabaseRule$apply$1.evaluate(ClearDatabaseRule.kt:30)
at com.schibsted.spain.barista.rule.cleardata.ClearPreferencesRule$1.evaluate(ClearPreferencesRule.java:26)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at com.schibsted.spain.barista.rule.flaky.internal.AllowFlakyStatement.evaluate(AllowFlakyStatement.java:27)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1970)
Caused by: junit.framework.AssertionFailedError: 'is displayed on the screen to the user' doesn't match the selected view.
Expected: is displayed on the screen to the user
Got: "AppCompatTextView{id=2131296487, res-name=notifyTextView, visibility=VISIBLE, width=0, height=65, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@e22c144, tag=null, root-is-layout-requested=false, has-input-connection=false, x=540.0, y=1423.0, text=, input-type=0, ime-target=false, has-links=false}"

at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:539)
at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:103)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:419)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:282)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:268)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

`checkNotificationViewContent`

```
Test failed to run to completion. Reason: 'Test run failed to complete. Expected 3 tests, received 2'. Check device logcat for details
```

```
java.lang.IllegalStateException: UiAutomation not connected!
     FATAL EXCEPTION: Instr: androidx.test.runner.AndroidJUnitRunner
Process: com.mapbox.navigation.examples, PID: 1990
java.lang.IllegalStateException: UiAutomation not connected!
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:971)
	at android.app.UiAutomation.disconnect(UiAutomation.java:237)
	at android.app.Instrumentation.finish(Instrumentation.java:222)
	at androidx.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:364)
	at androidx.test.runner.AndroidJUnitRunner.finish(AndroidJUnitRunner.java:412)
	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:401)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1970)
```

cc @RingerJK

**Comment by RingerJK** [comment]
@Guardiola31337 seems that it kind of flaky. I've received similar issues as well

**Comment by Guardiola31337** [comment]
`ui-tests-1_0` failed in https://circleci.com/gh/mapbox/mapbox-navigation-android/27043?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

`checkNotificationContent`

```
com.schibsted.spain.barista.internal.failurehandler.BaristaException: View (with id: com.mapbox.navigation.examples:id/notifyTextView) didn't match condition (is displayed on the screen to the user)
at com.schibsted.spain.barista.internal.failurehandler.SpyFailureHandler.resendFirstError(SpyFailureHandler.kt:25)
at com.schibsted.spain.barista.internal.AssertAnyKt.assertAnyView(AssertAny.kt:42)
at com.schibsted.spain.barista.internal.AssertAnyKt.assertAny(AssertAny.kt:18)
at com.schibsted.spain.barista.assertion.BaristaVisibilityAssertions.assertDisplayed(BaristaVisibilityAssertions.kt:30)
at com.mapbox.navigation.examples.activity.TripServiceActivityKtTest.checkNotificationContent(TripServiceActivityKtTest.kt:74)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at com.schibsted.spain.barista.rule.cleardata.ClearFilesRule$apply$1.evaluate(ClearFilesRule.kt:25)
at com.schibsted.spain.barista.rule.cleardata.ClearDatabaseRule$apply$1.evaluate(ClearDatabaseRule.kt:30)
at com.schibsted.spain.barista.rule.cleardata.ClearPreferencesRule$1.evaluate(ClearPreferencesRule.java:26)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at com.schibsted.spain.barista.rule.flaky.internal.AllowFlakyStatement.evaluate(AllowFlakyStatement.java:27)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1970)
Caused by: junit.framework.AssertionFailedError: 'is displayed on the screen to the user' doesn't match the selected view.
Expected: is displayed on the screen to the user
Got: "MaterialTextView{id=2131296572, res-name=notifyTextView, visibility=VISIBLE, width=0, height=65, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@b9a12e6, tag=null, root-is-layout-requested=false, has-input-connection=false, x=888.0, y=727.0, text=, input-type=0, ime-target=false, has-links=false}"

at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:539)
at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:103)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:419)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:282)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:268)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

`checkNotificationViewContent`

```
com.schibsted.spain.barista.internal.failurehandler.BaristaException: View (with id: com.mapbox.navigation.examples:id/notifyTextView) didn't match condition (is displayed on the screen to the user)
at com.schibsted.spain.barista.internal.failurehandler.SpyFailureHandler.resendFirstError(SpyFailureHandler.kt:25)
at com.schibsted.spain.barista.internal.AssertAnyKt.assertAnyView(AssertAny.kt:42)
at com.schibsted.spain.barista.internal.AssertAnyKt.assertAny(AssertAny.kt:18)
at com.schibsted.spain.barista.assertion.BaristaVisibilityAssertions.assertDisplayed(BaristaVisibilityAssertions.kt:30)
at com.mapbox.navigation.examples.activity.TripServiceActivityKtTest.checkNotificationViewContent(TripServiceActivityKtTest.kt:62)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at com.schibsted.spain.barista.rule.cleardata.ClearFilesRule$apply$1.evaluate(ClearFilesRule.kt:25)
at com.schibsted.spain.barista.rule.cleardata.ClearDatabaseRule$apply$1.evaluate(ClearDatabaseRule.kt:30)
at com.schibsted.spain.barista.rule.cleardata.ClearPreferencesRule$1.evaluate(ClearPreferencesRule.java:26)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at com.schibsted.spain.barista.rule.flaky.internal.AllowFlakyStatement.evaluate(AllowFlakyStatement.java:27)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.ext.junit.runners.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1970)
Caused by: junit.framework.AssertionFailedError: 'is displayed on the screen to the user' doesn't match the selected view.
Expected: is displayed on the screen to the user
Got: "MaterialTextView{id=2131296572, res-name=notifyTextView, visibility=VISIBLE, width=0, height=65, has-focus=false, has-focusable=false, has-window-focus=true, is-clickable=false, is-enabled=true, is-focused=false, is-focusable=false, is-layout-requested=false, is-selected=false, layout-params=androidx.constraintlayout.widget.ConstraintLayout$LayoutParams@647772, tag=null, root-is-layout-requested=false, has-input-connection=false, x=540.0, y=1423.0, text=, input-type=0, ime-target=false, has-links=false}"

at androidx.test.espresso.matcher.ViewMatchers.assertThat(ViewMatchers.java:539)
at androidx.test.espresso.assertion.ViewAssertions$MatchesViewAssertion.check(ViewAssertions.java:103)
at androidx.test.espresso.ViewInteraction$SingleExecutionViewAssertion.check(ViewInteraction.java:419)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:282)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:268)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by Guardiola31337** [comment]
`checkNotificationContent` and `checkNotificationViewContent` `ui-tests-1_0` failed again in https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/7419/workflows/9f76cc43-d115-4da6-9abd-83647b594aa6/jobs/28338/steps

cc @RingerJK @Lebedinsky

**Comment by Guardiola31337** [comment]
And again 😬 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/7429/workflows/46fd1d75-6a53-402c-a9a1-146768c09e67/jobs/28370/steps

**Comment by RingerJK** [comment]
@Guardiola31337 was it resolved?

**Comment by Guardiola31337** [comment]
@RingerJK 
> was it resolved?

I don't think so. That being said, we haven't seen `checkNotificationContent` failing recently (`checkNotificationViewContent` was removed in https://github.com/mapbox/mapbox-navigation-android/pull/3363).
