### ISSUE TITLE
IllegalStateException: MapboxNavigationAccounts: skuToken cannot be null or empty

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2424]
Found a 💥 during testing https://github.com/mapbox/mapbox-navigation-android/pull/2410

```
01-24 07:47:48.637 16782-16866/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.mapbox.navigation.examples, PID: 16782
    java.lang.IllegalStateException: MapboxNavigationAccounts: skuToken cannot be null or empty
        at com.mapbox.navigation.core.accounts.MapboxNavigationAccounts.obtainSkuToken(MapboxNavigationAccounts.kt:51)
        at com.mapbox.navigation.route.offboard.RouteBuilderProvider$getBuilder$1.intercept(RouteBuilderProvider.kt:37)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

As mentioned in https://github.com/mapbox/mapbox-navigation-android/pull/2410#pullrequestreview-347887903 it's probably an issue downstream in `mapboxAndroidAccounts` library caused by using an API that is not available in older devices as I'm getting an empty string from https://github.com/mapbox/mapbox-navigation-android/blob/959ff26789ce25643315ab8c5dbe82bdd8e7934c/libnavigation-core/src/main/java/com/mapbox/navigation/core/accounts/MapboxNavigationAccounts.kt#L50 and only when running in a Nexus 5 Android 6.0.1 but not when running in a Pixel 3 Android 9.

There's a new `mapbox-android-accounts` version available that updates the codebase to be AndroidX compatible, we should update `mapbox-navigation-accounts-android` and see if that solves the issue.

cc @abhishek1508 @mapbox/navigation-android

**Comment by zugaldia** [comment]
Capturing chat - this is possibly similar to https://github.com/mapbox/mapbox-gl-native-android/pull/145.
