### ISSUE TITLE
After turning off location permission navigation sdk crashes

### ISSUE THREAD

**Issue by jczerski** [mapbox/mapbox-navigation-android#2465]
**Android API: 24**
**Mapbox Navigation SDK version: 0.42.4**

### Steps to trigger behavior
```
fun test(route: DirectionsRoute, context: Context, mapboxToken: String) {
        val navigation = MapboxNavigation(context, mapboxToken)
        navigation.startNavigation(route)
        navigation.onDestroy()
}
```

 1. Trigger above code.
 2. Turn off location permission in app settings
 3. Go back to application

### Expected behavior
Navigation has stopped.

### Actual behavior
Crash with stacktrace:
```
java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission.
        at android.os.Parcel.readException(Parcel.java:1683)
        at android.os.Parcel.readException(Parcel.java:1636)
        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:614)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:887)
        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:503)
        at com.mapbox.android.core.location.AndroidLocationEngineImpl.requestLocationUpdates(AndroidLocationEngineImpl.java:71)
        at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:48)
        at com.mapbox.android.core.location.MapboxFusedLocationEngineImpl.requestLocationUpdates(MapboxFusedLocationEngineImpl.java:21)
        at com.mapbox.android.core.location.LocationEngineProxy.requestLocationUpdates(LocationEngineProxy.java:34)
        at com.mapbox.services.android.navigation.v5.navigation.LocationUpdater.requestInitialLocationUpdates(LocationUpdater.java:58)
        at com.mapbox.services.android.navigation.v5.navigation.LocationUpdater.<init>(LocationUpdater.java:31)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initializeLocationUpdater(NavigationService.java:124)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initialize(NavigationService.java:95)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.startNavigation(NavigationService.java:66)
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.onServiceConnected(MapboxNavigation.java:813)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1465)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1482)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756

```

**Comment by Guardiola31337** [comment]
Is this an issue in the `1.0` SDK @mapbox/navigation-android? cc @Lebedinsky

**Comment by LukasPaczos** [comment]
We've not seen any occurrences in 1TAP, this should be good to close.
