### ISSUE TITLE
Transaction too large in MapboxTripNotification

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2494]
I just run into this exception, which would suggest, that we're pushing too much data to the `MapboxTripNotification` via the `NotificationManager`:
```
2020-02-18 12:52:53.964 6775-6775/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 6775
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1037404 bytes
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:497)
        at android.app.NotificationManager.notify(NotificationManager.java:444)
        at android.app.NotificationManager.notify(NotificationManager.java:420)
        at com.mapbox.navigation.trip.notification.MapboxTripNotification.updateNotification(MapboxTripNotification.kt:96)
        at com.mapbox.navigation.core.trip.service.MapboxTripService.updateNotification(MapboxTripService.kt:98)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:278)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:30)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$fireOffStatusPolling$1.invokeSuspend(MapboxTripSession.kt:257)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1037404 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:510)
        at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:2753)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:494)
        at android.app.NotificationManager.notify(NotificationManager.java:444) 
        at android.app.NotificationManager.notify(NotificationManager.java:420) 
        at com.mapbox.navigation.trip.notification.MapboxTripNotification.updateNotification(MapboxTripNotification.kt:96) 
        at com.mapbox.navigation.core.trip.service.MapboxTripService.updateNotification(MapboxTripService.kt:98) 
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:278) 
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:30) 
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$fireOffStatusPolling$1.invokeSuspend(MapboxTripSession.kt:257) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

/cc @mapbox/navigation-android

**Comment by Guardiola31337** [comment]
Ohh the old good `TransactionTooLargeException` https://github.com/mapbox/mapbox-navigation-android/issues/1188 is back 😞 

Probably we can close here as duplicated but are you able to reproduce consistently with `1.0` @LukasPaczos? If so, could you add some more information around your test setup and used device?

**Comment by JunDai** [comment]
@LukasPaczos - second on @Guardiola31337 's comment above, are you able to consistently reproduce it and may I have more details around how you test it and what devices were you using?

**Comment by LukasPaczos** [comment]
I'm not able to reproduce. I had an emulator (Nexus 5X API 29) idling in the `SimpleMapboxNavigationKt` example with trip session started. After a couple of minutes I came back to the emulator, the app was closed and I noticed the stack trace. I don't have more info, sorry!

**Comment by evabishchevich** [comment]
I've also got this exception once  in the similar to @LukasPaczos situation

**Comment by Guardiola31337** [comment]
> After a couple of minutes I came back to the emulator, the app was closed and I noticed the stack trace.

Yeah, as mentioned in https://github.com/mapbox/mapbox-navigation-android/issues/1188#issuecomment-410692283

> Something is getting "built-up" until this exception occurs.

Let's close here and keep investigating and following up in https://github.com/mapbox/mapbox-navigation-android/issues/1188 as it seems this is not new from 1.0.

Closing here as duplicated.

cc @LukasPaczos @evabishchevich @JunDai
