### ISSUE TITLE
IndexOutOfBounds when rerouting

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2501]
Refs https://github.com/mapbox/mapbox-navigation-android/pull/2477.

When re-routing, the previous bearing's list might've been empty which will lead to the `IndexOutOfBoundsException`. We should fill it with nulls to match the number of coordinates instead.

```
2020-02-20 14:21:17.007 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.logistics_example, PID: 31056
    java.lang.IndexOutOfBoundsException: toIndex = 2
        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
        at java.util.ArrayList.subList(ArrayList.java:1008)
        at com.mapbox.navigation.core.MapboxNavigation.buildAdjustedRouteOptions(MapboxNavigation.kt:498)
        at com.mapbox.navigation.core.MapboxNavigation.reRoute(MapboxNavigation.kt:474)
        at com.mapbox.navigation.core.MapboxNavigation.access$reRoute(MapboxNavigation.kt:105)
        at com.mapbox.navigation.core.MapboxNavigation$createInternalOffRouteObserver$1.onOffRouteStateChanged(MapboxNavigation.kt:454)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.setOffRoute(MapboxTripSession.kt:80)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$setOffRoute$p(MapboxTripSession.kt:30)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$fireOffStatusPolling$1.invokeSuspend(MapboxTripSession.kt:258)
```

/cc @korshaknn

**Comment by LukasPaczos** [comment]
The reroute request still fails when the initial bearing list was empty (doesn't throw an exception anymore though), the number of new bearing arguments doesn't match.
https://github.com/mapbox/mapbox-navigation-android/blob/c325d9d2531a008f87cc14945edf69c3daf2f602/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt#L504-L515

Above, the number of bearing arguments should always be equal to the number of coordinates, we need to pass trailing `null`s in this case.

/cc @Guardiola31337 @korshaknn
