### ISSUE TITLE
ReplayRouteLocationEngine crashes when calling startTripSession early

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#2514]
**Mapbox Navigation SDK version:** 1.0.0

### Steps to trigger behavior

 1. Create an app that uses ReplayRouteLocationEngine
 2. Create a mapbox navigator and call startTripSession early

### Expected behavior
Does not crash

### Actual behavior
Crashes with stack trace
```
2020-02-26 17:29:36.733 9190-9190/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.example, PID: 9190
    kotlin.UninitializedPropertyAccessException: lateinit property lastLocation has not been initialized
        at com.mapbox.services.android.navigation.v5.location.replay.ReplayRouteLocationEngine.getLastLocation(ReplayRouteLocationEngine.kt:93)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.startLocationUpdates(MapboxTripSession.kt:108)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.start(MapboxTripSession.kt:98)
        at com.mapbox.navigation.core.MapboxNavigation.startTripSession(MapboxNavigation.kt:179)
        at com.mapbox.example.MyViewModel.startTripSession(MyViewModel.kt:123)
```

This should be nullable. Please don't make a default 0,0 location that makes the app think we're in the ocean :)
https://github.com/mapbox/mapbox-navigation-android/blob/c325d9d2531a008f87cc14945edf69c3daf2f602/libnavigation-core/src/main/java/com/mapbox/navigation/core/location/ReplayRouteLocationEngine.kt#L33
```

**Comment by kmadsen** [comment]
cc: @RingerJK

**Comment by RingerJK** [comment]
@kmadsen what app did you use to get the crash?

**Comment by RingerJK** [comment]
@kmadsen I think this one https://github.com/mapbox/driver/pull/462, doesn't it?
