### ISSUE TITLE
com.mapbox.api.directions.v5.models.LegStep.drivingSide() NPE

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#2555]
Run into the following 💥 when testing `master`

```
03-09 17:35:32.810 18055-18055/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 18055
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mapbox.api.directions.v5.models.LegStep.drivingSide()' on a null object reference
        at com.mapbox.navigation.ui.instruction.InstructionModel.<init>(InstructionModel.java:18)
        at com.mapbox.navigation.ui.instruction.InstructionView.updateDistanceWith(InstructionView.java:302)
        at com.mapbox.navigation.examples.core.NavigateWithInstructionViewActivity$routeProgressObserver$1.onRouteProgressChanged(NavigateWithInstructionViewActivity.kt:215)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:277)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:31)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$fireOffStatusPolling$1.invokeSuspend(MapboxTripSession.kt:255)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Steps to reproduce:

1. Open `examples` test app
2. Click on `Navigation Core SDK` card
3. Scroll down to `Navigate with InstructionView` example
4. Click on `Navigate with InstructionView`
5. Click on `START NAVIGATION`
6. 💥 

Also, why is `NavigateWithInstructionViewActivity` under the core examples? Shouldn't be under UI ones?

cc @abhishek1508

**Comment by Guardiola31337** [comment]
`NavigateWithInstructionViewActivity` example was brought in https://github.com/mapbox/mapbox-navigation-android/pull/2519

**Comment by abhishek1508** [comment]
@Guardiola31337 
Are you navigating on mock location app? I followed the same steps. The app is not crashing for me. 

The idea of `NavigateWithInstructionViewActivity ` is to show how to integrate `InstructionView` with core; hence it is under core.

**Comment by Guardiola31337** [comment]
> Are you navigating on mock location app? I followed the same steps. The app is not crashing for me. 

No mock location app. In any case, we should handle that `null` case down in the `InstructionView` / `InstructionModel`.

**Comment by JunDai** [comment]
@abhishek1508 - you need to test the master code to reproduce it.
I think @cafesilencio has code to fix this NPE in the branch `feature/ak-#253_navigation_view_example`

**Comment by abhishek1508** [comment]
I agree we should handle the `null` case down in the `InstructionView / InstructionModel.`
But still the app doesn't crash for me without using the mock location app.

**Comment by abhishek1508** [comment]
@jun I am testing `master`

**Comment by JunDai** [comment]
interesting, I can reproduce it.

**Comment by abhishek1508** [comment]
Also, this activity was added mostly to test `JunctionView`. If you look at 
```
mapboxNavigation.requestRoutes(
            RouteOptions.builder().applyDefaultParams()
                .baseUrl("https://api-valhalla-route-staging.tilestream.net")
                .accessToken(Mapbox.getAccessToken()!!)
                .coordinates(origin, null, destination)
                .alternatives(true)
                .profile(DirectionsCriteria.PROFILE_DRIVING_TRAFFIC)
                .bannerInstructions(true)
                .build(),
            routesReqCallback
        )
```
it uses `https://api-valhalla-route-staging.tilestream.net` as the baseURL combined with a specific `accessToken` to show junctions. If you don't have the `accessToken` it won't generate the route. In this case you are then navigating without a route. Try with `api.mapbox.com` as baseURL and see if it helps.

**Comment by Guardiola31337** [comment]
@abhishek1508 are we good to close here as https://github.com/mapbox/mapbox-navigation-android/pull/2559 landed? Is there something missing?

cc @JunDai

**Comment by abhishek1508** [comment]
Yes
