### ISSUE TITLE
Instrument tests throw exception

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#2612]
Instrumental tests exception.

**Android API:** any
**Mapbox Navigation SDK version:** 1.0.0-beta1

### Steps to trigger behavior
 1. run Instrumental tests on [examples module](https://github.com/mapbox/mapbox-navigation-android/tree/master/examples)([TripServiceActivityKtTest](https://github.com/mapbox/mapbox-navigation-android/blob/master/examples/src/androidTest/java/com/mapbox/navigation/examples/activity/TripServiceActivityKtTest.kt) is a good sample) via Android Studio UI or in _shell_
 ```
adb shell am instrument -w -r    -e debug false -e class 'com.mapbox.navigation.examples.activity.TripServiceActivityKtTest' com.mapbox.navigation.examples.test/androidx.test.runner.AndroidJUnitRunner
```
 2. wait for tests pass _Successfully_
 3. run it second time 

### Expected behavior
Tests must pass _Successfully_  
###  Actual behavior
Failing with Exception 
```
com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
    Process: com.mapbox.navigation.examples, PID: 26219
    java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
        at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.java:139)
        at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:119)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:142)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:409)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:92)
        at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:53)
        at androidx.room.RoomDatabase.beginTransaction(RoomDatabase.java:328)
        at androidx.work.impl.utils.ForceStopRunnable.cleanUp(ForceStopRunnable.java:135)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:79)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

### Note 
Problem doesn't make effect on CI because tests run ok **first time** but, it's a blocker for [Android Test Orchestrator](https://developer.android.com/training/testing/junit-runner#using-android-test-orchestrator) integration([issue](https://github.com/mapbox/mapbox-navigation-android/issues/2613))

cc @mapbox/navigation-android

**Comment by RingerJK** [comment]
Seems that issue was with `Telemetry SDK` and  `Support Android Library`, support was [replaced](https://github.com/mapbox/mapbox-events-android/pull/450) by Android X. Issue is not reproduced
