### ISSUE TITLE
NotificationManager throw Exception on huge parcel object

### ISSUE THREAD

**Issue by RingerJK** [mapbox/mapbox-navigation-android#2617]
**Android API:** 
**Mapbox Navigation SDK version:** 1.0.0-beta1

### Steps to trigger behavior

 1. Start Trip Session
 2. Wait for exception

```
2020-03-19 16:00:08.217 13131-13131/com.mapbox.navigation.examples E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1039052)
2020-03-19 16:00:08.225 13131-13131/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 13131
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1039052 bytes
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:342)
        at android.app.NotificationManager.notify(NotificationManager.java:292)
        at android.app.NotificationManager.notify(NotificationManager.java:276)
        at com.mapbox.navigation.trip.notification.MapboxTripNotification.updateNotification(MapboxTripNotification.kt:116)
        at com.mapbox.navigation.core.trip.service.MapboxTripService.updateNotification(MapboxTripService.kt:98)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:289)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:31)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$fireOffStatusPolling$1.invokeSuspend(MapboxTripSession.kt:268)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1039052 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:628)
        at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:899)
```

**Comment by Guardiola31337** [comment]
Are you able to consistently reproduce it? Could you add some more information around your test setup and used device?

BTW this is a well-known issue 👀 the old good `TransactionTooLargeException` https://github.com/mapbox/mapbox-navigation-android/issues/1188 😞 

Let's close here and keep investigating and following up in https://github.com/mapbox/mapbox-navigation-android/issues/1188 as it seems this is not new from 1.0.

Closing here as duplicated.

cc @JunDai

**Comment by RingerJK** [comment]
@Guardiola31337 I'll try to reproduce it and send an update to https://github.com/mapbox/mapbox-navigation-android/issues/1188
