### ISSUE TITLE
Fix NPE: VoiceInstructionLoader.requestInstruction()

### ISSUE THREAD

**Issue by abhishek1508** [mapbox/mapbox-navigation-android#2636]
```
03-23 11:56:45.386 14671-14671/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 14671
    java.lang.NullPointerException: Null instruction
        at com.mapbox.api.speech.v1.AutoValue_MapboxSpeech$Builder.instruction(AutoValue_MapboxSpeech.java:216)
        at com.mapbox.navigation.ui.voice.VoiceInstructionLoader.requestInstruction(VoiceInstructionLoader.java:98)
        at com.mapbox.navigation.ui.voice.VoiceInstructionLoader.cacheInstruction(VoiceInstructionLoader.java:124)
        at com.mapbox.navigation.ui.voice.VoiceInstructionLoader.cacheInstructions(VoiceInstructionLoader.java:76)
        at com.mapbox.navigation.ui.VoiceInstructionCache.cache(VoiceInstructionCache.java:82)
        at com.mapbox.navigation.ui.NavigationViewModel$1.onNewVoiceInstructions(NavigationViewModel.java:441)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateRouteProgress$3.invoke(MapboxTripSession.kt:297)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateRouteProgress$3.invoke(MapboxTripSession.kt:31)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.checkVoiceInstructionEvent(MapboxTripSession.kt:318)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:295)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:31)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$fireOffStatusPolling$1.invokeSuspend(MapboxTripSession.kt:267)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Guardiola31337** [comment]
@abhishek1508 are we good to close here as https://github.com/mapbox/mapbox-navigation-android/pull/2638 landed? I think so but just in case we're missing something.
