### ISSUE TITLE
Re-route crashes when Waypoint Indices is set and more than 2 waypoints are added.

### ISSUE THREAD

**Issue by tekblom** [mapbox/mapbox-navigation-android#2644]
Hi,

I'm having problems that re-route crashes when adding more than 2 waypoints and setting the Waypoint Indices. I have the problem in my app and was able to reproduce it in v0.42.6. 

In the v0.42.6 I've changed NavigationLauncherActivity on the following places:
- Changed row 206 to allow 6 waypoints: `if (wayPoints.size() == 6) {`
- Added the following line on row 264: `builder.addWaypointIndices(0,wayPoints.size());`

**Android API:** same as v0.42.6. 
**Mapbox Navigation SDK version:** same as v0.42.6. 

### Steps to trigger behavior
(add the lines of codes to the test app as I've written)
 1. Add more than 2 Waypoints
 2. Navigate off the route
![ezgif com-gif-maker](https://user-images.githubusercontent.com/607822/77564361-e43af000-6ec2-11ea-80ce-576ec609303f.gif)

### Expected behavior
It should re-route and I would prefer if it actually removed the waypoints and only kept the destination.

### Actual behavior
It crashes. Stacktrace is:
```
com.mapbox.core.exceptions.ServicesException: Waypoints must contain indices of the first and last coordinates
        at com.mapbox.api.directions.v5.MapboxDirections$Builder.build(MapboxDirections.java:920)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationRoute$Builder.build(NavigationRoute.java:713)
        at com.mapbox.services.android.navigation.v5.route.RouteFetcher.findRouteWith(RouteFetcher.java:148)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewRouter.findOnlineRouteWith(NavigationViewRouter.java:157)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewRouter.findRouteFrom(NavigationViewRouter.java:82)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.handleOffRouteEvent(NavigationViewModel.java:540)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.access$100(NavigationViewModel.java:54)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel$1.userOffRoute(NavigationViewModel.java:423)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onUserOffRoute(NavigationEventDispatcher.java:171)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorThreadListener.onUserOffRoute(RouteProcessorThreadListener.java:57)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable$1.run(RouteProcessorRunnable.java:149)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by hlinero** [comment]
I actually have the same problem when re-routing. I have been struggling with this problem for few months now and I cannot find a way of solving it. I am also using version v0.42.6. What can we do to make it work?

**Comment by Guardiola31337** [comment]
cc'ing @RingerJK as he has been working recently on 👀 https://github.com/mapbox/mapbox-navigation-android/issues/1781

**Comment by RingerJK** [comment]
We need support from native team to solve this issue. Keep this issue open to track problem

**Comment by LukasPaczos** [comment]
@RingerJK what's the support we need? Is this issue reproducible in 1.0.0 as well?

**Comment by RingerJK** [comment]
@LukasPaczos yes, this issue is reproduced at 1.0 and as mentioned above it should be resolved at #1781 . Supporting `Silent waypoints` by Native team was postponed to Q4 2020

**Comment by Guardiola31337** [comment]
A fix for https://github.com/mapbox/mapbox-navigation-android/issues/1781 landed 🎉 

Are we good to close here @RingerJK @Lebedinsky?

**Comment by RingerJK** [comment]
I would say yes, lets close it 🥳
