### ISSUE TITLE
Intermittent crash in VoiceInstructionLoader

### ISSUE THREAD

**Issue by Vavassor** [mapbox/mapbox-navigation-android#2687]
We're using a `NavigationView` in an activity very similar to the [Embedded Navigation](https://docs.mapbox.com/android/navigation/examples/embedded-navigation/) example. However, we don't set the `speechAnnouncementListener`. I think this means the navigation view is using the default speech announcement behavior.

When navigating and receiving directions, the app intermittently crashes. The device is docked and the user isn't interacting with it, but it is on and displaying the activity. It logs the following errors in this order, just before crashing.

```
onFailure cache instruction
java.net.SocketException: socket already closed
	at java.net.PlainSocketImpl.socketClose0(PlainSocketImpl.java:211)
	at java.net.AbstractPlainSocketImpl.socketClose(AbstractPlainSocketImpl.java:721)
	at java.net.AbstractPlainSocketImpl.close(AbstractPlainSocketImpl.java:546)
	at java.net.SocksSocketImpl.close(SocksSocketImpl.java:554)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:375)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
	at java.net.Socket.connect(Socket.java:616)
	at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:73)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.mapbox.services.android.navigation.ui.v5.voice.VoiceInstructionLoader$1.intercept(VoiceInstructionLoader.java:135)
	...
```
```
onFailure cache instruction
java.net.SocketException: socket failed: EMFILE (Too many open files)
	at java.net.Socket.createImpl(Socket.java:487)
	at java.net.Socket.getImpl(Socket.java:547)
	at java.net.Socket.setSoTimeout(Socket.java:1175)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:245)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.mapbox.services.android.navigation.ui.v5.voice.VoiceInstructionLoader$1.intercept(VoiceInstructionLoader.java:135)
	...
```

```
java.lang.RuntimeException: javax.net.ssl.SSLException: Unable to create application data
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.newSsl(ConscryptFileDescriptorSocket.java:161)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.<init>(ConscryptFileDescriptorSocket.java:152)
	at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:149)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:309)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.mapbox.services.android.navigation.ui.v5.voice.VoiceInstructionLoader$1.intercept(VoiceInstructionLoader.java:135)
...
```

Before those three messages, it logs a message `Unknown`, with no other text. It does this 300-400 times, once per second. The "unknown" message is at the log level of "warning" and has no stack trace. I'm not clear where that message is logged.

If I were to guess, it seems to indicate something is failing over and over. And then eventually running out the limit of open files allowed.

**Device Manufacturer**: Zebra 
**Device Model**: TC57

**Android API:** 27
**Mapbox Navigation SDK version:** 0.42.6

### Steps to trigger behavior

 1. Follow directions along a single long route with no waypoints and without reaching the destination.
 2. It eventually crashes with no user action. The device and screen are both on with the navigation activity foregrounded. It has also occurred with the screen off.

### Expected behavior

The navigation view should display directions until the destination is reached.

### Actual behavior

The entire app crashes.

**Comment by Guardiola31337** [comment]
@JunDai could we check if this would be an issue in `1.0`? Probably fixed by https://github.com/mapbox/mapbox-navigation-android/pull/3297, right?

**Comment by Guardiola31337** [comment]
@JunDai did you have a chance to check?

**Comment by JunDai** [comment]
I don't see such issue during my day to day testing in `1.0` but it might because I am always using a relative short route.
Let me try with some longer route and use the same step as @Vavassor mentioned in the ticket.

**Comment by Vavassor** [comment]
@JunDai I was not able to reproduce this on `1.0.0-rc6`, so it would be fair to close this issue.

I originally said it was intermittent, but we found a pretty reliable route that would crash around the 10 minute mark. My coworker also had a reproduction app he made for support, which we tested on `0.42.6`. And it later worked on `1.0.0-rc6`. So I'm fairly confident it's fixed.
