### ISSUE TITLE
Null-Pointer exception when starting navigation

### ISSUE THREAD

**Issue by DavidMautendorfer** [mapbox/mapbox-navigation-android#2760]
gradle:
 implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.1.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'

Activity:
 NavigationRoute.builder(NavigationActivityCar.this)
                                .accessToken(getAccesToken())
                                .origin(originPoint)
                                .destination(destinationPoint)
                                .build()
                                .getRoute(new Callback<DirectionsResponse>() {
                                    @Override
                                    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
                                       
                                        currentRoute=response.body().routes().get(0);
                                    }

                                    @Override
                                    public void onFailure(Call<DirectionsResponse> call, Throwable t) {

                                    }
                                });
                        NavigationLauncherOptions options = NavigationLauncherOptions.builder()
                                .directionsRoute(currentRoute)
                                .shouldSimulateRoute(simulateRoute)
                                .build();
 NavigationLauncher.startNavigation(NavigationActivityCar.this, options);

This produces an error in NavigatioLauncherOptions in " NavigationLauncher.startNavigation(NavigationActivityCar.this, options);"

AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.caring_app, PID: 803
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.caring_app/com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(android.os.Bundle)' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(android.os.Bundle)' on a null object reference
        at com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity.onCreate(MapboxNavigationActivity.java:32)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6077) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by muhammad-azhar** [comment]
@DavidMautendorfer Have you resolved this issue cause i am having the same error?

**Comment by Guardiola31337** [comment]
@abhishek1508 could we check if this would be an issue in `1.0`?

Also this references https://github.com/mapbox/mapbox-navigation-android/issues/3034

**Comment by Guardiola31337** [comment]
Also noting that `NavigationLauncher` is going to be deprecated in UI SDK `1.0`.

**Comment by abhishek1508** [comment]
Since `NavigationLauncher` is deprecated in `1.0` we are not going to address this.

cc @Guardiola31337

**Comment by Guardiola31337** [comment]
Closing then @abhishek1508?
