### ISSUE TITLE
Resources$NotFoundException: crash on Pre-Lollipop Emulator

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#2763]
**Android API:** 19

### Steps to trigger behavior

 1. run `example` app on Android OS 19 emulator
 2. select **Navigation UI SDK** 
 3. launch `Navigation View` or `Custom Puck Example` or `Custom Camera Example` -- _seems only these three example crashes._

### Expected behavior
example activity shows

### Actual behavior
the app crashes.

### Stack Trace:
```
04-13 15:14:22.812 9076-9076/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 9076
    android.content.res.Resources$NotFoundException: File res/drawable/user_puck_icon_uncertain_location.xml from drawable resource ID #0x7f0800db. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
        at android.content.res.Resources.loadDrawable(Resources.java:2101)
        at android.content.res.Resources.getDrawable(Resources.java:700)
        at com.mapbox.mapboxsdk.utils.BitmapUtils.getDrawableFromRes(BitmapUtils.java:154)
        at com.mapbox.mapboxsdk.location.LayerBitmapProvider.generateBitmap(LayerBitmapProvider.java:24)
        at com.mapbox.mapboxsdk.location.LocationLayerController.styleForeground(LocationLayerController.java:341)
        at com.mapbox.mapboxsdk.location.LocationLayerController.applyStyle(LocationLayerController.java:125)
        at com.mapbox.mapboxsdk.location.LocationComponent.applyStyle(LocationComponent.java:713)
        at com.mapbox.navigation.ui.puck.NavigationPuckPresenter.updateCurrentLocationDrawable(NavigationPuckPresenter.kt:62)
        at com.mapbox.navigation.ui.puck.NavigationPuckPresenter.access$updateCurrentLocationDrawable(NavigationPuckPresenter.kt:13)
        at com.mapbox.navigation.ui.puck.NavigationPuckPresenter$routeProgressObserver$1.onRouteProgressChanged(NavigationPuckPresenter.kt:22)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:289)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:31)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$fireOffStatusPolling$1.invokeSuspend(MapboxTripSession.kt:267)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #1: invalid drawable tag vector
        at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:933)
        at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
        at android.content.res.Resources.loadDrawable(Resources.java:2097)
        at android.content.res.Resources.getDrawable(Resources.java:700) 
        at com.mapbox.mapboxsdk.utils.BitmapUtils.getDrawableFromRes(BitmapUtils.java:154) 
        at com.mapbox.mapboxsdk.location.LayerBitmapProvider.generateBitmap(LayerBitmapProvider.java:24) 
        at com.mapbox.mapboxsdk.location.LocationLayerController.styleForeground(LocationLayerController.java:341) 
        at com.mapbox.mapboxsdk.location.LocationLayerController.applyStyle(LocationLayerController.java:125) 
        at com.mapbox.mapboxsdk.location.LocationComponent.applyStyle(LocationComponent.java:713) 
        at com.mapbox.navigation.ui.puck.NavigationPuckPresenter.updateCurrentLocationDrawable(NavigationPuckPresenter.kt:62) 
        at com.mapbox.navigation.ui.puck.NavigationPuckPresenter.access$updateCurrentLocationDrawable(NavigationPuckPresenter.kt:13) 
        at com.mapbox.navigation.ui.puck.NavigationPuckPresenter$routeProgressObserver$1.onRouteProgressChanged(NavigationPuckPresenter.kt:22) 
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:289) 
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:31) 
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$fireOffStatusPolling$1.invokeSuspend(MapboxTripSession.kt:267) 
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56) 
        at android.os.Handler.handleCallback(Handler.java:733) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by JunDai** [comment]
it seems related to customize puck icon

**Comment by JunDai** [comment]
#2812 fixed this issue.
