### ISSUE TITLE
Exception when inflating InstructionView

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#2891]
When inflating the `InstructionView` inside a fragment, I run into:
```
Caused by: java.lang.IllegalStateException: this.resources.configuration.locales.get(0) must not be null
   at com.mapbox.navigation.base.internal.extensions.ContextEx.inferDeviceLocale(ContextEx.kt:23)
   at com.mapbox.navigation.ui.instruction.InstructionView.initialize(InstructionView.java:552)
   at com.mapbox.navigation.ui.instruction.InstructionView.<init>(InstructionView.java:150)
   at com.mapbox.navigation.ui.instruction.InstructionView.<init>(InstructionView.java:144)
   at java.lang.reflect.Constructor.newInstance0(Native Method) 
  at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
   at android.view.LayoutInflater.createView(LayoutInflater.java:854) 
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006) 
   at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
   at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123) 
   at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:682) 
   at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
```

This is reproducible on Pixel 2XL after a couple of tries when opening/closing the app.

**Comment by cafesilencio** [comment]
A fix was merged.
