### ISSUE TITLE
FeedbackButtonActivity example crash on replay engine

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3013]
```
Process: com.mapbox.navigation.examples, PID: 11177
java.lang.IllegalArgumentException: Non-empty location list required.
	at com.mapbox.navigation.core.replay.route.ReplayLocationDispatcher.checkValidInput(ReplayLocationDispatcher.kt:74)
	at com.mapbox.navigation.core.replay.route.ReplayLocationDispatcher.<init>(ReplayLocationDispatcher.kt:22)
	at com.mapbox.navigation.core.replay.route.ReplayRouteLocationEngine.obtainDispatcher(ReplayRouteLocationEngine.kt:208)
	at com.mapbox.navigation.core.replay.route.ReplayRouteLocationEngine.start(ReplayRouteLocationEngine.kt:197)
	at com.mapbox.navigation.core.replay.route.ReplayRouteLocationEngine.beginReplayWith(ReplayRouteLocationEngine.kt:261)
	at com.mapbox.navigation.core.replay.route.ReplayRouteLocationEngine.requestLocationUpdates(ReplayRouteLocationEngine.kt:138)
	at com.mapbox.navigation.core.internal.trip.session.MapboxTripSession.startLocationUpdates(MapboxTripSession.kt:155)
	at com.mapbox.navigation.core.internal.trip.session.MapboxTripSession.start(MapboxTripSession.kt:150)
	at com.mapbox.navigation.core.MapboxNavigation.startTripSession(MapboxNavigation.kt:229)
	at com.mapbox.navigation.examples.core.FeedbackButtonActivity$initListeners$1.onClick(FeedbackButtonActivity.kt:184)
	at android.view.View.performClick(View.java:6256)
	at android.view.View$PerformClick.run(View.java:24697)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Caught during a robo test run - https://console.firebase.google.com/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/7883211736378652655.

/cc @kmadsen

**Comment by Guardiola31337** [comment]
This also happens in other examples 👀 

```
java.lang.IllegalArgumentException: Non-empty location list required.
     FATAL EXCEPTION: main
Process: com.mapbox.navigation.examples, PID: 14400
java.lang.IllegalArgumentException: Non-empty location list required.
	at com.mapbox.navigation.core.replay.route.ReplayLocationDispatcher.checkValidInput(ReplayLocationDispatcher.kt:74)
	at com.mapbox.navigation.core.replay.route.ReplayLocationDispatcher.<init>(ReplayLocationDispatcher.kt:22)
	at com.mapbox.navigation.core.replay.route.ReplayRouteLocationEngine.obtainDispatcher(ReplayRouteLocationEngine.kt:208)
	at com.mapbox.navigation.core.replay.route.ReplayRouteLocationEngine.start(ReplayRouteLocationEngine.kt:197)
	at com.mapbox.navigation.core.replay.route.ReplayRouteLocationEngine.beginReplayWith(ReplayRouteLocationEngine.kt:261)
	at com.mapbox.navigation.core.replay.route.ReplayRouteLocationEngine.requestLocationUpdates(ReplayRouteLocationEngine.kt:138)
	at com.mapbox.navigation.core.internal.trip.session.MapboxTripSession.startLocationUpdates(MapboxTripSession.kt:155)
	at com.mapbox.navigation.core.internal.trip.session.MapboxTripSession.start(MapboxTripSession.kt:150)
	at com.mapbox.navigation.core.MapboxNavigation.startTripSession(MapboxNavigation.kt:229)
	at com.mapbox.navigation.examples.core.SummaryBottomSheetActivity$initListeners$1.onClick(SummaryBottomSheetActivity.kt:195)
	at android.view.View.performClick(View.java:6256)
	at android.view.View$PerformClick.run(View.java:24697)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/8602442196128900923/executions/bs.9d5dbea799e814e2/issues

We've seen this in the past (legacy) https://github.com/mapbox/mapbox-navigation-android/issues/2019 

In this particular case I believe it happens because the Robo test is pretty fast and does a double click in the same point i.e. same `origin` and `destination` means no locations generated which makes `checkValidInput` to fail.

We could add a check in the examples to prevent ☝️ from happening but `ReplayRouteLocationEngine` is going to be deprecated and replaced by `ReplayLocationEngine` 👀 https://github.com/mapbox/mapbox-navigation-android/pull/300 and these issues will go away.

**Comment by JunDai** [comment]
I have no access to the above firebase link. who should I talk to get it or it's limited to certain people only? @Guardiola31337 / @LukasPaczos ?

<img width="674" alt="Screen Shot 2020-05-21 at 08 20 37" src="https://user-images.githubusercontent.com/3918950/82574434-fbe9ca00-9b3b-11ea-9a27-b6d5fe05489c.png">

**Comment by LukasPaczos** [comment]
@JunDai you should have an invite in the inbox :)

**Comment by JunDai** [comment]
thanks @LukasPaczos
