### ISSUE TITLE
Examples MainActivity null pointer exception

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#3045]
**Android API:** tested on 0cd17b89896d196c2e65e036645a8d724e81089d

Noticed a crash while developing. Adding the stack trace here

### Steps to trigger behavior
Unknown
 
### Actual behavior
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 3740
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=0, data=null} to activity {com.mapbox.navigation.examples/com.mapbox.navigation.examples.MainActivity}: kotlin.KotlinNullPointerException
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: kotlin.KotlinNullPointerException
        at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl.toggleHistory(MapboxNativeNavigatorImpl.kt:274)
        at com.mapbox.navigation.examples.MainActivity.updateNavNativeHistoryCollection(MainActivity.kt:102)
        at com.mapbox.navigation.examples.MainActivity.onActivityResult(MainActivity.kt:51)
        at android.app.Activity.dispatchActivityResult(Activity.java:8135)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by kmadsen** [comment]
Did a little digging into this. The null pointer exception comes from MapboxNativeNavigatorImpl, and it is by design.

Callers need to first [create](https://github.com/mapbox/mapbox-navigation-android/blob/526b008dc204e7083d1d01aabcc73be055a85df6/libnavigation-core/src/main/java/com/mapbox/navigation/core/MapboxNavigation.kt#L153) an instance of MapboxNavigation before they can use MapboxNativeNavigatorImpl

This is not an issue with the core SDK, it's an issue with the examples.

Considering better error handling so this expected error, looks expected
