### ISSUE TITLE
TripSessionActivity (kotlin) example crash

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#3064]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1. Open the Examples app and select the TripSession Kotlin example
 2. Press 'Start' button

### Expected behavior
The navigation should start without a crash.

### Actual behavior
The activity crashes.

**Comment by Guardiola31337** [comment]
@cafesilencio could you share the stacktrace 🙏?

**Comment by cafesilencio** [comment]
E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-2
    Process: com.mapbox.navigation.examples, PID: 32302
    kotlin.KotlinNullPointerException
        at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl.updateLocation(MapboxNativeNavigatorImpl.kt:79)
        at com.mapbox.navigation.core.internal.trip.session.MapboxTripSession$updateRawLocation$2.invokeSuspend(MapboxTripSession.kt:414)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by cafesilencio** [comment]
@kmadsen Can you take a peek at this?

**Comment by kmadsen** [comment]
Which Activity crashes? Is it TripSessionActivity?

This crash will occur when MapboxNativeNavigatorImpl.updateLocation is called before MapboxNavigation(..) is constructed
