### ISSUE TITLE
Example crashes with NPE at MapboxNativeNavigatorImpl.kt

### ISSUE THREAD

**Issue by JunDai** [mapbox/mapbox-navigation-android#3068]
**Android API:**
**Mapbox Navigation SDK version:** UI SDK 1.0

### Steps to trigger behavior

 1. Launch `example` app
 2. Click the `setting` FAB at bottom-right corner
 3. Press `Back` key -- no matter you do change or do nothing

### Expected behavior
Goes back to `MainActivity` without problem

### Actual behavior
The `example` crashes.

**Comment by JunDai** [comment]
Stacktrace:
```
2020-05-29 16:15:19.501 14592-14592/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 14592
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1001, result=-1, data=Intent { (has extras) }} to activity {com.mapbox.navigation.examples/com.mapbox.navigation.examples.MainActivity}: kotlin.KotlinNullPointerException
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5097)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5138)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2147)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7811)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
     Caused by: kotlin.KotlinNullPointerException
        at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl.toggleHistory(MapboxNativeNavigatorImpl.kt:274)
        at com.mapbox.navigation.examples.MainActivity.updateNavNativeHistoryCollection(MainActivity.kt:102)
        at com.mapbox.navigation.examples.MainActivity.onActivityResult(MainActivity.kt:51)
        at android.app.Activity.dispatchActivityResult(Activity.java:8292)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5090)
```

**Comment by JunDai** [comment]
@kmadsen - would you mind to take a look? I think this one might be very similar to #3064 

I don't know if this NPE only happens in our `example` app. Maybe we are using it wrong with the wrong setup? But I think it would be great to revisit the PR #2974 so we don't have problem in the real use cases.

**Comment by kmadsen** [comment]
Nice, looks like you found reproducible steps for https://github.com/mapbox/mapbox-navigation-android/issues/3045
