### ISSUE TITLE
BaseRouterActivityJava SymbolManager.deleteAll() NPE

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3070]
Here's a crash caught by the Robo tests https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/7854849250007136398/executions/bs.30fa2c687c361f5e in https://github.com/mapbox/mapbox-navigation-android/pull/3036 https://circleci.com/gh/mapbox/mapbox-navigation-android/26667?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.deleteAll()' on a null object reference
     FATAL EXCEPTION: Thread-2
Process: com.mapbox.navigation.examples, PID: 12825
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.plugins.annotation.SymbolManager.deleteAll()' on a null object reference
	at com.mapbox.navigation.examples.core.BaseRouterActivityJava.clearMap(BaseRouterActivityJava.java:170)
	at com.mapbox.navigation.examples.core.BaseRouterActivityJava.newOrigin(BaseRouterActivityJava.java:145)
	at com.mapbox.navigation.examples.core.BaseRouterActivityJava.onNewLocationClick(BaseRouterActivityJava.java:140) 
	at com.mapbox.navigation.examples.core.BaseRouterActivityJava_ViewBinding$1.doClick(BaseRouterActivityJava_ViewBinding.java:36)
	at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:18)
	at android.view.View.performClick(View.java:6256)
	at android.view.View$PerformClick.run(View.java:24697)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:132)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:126)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:42)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:75)
	at androidx.test.espresso.action.Tap.b(Tap.java:16)
	at androidx.test.espresso.action.Tap$1.a(Tap.java:2)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:33)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

cc @cafesilencio

**Comment by Guardiola31337** [comment]
`BaseRouterActivityJava` was removed in https://github.com/mapbox/mapbox-navigation-android/pull/3209

Closing as not actionable.
