### ISSUE TITLE
NavigationMapRouteActivity#handleClicked NPE

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3108]
Here's a crash caught by the Robo tests https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/8003412440672095464/executions/bs.7cc24e7011db8da2 in https://github.com/mapbox/mapbox-navigation-android/pull/3098 https://circleci.com/gh/mapbox/mapbox-navigation-android/27007?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLongitude()' on a null object reference
     FATAL EXCEPTION: Thread-2
Process: com.mapbox.navigation.examples, PID: 15419
java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLongitude()' on a null object reference
	at com.mapbox.navigation.examples.core.NavigationMapRouteActivity.handleClicked(NavigationMapRouteActivity.java:210)
	at com.mapbox.navigation.examples.core.NavigationMapRouteActivity.onMapLongClick(NavigationMapRouteActivity.java:136)
	at com.mapbox.mapboxsdk.maps.MapGestureDetector.notifyOnMapLongClickListeners(MapGestureDetector.java:1005)
	at com.mapbox.mapboxsdk.maps.MapGestureDetector$StandardGestureListener.onLongPress(MapGestureDetector.java:403)
	at com.mapbox.android.gestures.StandardGestureDetector$1.onLongPress(StandardGestureDetector.java:45)
	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:778)
	at android.view.GestureDetector.-wrap0(Unknown Source:0)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:132)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:126)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:102)
	at androidx.test.espresso.action.Tap$2.a(Tap.java:7)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:33)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

cc @JunDai @abhishek1508 @cafesilencio

**Comment by cafesilencio** [comment]
This should have been fixed in PR: https://github.com/mapbox/mapbox-navigation-android/pull/3153
