### ISSUE TITLE
NavigationCamera.showRouteOverview NPE

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3123]
When testing `master` `CustomUIComponentStyleActivity` `examples` test app run into the following crash 👀 

```
06-05 13:48:55.703 24128-24128/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 24128
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.api.directions.v5.models.DirectionsRoute com.mapbox.navigation.base.trip.model.RouteProgress.getRoute()' on a null object reference
        at com.mapbox.navigation.ui.camera.NavigationCamera.showRouteOverview(NavigationCamera.java:244)
        at com.mapbox.navigation.ui.map.NavigationMapboxMap.showRouteOverview(NavigationMapboxMap.java:590)
        at com.mapbox.navigation.examples.ui.CustomUIComponentStyleActivity$initViews$3.onClick(CustomUIComponentStyleActivity.kt:263)
        at android.view.View.performClick(View.java:5204)
        at android.view.View$PerformClick.run(View.java:21153)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

Interestingly there was no data populated to banner, summary bottom sheet and the notification 👀 

![CustomUIComponentStyleActivity_no_data](https://user-images.githubusercontent.com/1668582/83908397-0fe51c80-a735-11ea-896c-83b9684d1feb.png)

![CustomUIComponentStyleActivity_no_data_notification](https://user-images.githubusercontent.com/1668582/83908403-1378a380-a735-11ea-9d8d-7fd50598cefc.png)

## Steps to reproduce

1. Open `CustomUIComponentStyleActivity` examples from `Navigation UI SDK` tab
2. Long press on the map to place a waypoint
3. Click on `START NAVIGATION`
4. Data is not populated as above-mentioned
5. Click on the overview button in the `SummaryBottomSheet`
6. 💥 

cc @JunDai

**Comment by Guardiola31337** [comment]
Noting that I was able to reproduce with and without any location updates. When having location updates enabled (from using a mock location app) puck didn't move / got updated either.

**Comment by JunDai** [comment]
which device are you using? Is it a Pixel 2XL emulator or?

**Comment by Guardiola31337** [comment]
@JunDai 
> which device are you using?

Nexus 5 Android version `6.0.1`
