### ISSUE TITLE
NavigationViewFragment onCancelNavigation NPE

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3149]
When testing `NavigationViewFragment` run into the following crash 💥 

```
06-10 09:37:26.132 6307-6307/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 6307
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.navigation.ui.NavigationView.stopNavigation()' on a null object reference
        at com.mapbox.navigation.examples.ui.NavigationViewFragment.onCancelNavigation(NavigationViewFragment.kt:120)
        at com.mapbox.navigation.ui.NavigationViewEventDispatcher.onCancelNavigation(NavigationViewEventDispatcher.java:118)
        at com.mapbox.navigation.ui.CancelBtnClickListener.onClick(CancelBtnClickListener.java:15)
        at android.view.View.performClick(View.java:5204)
        at android.view.View$PerformClick.run(View.java:21153)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

#### Steps to reproduce

1. Run `examples` test app
2. Launch `NavigationViewFragment` example
3. Rotate the screen
4. Click on `X` from `SummaryBottomSheet`
5. 💥 

cc @abhishek1508 @JunDai @cafesilencio

**Comment by JunDai** [comment]
refresh this ticket. I am going to take a look at it today.

**Comment by JunDai** [comment]
took a quick look at it, the NavigationViewModel held the listener instance prior to the rotation and that NavigationView has been destroyed. We should update the callback in rotation case. Will put a fix of it later.
