### ISSUE TITLE
DownloadTask.saveAsFile RuntimeException when running out of space

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3168]
Testing https://github.com/mapbox/mapbox-navigation-android/pull/3166 run into an interesting crash we're not covering 👀 

```
06-12 15:44:32.604 15498-16136/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
    Process: com.mapbox.navigation.examples, PID: 15498
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.FileNotFoundException: /data/user/0/com.mapbox.navigation.examples/cache/mapbox_instruction_cache/9.mp3: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:452)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
        at com.mapbox.navigation.ui.DownloadTask.saveAsFile(DownloadTask.kt:64)
        at com.mapbox.navigation.ui.DownloadTask.doInBackground(DownloadTask.kt:42)
        at com.mapbox.navigation.ui.DownloadTask.doInBackground(DownloadTask.kt:20)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at libcore.io.IoBridge.open(IoBridge.java:438)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
        at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
        at com.mapbox.navigation.ui.DownloadTask.saveAsFile(DownloadTask.kt:64) 
        at com.mapbox.navigation.ui.DownloadTask.doInBackground(DownloadTask.kt:42) 
        at com.mapbox.navigation.ui.DownloadTask.doInBackground(DownloadTask.kt:20) 
        at android.os.AsyncTask$2.call(AsyncTask.java:295) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

Was running out of space in my device 😬 

cc @JunDai

**Comment by Guardiola31337** [comment]
Wondering what would happen when trying to download routing tiles in the same situation 🤔 cc @mskurydin @LukasPaczos

**Comment by JunDai** [comment]
> Was running out of space in my device 😬

@Guardiola31337 - are you able to reproduce it on your **OUT OF SPACE** device?

**Comment by JunDai** [comment]
https://github.com/mapbox/mapbox-navigation-android/issues/2837 might be the same reason? 🤔

**Comment by Guardiola31337** [comment]
@Guardiola31337 
> are you able to reproduce it on your **OUT OF SPACE** device?

It seems that's the root cause. Run into 👇 

```
06-16 19:50:39.413 7420-7494/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.mapbox.navigation.examples, PID: 7420
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:309)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.io.FileNotFoundException: /data/user/0/com.mapbox.navigation.examples/cache/mapbox_instruction_cache/6.mp3: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:452)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
        at com.mapbox.navigation.ui.DownloadTask.saveAsFile(DownloadTask.kt:64)
        at com.mapbox.navigation.ui.DownloadTask.doInBackground(DownloadTask.kt:42)
        at com.mapbox.navigation.ui.DownloadTask.doInBackground(DownloadTask.kt:20)
        at android.os.AsyncTask$2.call(AsyncTask.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Posix.open(Native Method)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
        at libcore.io.IoBridge.open(IoBridge.java:438)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
        at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
        at com.mapbox.navigation.ui.DownloadTask.saveAsFile(DownloadTask.kt:64) 
        at com.mapbox.navigation.ui.DownloadTask.doInBackground(DownloadTask.kt:42) 
        at com.mapbox.navigation.ui.DownloadTask.doInBackground(DownloadTask.kt:20) 
        at android.os.AsyncTask$2.call(AsyncTask.java:295) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at java.lang.Thread.run(Thread.java:818) 
```

and 👀 

![storage_space_running_out](https://user-images.githubusercontent.com/1668582/84912406-69c7d980-b087-11ea-8f30-d70fd518ccbb.png)

😬 

Let me know if you work on any potential fix and I can try to test / repro on my side - I know testing running out of space scenarios may be difficult / challenging 😅

**Comment by JunDai** [comment]
@Guardiola31337 - thanks for confirming it's reproducible in that case.
I filled up my android device this morning and I could reproduce it too. which took me about 10 minutes to copy videos :)

I feel we may only be able to catch the exception and let the speech play fallback to use TTS. wdyt?

**Comment by Guardiola31337** [comment]
@JunDai 
> I feel we may only be able to catch the exception and let the speech play fallback to use TTS. wdyt?

And log an error message 🤔?

**Comment by JunDai** [comment]
> @JunDai
> 
> > I feel we may only be able to catch the exception and let the speech play fallback to use TTS. wdyt?
> 
> And log an error message 🤔?

yeah, here is the PR. https://github.com/mapbox/mapbox-navigation-android/pull/3190
