### ISSUE TITLE
java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by samvgorode** [mapbox/mapbox-navigation-android#327]
`com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT`
it started today morning
```
E/UncaughtException: java.lang.NoSuchMethodError: No direct method <init>(Landroid/content/Context;Ljava/lang/String;)V in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/no.sammevei.app-2/base.apk:classes2.dex)
                                                                      at com.mapbox.services.android.navigation.v5.navigation.NavigationNotification.buildPersistentNotification(NavigationNotification.java:66)
                                                                      at com.mapbox.services.android.navigation.v5.navigation.NavigationService.initializeNotification(NavigationService.java:130)
                                                                      at com.mapbox.services.android.navigation.v5.navigation.NavigationService.startNavigation(NavigationService.java:118)
                                                                      at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.onServiceConnected(MapboxNavigation.java:675)
                                                                      at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java)
                                                                      at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java)
                                                                      at android.os.Handler.handleCallback(Handler.java)
                                                                      at android.os.Handler.dispatchMessage(Handler.java)
                                                                      at android.os.Looper.loop(Looper.java)
                                                                      at android.app.ActivityThread.main(ActivityThread.java)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
```

**Comment by samvgorode** [comment]
it happens only with `0.7.0-SNAPSHOT` , but with `0.6.1` its okay

**Comment by danesfeder** [comment]
@samvgorode We recently upgraded our notification to work with Android O's new notification channels https://github.com/mapbox/mapbox-navigation-android/pull/298.  If you do not have `transitive = true` when compiling our dependency, you will need to compile support library `26.1.0`

**Comment by danesfeder** [comment]
@samvgorode please let us know if you run into this, but this should be updated in our latest code without conflict.  Thanks!
