### ISSUE TITLE
Android: Error when starting navigation in landscape

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#331]
I have my orientation for my MapView Activity set to `Forced Portrait`, when i turn the device into `Landscape` (_my activity is still in potrait - this is what i expect_).

When I start the NavigationUI in this way I get the below error:

**Android Version:** 4.1.2
**Device:*** Motorola TC55 

```
10-09 14:06:58.334 15284-15284/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           java.lang.RuntimeException: Unable to start activity ComponentInfo{uk.co.ainscough.routeinfo/com.mapbox.services.android.navigation.ui.v5.NavigationView}: java.lang.NullPointerException
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2108)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2133)
                                                                               at android.app.ActivityThread.access$600(ActivityThread.java:142)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                               at android.os.Looper.loop(Looper.java:137)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4895)
                                                                               at java.lang.reflect.Method.invokeNative(Native Method)
                                                                               at java.lang.reflect.Method.invoke(Method.java:511)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                               at dalvik.system.NativeStart.main(Native Method)
                                                                            Caused by: java.lang.NullPointerException
                                                                               at android.support.v4.graphics.drawable.DrawableWrapperApi14.getState(DrawableWrapperApi14.java:155)
                                                                               at android.support.v4.graphics.drawable.DrawableWrapperApi14.setTintList(DrawableWrapperApi14.java:278)
                                                                               at android.support.v4.graphics.drawable.DrawableWrapperApi14.setTint(DrawableWrapperApi14.java:272)
                                                                               at android.support.v4.graphics.drawable.DrawableCompat$DrawableCompatBaseImpl.setTint(DrawableCompat.java:68)
                                                                               at android.support.v4.graphics.drawable.DrawableCompat.setTint(DrawableCompat.java:421)
                                                                               at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.initBackground(InstructionView.java:249)
                                                                               at com.mapbox.services.android.navigation.ui.v5.instruction.InstructionView.onFinishInflate(InstructionView.java:106)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:754)
                                                                               at android.view.LayoutInflater.rInflate(LayoutInflater.java:749)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
                                                                               at android.view.LayoutInflater.inflate(LayoutInflater.java:352)
                                                                               at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                               at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
                                                                               at com.mapbox.services.android.navigation.ui.v5.NavigationView.onCreate(NavigationView.java:87)
                                                                               at android.app.Activity.performCreate(Activity.java:5042)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2072)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2133) 
                                                                               at android.app.ActivityThread.access$600(ActivityThread.java:142) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                               at android.os.Looper.loop(Looper.java:137) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:4895) 
                                                                               at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                               at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556) 
                                                                               at dalvik.system.NativeStart.main(Native Method) 
10-09 14:06:58.344 631-631/? W/ActivityManager:   Force finishing activity uk.co.ainscough.routeinfo/com.mapbox.services.android.navigation.ui.v5.NavigationView
```

**Comment by danesfeder** [comment]
@Danny-James this looks related to the drawable work I did to get theming setup for API 19.  I'll look into it

**Comment by danesfeder** [comment]
Nice catch @Danny-James https://github.com/mapbox/mapbox-navigation-android/pull/343
