### ISSUE TITLE
SimpleMapboxNavigationKt - lateinit property navigationMapboxMap has not been initialized

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3368]
An issue caught by a robo test:
```
     FATAL EXCEPTION: main
Process: com.mapbox.navigation.examples, PID: 25814
f.r: lateinit property navigationMapboxMap has not been initialized
	at com.mapbox.navigation.examples.core.SimpleMapboxNavigationKt.i()
	at com.mapbox.navigation.examples.core.SimpleMapboxNavigationKt$e.onClick()
	at android.view.View.performClick(View.java:5207)
	at android.view.View$PerformClick.run(View.java:21168)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by LukasPaczos** [comment]
Still happens regardless of the temp fix.
