### ISSUE TITLE
ReRouteActivity LocationComponent has to be activated Robo test crash

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3404]
An issue caught by a Robo test https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/8121/workflows/ca4d7057-f723-42c1-80f3-a0fa5c6a5132/jobs/30545 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/7230244338293187876/executions/bs.ac9992e5d9a2159d/issues

```
Fatal exception
	at d.b.a.b.o$a.onLongPress()
     FATAL EXCEPTION: Thread-828
Process: com.mapbox.navigation.examples, PID: 16564
com.mapbox.mapboxsdk.location.n: The LocationComponent has to be activated with one of the LocationComponent#activateLocationComponent overloads before any other methods are invoked.
	at com.mapbox.mapboxsdk.location.k.j()
	at com.mapbox.mapboxsdk.location.k.b()
	at com.mapbox.navigation.examples.core.ReRouteActivity$h.b()
	at com.mapbox.mapboxsdk.maps.l.b()
	at com.mapbox.mapboxsdk.maps.l$h.onLongPress()
	at d.b.a.b.o$a.onLongPress()
	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:690)
	at android.view.GestureDetector.access$200(GestureDetector.java:37)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:266)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:130)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:124)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:100)
	at androidx.test.espresso.action.Tap$2.a(Tap.java:6)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:9)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by Guardiola31337** [comment]
Noting that https://github.com/mapbox/mapbox-navigation-android/pull/3407 reproduced the same issue 👀 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/6414974696113934416/executions/bs.60faf2bb4ac66cee 

cc @abhishek1508

**Comment by Guardiola31337** [comment]
Same issue caught again by Robo test from `BasicNavigationActivity` this time

An issue caught by a Robo test https://github.com/mapbox/mapbox-navigation-android/pull/3540 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/9179/workflows/520aee36-ffad-4a9e-8d02-40860f6eb1d1/jobs/34264 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/6313297879129535402/executions/bs.8ad60368c7f55a98

```
	at d.b.a.b.o$a.onLongPress(Unknown Source:15)
     FATAL EXCEPTION: Thread-2
Process: com.mapbox.navigation.examples, PID: 14693
com.mapbox.mapboxsdk.location.n: The LocationComponent has to be activated with one of the LocationComponent#activateLocationComponent overloads before any other methods are invoked.
	at com.mapbox.mapboxsdk.location.k.u(Unknown Source:7)
	at com.mapbox.mapboxsdk.location.k.A(Unknown Source:0)
	at com.mapbox.navigation.examples.core.BasicNavigationActivity$e.D(Unknown Source:16)
	at com.mapbox.mapboxsdk.maps.l.J(Unknown Source:24)
	at com.mapbox.mapboxsdk.maps.l$h.onLongPress(Unknown Source:15)
	at d.b.a.b.o$a.onLongPress(Unknown Source:15)
	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:779)
	at android.view.GestureDetector.access$200(GestureDetector.java:40)
	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:293)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:11)
	at androidx.test.espresso.base.UiControllerImpl.n(UiControllerImpl.java:6)
	at androidx.test.espresso.base.UiControllerImpl.m(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.e(UiControllerImpl.java:8)
	at androidx.test.espresso.action.Tap$2.sendTap(Tap.java:5)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
	at androidx.test.espresso.ViewInteraction.a(Unknown Source:140)
	at androidx.test.espresso.ViewInteraction$1.call(Unknown Source:4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Interesting that Firebase started reporting 👇 

>  Non-SDK API Usage Violation Learn more
Your app uses 20 non-SDK interfaces, which are incompatible with Android P+.

cc @mapbox/android

**Comment by tobrun** [comment]
> Non-SDK API Usage Violation Learn more
Your app uses 20 non-SDK interfaces, which are incompatible with Android P+.

Can you please add which?

**Comment by Guardiola31337** [comment]
Following you can find what it's reported https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/6313297879129535402/executions/bs.8ad60368c7f55a98 There's also a link to https://developer.android.com/distribute/best-practices/develop/restrictions-non-sdk-interfaces

```
Landroid/view/View;->mViewFlags:I
Landroid/os/Trace;->isTagEnabled(J)Z
Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z
One possible root cause for this warning is Google-owned library AndroidX. No action need be taken at this time.
Landroid/graphics/Typeface;->sSystemFontMap:Ljava/util/Map;
Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B
Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V
Landroid/graphics/Typeface;->createFromFamiliesWithDefault([Landroid/graphics/FontFamily;Ljava/lang/String;II)Landroid/graphics/Typeface;
Landroid/graphics/FontFamily;->addFontFromBuffer(Ljava/nio/ByteBuffer;I[Landroid/graphics/fonts/FontVariationAxis;II)Z
Landroid/os/Trace;->TRACE_TAG_APP:J
Landroid/graphics/FontFamily;->addFontFromAssetManager(Landroid/content/res/AssetManager;Ljava/lang/String;IZIII[Landroid/graphics/fonts/FontVariationAxis;)Z
Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V
Landroid/graphics/FontFamily;-><init>()V
Landroid/os/Trace;->traceCounter(JLjava/lang/String;I)V
Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V
Landroid/graphics/FontFamily;->freeze()Z
Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V
One possible root cause for this warning is Google-owned library AndroidX. No action need be taken at this time.
Landroid/graphics/FontFamily;->abortCreation()V
Landroid/widget/PopupWindow;->setClipToScreenEnabled(Z)V
Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate;
One possible root cause for this warning is Google-owned library AndroidX. No action need be taken at this time.
Landroid/widget/PopupWindow;->setEpicenterBounds(Landroid/graphics/Rect;)V
```
