### ISSUE TITLE
IndexOutOfBoundsException during navigation

### ISSUE THREAD

**Issue by songyanho** [mapbox/mapbox-navigation-android#3419]
**Android API: SDK 29**
**Mapbox Navigation SDK version: **
```
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.2.0'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-core:2.0.1'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6')
```

### Steps to trigger behavior

 1. start navigation
 2. use emulator to simulate driving

### Actual behavior

App crashed with error

```
E/AndroidRuntime: FATAL EXCEPTION: mapbox_navigation_thread
    Process: sg.rushowl.driver.internal.debug, PID: 2788
    java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.decodeStepPoints(NavigationHelper.java:84)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.updateStepPoints(NavigationRouteProcessor.java:117)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.buildRouteProgressFrom(NavigationRouteProcessor.java:73)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteProcessor.buildNewRouteProgress(NavigationRouteProcessor.java:44)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable.process(RouteProcessorRunnable.java:63)
        at com.mapbox.services.android.navigation.v5.navigation.RouteProcessorRunnable.run(RouteProcessorRunnable.java:46)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by Guardiola31337** [comment]
Hey @songyanho thanks for reaching out and report your issue.

Would you mind re-testing / confirming if OP is still an issue in `1.0.0`? You can review the developer [documentation](https://docs.mapbox.com/android/beta/navigation/overview/) to start building with the Mapbox Navigation SDK v1.0 for Android and check out the [migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide) to transition your project from the "legacy" Navigation SDK to the 1.0 version and let us know if you have any questions or run into issues. We would love your feedback.
