### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String com.mapbox.navigator.VoiceInstruction.getSsmlAnnouncement()' on a null object reference

### ISSUE THREAD

**Issue by benorgan** [mapbox/mapbox-navigation-android#3488]
**Android API: 29**
**Mapbox Navigation SDK version: 0.42.0**

### Steps to trigger behavior

Since this afternoon we are seeing this error on Android after starting navigation:

```java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.mapbox.navigator.VoiceInstruction.getSsmlAnnouncement()' on a null object reference
        at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.retrieveSsmlAnnouncementInstruction(MapboxNavigation.java:802)
        at com.mapbox.services.android.navigation.ui.v5.VoiceInstructionCache.preCache(VoiceInstructionCache.java:50)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.startNavigation(NavigationViewModel.java:459)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.updateRoute(NavigationViewModel.java:262)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewRouteEngineListener.onRouteUpdate(NavigationViewRouteEngineListener.java:17)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewRouter.updateCurrentRoute(NavigationViewRouter.java:96)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewRouter.extractRouteFrom(NavigationViewRouter.java:121)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewRouter.extractRouteOptions(NavigationViewRouter.java:72)```

It looks like the Directions API is returning the correct response but for some reason the SDK can no longer parse it and this results in a null pointer exception. 

### Expected behavior

The navigation loads with voice instructions.

### Actual behavior

The app crashes.

**Comment by songyanho** [comment]
I also encounter this issue early today. It crash the entire app though

**Comment by benorgan** [comment]
> Android API: 28
> Mapbox Navigation UI SDK version: 0.42.6
> 
> I also encounter this issue early today. It crash the entire app though.

Yep, it's crashing the entire app for us too. You can catch the error using try / catch around `startNavigation`

**Comment by songyanho** [comment]
I am trying to debug but class com.mapbox.navigator.Navigator is compiled.

**Comment by songyanho** [comment]
@joshuagoing +1

**Comment by benorgan** [comment]
> I am trying to debug but class com.mapbox.navigator.Navigator is compiled.

Yep, that's where I got stuck too!

**Comment by benorgan** [comment]
Mapbox have just rolled back some changes on the Directions API and this fixed our issue. Hopefully your issue is resolved too @songyanho? We also found that we had to not send the bearing in order to get a route back, whereas before we were sending a bearing and getting results. 

```
MapboxDirections client = MapboxDirections.builder()
 [...]
.addBearing(new Double(Float.toString(bearing)), new Double(90)) // We removed this
[...]
.build();
```

**Comment by songyanho** [comment]
@benorgan May I know how you use MapboxDirections here? My app is using the following implementation

```
val builder: NavigationRoute.Builder = NavigationRoute.builder(this.applicationContext)
                    .accessToken(mapboxToken)
                    .origin(origin)
                    .destination(destination)
.build()
                    .getRoute(object : Callback<DirectionsResponse?> {
                        override fun onResponse(call: Call<DirectionsResponse?>?, response: Response<DirectionsResponse?>) {
                            val directionsRoute = response.body()!!.routes()[0]
                            startNavigation(directionsRoute!!)
```

**Comment by aindeev** [comment]
@songyanho I work with @benorgan 

This is our full routing call implementation (now works once mapbox rolled back their changes)

```
MapboxDirections client = MapboxDirections.builder()
                .origin(origin)
                .destination(destination)
                .addBearing(new Double(Float.toString(bearing)), new Double(90))
                .addBearing(new Double(Float.toString(bearing)), new Double(90))
                .accessToken(reactContext.getString(R.string.MAPBOX_ACCESS_TOKEN))
                .overview(DirectionsCriteria.OVERVIEW_FULL)
                .profile(DirectionsCriteria.PROFILE_DRIVING)
                .steps(true)
                .voiceInstructions(true)
                .bannerInstructions(true)
                .build();
```
