### ISSUE TITLE
IndexOutOfBoundsException MapMatchingActivity Robo test crash

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3543]
An issue caught by a Robo test https://github.com/mapbox/mapbox-navigation-android/pull/3542 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/8650/workflows/b8f7787e-4e41-4b47-a5fa-e488d009d61f/jobs/31813 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/6224214162069429918/executions/bs.5a0d623ec5801783

```
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
     FATAL EXCEPTION: main
Process: com.mapbox.navigation.examples, PID: 21281
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at com.mapbox.navigation.examples.core.MapMatchingActivity$c.a()
	at d.b.c.d.a.c$a.a()
	at h.i$b$a.d()
	at h.a.run(lambda)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by Guardiola31337** [comment]
Noting that this was reproduced again in https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/8734/workflows/460b3e97-ce3c-40e7-be0a-e6b791beaf04/jobs/32189 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/6448705649202468225/executions/bs.b87851fc0fccf555
