### ISSUE TITLE
AttributionDialogManager RuntimeException: Could not read input channel file descriptors from parcel

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3549]
An issue caught by a Robo test https://github.com/mapbox/mapbox-navigation-android/pull/3542 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/8682/workflows/7f2e9ba6-03b6-450f-8674-57a71e8c4e0e/jobs/31962 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/5664291627463855315/executions/bs.5a4a06c10f50da57

```
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
     FATAL EXCEPTION: Thread-861
Process: com.mapbox.navigation.examples, PID: 14792
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
	at android.view.InputChannel.nativeReadFromParcel(Native Method)
	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:759)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:543)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.app.Dialog.show(Dialog.java:319)
	at android.app.AlertDialog$Builder.show(AlertDialog.java:1112)
	at com.mapbox.mapboxsdk.maps.d.i()
	at com.mapbox.mapboxsdk.maps.d.onClick()
	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1108)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3073)
	at android.widget.AbsListView$3.run(AbsListView.java:3910)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:130)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:124)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:100)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:5)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:9)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

cc @tobrun @mapbox/maps-android

**Comment by Guardiola31337** [comment]
Going to transfer this into https://github.com/mapbox/mapbox-gl-native-android
