### ISSUE TITLE
Crash while updating navigation notification: android.os.TransactionTooLargeException

### ISSUE THREAD

**Issue by Kahtaf** [mapbox/mapbox-navigation-android#355]
While testing 0.6.1 this morning, I received the following crash during the course of the navigation (was about half way through the route when it happened). I was not using the navigation UI, and my app wasn't showing any notifications.

```
FATAL EXCEPTION: main
Process: com.bitspice.automate, PID: 31082
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 609192 bytes
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:320)
	at android.app.NotificationManager.notify(NotificationManager.java:289)
	at android.app.NotificationManager.notify(NotificationManager.java:273)
	at com.mapbox.services.android.navigation.v5.navigation.NavigationNotification.updateDefaultNotification(NavigationNotification.java:118)
	at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:202)
	at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:82)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: android.os.TransactionTooLargeException: data parcel size 609192 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:748)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:1247)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:317)
	... 12 more

java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 609192 bytes
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:320)
	at android.app.NotificationManager.notify(NotificationManager.java:289)
	at android.app.NotificationManager.notify(NotificationManager.java:273)
	at com.mapbox.services.android.navigation.v5.navigation.NavigationNotification.updateDefaultNotification(NavigationNotification.java:118)
	at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:202)
	at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:82)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: android.os.TransactionTooLargeException: data parcel size 609192 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:748)
	at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:1247)
	at android.app.NotificationManager.notifyAsUser(NotificationManager.java:317)
	... 12 more
```

**Comment by cammace** [comment]
Can you try updating to 0.6.2, we made a few changes that address a few issues in the notification. Also, which Android version are you running?

**Comment by Kahtaf** [comment]
It was a Nexus 6P running Oreo. I upgraded to 0.6.2 and drove the same route today, but didn't see that issue. It may be fixed in this version. 

However, I started seeing the blue notification that I wasn't seeing in 0.6.1. How do I turn off the notification?

**Comment by danesfeder** [comment]
@Kahtaf We recently reworked the notification to get it working smoothly with Android O in https://github.com/mapbox/mapbox-navigation-android/pull/298.  We were using a builder that was deprecated (we now need to provide a notification channel ID).  Please keep an eye out for this crash regardless, as we haven't been able to reproduce it.

You can enable / disable the notification with `MapboxNavigationOptions` https://www.mapbox.com/android-docs/api/navigation-sdk/navigation/0.6.2/index.html

**Comment by Kahtaf** [comment]
Thanks! I'll report back if this issue happens again.

**Comment by danesfeder** [comment]
This was re-worked again in #564 @Kahtaf please let us know if you see it again.
