### ISSUE TITLE
ReplayHistoryActivity NullPointerException

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3562]
An issue caught by a Robo test https://github.com/mapbox/mapbox-navigation-android/pull/3560 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/8743/workflows/41b0eda6-aba4-4de4-89ab-1a665f40e875/jobs/32228 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/9017603961185076236/executions/bs.b931d6abe839017a/issues

```
FATAL EXCEPTION: main
Process: com.mapbox.navigation.examples, PID: 16700
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String d.b.f.b.o.c.d.f()' on a null object reference
	at d.b.f.b.o.b.g()
	at d.b.f.b.o.b.e()
	at d.b.f.b.o.a.g()
	at com.mapbox.navigation.examples.core.ReplayHistoryActivity.l0()
	at com.mapbox.navigation.examples.core.ReplayHistoryActivity.b0()
	at com.mapbox.navigation.examples.core.ReplayHistoryActivity$g.a()
	at com.mapbox.navigation.examples.core.ReplayHistoryActivity$g.m()
	at com.mapbox.navigation.examples.core.ReplayHistoryActivity$b.g()
	at e.v.k.a.a.i()
	at kotlinx.coroutines.b1.run()
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:130)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:124)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:100)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:6)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

cc @kmadsen

**Comment by kmadsen** [comment]
It's unclear where this stack trace is

should we use a debug.apk? 

```
#!/bin/bash -eo pipefail
gcloud firebase test android run --type robo \
  --app examples/build/outputs/apk/release/examples-release.apk \
  --device model=hammerhead,version=21,locale=en,orientation=portrait  \
  --device model=athene,version=23,locale=fr,orientation=landscape \
  --device model=sailfish,version=26,locale=es,orientation=portrait \
  --device model=walleye,version=28,locale=de,orientation=landscape \
  --timeout 5m
```

**Comment by Guardiola31337** [comment]
> should we use a debug.apk?

Yeah, let's change it. It was `release` to detect any Proguard regressions.

**Comment by kmadsen** [comment]
Considering this issue blocked by https://github.com/mapbox/navigation-sdks/issues/582

**Comment by Guardiola31337** [comment]
OP crash was reproduced again in https://github.com/mapbox/mapbox-navigation-android/pull/3582 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/8837/workflows/7db4b80f-0688-4b67-bb08-c867d98e8bf4/jobs/32634 https://console.firebase.google.com/u/1/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/6136398722165371885/executions/bs.5eba3f3d8a191ccf

**Comment by langsmith** [comment]
This crash has come up a couple of times during the stable `1.1.0` release I've been rolling with today.

**Comment by langsmith** [comment]
https://console.firebase.google.com/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/5950329547653739324/executions/bs.112e36bd134db8cc

<img width="1026" alt="Screen Shot 2020-10-07 at 5 05 33 PM" src="https://user-images.githubusercontent.com/4394910/95400465-864e8280-08bf-11eb-920c-9933210884b8.png">

**Comment by kmadsen** [comment]
Firebase requires us to register the examples app in order to upload the mapping, and register to a google-services.json. There are complications when doing that. So whatever, I'll spend a little time figuring out how deobfuscation mappings work.

1. cd mapbox-navigation-android
1. checkout [636b80996fda864bffc60645a4ef0becb5dedb72](https://github.com/mapbox/mapbox-navigation-android/commit/636b80996fda864bffc60645a4ef0becb5dedb72)
1. ./gradlew examples:assembleRelease (don't worry about the "storePassword")
1. ls examples/build/outputs/mapping/release/
[mapping.txt](https://github.com/mapbox/mapbox-navigation-android/files/5366670/mapping.txt) seeds.txt   usage.txt

Figuring out the mapping, it looks like this is the mapping. I'm not really sure how to figure out line numbers

```
at d.b.f.b.o.b.g() <- com.mapbox.navigation.core.replay.ReplayLocationEngine.replayLocation
at d.b.f.b.o.b.e() <- com.mapbox.navigation.core.replay.ReplayLocationEngine.replayEvents
at d.b.f.b.o.a.g() <- com.mapbox.navigation.core.replay.ReplayLocationEngine.playFirstLocation
at com.mapbox.navigation.examples.core.ReplayHistoryActivity.l0() => onNavigationReady
at com.mapbox.navigation.examples.core.ReplayHistoryActivity.b0() => getNavigationAsync
at com.mapbox.navigation.examples.core.ReplayHistoryActivity$g.a() => onCreate invoke
at com.mapbox.navigation.examples.core.ReplayHistoryActivity$g.m() => onCreate
```
