### ISSUE TITLE
Crash when route contains less than two coordinates.

### ISSUE THREAD

**Issue by cafesilencio** [mapbox/mapbox-navigation-android#3584]
A customer reported a crash that appears to be caused by a route containing less than two coordinates.  When the vanishing route line update is done there is a Turf measurement done. The Turf call requires a collection of at least two coordinates. This is where the crash is occurring based on the stack trace.

The stack trace provided:

1328 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: Process: com.group.idnext.navigation, PID: 4927
1329 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: com.mapbox.turf.TurfException: Turf nearestPointOnLine requires a List of Points made up of at least 2 coordinates.
1330 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at com.mapbox.turf.TurfMisc.nearestPointOnLine(TurfMisc.java:242)
1331 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at com.mapbox.navigation.ui.route.MapRouteLine.updateTraveledRouteLine(MapRouteLine.kt:921)
1332 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at com.mapbox.navigation.ui.route.NavigationMapRoute.lambda$new$0$NavigationMapRoute(NavigationMapRoute.java:329)
1333 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at com.mapbox.navigation.ui.route.-$$Lambda$NavigationMapRoute$pxgGPAwZhxz8YVKAhhU7HaqoqZM.onIndicatorPositionChanged(Unknown Source:2)
1334 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at com.mapbox.mapboxsdk.location.LocationComponent$10.onIndicatorPositionChanged(LocationComponent.java:1805)
1335 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at com.mapbox.mapboxsdk.location.LocationLayerController$1.onNewAnimationValue(LocationLayerController.java:269)
1336 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at com.mapbox.mapboxsdk.location.LocationLayerController$1.onNewAnimationValue(LocationLayerController.java:265)
1337 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at com.mapbox.mapboxsdk.location.MapboxAnimator.postUpdates(MapboxAnimator.java:106)
1338 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at com.mapbox.mapboxsdk.location.MapboxAnimator.onAnimationUpdate(MapboxAnimator.java:93)
1339 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1547)
1340 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:674)
1341 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.animation.ValueAnimator.start(ValueAnimator.java:1071)
1342 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.animation.ValueAnimator.start(ValueAnimator.java:1088)
1343 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.animation.AnimatorSet.end(AnimatorSet.java:504)
1344 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.animation.AnimatorSet.forceToEnd(AnimatorSet.java:436)
1345 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:995)
1346 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
1347 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
1348 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
1349 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.view.Choreographer$CallbackRecord.run(Choreographer.java:947)
1350 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.view.Choreographer.doCallbacks(Choreographer.java:761)
1351 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.view.Choreographer.doFrame(Choreographer.java:693)
1352 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
1353 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:873)
1354 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
1355 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.os.Looper.loop(Looper.java:193)
1356 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6669)
1357 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
1358 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
1359 | 09-22 08:45:57.790 4927 4927 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by cafesilencio** [comment]
Fixed in PR https://github.com/mapbox/mapbox-navigation-android/pull/3585
