### ISSUE TITLE
NPE when route overview clicked before first route progress update

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3593]
**Android API: 30**
**Mapbox Navigation SDK version: 1.1.0-beta.1**

### Steps to trigger behavior

 1. Set a route
 2. Start navigation
 3. Immediately click route overview (supposedly before we get the first progress update)

### Expected behavior
No crash.

### Actual behavior
```
2020-09-25 12:01:27.547 16688-16688/com.mapbox.onetap.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.onetap.app, PID: 16688
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.api.directions.v5.models.DirectionsRoute com.mapbox.navigation.base.trip.model.RouteProgress.getRoute()' on a null object reference
        at com.mapbox.navigation.ui.camera.NavigationCamera.showRouteOverview(NavigationCamera.java:222)
        at com.mapbox.navigation.ui.map.NavigationMapboxMap.showRouteOverview(NavigationMapboxMap.java:718)
        at com.mapbox.onetap.map.presentation.ui.MapFragment$setupSummary$1.onClick(MapFragment.kt:193)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

/cc @abhishek1508 @JunDai @langsmith @cafesilencio

**Comment by JunDai** [comment]
I tried to use the `example` app to reproduce, but no lucky. I may used a different steps as you.

@LukasPaczos - can you give more detail of how to reproduce it? maybe a screen recording will be more helpful?

**Comment by LukasPaczos** [comment]
When I had a repro case to share, I just opted to fix right away - https://github.com/mapbox/mapbox-navigation-android/pull/3626 :upside_down_face:
