### ISSUE TITLE
Crash on addProgressChangeListener even if the progress listener is given.

### ISSUE THREAD

**Issue by redavid7** [mapbox/mapbox-navigation-android#3614]
**Android API: Android X**
**Android Target Level: 29**
**Mapbox Navigation SDK version: 0.42.6**

### Problem description

The error occurs in a complicated structure. I have two instances of navigators in my app: one is in a portrait mode, and another is in landscape mode, and they have to be different due to the app design.
The portrait one works fine, there aren't problems.
The landscape one, instead, doesn't work. This navigationView is inflated in a fragment located in a view pager, so is one of the fragments you can swipe to.
Long story short, i'm using also the navigationView's child mapView to set markers and route to show the preview route to the user. When the user is ok with the route, he can press the start button, which makes all crash. But I cannot understand what is appening at the time this crash occurs.

### Code part

Here i will share with you some of my code to help you understand the situation.

`// creating navigation options
            val options = NavigationViewOptions.builder()
                .navigationListener(this)
                .directionsRoute(currentRoute)
                .shouldSimulateRoute(false)
                .instructionListListener(this)
                .routeListener(this)
                .speechAnnouncementListener(this)
                .bannerInstructionsListener(this)
                .progressChangeListener { location, routeProgress ->
                    logger.debug(location.toString())
                    logger.debug(routeProgress.toString())
                }.build()

            logger.debug("Landscape navigator: assignment proof: "+(options.progressChangeListener()== null).toString())

            // start navigation
            navigationView.startNavigation(options)`

`
2020-10-02 15:30:53.164 12458-12458/it.dummy.mobile.application/LandscapeNavigationFragment: Landscape navigator: assignment proof: false
...
2020-10-02 15:30:53.295 12458-12458/it.dummy.mobile.application E/AndroidRuntime: FATAL EXCEPTION: main
    Process :it.dummy.mobile.application, PID: 12458
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.addProgressChangeListener(com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation)' on a null object reference
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationListeners(NavigationView.java:691)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigation(NavigationView.java:632)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:394)
        at it.dummy.mobile.application.ui.LandscapeNavigationFragment$setRouteInfoOnLayout$3.onClick(LandscapeNavigationFragment.kt:1712)
        at android.view.View.performClick(View.java:7862)
        at android.view.View.performClickInternal(View.java:7831)
        at android.view.View.access$3600(View.java:879)
        at android.view.View$PerformClick.run(View.java:29359)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

### Other informations

The map is used and works until the navigation is set to start. I also tried to make my fragment extend the progressChangeListener, without any different results. The code posted is one of the last tries i made. It seems that until the library goes to retrieve the listener from the NavigationViewOptions object, it loses his reference. Or maybe the NavigationView's mapView is not meant to be used outside the navigation purpose. Those are my mainly two suspects.

I hope i've been clear enought. Can someone help my sad soul?
Many thanks to whoever reply to me.

**Comment by Guardiola31337** [comment]
Hey @redavid7 thanks for reaching out and report your issue.

Would you mind re-testing / confirming if OP is still an issue in 1.x (latest stable available is [`1.3.0`](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v1.3.0))? You can review the developer [documentation](https://docs.mapbox.com/android/beta/navigation/overview/) to start building with the Mapbox Navigation SDK v1.0 for Android and check out the [migration guide](https://github.com/mapbox/mapbox-navigation-android/wiki/1.0-Navigation-SDK-Migration-Guide) to transition your project from the "legacy" Navigation SDK to the 1.0 version and let us know if you have any questions or run into issues. We would love your feedback.

**Comment by abhishek1508** [comment]
Thanks for using the Mapbox Navigation SDK for Android and being a valued customer.

Mapbox will be soon deprecating any support for `v0` and `v1` versions of the SDK. To facilitate this transition we’re launching a new drop-in UI component into `v2`, equivalent to the existing `NavigationView` `v1` in its design goals, however with a more modern and customizable API. 

We plan to launch this new drop-in UI component as a Developer Preview feature in April, as part of the `v2.5` series. Since you are using `NavigationView` with `v1`, we’d love to hear your feedback so that we can incorporate it ahead of a GA release.

If you’re interested in having early access to the upcoming drop-in UI for `v2` and its documentation, drop a comment on this ticket or send an email to abhishek.kejriwal@mapbox.com

/cc @zugaldia @AhmerKhan1
