### ISSUE TITLE
MapboxNavigation initialization

### ISSUE THREAD

**Issue by ThinClient** [mapbox/mapbox-navigation-android#3641]
When trying to initialize a MapboxNavigation instance:

NavigationOptions mapboxNavigationOptions = MapboxNavigation.
                defaultNavigationOptionsBuilder(this, ACCESS_TOKEN)
                .build();
        mapboxNavigation = new MapboxNavigation(mapboxNavigationOptions);

error:

 Caused by: java.lang.IllegalStateException: Missing required properties: distance duration
        at com.mapbox.api.directions.v5.models.$AutoValue_DirectionsRoute$Builder.build($AutoValue_DirectionsRoute.java:283)
        at com.mapbox.navigation.core.telemetry.TelemetryLocationAndProgressDispatcher.<init>(TelemetryLocationAndProgressDispatcher.kt:33)
        at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry.registerForNotification(MapboxNavigationTelemetry.kt:624)
        at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry.access$registerForNotification(MapboxNavigationTelemetry.kt:105)
        at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry$preInitializePredicate$1.invoke(MapboxNavigationTelemetry.kt:325)
        at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry$preInitializePredicate$1.invoke(MapboxNavigationTelemetry.kt:105)
        at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry.initialize(MapboxNavigationTelemetry.kt:375)
        at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:199)

**Comment by takeshi4126** [comment]
@ThinClient I encountered the same issue today, but the error disappeared after upgrading the library to 1.1.0 in the build.grade, sync and rebuilt the project.

`
implementation "com.mapbox.navigation:ui:1.1.0"
`

If you're using 1.0.0 version of the library, it may worth a try.

**Comment by ThinClient** [comment]
@takeshi4126  upgrading solves the issue. Thanks.

**Comment by LukasPaczos** [comment]
Glad it works for you @ThinClient, thanks @takeshi4126!

**Comment by takeshi4126** [comment]
@lukasPaczos My pleasure. It may help someone like me if you update the version in the Overview page from 1.0.0 to 1.1.0, thanks.

https://docs.mapbox.com/android/navigation/overview/

**Comment by ThinClient** [comment]
I second @takeshi4126 

e.g https://docs.mapbox.com/android/navigation/overview/route-generation/ 

mapboxNavigation.requestRoutes(
    RouteOptions.builder()
        .applyDefaultParams()
        .accessToken(MAPBOX_TOKEN)
        .coordinates(listOf(originPoint, destinationPoint))
        .build()
)

example is not working.

**Comment by takeshi4126** [comment]
@ThinClient I have a similar (or more or less same as your) use case where mapboxNavigation is used for finding a route before startNavigation is called. I think it is related to #3092 which is still open.

**Comment by ThinClient** [comment]
@takeshi4126 yeah they are the same issue.

**Comment by LukasPaczos** [comment]
@takeshi4126 @ThinClient a short follow up to your question above - https://github.com/mapbox/mapbox-navigation-android/issues/3092#issuecomment-716432855.
