### ISSUE TITLE
Firebase robo crash NoSuchFieldException: HTTP_SERVER

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#3645]
Another one, just like this one https://github.com/mapbox/mapbox-navigation-android/issues/3562

https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/5209702353643546555/executions/bs.cc403ab7797043e8
```
	at h.u$a.invoke()
     FATAL EXCEPTION: main
Process: com.mapbox.navigation.examples, PID: 16019
java.lang.AssertionError: java.lang.NoSuchFieldException: HTTP_SERVER
	at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>()
	at com.google.gson.internal.bind.TypeAdapters$30.create()
	at com.google.gson.Gson.getAdapter()
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField()
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields()
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create()
	at com.google.gson.Gson.getAdapter()
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory.create()
	at com.google.gson.Gson.getAdapter()
	at h.z.a.a.d()
	at h.u.f()
	at h.u.h()
	at h.k.e()
	at h.k.f()
	at h.v.b()
	at h.u.c()
	at h.u$a.invoke()
	at java.lang.reflect.Proxy.invoke(Proxy.java:393)
	at $Proxy11.a(Unknown Source)
	at com.mapbox.navigation.examples.history.c.c()
	at com.mapbox.navigation.examples.history.c$b.g()
	at e.v.k.a.a.i()
	at kotlinx.coroutines.b1.run()
	at kotlinx.coroutines.f3.b.G()
	at kotlinx.coroutines.f3.b$a.c()
	at kotlinx.coroutines.f3.b$a.m()
	at kotlinx.coroutines.f3.b$a.run()
Caused by: java.lang.NoSuchFieldException: HTTP_SERVER
	at java.lang.Class.getField(Class.java:891)
	... 27 more
```

**Comment by kmadsen** [comment]
Similar to this comment https://github.com/mapbox/mapbox-navigation-android/issues/3562#issuecomment-707265067

1. cd mapbox-navigation-android
1. ./gradlew examples:assembleRelease (don't worry about the "storePassword")
1. ls examples/build/outputs/mapping/release/
[mapping.txt](https://github.com/mapbox/mapbox-navigation-android/files/5366670/mapping.txt) seeds.txt   usage.txt

Notice these lines in the crash
```
	at com.mapbox.navigation.examples.history.c.c() <== to HistoryFilesClient.requestHistoryCall()
	at com.mapbox.navigation.examples.history.c$b.g() <== to HistoryFilesClient.invokeSuspend()
	at e.v.k.a.a.i()  <== kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith
```

**Comment by Guardiola31337** [comment]
Run into this https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/6701210065111416946/executions/bs.6fddbda7d0cbe33e when working on https://github.com/mapbox/mapbox-navigation-android/pull/3653 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/9060/workflows/66546f08-e3d0-40ab-be17-8e8848692865/jobs/33689

**Comment by kmadsen** [comment]
https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/7464126921186382426/executions/bs.e879f668badafc2

Reopening because maybe it hasn't been solved

**Comment by kmadsen** [comment]
Hmm trying to reproduce locally, but it's working.

1. add `minifyEnabled true` to the debug build (in the pull request description https://github.com/mapbox/mapbox-navigation-android/pull/3646)
1. remove `@Keep` from here https://github.com/mapbox/mapbox-navigation-android/pull/3646/files#diff-b626863f61bbe9a5178c1c9f7fc1aa72e44a758f35afcf049728bfd9426d28e7R30

```
2020-10-27 13:49:06.411 12509-12509/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 12509
    java.lang.AssertionError: java.lang.NoSuchFieldException: HTTP_SERVER
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.<init>(:792)
        at com.google.gson.internal.bind.TypeAdapters$30.create(:818)
        at com.google.gson.Gson.getAdapter(:458)
```

If you add `@Keep`, the crash is fixed.. So am wondering if there is a different way to reproduce this crash.

**Comment by Guardiola31337** [comment]
We can close re-close as changes were not brought to https://github.com/mapbox/mapbox-navigation-android/pull/3540 yet 👀  (no `@Keep`)

https://github.com/mapbox/mapbox-navigation-android/blob/683b8da63b35c989b84adfde490e99e54f7b05f7/examples/src/main/java/com/mapbox/navigation/examples/history/HistoryFilesClient.kt#L29

cc @korshaknn
