### ISSUE TITLE
Layout with com.mapbox.services.android.navigation.ui.v5.NavigationView will crash

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-navigation-android#3656]
I Run my app will crash when i use com.mapbox.services.android.navigation.ui.v5.NavigationView in my layout

Process: com.nuro.mapboxnavigationview, PID: 16377
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.nuro.mapboxnavigationview/com.nuro.mapboxnavigationview.MainActivity}: android.view.InflateException: Binary XML file line #9: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2505)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2577)
        at android.app.ActivityThread.access$1000(ActivityThread.java:164)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1462)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:159)
        at android.app.ActivityThread.main(ActivityThread.java:5541)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:975)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
     Caused by: android.view.InflateException: Binary XML file line #9: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at com.nuro.mapboxnavigationview.MainActivity.onCreate(MainActivity.java:12)

activity_main.xml

<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".MainActivity">

<com.mapbox.mapboxsdk.maps.MapView
        android:id="@+id/mapView"
        android:layout_width="0dp"
        android:layout_height="0dp"
        mapbox:layout_constraintBottom_toBottomOf="parent"
        mapbox:layout_constraintEnd_toEndOf="parent"
        mapbox:layout_constraintStart_toStartOf="parent"
        mapbox:layout_constraintTop_toTopOf="parent"
        mapbox:mapbox_cameraTargetLat="24.8136065"
        mapbox:mapbox_cameraTargetLng="121.021013"
        mapbox:mapbox_cameraZoom="15">
    </com.mapbox.mapboxsdk.maps.MapView>

    <com.mapbox.services.android.navigation.ui.v5.NavigationView
        android:id="@+id/navigationUIView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        />

</androidx.constraintlayout.widget.ConstraintLayout>

**Comment by KayHung** [comment]
If I use MainActivity extends AppCompatActivity, then it can work well.
But when I use MainActivity extends Activity, it will crash
