### ISSUE TITLE
RuntimeException: Could not read input channel file descriptors from parcel

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3676]
An issue caught by a Robo test https://github.com/mapbox/mapbox-navigation-android/pull/3674 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/9141/workflows/168ee1b2-0460-453c-a21f-bba01371fd04/jobs/34080 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/6855818869958487339/executions/bs.c8929c74aac70707

```
FATAL EXCEPTION: main
Process: com.mapbox.navigation.examples, PID: 13891
java.lang.RuntimeException: Could not read input channel file descriptors from parcel.
	at android.view.InputChannel.nativeReadFromParcel(Native Method)
	at android.view.InputChannel.readFromParcel(InputChannel.java:148)
	at android.view.InputChannel$1.createFromParcel(InputChannel.java:39)
	at android.view.InputChannel$1.createFromParcel(InputChannel.java:36)
	at com.android.internal.view.InputBindResult.<init>(InputBindResult.java:68)
	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:112)
	at com.android.internal.view.InputBindResult$1.createFromParcel(InputBindResult.java:109)
	at com.android.internal.view.IInputMethodManager$Stub$Proxy.windowGainedFocus(IInputMethodManager.java:735)
	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1227)
	at android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:1453)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3398)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

cc @LukasPaczos

**Comment by alagunas91** [comment]
@LukasPaczos I have the same problem. 
I have also this line code:
E/Parcel: fcntl(F_DUPFD_CLOEXEC) failed in Parcel::read, i is 1, fds[i] is -1, fd_count is 2, error: Too many open files.

Any suggestions?

**Comment by LukasPaczos** [comment]
Sorry @alagunas91, no additional info so far.
