### ISSUE TITLE
NavigationView crashes from time to time while trying to build the distance formatter object

### ISSUE THREAD

**Issue by agap** [mapbox/mapbox-navigation-android#3713]
**Android API:** 28
**Mapbox Navigation SDK version:** 1.1.1

### Steps to trigger behavior

It's hard to describe the specific set of steps to trigger that behavior since the issue can not be reproduced all the time. What we'm doing is requesting the list of routes from point A to point B via `MapboxGeocoding.Builder`, and, once `RoutesRequestCallback#onRoutesReady` gets triggered, we start navigation like so:

```
val route = routes[0]

val options = NavigationViewOptions
    .builder(this@NavigationActivity)
    .navigationListener(navigationListener)
    .directionsRoute(route)
    .build()

binding.navigationView.startNavigation(options)
```

It works just fine 99% of the time, but occasionally it fails while trying to build the distance formatter (see below).

### Expected behavior

No crash

### Actual behavior

The app is crashing with the following stacktrace:

```
Fatal Exception: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter unitType
       at com.mapbox.navigation.core.internal.formatter.MapboxDistanceFormatter$Builder.unitType(:2)
       at com.mapbox.navigation.ui.NavigationViewModel.buildDistanceFormatter(NavigationViewModel.java:339)
       at com.mapbox.navigation.ui.NavigationViewModel.initializeDistanceFormatter(NavigationViewModel.java:310)
       at com.mapbox.navigation.ui.NavigationViewModel.initialize(NavigationViewModel.java:183)
       at com.mapbox.navigation.ui.NavigationView.initializeNavigation(NavigationView.java:844)
       at com.mapbox.navigation.ui.NavigationView.startNavigation(NavigationView.java:453)
```

**Comment by JunDai** [comment]
@agap : thanks for using our SDK and reporting the issue.

I don't see a clear path that can lead to this crash but it worths to add a null protection and uses default voiceUnit if it is missed in the `routeOptions`.
