### ISSUE TITLE
IllegalStateException in MapboxSpeechPlayer

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3750]
Caught by crashlytics on `v1.2.0-beta.1` on Nexus 5 (6.0.1):

```
Fatal Exception: java.lang.IllegalStateException
       at android.media.MediaPlayer.prepareAsync(MediaPlayer.java)
       at com.mapbox.navigation.ui.voice.MapboxSpeechPlayer.setupMediaPlayer(MapboxSpeechPlayer.java:172)
       at com.mapbox.navigation.ui.voice.MapboxSpeechPlayer.playInstruction(MapboxSpeechPlayer.java:163)
       at com.mapbox.navigation.ui.voice.MapboxSpeechPlayer.playInstructionIfUpNext(MapboxSpeechPlayer.java:251)
       at com.mapbox.navigation.ui.voice.MapboxSpeechPlayer.access$500(MapboxSpeechPlayer.java:30)
       at com.mapbox.navigation.ui.voice.MapboxSpeechPlayer$4.onFinishedDownloading(MapboxSpeechPlayer.java:238)
       at com.mapbox.navigation.ui.voice.DownloadTask.onPostExecute(DownloadTask.java:100)
       at com.mapbox.navigation.ui.voice.DownloadTask.onPostExecute(DownloadTask.java:22)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.-wrap1(AsyncTask.java)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

/cc @abhishek1508 @JunDai @cafesilencio

**Comment by Guardiola31337** [comment]
Noting that run into this while testing https://github.com/mapbox/mapbox-navigation-android/pull/3715 locally.
