### ISSUE TITLE
NPE after navigation ended

### ISSUE THREAD

**Issue by Kahtaf** [mapbox/mapbox-navigation-android#376]
I am getting a null pointer at the end of a route starting in 0.6.2. It occurs after endNavigation() is called. I haven't seen this in previous versions and am able to consistently reproduce it. 

```
--------- beginning of crash
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: FATAL EXCEPTION: main
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: Process: com.bitspice.automate, PID: 27596
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: java.lang.RuntimeException: Unable to stop service com.mapbox.services.android.navigation.v5.navigation.NavigationService@b1a1984: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.v5.navigation.NavigationNotification.unregisterReceiver()' on a null object reference
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:3587)
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at android.app.ActivityThread.-wrap26(Unknown Source:0)
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1703)
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6541)
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.v5.navigation.NavigationNotification.unregisterReceiver()' on a null object reference
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at com.mapbox.services.android.navigation.v5.navigation.NavigationService.endNavigation(NavigationService.java:143)
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onDestroy(NavigationService.java:107)
10-12 19:54:55.206 10226 27596 27596 E AndroidRuntime: 	at android.app.ActivityThread.handleStopService(ActivityThread.java:3569)
```

Nexus 6P, Android Oreo, Mapbox navigation 0.6.2.

**Comment by danesfeder** [comment]
Hey @Kahtaf, this should be fixed in our latest SNAPSHOT - https://github.com/mapbox/mapbox-navigation-android/pull/332
