### ISSUE TITLE
Mapbox load java activity class , but after destroy activity application cress in mapbox sdk.

### ISSUE THREAD

**Issue by Vishal949** [mapbox/mapbox-navigation-android#3830]
**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1.Used Navigation functionality in my project.
 2.Navigation working fine. but after back press application cress.
 3.And showing log then found the issue in mapbox cress log.
 
 @Override
    public void onDestroyView() {
        super.onDestroyView();

        mapboxReplayer.finish();
        mapboxNavigation.unregisterTripSessionStateObserver(tripSessionState());
        mapboxNavigation.unregisterRouteProgressObserver(routeProgressObserver());
        mapboxNavigation.unregisterBannerInstructionsObserver(bannerInstructionObserver());
        mapboxNavigation.unregisterVoiceInstructionsObserver(voiceInstructionsObserver());

        mapboxNavigation.stopTripSession();
        mapboxNavigation.onDestroy();

        speechPlayer.onDestroy();
    }

### Actual behavior
java.lang.IllegalStateException: Calling getSourceAs when a newer style is loading/has loaded.
        at com.mapbox.mapboxsdk.maps.Style.validateState(Style.java:786)
        at com.mapbox.mapboxsdk.maps.Style.getSourceAs(Style.java:148)
        at com.mapbox.mapboxsdk.location.SymbolLocationLayerRenderer.refreshSource(SymbolLocationLayerRenderer.java:321)
        at com.mapbox.mapboxsdk.location.SymbolLocationLayerRenderer.setLocationPoint(SymbolLocationLayerRenderer.java:331)
        at com.mapbox.mapboxsdk.location.SymbolLocationLayerRenderer.setLatLng(SymbolLocationLayerRenderer.java:162)
        at com.mapbox.mapboxsdk.location.LocationLayerController$1.onNewAnimationValue(LocationLayerController.java:268)
        at com.mapbox.mapboxsdk.location.LocationLayerController$1.onNewAnimationValue(LocationLayerController.java:265)
        at com.mapbox.mapboxsdk.location.MapboxAnimator.postUpdates(MapboxAnimator.java:106)
        at com.mapbox.mapboxsdk.location.MapboxAnimator.onAnimationUpdate(MapboxAnimator.java:93)
        at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1350)
        at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1262)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1310)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.-wrap2(AnimationHandler.java)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:872)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:618)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by LukasPaczos** [comment]
Hey @Vishal949, which navigation component are you using, `NavigationView`, `NavigationMapboxMap` or are you managing the `LocationComponent` manually? If you're manually managing the `LocationComponent`, do you stop pushing location updates after the map is destroyed?

Are you calling all of the `MapView` lifecycle methods correctly?

**Comment by Guardiola31337** [comment]
Also @Vishal949 do you mind sharing what version of the SDK you're using?
