### ISSUE TITLE
navigationView.retrieveMapboxNavigation() returns null

### ISSUE THREAD

**Issue by simon-the-shark** [mapbox/mapbox-navigation-android#3832]
**Android API: 29**
**Mapbox Navigation SDK version: com.mapbox.navigation:ui:1.1.0**

### Steps to trigger behaviour
1. I tried to implement custom routing with Mapbox map matching and in order to do that I need to disable default rerouting. At the moment completely, but in the future maybe also implement some custom rerouting behaviour.
2. So I set the rerouteController to null. I also tried with custom reroute controller with empty reroute function, but the result was the same
3. When I set  .shouldSimulateRoute to true, everything works completely fine (only because it doesn't try to reroute)
4. My onNavigationReady code below:

```Kotlin
override fun onNavigationReady(isRunning: Boolean) {
        // I set some dummy list of points that normally are retrieved elsewhere
        points = listOf(listOf(51.11426612028596,17.034100075627506), listOf(51.116461549539906,17.04205658201237), listOf(51.11416666666667,17.046111111111113)).map { e -> com.mapbox.geojson.Point.fromLngLat(e[1], e[0]) }
        if (!isRunning && !::navigationMapboxMap.isInitialized) {
            if (navigationView.retrieveNavigationMapboxMap() != null) {
                this.navigationMapboxMap = navigationView.retrieveNavigationMapboxMap()!!
                navigationView.retrieveMapboxNavigation()?.let {
                    it.registerLocationObserver(this)
//some custom reroute controller with empty reroute function also cause a crash
                    it.setRerouteController(null) 
                    this.mapboxNavigation = it;
                }
                val radiuses = Array(points.size) { _ -> 25.0 }
                MapboxMapMatching.builder()
                        .accessToken(Mapbox.getAccessToken()!!)
                        .coordinates(points)
                        .steps(true)
                        .voiceInstructions(true)
                        .bannerInstructions(true)
                        .profile(DirectionsCriteria.PROFILE_DRIVING)
                        .radiuses(*radiuses)
                        .language("en")
                        .overview(DirectionsCriteria.OVERVIEW_FULL)
                        .voiceUnits(DirectionsCriteria.METRIC)
                        .waypointIndices(0, points.size - 1)
                        .build()
                        .enqueueCall(object : Callback<MapMatchingResponse> {
                            override fun onResponse(call: Call<MapMatchingResponse>, response: Response<MapMatchingResponse>) {
                                Log.i(TAG, response.body()?.matchings()!![0].toDirectionRoute().toString())
                                if (response.isSuccessful)
                                    response.body()?.matchings()?.let { matchingList ->
                                        matchingList[0].toDirectionRoute().apply {
                                            val optionsBuilder = NavigationViewOptions.builder(self)
                                                    .navigationListener(self)
                                                    .directionsRoute(this)
                                                    .shouldSimulateRoute(false) // when set to true, everything works completely fine
                                            navigationView.startNavigation(optionsBuilder.build())
                                            return;
                                        }
                                    }
                                finish()
                            }

                            override fun onFailure(call: Call<MapMatchingResponse>, throwable: Throwable) {
                                finish()
                            }
                        })

            }
        }
    }
```

### Expected behaviour
It starts the navigation, doesn't reroute and doesn't crash

### Actual behaviour
It opens up the map, but instead of starting the navigation, it throws an error like this and crashes the app
```
java.lang.IndexOutOfBoundsException: toIndex = 3
        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
        at java.util.ArrayList.subList(ArrayList.java:1008)
        at com.mapbox.navigation.core.routeoptions.MapboxRouteOptionsUpdater.update(MapboxRouteOptionsUpdater.kt:103)
        at com.mapbox.navigation.core.reroute.MapboxRerouteController.reroute(MapboxRerouteController.kt:50)
        at com.mapbox.navigation.core.MapboxNavigation.reroute(MapboxNavigation.kt:687)
        at com.mapbox.navigation.core.MapboxNavigation.access$reroute(MapboxNavigation.kt:127)
        at com.mapbox.navigation.core.MapboxNavigation$createInternalOffRouteObserver$1.onOffRouteStateChanged(MapboxNavigation.kt:681)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.setOffRoute(MapboxTripSession.kt:128)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$setOffRoute$p(MapboxTripSession.kt:49)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.kt:461)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by simon-the-shark** [comment]
I have found the real cause of my problem. It seems that ```navigationView.retrieveMapboxNavigation()``` return null and that's why none of the invoked methods has any effect.  Including reroute controller and all of the observers. The question is why it can happen to me

**Comment by simon-the-shark** [comment]
Ok, so it looks like [navigation has to be started before](https://docs.mapbox.com/android/navigation/api/ui/1.1.0/com.mapbox.navigation.ui/-navigation-view/retrieve-mapbox-navigation.html) I want to access MapboxNavigation.

**Comment by simon-the-shark** [comment]
Basically, I resolved it by myself
