### ISSUE TITLE
waypointIndicesList crash in reroute case?

### ISSUE THREAD

**Issue by karaipan** [mapbox/mapbox-navigation-android#3854]
**Android API:**30
**Mapbox Navigation SDK version:**1.2.1

### Steps to trigger behavior

 1. Request route with coordinates list, and pick some coordinates to make waypointIndicesList. I also check waypointIndicesList contains first coordinate (0) at first element of list, and coordinate size at last element of list
 2. Request route works with first time
 3. Make off-route case, app crashes with below log

```
java.lang.IndexOutOfBoundsException: toIndex = 17
        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
        at java.util.ArrayList.subList(ArrayList.java:1008)
        at com.mapbox.navigation.core.routeoptions.MapboxRouteOptionsUpdater.update(MapboxRouteOptionsUpdater.kt:103)
        at com.mapbox.navigation.core.reroute.MapboxRerouteController.reroute(MapboxRerouteController.kt:50)
        at com.mapbox.navigation.core.MapboxNavigation.reroute(MapboxNavigation.kt:738)
        at com.mapbox.navigation.core.MapboxNavigation.access$reroute(MapboxNavigation.kt:130)
        at com.mapbox.navigation.core.MapboxNavigation$createInternalOffRouteObserver$1.onOffRouteStateChanged(MapboxNavigation.kt:732)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.setOffRoute(MapboxTripSession.kt:121)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$setOffRoute$p(MapboxTripSession.kt:48)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.kt:512)
```

I also found out this information here:
https://github.com/mapbox/mapbox-navigation-android/pull/3581

It's related to problem I mention above? I use 1.2.1 version now, and it still happens.

Thank you for spending time to check my question.

**Comment by Guardiola31337** [comment]
@Lebedinsky could you confirm if #3581 would fix this issue? 🙏 

cc @RingerJK

**Comment by karaipan** [comment]
@Guardiola31337 
Thank you so much for check! 
Could you please tell me by any chance if this issue will be fixed soon and released in the next version?
Because it seems that the same function works normally in iOS and I'm really looking forward to knowing how's about status in Android.

Thank you and hope you guys have a nice week!

**Comment by Lebedinsky** [comment]
Yes, this issue fixed in [this PR](https://github.com/mapbox/mapbox-navigation-android/pull/3497)
