### ISSUE TITLE
java.lang.String java.lang.CharSequence.toString()' on a null object reference ThemeSwitcher

### ISSUE THREAD

**Issue by dkpapo** [mapbox/mapbox-navigation-android#3873]
**Android API: 29**
**Mapbox Navigation SDK version:5.7.0**

### Steps to trigger behavior

 1. init navigation turn by turn navigation

### Actual behavior

java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
        at com.mapbox.navigation.ui.internal.ThemeSwitcher.retrieveMapStyle(ThemeSwitcher.java:97)
        at com.mapbox.navigation.ui.NavigationView.onMapReady(NavigationView.java:239)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1320)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.initialised(MapView.java:1306)
        at com.mapbox.mapboxsdk.maps.MapView.initialiseMap(MapView.java:197)
        at com.mapbox.mapboxsdk.maps.MapView.access$800(MapView.java:63)
        at com.mapbox.mapboxsdk.maps.MapView$6.run(MapView.java:353)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

**Comment by LukasPaczos** [comment]
Hey @dkpapo could you double-check the Navigation SDK version on which the issue was caught? There's no version `5.7.0`.

Also, could you provide reproduction steps? Are you providing a custom `navigationViewMapStyle` resource?

**Comment by abhishek1508** [comment]
Thanks for using the Mapbox Navigation SDK for Android and being a valued customer.

Mapbox will be soon deprecating any support for `v0` and `v1` versions of the SDK. To facilitate this transition we’re launching a new drop-in UI component into `v2`, equivalent to the existing `NavigationView` `v1` in its design goals, however with a more modern and customizable API. 

We plan to launch this new drop-in UI component as a Developer Preview feature in April, as part of the `v2.5` series. Since you are using `NavigationView` with `v1`, we’d love to hear your feedback so that we can incorporate it ahead of a GA release.

If you’re interested in having early access to the upcoming drop-in UI for `v2` and its documentation, drop a comment on this ticket or send an email to abhishek.kejriwal@mapbox.com

/cc @zugaldia @AhmerKhan1
