### ISSUE TITLE
IndexOutOfBoundsException when rerouting

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3888]
**Mapbox Navigation SDK version:** `1.4.0-beta.1`

An exception caught by a crashlytics service, stacktrace:
```
Fatal Exception: java.lang.IndexOutOfBoundsException: toIndex = 3
       at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
       at java.util.ArrayList.subList(ArrayList.java:1008)
       at com.mapbox.navigation.core.routeoptions.MapboxRouteOptionsUpdater.update(MapboxRouteOptionsUpdater.java:65)
       at com.mapbox.navigation.core.reroute.MapboxRerouteController.reroute(MapboxRerouteController.java:50)
       at com.mapbox.navigation.core.MapboxNavigation.reroute(MapboxNavigation.java:746)
       at com.mapbox.navigation.core.MapboxNavigation.access$paramsProvider(MapboxNavigation.java:131)
       at com.mapbox.navigation.core.MapboxNavigation$createInternalOffRouteObserver$1.onOffRouteStateChanged(MapboxNavigation.java:740)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession.setOffRoute(MapboxTripSession.java:123)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$setUNCONDITIONAL_STATUS_POLLING_INTERVAL$cp(MapboxTripSession.java:48)
       at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.java:514)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

Might be related to https://github.com/mapbox/mapbox-navigation-android/pull/3581.

/cc @Lebedinsky @RingerJK @Guardiola31337

**Comment by amalmadawa90** [comment]
I have disabled rerouting but I also having this issue when trying to navigate 

 ```
mapboxNavigation = MapboxNavigation(mapboxNavigationOptions)
mapboxNavigation?.setRerouteController(null)
```

```
java.lang.IndexOutOfBoundsException
        at java.util.AbstractList.subList(AbstractList.java:738)
        at com.mapbox.navigation.core.routeoptions.MapboxRouteOptionsUpdater.update(MapboxRouteOptionsUpdater.kt:103)
        at com.mapbox.navigation.core.reroute.MapboxRerouteController.reroute(MapboxRerouteController.kt:50)
        at com.mapbox.navigation.core.MapboxNavigation.reroute(MapboxNavigation.kt:687)
        at com.mapbox.navigation.core.MapboxNavigation.access$reroute(MapboxNavigation.kt:127)
        at com.mapbox.navigation.core.MapboxNavigation$createInternalOffRouteObserver$1.onOffRouteStateChanged(MapboxNavigation.kt:681)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.setOffRoute(MapboxTripSession.kt:128)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$setOffRoute$p(MapboxTripSession.kt:49)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.kt:461)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by RingerJK** [comment]
@amalmadawa90 could you provide version of the SDK as well?

**Comment by amalmadawa90** [comment]
@RingerJK  implementation "com.mapbox.navigation:ui:1.1.0"

**Comment by amalmadawa90** [comment]
I have tried to implement 1.4.0 it's not working.
Failed to resolve: com.mapbox.navigation:ui:1.4.0

**Comment by RingerJK** [comment]
> I have tried to implement 1.4.0 it's not working.
> Failed to resolve: com.mapbox.navigation:ui:1.4.0

`1.4.0` hasn't been released. The only available is `1.4.0-beta.1`. See https://github.com/mapbox/mapbox-navigation-android/releases

**Comment by LukasPaczos** [comment]
@RingerJK the reported issue was also caught using `1.4.0-beta.1` (see the original post), so something else might be the culprit.

**Comment by RingerJK** [comment]
> @RingerJK the reported issue was also caught using `1.4.0-beta.1` (see the original post), so something else might be the culprit.

yes, top problem was addressed into https://github.com/mapbox/mapbox-navigation-android/pull/3899 , but https://github.com/mapbox/mapbox-navigation-android/issues/3888#issuecomment-756076302 is a bit different and might be not reproduced with 1.4.0.beta.1+

**Comment by LukasPaczos** [comment]
Gotcha, thanks @RingerJK :+1:
