### ISSUE TITLE
MockWebServer Request url is not handled

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#3900]
An issue / flaky test caught by `instrumentation-tests` in https://github.com/mapbox/mapbox-navigation-android/pull/3899 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/9967/workflows/056a598a-ce2f-46b1-9838-9ef5a9f95572/jobs/38326 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/5577302644484227501/executions/bs.eb35ac1ccb9e1e59

```
Available handlers:
     FATAL EXCEPTION: MockWebServer
Process: com.mapbox.navigation.instrumentation_tests, PID: 13311
java.lang.Error: Request url:
/voice/v1/speak/%3Cspeak%3E%3Camazon:effect%20name=%22drc%22%3E%3Cprosody%20rate=%221.08%22%3EYou%20have%20arrived%20at%20your%20destination.%3C%2Fprosody%3E%3C%2Famazon:effect%3E%3C%2Fspeak%3E?textType=ssml&language=es&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNqa3UwZng4djBhZmUza3AzYWh2cXVyZHMifQ.lnkA4GqBmNtIiBFnHsA7Ng&sku=108kju7f48uc50c354b4db3436bafd35caf610d88cb
is not handled.
Available handlers:
	at com.mapbox.navigation.testing.ui.http.MockWebServerRule$1.dispatch(MockWebServerRule.kt:46)
	at okhttp3.mockwebserver.MockWebServer$3.processOneRequest(MockWebServer.java:558)
	at okhttp3.mockwebserver.MockWebServer$3.processConnection(MockWebServer.java:516)
	at okhttp3.mockwebserver.MockWebServer$3.execute(MockWebServer.java:443)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

Refs. https://github.com/mapbox/mapbox-navigation-android/pull/3715

cc @LukasPaczos

**Comment by Guardiola31337** [comment]
Let's close for now as we haven't seen this for a while. If pops up again we'll reopen.
