### ISSUE TITLE
Missing mock request handlers

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3902]
https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/9967/workflows/056a598a-ce2f-46b1-9838-9ef5a9f95572/jobs/38326
```
Available handlers:
     FATAL EXCEPTION: MockWebServer
Process: com.mapbox.navigation.instrumentation_tests, PID: 13311
java.lang.Error: Request url:
/voice/v1/speak/%3Cspeak%3E%3Camazon:effect%20name=%22drc%22%3E%3Cprosody%20rate=%221.08%22%3EYou%20have%20arrived%20at%20your%20destination.%3C%2Fprosody%3E%3C%2Famazon:effect%3E%3C%2Fspeak%3E?textType=ssml&language=es&access_token={token}&sku={sku}
is not handled.
Available handlers:
	at com.mapbox.navigation.testing.ui.http.MockWebServerRule$1.dispatch(MockWebServerRule.kt:46)
	at okhttp3.mockwebserver.MockWebServer$3.processOneRequest(MockWebServer.java:558)
	at okhttp3.mockwebserver.MockWebServer$3.processConnection(MockWebServer.java:516)
	at okhttp3.mockwebserver.MockWebServer$3.execute(MockWebServer.java:443)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

An issue caught in our instrumentation test suite. The `Available handlers` list looks to be empty, so the issue might be in the initialization of the test itself.

**Comment by LukasPaczos** [comment]
Duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/3900.
