### ISSUE TITLE
Flaky firebase instrumentation tests FATAL EXCEPTION: MockWebServer

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#3921]
https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/5630447067179515230/executions/bs.68e6add9231c1702

~5/20 of the tests are failing with this stack trace. Not sure if it's Firebase or our tests 🤔 

<img width="973" alt="Screen Shot 2021-01-22 at 2 51 48 PM" src="https://user-images.githubusercontent.com/3021882/105552580-5cc83400-5cc1-11eb-872b-b9e9bd9f56a3.png">

```
Available handlers:
     FATAL EXCEPTION: MockWebServer
Process: com.mapbox.navigation.instrumentation_tests, PID: 18664
java.lang.Error: Request url:
/voice/v1/speak/%3Cspeak%3E%3Camazon:effect%20name=%22drc%22%3E%3Cprosody%20rate=%221.08%22%3EYou%20have%20arrived%20at%20your%20destination.%3C%2Fprosody%3E%3C%2Famazon:effect%3E%3C%2Fspeak%3E?textType=ssml&language=fr&access_token=pk.eyJ1IjoibHVrYXNwYWN6b3MiLCJhIjoiY2phMnE0ZTZlMmc3NDJxcG82MWNlcHV6ZCJ9.FAw-i97z7eh61baosyzVxQ&sku=108kk8c0fg8ea10622578c74b03890a0a8ac8a7be51
is not handled.
Available handlers:
	at com.mapbox.navigation.testing.ui.http.MockWebServerRule$1.dispatch(MockWebServerRule.kt:46)
	at okhttp3.mockwebserver.MockWebServer$3.processOneRequest(MockWebServer.java:558)
	at okhttp3.mockwebserver.MockWebServer$3.processConnection(MockWebServer.java:516)
	at okhttp3.mockwebserver.MockWebServer$3.execute(MockWebServer.java:443)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by Guardiola31337** [comment]
Duplicated of https://github.com/mapbox/mapbox-navigation-android/issues/3900

Closing here.
