### ISSUE TITLE
crash while .startNavigation been called

### ISSUE THREAD

**Issue by ShalevCohen2112** [mapbox/mapbox-navigation-android#3924]
My application crash when I try to use the navigation function while my network connection is on data(4G), when the connection is wifi, the navigation is working.

using android 8.0, kotliin and com.mapbox.navigation:ui:1.1.0

**Code:**
 override fun onRoutesReady(routes: List<DirectionsRoute>) {
        if (routes.isNullOrEmpty()) {
            handleRouteError()
            return
        }
        val optionsBuilder = NavigationViewOptions.builder(requireContext())
        optionsBuilder.camera(SimpleCamera())
        optionsBuilder.arrivalObserver(this)
        optionsBuilder.shouldSimulateRoute(true)
        optionsBuilder.directionsRoute(routes[0])
        val options = optionsBuilder.build()
        navigationView.startNavigation(options)

    }

**Crash :**
2021-01-26 09:24:17.568 22164-22164/com.mannadelivery.delivery E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mannadelivery.delivery, PID: 22164
    java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter unitType
        at com.mapbox.navigation.core.internal.formatter.MapboxDistanceFormatter$Builder.unitType(Unknown Source:3)
        at com.mapbox.navigation.ui.NavigationViewModel.buildDistanceFormatter(NavigationViewModel.java:339)
        at com.mapbox.navigation.ui.NavigationViewModel.initializeDistanceFormatter(NavigationViewModel.java:310)
        at com.mapbox.navigation.ui.NavigationViewModel.initialize(NavigationViewModel.java:183)
        at com.mapbox.navigation.ui.NavigationView.initializeNavigation(NavigationView.java:844)
        at com.mapbox.navigation.ui.NavigationView.startNavigation(NavigationView.java:453)
        at com.mannadelivery.delivery.ui.main.fragments.MapFragment.onRoutesReady(MapFragment.kt:240)
        at com.mapbox.navigation.core.directions.session.MapboxDirectionsSession$requestRoutes$1.onResponse(MapboxDirectionsSession.kt:85)
        at com.mapbox.navigation.route.internal.hybrid.MapboxHybridRouter$RouterHandler.onResponse(MapboxHybridRouter.kt:124)
        at com.mapbox.navigation.route.internal.onboard.MapboxOnboardRouter$retrieveRoute$1.invokeSuspend(MapboxOnboardRouter.kt:137)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by abhishek1508** [comment]
Thanks for using the Mapbox Navigation SDK for Android and being a valued customer.

Mapbox will be soon deprecating any support for `v0` and `v1` versions of the SDK. To facilitate this transition we’re launching a new drop-in UI component into `v2`, equivalent to the existing `NavigationView` `v1` in its design goals, however with a more modern and customizable API. 

We plan to launch this new drop-in UI component as a Developer Preview feature in April, as part of the `v2.5` series. Since you are using `NavigationView` with `v1`, we’d love to hear your feedback so that we can incorporate it ahead of a GA release.

If you’re interested in having early access to the upcoming drop-in UI for `v2` and its documentation, drop a comment on this ticket or send an email to abhishek.kejriwal@mapbox.com

/cc @zugaldia @AhmerKhan1
