### ISSUE TITLE
MapboxRouteLineApiExampleActivity NullPointerException

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#3940]
@kmadsen commented on [Thu Feb 04 2021](https://github.com/mapbox/mapbox-navigation-android-internal/issues/125)

**Android API:**
**Mapbox Navigation SDK version:** https://github.com/mapbox/mapbox-navigation-android-internal/pull/91/commits/92dca22ebb935d60e2afa2a949b1ef28ae00a418

The crash is on a dev branch but, the crash is unrelated to the changes. I'm guessing this is happening on [master](https://github.com/mapbox/mapbox-navigation-android-internal/commit/769430a35084cd102f2b279ee6ce6eee07043113). 

Saving a crash from a firebase robo run
https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.a6f59f5d2c1849b4/matrices/5285170341170017134/executions/bs.507b023e0e010579

```
	at com.mapbox.navigation.examples.core.MapboxRouteLineApiExampleActivity$a.onClick(Unknown Source:16)
     FATAL EXCEPTION: Thread-2
Process: com.mapbox.navigation.test_app, PID: 12416
java.lang.NullPointerException: Parameter specified as non-null is null: method e.z.d.k.h, parameter style
	at d.c.f.g.b.g.b.h.b.b(Unknown Source:2)
	at com.mapbox.navigation.examples.core.MapboxRouteLineApiExampleActivity$a.onClick(Unknown Source:16)
	at android.view.View.performClick(View.java:6256)
	at android.view.View$PerformClick.run(View.java:24697)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:11)
	at androidx.test.espresso.base.UiControllerImpl.n(UiControllerImpl.java:6)
	at androidx.test.espresso.base.UiControllerImpl.m(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:6)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:15)
	at androidx.test.espresso.action.Tap.b(Unknown Source:9)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
	at androidx.test.espresso.ViewInteraction.a(Unknown Source:137)
	at androidx.test.espresso.ViewInteraction$1.call(Unknown Source:4)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by cafesilencio** [comment]
The only onClick I see in this activity now has a check for the map style being null. Closing this issue.
