### ISSUE TITLE
Crash on reroute event

### ISSUE THREAD

**Issue by palto-ccadoret** [mapbox/mapbox-navigation-android#395]
A crash occurs on reroute event :

```
10-18 11:50:52.899 7155-7155/com.palto.line.integration.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.palto.line.integration.debug, PID: 7155
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'double com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress.distanceTraveled()' on a null object reference
                                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationMetricsWrapper.rerouteEvent(NavigationMetricsWrapper.java:110)
                                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationService$1.run(NavigationService.java:282)
                                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
```

You are calling distanceTraveled method on a nullable object return by sessionState.routeProgressBeforeReroute() method.

https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationMetricsWrapper.java#L108

**Comment by cammace** [comment]
Thanks for reporting this, added to the 0.7 milestone to make sure we resolve this before the next release.

**Comment by Guardiola31337** [comment]
This is being tracked in #351 

Thanks for reporting it @palto-ccadoret 

Closing here.
