### ISSUE TITLE
NullPointerException MapboxRouteLineApiExampleActivity: Parameter specified as non-null is null

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#4061]
An issue caught by a Robo test https://github.com/mapbox/mapbox-navigation-android/pull/4048 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/10469/workflows/5fff40b9-ac62-4136-b5ae-74646626acfa/jobs/40835 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.a6f59f5d2c1849b4/matrices/8383225816648153745/executions/bs.1bd40a630ce49e31

```
FATAL EXCEPTION: Thread-2
Process: com.mapbox.navigation.test_app, PID: 12243
java.lang.NullPointerException: Parameter specified as non-null is null: method e.y.d.m.h, parameter style
	at d.c.f.g.c.h.b.h.b.b(Unknown Source:2)
	at com.mapbox.navigation.examples.core.MapboxRouteLineApiExampleActivity$a.onClick(Unknown Source:16)
	at android.view.View.performClick(View.java:6256)
	at android.view.View$PerformClick.run(View.java:24697)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.access$100(Tap.java:1)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:19)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

cc @cafesilencio

**Comment by Guardiola31337** [comment]
Closing as duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/3940
