### ISSUE TITLE
Refactor how we manage firebase gradle plugins for the test-app

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4076]
Following up from https://github.com/mapbox/mapbox-navigation-android/pull/4075
Other approaches considered https://github.com/mapbox/mapbox-navigation-android/issues/4071

### Problem

Right now we have an empty google-services.json to allow customers to run the app without access to Firebase. But we don't want to require an empty 

This ticket is to consider approaches and find a long term solution. Iterations attempted may need to be expanded on. 

### Requirements

- Customers outside of Mapbox should be able to clone the repo and run the test-app
- Firebase robotic runs should be able to run the test app
- Firebase robotic runs should include crashlytics

### Approaches

Pass in a gradle parameter to disable plugins ./gradlew ... -PuseFirebasePerfAndCrashlytics=true 

if (useFirebasePerfAndCrashlytics) {
    apply(plugin = "com.google.firebase.firebase-perf")
    apply(plugin = "com.google.firebase.crashlytics")
    println("Firebase performance and crashlytics plugins applied")
}

This doesn't work because the plugin is required even if the build type is not used
``` groovy
release {
    minifyEnabled true
    signingConfig signingConfigs.release
    manifestPlaceholders = [enableCrashReporting: "true"]
    firebaseCrashlytics { << == required even when the variant is debug build
        mappingFileUploadEnabled = true
        nativeSymbolUploadEnabled = true
        strippedNativeLibsDir = 'build/intermediates/stripped_native_libs/debug/release/lib/'
        unstrippedNativeLibsDir = com.mapbox.gradle.NativeDownloadTask.UNSTRIPPED_NATIVE_LIBS_PATH
    }
}
```

**Comment by kmadsen** [comment]
Capturing an error message when we use an invalid firebase app id

```
E/FirebaseCrashlytics: Error fetching settings.
    java.lang.IllegalArgumentException: Please set your Application ID. A valid Firebase App ID is required to communicate with Firebase server APIs: It identifies your application with Firebase.Please refer to https://firebase.google.com/support/privacy/init-options.
        at com.google.android.gms.common.internal.Preconditions.checkArgument(Unknown Source:35)
        at com.google.firebase.installations.FirebaseInstallations.preConditionChecks(FirebaseInstallations.java:181)
        at com.google.firebase.installations.FirebaseInstallations.getId(FirebaseInstallations.java:240)
        at com.google.firebase.crashlytics.internal.common.IdManager.getCrashlyticsInstallId(IdManager.java:103)
        at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.applyHeadersTo(DefaultSettingsSpiCall.java:184)
        at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:108)
        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:199)
        at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:192)
        at com.google.android.gms.tasks.zzp.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
        at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
        at java.lang.Thread.run(Thread.java:923)
```
