### ISSUE TITLE
OOM exception building really long routes

### ISSUE THREAD

**Issue by yunikkk** [mapbox/mapbox-navigation-android#4153]
**Android API:any
**Mapbox Navigation SDK version:1.4.0

### Steps to trigger behavior

 1. Build long route (thousand of kimoleters)
 2. App crashes randomly, depending on memory of the device. 

Crash happens within [DirectionsJsonObject](https://github.com/mapbox/mapbox-java/blob/master/services-directions-models/src/main/java/com/mapbox/api/directions/v5/models/DirectionsJsonObject.java) at GSON serialization with the following stacktrace : 

```
E/AndroidRuntime(11384): FATAL EXCEPTION: main
E/AndroidRuntime(11384): Process: com.mapbox.nav.gm, PID: 11384
E/AndroidRuntime(11384): java.lang.OutOfMemoryError: Failed to allocate a 3690812 byte allocation with 2202366 free bytes and 2MB until OOM
E/AndroidRuntime(11384): 	at java.lang.String.<init>(String.java:400)
E/AndroidRuntime(11384): 	at java.lang.AbstractStringBuilder.toString(AbstractStringBuilder.java:633)
E/AndroidRuntime(11384): 	at java.lang.StringBuffer.toString(StringBuffer.java:723)
E/AndroidRuntime(11384): 	at java.io.StringWriter.toString(StringWriter.java:100)
E/AndroidRuntime(11384): 	at com.google.gson.Gson.toJson(Gson.java:639)
E/AndroidRuntime(11384): 	at com.google.gson.Gson.toJson(Gson.java:618)
E/AndroidRuntime(11384): 	at com.mapbox.api.directions.v5.models.DirectionsJsonObject.toJson(DirectionsJsonObject.java:30)
E/AndroidRuntime(11384): 	at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl$setRoute$2.invokeSuspend(MapboxNativeNavigatorImpl.kt:150)
E/AndroidRuntime(11384): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(11384): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime(11384): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(11384): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(11384): 	at java.lang.Thread.run(Thread.java:818)
```

From my analysis reason is that nav native implementation accepts route as a single string thus fails if string becomes really large. 
While possible solutions are to pass some Json/Route object entity instead of string, temporary workaround returning some error instead of throwing an exception from background thread would also be nice.

**Comment by Zayankovsky** [comment]
Reproduced in 2.0.0-beta.21 as well.

**Comment by zugaldia** [comment]
Adding it to our next milestone to prioritize an investigation to understand the root cause.

**Comment by Zayankovsky** [comment]
Hey @mapbox/navnative, currently in order to pass a route to the nav native (e.g. for `Navigator.setRoute` or `Navigator.isDifferentRoute`), we have to convert it to a json string. This may lead to `OutOfMemoryError` if the route is really long and the device has little memory available. Can there be any alternative to this? On Android it looks like we can pass objects directly which can then be treated as [`jobject`s](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/types.html), not sure how that would play on iOS though.

**Comment by mskurydin** [comment]
@Zayankovsky the alternative would be to make all platforms use our strongly typed objects that the native part may provide and avoid any JSON object parsing in the platform code. However, there is a number of things that should be made first to make it possible.

**Comment by Zayankovsky** [comment]
@mskurydin is this something we want to eventually come to? If so, we should cut a ticket to discuss it.

**Comment by zugaldia** [comment]
@Zayankovsky we should explore that option (use NN strongly typed objects) as an additional API (we cannot remove the existing one to avoid breaking SEMVER). Could you cut a NN ticket to track that request?
