### ISSUE TITLE
NullPointerException: mapboxNavigation.startNavigation(directionsRoute)

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#420]
Hey,

my setup is:
```
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.4@aar') {
 transitive = true
}
compile('com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT') {
  transitive = true
}
compile('com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.2.0-SNAPSHOT') {
 transitive = false
}
// Used for custom UI and (german) instructions
compile 'com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.6'
compile 'com.mapbox.mapboxsdk:mapbox-android-services:2.2.6'
```

and the code:
```
import com.mapbox.directions.v5.MapboxDirections;
import com.mapbox.directions.v5.models.DirectionsResponse;
import com.mapbox.directions.v5.models.DirectionsRoute;

...

private DirectionsRoute directionsRoute;
private final MapboxNavigation mapboxNavigation;

...

MapboxDirections mapboxDirectionsClient = MapboxDirections.builder()
.origin(Point.fromLngLat(startPosition.getLongitude(), startPosition.getLatitude()))
.destination(Point.fromLngLat(zielPosition.getLongitude(), zielPosition.getLatitude()))
.overview(DirectionsCriteria.OVERVIEW_FULL)
.steps(true)
.profile(routenModus)
.accessToken(Mapbox.getAccessToken())
.roundaboutExits(true)
.overview(DirectionsCriteria.OVERVIEW_FULL)
.build();

...

mapboxNavigation = new MapboxNavigation(context, context.getString(R.string.mapbox_access_token), navigationOptions);

...

DirectionsRoute  directionsRoute = response.body().routes().get(0);
mapboxNavigation.startNavigation(directionsRoute);
```

...results in this exception:
```
10-24 17:12:39.755 ... W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
10-24 17:12:39.756 ... W/System.err:     at com.mapbox.services.android.navigation.v5.milestone.ApiMilestone.isOccurring(ApiMilestone.java:25)
10-24 17:12:39.756 ... W/System.err:     at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.checkMilestones(NavigationHelper.java:171)
10-24 17:12:39.756 ... W/System.err:     at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleRequest(NavigationEngine.java:70)
10-24 17:12:39.756 ... W/System.err:     at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleMessage(NavigationEngine.java:62)
10-24 17:12:39.756 ... W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
10-24 17:12:39.756 ... W/System.err:     at android.os.Looper.loop(Looper.java:154)
10-24 17:12:39.756 ... W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
```

If I commend out `mapboxNavigation.startNavigation(directionsRoute);` everything is "fine".

I don't understand why there is a null pointer, because I receive a valid DirectionsRoute which I can display on the map:
` DirectionsRoute{distance=265909.2, duration=191870.4, geometry=mnfweBkvbkSjU~A|DvKvChIrAhDv]p}@h@BlL@rDJ|GfCjAVzEBfBj@JeIAgRjBcg@dAiI....
`

The differences between my working App from two weeks ago and now are:
- your API changes 
- the use of
```
import com.mapbox.directions.v5.DirectionsCriteria;
import com.mapbox.directions.v5.MapboxDirections;
import com.mapbox.directions.v5.models.DirectionsResponse;
import com.mapbox.directions.v5.models.DirectionsRoute;
import com.mapbox.directions.v5.models.StepManeuver;
```
instead of
```
import com.mapbox.services.api.directions.v5.DirectionsCriteria;
import com.mapbox.services.api.directions.v5.MapboxDirections;
import com.mapbox.services.api.directions.v5.models.DirectionsResponse;
import com.mapbox.services.api.directions.v5.models.DirectionsRoute;
import com.mapbox.services.api.directions.v5.models.StepManeuver;
```
- and I see new dependencies (e.g. mapbox-java-services-directions / mapbox-java-services-turf): 
```
+--- com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT
|    +--- com.mapbox.mapboxsdk:mapbox-android-telemetry:2.2.6 (*)
|    +--- com.mapbox.mapboxsdk:mapbox-android-services:2.2.6 (*)
|    +--- com.mapbox.mapboxsdk:mapbox-java-services-directions:3.0.0-SNAPSHOT
|    |    +--- com.mapbox.mapboxsdk:mapbox-java-services-core:3.0.0-SNAPSHOT
|    |    +--- com.google.code.gson:gson:2.8.0
|    |    +--- com.squareup.retrofit2:retrofit:2.2.0 (*)
|    |    +--- com.squareup.retrofit2:converter-gson:2.2.0 (*)
|    |    \--- com.squareup.okhttp3:logging-interceptor:3.9.0 (*)
|    |    +--- com.mapbox.mapboxsdk:mapbox-java-services-geojson:3.0.0-SNAPSHOT
|    |    +--- com.mapbox.mapboxsdk:mapbox-java-services-core:3.0.0-SNAPSHOT (*)
|    |    \--- com.google.code.gson:gson:2.8.0
|    |    +--- com.squareup.retrofit2:retrofit:2.2.0 (*)
|    |    +--- com.squareup.retrofit2:converter-gson:2.2.0 (*)
|    |    \--- com.squareup.okhttp3:logging-interceptor:3.9.0 (*)
|    +--- com.mapbox.mapboxsdk:mapbox-java-services-turf:3.0.0-SNAPSHOT
|    |    +--- com.mapbox.mapboxsdk:mapbox-java-services-core:3.0.0-SNAPSHOT (*)
|    |    \--- com.mapbox.mapboxsdk:mapbox-java-services-geojson:3.0.0-SNAPSHOT (*)
|    +--- com.android.support:appcompat-v7:26.1.0 (*)
|    \--- com.jakewharton.timber:timber:4.5.1
```

Any suggestions what I'am doing wrong?

**Comment by cammace** [comment]
The crash is occurring because you are using the new default milestone instructions which require your directions request to set `voiceInstructions()` to true. The alternative would be to disable the default milestones. 

I've added a validation check which makes this more clear -> #424
