### ISSUE TITLE
RouteDrawingActivity Error: A line string must have two or more coordinate points

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#4220]
An issue caught by a Robo test https://github.com/mapbox/mapbox-navigation-android/pull/4219 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/11201/workflows/906a1558-9757-402d-b35d-a8fd717155c3/jobs/44549 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/9011542105070413632/executions/bs.2274b47a24acfc95

```
FATAL EXCEPTION: Thread-2
Process: com.mapbox.navigation.examples, PID: 16417
java.lang.RuntimeException: Set source property "data" failed:
Error: A line string must have two or more coordinate points.
Value set: {"type":"Feature","geometry":{"type":"LineString","coordinates":[]}}
	at com.mapbox.maps.extension.style.sources.Source.updateProperty(Unknown Source:75)
	at com.mapbox.maps.extension.style.sources.Source.setProperty$extension_style_release(Unknown Source:16)
	at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.feature(Unknown Source:16)
	at com.mapbox.navigation.examples.util.b$b.onStyleLoaded(Unknown Source:65)
	at com.mapbox.maps.MapboxMap.getStyle(Unknown Source:24)
	at com.mapbox.navigation.examples.util.b.d(Unknown Source:13)
	at com.mapbox.navigation.examples.util.RouteDrawingActivity$d.onClick(Unknown Source:6)
	at android.view.View.performClick(View.java:6597)
	at android.view.View.performClickInternal(View.java:6574)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25885)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.access$100(Tap.java:1)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:19)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Refs. https://github.com/mapbox/mapbox-navigation-android/pull/4148

cc @cafesilencio

**Comment by Guardiola31337** [comment]
While testing https://github.com/mapbox/mapbox-navigation-android/pull/3980 was able to reproduce this consistently 👀 

![examples_route_drawing_activity_crash_fetch_route](https://user-images.githubusercontent.com/1668582/113449762-8fcb2a00-93cc-11eb-876d-718b59d64247.gif)

![examples_route_drawing_activity_crash_clear_points_line](https://user-images.githubusercontent.com/1668582/113449766-922d8400-93cc-11eb-8229-5a2d5bf5508d.gif)

```
2021-04-02 14:36:02.754 24653-24653/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 24653
    java.lang.RuntimeException: Set source property "data" failed:
    Error: A line string must have two or more coordinate points.
    Value set: {"type":"Feature","geometry":{"type":"LineString","coordinates":[]}}
        at com.mapbox.maps.extension.style.sources.Source.updateProperty(Source.kt:99)
        at com.mapbox.maps.extension.style.sources.Source.setProperty$extension_style_release(Source.kt:83)
        at com.mapbox.maps.extension.style.sources.generated.GeoJsonSource.feature(GeoJsonSource.kt:474)
        at com.mapbox.navigation.examples.util.RouteDrawingUtil$clear$1.onStyleLoaded(RouteDrawingUtil.kt:119)
        at com.mapbox.maps.MapboxMap.getStyle(MapboxMap.kt:229)
        at com.mapbox.navigation.examples.util.RouteDrawingUtil.clear(RouteDrawingUtil.kt:118)
        at com.mapbox.navigation.examples.util.RouteDrawingActivity$initListeners$4.onClick(RouteDrawingActivity.kt:137)
        at android.view.View.performClick(View.java:7140)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-04-02 14:36:02.756 24653-24711/? E/FirebaseCrashlytics: Tried to write a fatal exception while no session was open.
```

cc @cafesilencio

**Comment by cafesilencio** [comment]
fixed here: https://github.com/mapbox/mapbox-navigation-android/pull/4225
