### ISSUE TITLE
NullPointerException RouteArrowUtils.obtainArrowPointsFrom(RouteArrowUtils.kt:33) 

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4249]
I rebased a dev branch on the latest `main` changes and hit a crash. Recording here

**Mapbox Navigation SDK version:** v2.0.0-beta.5
### Steps to trigger behavior

 1. During active navigation with waypoints

~I've run it multiple times and am not reproducing~
EDIT: Found a way https://github.com/mapbox/mapbox-navigation-android/issues/4249#issuecomment-818064837

### Actual behavior

```
2021-04-09 18:57:05.762 494-741/? E/SQLiteLog: (1) duplicate column name: EVENT_HOST_APP_VERSION_CODE in "alter table DYNAMIC_DETECTION_CALL_API_COUNTS_LOG add column EVENT_HOST_APP_VERSION_CODE INTEGER"
2021-04-09 18:57:05.845 32666-32703/com.mapbox.navigation.examples E/FirebaseCrashlytics: Tried to write a fatal exception while no session was open.
2021-04-09 18:57:05.846 32666-32666/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 32666
    java.lang.NullPointerException
        at com.mapbox.navigation.ui.maps.route.arrow.RouteArrowUtils.obtainArrowPointsFrom(RouteArrowUtils.kt:33)
        at com.mapbox.navigation.ui.maps.route.arrow.api.MapboxRouteArrowApi.getManeuverArrow(MapboxRouteArrowApi.kt:152)
        at com.mapbox.navigation.ui.maps.route.arrow.api.MapboxRouteArrowApi.addUpcomingManeuverArrow(MapboxRouteArrowApi.kt:127)
        at com.mapbox.navigation.examples.core.MapboxNavigationActivity$routeProgressObserver$1.onRouteProgressChanged(MapboxNavigationActivity.kt:286)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:554)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:55)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.kt:524)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by kmadsen** [comment]
cc: @cafesilencio @LukasPaczos

**Comment by kmadsen** [comment]
Hmm i took a little look, and RouteArrowUtils is assuming non null step points . almost like it could be coming from core
`LineString.fromLngLats(routeProgress.upcomingStepPoints!!)`

speaking with @Guardiola31337 , someone ran into the same crash on beta.5

**Comment by kmadsen** [comment]
found a consistent way to reproduce this. video shows another issue with the maneuver arrow

1. Start "Turn By Turn" examples
2. Long press to a nearby street
3. Start navigation and wait for simulator to arrive
4. Long press a new nearby stop
5. 💥 

![output](https://user-images.githubusercontent.com/3021882/114448256-2a272c80-9b88-11eb-91de-4eb533378a9d.gif)

**Comment by cafesilencio** [comment]
> almost like it could be coming from core

Do you think this is a core issue or should the method not be assuming non-null?

**Comment by kmadsen** [comment]
> > almost like it could be coming from core
> Do you think this is a core issue or should the method not be assuming non-null?

Now that this is easy to reproduce, motivated some more digging. Seems like it's right here, for some reason the upcoming step doesn't have geometry
```
if (upcomingStepIndex < steps.size) {
    val upcomingStep = steps[upcomingStepIndex]
    legProgressBuilder.upcomingStep(upcomingStep)

    val stepGeometry = upcomingStep.geometry()
    stepGeometry?.let {
        routeProgressBuilder.upcomingStepPoints(
            PolylineUtils.decode(
                stepGeometry, /* todo add core dependency PRECISION_6*/
                6
            )
        )
    }
}
```
https://github.com/mapbox/mapbox-navigation-android/blob/97f94b7657965fc435155c014590b2a8f49da8e7/libnavigation-core/src/main/java/com/mapbox/navigation/core/navigator/NavigatorMapper.kt#L248-L261

cc: @Guardiola31337

**Comment by kmadsen** [comment]
I fixed the view crash locally, and this is what happens. It's something weird with re-routing after adding a new waypoint

![output](https://user-images.githubusercontent.com/3021882/114468274-0a9bfe00-9ba0-11eb-9d8b-dc8581aee41a.gif)

**Comment by kmadsen** [comment]
[2021-04-12_22_17_33_2021-04-12_22_19_21_.json.gz](https://github.com/mapbox/mapbox-navigation-android/files/6300121/2021-04-12_22_17_33_2021-04-12_22_19_21_.json.gz)

Here's a history when I was repeating the experience above.
