### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by KayHung** [mapbox/mapbox-navigation-android#4269]
I add this in my layout

> <com.mapbox.navigation.ui.summary.SummaryBottomSheet
>             android:id="@+id/summaryBottomSheet"
>             android:layout_width="match_parent"
>             android:layout_height="wrap_content"
>             android:visibility="gone"
>             app:layout_behavior="com.google.android.material.bottomsheet.BottomSheetBehavior" />

 
show the layout on the Second screen
```
 public MyPresentation extends Presentation{
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setCanceledOnTouchOutside(false);
        setContentView(R.layout.my_layout);
}
```
Then I run app and get error

**Android API:**
**Mapbox Navigation SDK version:1.4.0**

Caused by: android.view.InflateException: Binary XML file line #7 in com.example.carbittest:layout/mapbox_summary_bottomsheet: Binary XML file line #23 in com.example.carbittest:layout/mapbox_partial_summary_peek: Error inflating class <unknown>
     Caused by: android.view.InflateException: Binary XML file line #23 in com.example.carbittest:layout/mapbox_partial_summary_peek: Error inflating class <unknown>
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createView(LayoutInflater.java:776)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:930)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:950)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)

**Comment by KayHung** [comment]
@LukasPaczos Do you have any updates about this issue?

**Comment by LukasPaczos** [comment]
Sorry @KayHung, no updates yet. What is the Android OS version this is reproducible on?

**Comment by KayHung** [comment]
> Sorry @KayHung, no updates yet. What is the Android OS version this is reproducible on?
Android 10/9/7/5.5.1
