### ISSUE TITLE
MapboxMultipleArrowActivity NullPointerException

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4279]
**Mapbox Navigation SDK version:** https://github.com/mapbox/mapbox-navigation-android/pull/4273

https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.2e74b6b076d6fa53/matrices/6735697377542270489/executions/bs.50a4aaa25819e87f

The check-in robo is crashing

```
	at com.mapbox.navigation.examples.core.MapboxMultipleArrowActivity$e.onClick(Unknown Source:81)
     FATAL EXCEPTION: Thread-2
Process: com.mapbox.navigation.examples, PID: 11991
java.lang.NullPointerException
	at com.mapbox.navigation.examples.core.MapboxMultipleArrowActivity$e.onClick(Unknown Source:81)
	at android.view.View.performClick(View.java:6256)
	at android.view.View$PerformClick.run(View.java:24697)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.access$100(Tap.java:1)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:19)
	at androidx.test.espresso.ViewInteraction.access$100(ViewInteraction.java:1)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6541)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by Guardiola31337** [comment]
This https://github.com/mapbox/mapbox-navigation-android/pull/4275 may fixed these.

cc @cafesilencio @LukasPaczos

**Comment by kmadsen** [comment]
ok will make sure to rebase

**Comment by LukasPaczos** [comment]
That the same one.
