### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.addProgressChangeListener

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [mapbox/mapbox-navigation-android#4288]
We are getting random crash on com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6 sdk 

**Android API:**
30 (Android 11)

below are the logs from Sentry : 

`java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.map.NavigationMapboxMap.addProgressChangeListener(com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation)' on a null object reference
    at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigationListeners(NavigationView.java:691)
    at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigation(NavigationView.java:632)
    at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:394)
    at com.bom.mappo.Mapbox.EmbeddedNavigationActivity.startNavigation(EmbeddedNavigationActivity.java:234)
    at com.bom.mappo.Mapbox.EmbeddedNavigationActivity.access$000(EmbeddedNavigationActivity.java:43)
    at com.bom.mappo.Mapbox.EmbeddedNavigationActivity$2.onResponse(EmbeddedNavigationActivity.java:265)
    at com.mapbox.services.android.navigation.v5.navigation.NavigationRouteCallback.onResponse(NavigationRouteCallback.java:30)
    at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:186)
    at retrofit2.DefaultCallAdapterFactory$ExecutorCallbackCall$1.lambda$onResponse$0$DefaultCallAdapterFactory$ExecutorCallbackCall$1(DefaultCallAdapterFactory.java:82)
    at retrofit2.-$$Lambda$DefaultCallAdapterFactory$ExecutorCallbackCall$1$hVGjmafRi6VitDIrPNdoFizVAdk.run
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8512)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

**Comment by LukasPaczos** [comment]
Hey @ghadeeraqraa1992, unfortunately, the `v0.x` versions of the Navigation SDKs are not supported anymore. Please check out https://docs.mapbox.com/android/navigation/guides/ and our migration guides in the wiki - https://github.com/mapbox/mapbox-navigation-android/wiki.
