### ISSUE TITLE
[Mapbox Navigation v2]: Crash on route progress changed

### ISSUE THREAD

**Issue by sandyscoffable** [mapbox/mapbox-navigation-android#4289]
**Android API:** 30
**Mapbox Navigation SDK version:** 2.0.0-beta.6

### Steps to trigger behavior

 1. Specify a Route Progress Observer like: 
 ```kotlin
private val routeProgressObserver = object : RouteProgressObserver {
    override fun onRouteProgressChanged(routeProgress: RouteProgress) {
        viewportDataSource.onRouteProgressChanged(routeProgress)
        ...
     }
 }
```
2. Start navigating a route
3. Finish navigating your route (which works fine), and then request a new route (e.g in the app I'm developing, the driver has an option to return to the start so the app requests a new route to do that)

### Expected behavior

Route should be shown for navigation

### Actual behavior

```
2021-04-20 12:12:15.545 19146-19146/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.XXXXX.YYYYY, PID: 19146
    java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.mapbox.navigation.ui.maps.camera.data.ViewportDataSourceProcessor.getPointsToFrameOnCurrentStep(ViewportDataSourceProcessor.kt:158)
        at com.mapbox.navigation.ui.maps.camera.data.MapboxNavigationViewportDataSource.onRouteProgressChanged(MapboxNavigationViewportDataSource.kt:454)
        at com.XXXXX.YYYYY.fragments.navigation.NavigationFragment$routeProgressObserver$1.onRouteProgressChanged(NavigationFragment.kt:660)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:554)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:55)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.kt:524)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8506)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

I presumably this is due to a race condition in either my code or the SDK. In the meantime, I'm going to put in some sort of safety measure as this is hitting me quite frequently.

**Comment by sandyscoffable** [comment]
I've got a similar-ish bug reported in this issue: https://github.com/mapbox/mapbox-navigation-android/issues/4285

I've pulled out the route manipulation thing I was doing in that issue, so I'm not post processing the route any more (just in case you're wondering)

**Comment by LukasPaczos** [comment]
Hey @sandyscoffable, what is your order of invocation of `MapboxNavigationViewportDataSource#onRouteChanged` and `MapboxNavigationViewportDataSource#onRouteProgressChanged` in this scenario?

Do you see any logs like this:
```
Provided route and navigated route do not have the same UUID.
```

**Comment by sandyscoffable** [comment]
Hi, this happened again this morning (`2.0.0-beta.6`), and I did observe the following immediately before the crash:
```
2021-04-23 11:06:43.964 13696-13696/com.XXXX.YYYY.debug W/MbxViewportDataSource: Provided route and navigated route do not have the same UUID.
```

Crash:
```
2021-04-23 11:06:44.234 13696-13696/com.XXXX.YYYY.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.XXXX.YYYY.debug, PID: 13696
    java.lang.IndexOutOfBoundsException: Index: 7, Size: 2
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.mapbox.navigation.ui.maps.camera.data.ViewportDataSourceProcessor.getPointsToFrameOnCurrentStep(ViewportDataSourceProcessor.kt:158)
        at com.mapbox.navigation.ui.maps.camera.data.MapboxNavigationViewportDataSource.onRouteProgressChanged(MapboxNavigationViewportDataSource.kt:454)
        at com.XXXX.YYYY.fragments.navigation.NavigationFragment$routeProgressObserver$1.onRouteProgressChanged(NavigationFragment.kt:735)
```

👍

**Comment by LukasPaczos** [comment]
I just merged https://github.com/mapbox/mapbox-navigation-android/pull/4302 to make the behavior more robust, but in general, the route that's inside of the `RouteProgress` in `#onRouteProgressChanged` should always exactly match what's been provided via `#onRouteChanged`. Now, the viewport data source will fall back as if there was no route set at all (in the `following` state) if they are mismatched.
