### ISSUE TITLE
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by ghadeeraqraa1992** [mapbox/mapbox-navigation-android#4290]
We are getting the below crash on com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6 sdk under production environment (the version installed from google play)

`android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{f8e4014 u0 com.bom.mappo/com.mapbox.services.android.navigation.v5.navigation.NavigationService}
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2240)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8512)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)`

**Android API:**
30 (Android 11)

**Comment by LukasPaczos** [comment]
Hey @ghadeeraqraa1992, unfortunately, the `v0.x` versions of the Navigation SDKs are not supported anymore. Please check out https://docs.mapbox.com/android/navigation/guides/ and our migration guides in the wiki - https://github.com/mapbox/mapbox-navigation-android/wiki.
