### ISSUE TITLE
Refactor incorrect `CoreRerouteTest` and `RouteAlternativesTest`

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-navigation-android#4429]
An issue caught by an Instrumentation test found while working on https://github.com/mapbox/mapbox-navigation-android/pull/4419 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/12041/workflows/6cc8f997-07d1-49f4-a898-9243e7ace970/jobs/48760 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/5010895745904766073/executions/bs.1e3c7202ff856a89/testcases/2/errors

```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.mapbox.navigation.instrumentation_tests.core.RouteAlternativesTest.expect_faster_route_alternatives(RouteAlternativesTest.kt:79)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
at com.schibsted.spain.barista.rule.cleardata.ClearDatabaseRule$apply$1.evaluate(ClearDatabaseRule.kt:30)
at com.schibsted.spain.barista.rule.cleardata.ClearPreferencesRule$1.evaluate(ClearPreferencesRule.java:26)
at com.schibsted.spain.barista.rule.cleardata.ClearFilesRule$apply$1.evaluate(ClearFilesRule.kt:25)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2074)
```

cc @RingerJK @kmadsen

**Comment by Guardiola31337** [comment]
It seems related to the `RouteAlternativesIdlingResource` and the fact that now (ttps://github.com/mapbox/mapbox-navigation-android/pull/4419) `onStatus` are controlled by NN.

**Comment by kmadsen** [comment]
Looking at the logs, the test is actually looking good.

the integration test should work with new changes of nav-native, because it doesn't mock nav native. 

Are you saying we need to change the behavior of the `RoutesObserver`?

**Comment by kmadsen** [comment]
`RouteAlternativesController` also pulls the `RouteProgress` from the `TripSession`

https://github.com/mapbox/mapbox-navigation-android/blob/540480132c4f7635810e5f978026ffff98182b5a/libnavigation-core/src/main/java/com/mapbox/navigation/core/routealternatives/RouteAlternativesController.kt#L104

^ is the TripSession RouteProgress getting updated?

**Comment by kmadsen** [comment]
The test is failing because 
```
assertTrue(alternativeRouteDuration < durationRemaining)
```

You could add a log in your pull request, to see why those durations are the same. The alternative route is hardcoded to be faster than the current route. Did something change there?

**Comment by Guardiola31337** [comment]
```
2021-05-21 18:52:04.828 6157-6196/com.mapbox.navigation.instrumentation_tests E/PGS: alternativeRouteDuration=320.427 < durationRemaining=296.209
```

**Comment by Guardiola31337** [comment]
Is

> `assertTrue(alternativeRouteDuration < durationRemaining)`

repeatable? I mean, it seems this 

```kotlin
// Prepare with a slow alternative route.
val coordinates = listOf(
    Point.fromLngLat(-121.46685, 38.56301),
    Point.fromLngLat(-121.445697, 38.56707)
)
```

is not always true / valid.

**Comment by kmadsen** [comment]
>  alternativeRouteDuration=320.427 < durationRemaining=296.209

the `alternativeRouteDuration` is supposed to come from a [mocked response](https://github.com/mapbox/mapbox-navigation-android/blob/540480132c4f7635810e5f978026ffff98182b5a/instrumentation-tests/src/main/res/raw/route_response_alternative_start.json#L1). That value comes from a file and is `296.209`

🤔  it seems the values are flipped on your branch. I just tried it again on the main branch and this is what I'm getting
![Screen Shot 2021-05-21 at 1 42 44 PM](https://user-images.githubusercontent.com/3021882/119196037-6dec3c00-ba3a-11eb-86f7-19e5ce2d4bbb.png)

**Comment by kmadsen** [comment]
Looking at the logs, it appears the navigator goes off route. Maybe this is the issue?
https://console.firebase.google.com/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/5658557208547000507/executions/bs.ebe194bc5796461a/testcases/2/logs
```
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
05-21 13:52:29.831: I/PlacesLogger(18887): [PlaceInferenceEngine]: Too few candidate results: percentageOfMissingArea 100 [CONTEXT service_id=253 ]
05-21 13:52:29.843: D/MbxTelemetry(21498): populateNavigationEvent
05-21 13:52:29.844: D/MbxTelemetry(21498): class com.mapbox.navigation.core.telemetry.events.NavigationDepartEvent event sent
05-21 13:52:29.845: D/MbxTelemetry(21498): onOffRouteStateChanged true
05-21 13:52:29.845: D/MbxRerouteController(21498): Fetching route
05-21 13:52:29.862: V/ContextHubHal(705): queryApps
05-21 13:52:29.863: V/ContextHubHal(705): Got nanoapp list response with 6 apps
05-21 13:52:29.863: V/ContextHubHal(705): App 0x476f6f676c00100b ver 0x20004 enabled 1 system 0
05-21 13:52:29.863: V/ContextHubHal(705): App 0x476f6f676c00100e ver 0x1 enabled 1 system 0
05-21 13:52:29.863: V/ContextHubHal(705): App 0x476f6f676c001004 ver 0x40001 enabled 1 system 0
05-21 13:52:29.863: V/ContextHubHal(705): App 0x476f6f676c001011 ver 0x10001 enabled 1 system 0
```

**Comment by kmadsen** [comment]
I'd think it was an issue with the test if it was happening on the `main` line. But those re-routes are not happening there, only on the new dev branch. 

Here is a recent run that shows no `onOffRouteStateChange true` events
https://console.firebase.google.com/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/6604507411565890279/executions/bs.1c57239bab83fea0/testcases/2

**Comment by Guardiola31337** [comment]
Interesting, I cannot reproduce consistently locally. Was wondering if it was because of missing routing tiles but I uninstalled the app and re-run the test and passed 🤔 

Any ideas @DmitryAk?

At the moment we cannot retrieve a history file due to https://github.com/mapbox/mapbox-navigation-android/pull/4478 😬

**Comment by Guardiola31337** [comment]
Last run `AlternativeRouteSelectionTest#selectAlternateRoute` failed https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/4908335199249285018/executions/bs.5c115477058a2782/testcases/6/logs

```
06-07 02:15:38.996: W/System.err(21218): java.lang.AssertionError: expected:<DirectionsRoute{routeIndex=0, distance=1683.8, duration=207.3, durationTypical=null, geometry=mvl`gAnalshFa@iVUuMG}D[{Rq@y`@ScLaB{aA{@gi@[kQGmEIqE[yQ{@uh@aAgl@_@{Ta@qU_Agk@wl@hBiRj@eELag@|AiDJkELimB~FusBlGwAg|@IuDGwDoAwu@GmEsDLcIVooAxDqCHoFPaGP}FPTlN, weight=365.4, weightName=routability, legs=[RouteLeg{distance=1683.8, duration=207.3, durationTypical=null, summary=Fulton Street, 27th Avenue, admins=null, steps=[LegStep{distance=628.0, duration=63.099999999999994, durationTypical=null, speedLimitUnit=mph, speedLimitSign=mutcd, geometry=mvl`gAnalshFa@iVUuMG}D[{Rq@y`@ScLaB{aA{@gi@[kQGmEIqE[yQ{@uh@aAgl@_@{Ta@qU_Agk@, name=Fulton Street, ref=null, destinations=null, mode=driving, pronunciation=null, rotaryName=null, rotaryPronunciation=null, maneuver=StepManeuver{rawLocation=[-122.49348, 37.772151], bearingBefore=0.0, bearingAfter=87.0, instruction=Head east on Fulton Street, type=depart, modifier=null, exit=null}, voiceInstructions=[VoiceInstructions{distanceAlongGeometry=628.0, announcement=Head east on Fulton Street, then turn left onto 27th Avenue, ssmlAnnouncement=<speak><amazon:effect name="drc"><prosody rate="1.08">Head east on Fulton Street, then turn left onto <say-as interpret-as="address">27th</say-as> Avenue</prosody></amazon:effect></speak>}, VoiceInstructions{distanceAlongGeometry=149.3, announcement=Turn left onto 27th Avenue, ssmlAnnouncement=<speak><amazon:effect name="drc"><prosody rate="1.08">Turn left onto <say-as interpret-as="address">27th</say-as> Avenue</prosody></amazon:effect></speak>}], bannerInstructions=[BannerInstructions{distanceAlongGeometry=628.0, primary=BannerText{text=27th Avenue, components=[BannerComponents{text=27th Avenue, type=text, subType=null, abbreviation=27th Ave, abbreviationPriority=0, imageBaseUrl=null, imageUrl=null, directions=null, active=null}], type=turn, modifier=left, degrees=null, drivingSide=null}, secondary=null, sub=null, view=null}], drivingSide=right, weight=107.7, intersections=[StepIntersection{rawLocation=[-122.49348, 37.772151], bearings=[87], classes=null, entry=[true], in=null, out=0, lanes=null, geometryIndex=null, isUrban=null, adminIndex=null, restStop=null, tollCollection=null, mapboxStreetsV8=null, tunnelName=null}, StepIntersection{rawLocation=[-122.492777, 37.772183], bearings=[0, 90, 270], classes=null, entry=[true, true, false], in=2, out=1, lanes=null, geometryIndex=null, isUrban=null, adminIndex=null, restStop=null, tollCollection=null, mapboxStreetsV8=null, tunnelName=null}, StepIntersection{rawLocation=[-122.491708, 37.772232], bearings=[0, 90, 270], classes=null, entry=[true, true, false], in=2, out=1, lanes=null, geometryIndex=null, isUrban=null, adminIndex=null, restStop=null, tollCollection=null, mapboxStreetsV8=null, tunnelName=null}, StepIntersection{rawLocation=[-122.490638, 37.772281], bearings=[0, 90, 270], classes=null, entry=[true, true, false], in=2, out=1, lanes=null, geometryIndex=null, isUrban=null, adminIndex=null, restStop=null, tollCollection=null, mapboxStreetsV8=null, tunnelName=null}, StepIntersection{rawLocation=[-122.489565, 37.772329], bearings=[0, 90, 180, 270], classes=null, entry=[true, true, true, false], in=3, out=1, lanes=null, geometryIndex=null, isUrban=null, adminIndex=null, restStop=null, tollCollection=null, mapboxStreetsV8=null, tunnelName=null}, StepIntersection{rawLocation=[-122.488492, 37.772378], bearings=[0, 90, 270], classes=null, entry=[true, true, false], in=2, out=1, lanes=null, geometryIndex=null, isUrban=null, adminIndex=null, restStop=null, tollCollection=null, mapboxStreetsV8=null, tunnelName=null}, StepIntersection{rawLocation=[-122.487418, 37.772427], bearings=[0, 90, 270], classes=null, entry=[true, true, false], in=2, out=1, lanes=null, geometryIndex=null, isUrban=null, adminIndex=null, restStop=null, tollCollection=null, mapboxStreetsV8=null, tunnelName=null}], exits=null}, LegStep{distance=623.9, duration=72.3, durationTypical=null, speedLimitUnit=mph, speedLimitSign=mutcd, geometry=wjm`gAxc~rhFwl@hBiRj@eELag@|AiDJk
06-07 02:15:38.997: W/System.err(21218): 	at org.junit.Assert.fail(Assert.java:89)
06-07 02:15:38.997: W/System.err(21218): 	at org.junit.Assert.failNotEquals(Assert.java:835)
06-07 02:15:38.997: W/System.err(21218): 	at org.junit.Assert.assertEquals(Assert.java:120)
06-07 02:15:38.997: W/System.err(21218): 	at org.junit.Assert.assertEquals(Assert.java:146)
06-07 02:15:38.997: W/System.err(21218): 	at com.mapbox.navigation.instrumentation_tests.ui.routeline.AlternativeRouteSelectionTest$selectAlternateRoute$1$2.onRouteProgressChanged(AlternativeRouteSelectionTest.kt:127)
06-07 02:15:38.997: W/System.err(21218): 	at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:557)
06-07 02:15:38.997: W/System.err(21218): 	at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:55)
06-07 02:15:38.997: W/System.err(21218): 	at com.mapbox.navigation.core.trip.session.MapboxTripSession$navigatorObserver$1.onStatus(MapboxTripSession.kt:217)
06-07 02:15:38.997: W/System.err(21218): 	at android.os.MessageQueue.nativePollOnce(Native Method)
06-07 02:15:38.997: W/System.err(21218): 	at android.os.MessageQueue.next(MessageQueue.java:326)
06-07 02:15:38.997: W/System.err(21218): 	at java.lang.reflect.Method.invoke(Native Method)
06-07 02:15:38.997: W/System.err(21218): 	at androidx.test.espresso.base.Interrogator.getNextMessage(Interrogator.java:199)
06-07 02:15:38.997: W/System.err(21218): 	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:140)
06-07 02:15:38.997: W/System.err(21218): 	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:519)
06-07 02:15:38.997: W/System.err(21218): 	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:441)
06-07 02:15:38.997: W/System.err(21218): 	at androidx.test.espresso.Espresso$1.run(Espresso.java:277)
06-07 02:15:38.997: W/System.err(21218): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
06-07 02:15:38.997: W/System.err(21218): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
06-07 02:15:38.997: W/System.err(21218): 	at android.os.Handler.handleCallback(Handler.java:873)
06-07 02:15:38.998: W/System.err(21218): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-07 02:15:38.998: W/System.err(21218): 	at android.os.Looper.loop(Looper.java:193)
06-07 02:15:38.998: W/System.err(21218): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
06-07 02:15:38.998: W/System.err(21218): 	at java.lang.reflect.Method.invoke(Native Method)
06-07 02:15:38.998: W/System.err(21218): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
06-07 02:15:38.998: W/System.err(21218): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
06-07 02:15:39.000: E/libc++abi(21218): terminating with uncaught exception of type jni::PendingJavaException
```

Noting that It's not failing locally.

**Comment by DmitryAk** [comment]
@Guardiola31337 I don't see how this error could be related to callback approach.
`at com.mapbox.navigation.testing.ui.http.MockWebServerRule$1.dispatch(MockWebServerRule.kt:46)` - what is this `MockWebServer` ?
As I can understand, it is failing because of missing handler `/directions/v5/mapbox/driving-traffic/-77.03195,38.896099;-77.030923,38.895433?access_token=pk.1234&geometries=polyline6&overview=full&steps=true&bearings=0%2C90%3B&continue_straight=true&annotations=congestion%2Cmaxspeed%2Cspeed%2Cduration%2Cdistance%2Cclosure&language=en&roundabout_exits=true&voice_instructions=true&banner_instructions=true&voice_units=imperial&enable_refresh=true&sku=1083rxbyZc3f577850e0d18ee0564e7c138345b7e46
    is not handled.`
Maybe, it is required to review the test and mock handlers?

**Comment by Guardiola31337** [comment]
@DmitryAk if there's a reroute request then that won't be handled by the mock web server, the problem is why are these unexpected off-routes happening while they don't in `main` i.e. callback vs polling approach 🤔

**Comment by Guardiola31337** [comment]
Tested multiple times on `main` and this is what I got:

```
2021-06-08 13:37:24.224 32306-32345/com.mapbox.navigation.instrumentation_tests E/PGS: PGS reroute_completes
2021-06-08 13:37:24.477 32306-32306/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=INVALID
2021-06-08 13:37:24.481 32306-32306/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=INVALID
2021-06-08 13:37:24.619 32306-32306/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:25.688 32306-32306/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:26.674 32306-32306/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:27.767 32306-32306/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=OFF_ROUTE
2021-06-08 13:37:28.050 32306-32306/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING


2021-06-08 13:37:33.283 32488-32527/com.mapbox.navigation.instrumentation_tests E/PGS: PGS expect_faster_route_alternatives
2021-06-08 13:37:33.839 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:33.848 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:33.856 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:34.677 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:35.696 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:36.893 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:37.782 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:38.700 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:39.724 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:40.742 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:42.702 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:37:43.718 32488-32488/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
```

So the issue is for `reroute_completes` is a missing [`TRACKING`](https://github.com/mapbox/mapbox-navigation-android/blob/e966c66a3082ea23c62311729b7a3716cba33858/instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/CoreRerouteTest.kt#L98) and then an unexpected `OFF_ROUTE` for `expect_faster_route_alternatives` (also look at the diff between `INITIALIZED` vs `TRACKING`).

Noting that I was able to repro the `reroute_completes failure` but not the `expect_faster_route_alternatives`. Similar logs as above:

```
2021-06-08 13:45:47.690 5870-5909/com.mapbox.navigation.instrumentation_tests E/PGS: PGS reroute_completes
2021-06-08 13:45:47.925 5870-5870/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=INVALID
2021-06-08 13:45:47.929 5870-5870/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=INVALID
2021-06-08 13:45:48.065 5870-5870/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:45:49.132 5870-5870/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:45:50.161 5870-5870/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:45:51.224 5870-5870/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=OFF_ROUTE
2021-06-08 13:45:55.843 6041-6082/com.mapbox.navigation.instrumentation_tests E/PGS: PGS expect_faster_route_alternatives
2021-06-08 13:45:56.405 6041-6041/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:45:56.419 6041-6041/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:45:57.344 6041-6041/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:45:58.313 6041-6041/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:45:59.319 6041-6041/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:46:00.418 6041-6041/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:46:01.286 6041-6041/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:46:02.333 6041-6041/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:46:03.316 6041-6041/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:46:05.278 6041-6041/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-08 13:46:06.351 6041-6041/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
```

cc @DmitryAk @mskurydin @SiarheiFedartsou

**Comment by Guardiola31337** [comment]
Rebased https://github.com/mapbox/mapbox-navigation-android/pull/4419 from `main` and can't reproduce consistently locally anymore 🤔 

Now I'm getting that `TRACKING` status, most of the times...

```
2021-06-14 14:50:52.011 32005-32045/com.mapbox.navigation.instrumentation_tests E/PGS: PGS reroute_completes
2021-06-14 14:50:52.347 32005-32005/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=INVALID
2021-06-14 14:50:52.539 32005-32005/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-14 14:50:53.578 32005-32005/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-14 14:50:54.571 32005-32005/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
2021-06-14 14:50:55.613 32005-32005/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=OFF_ROUTE
2021-06-14 14:50:55.905 32005-32005/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=INITIALIZED
2021-06-14 14:50:56.596 32005-32005/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=INITIALIZED
2021-06-14 14:50:58.613 32005-32005/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=INITIALIZED
2021-06-14 14:50:59.600 32005-32005/com.mapbox.navigation.instrumentation_tests E/PGS: PGS routeState=TRACKING
```

**Comment by Guardiola31337** [comment]
> Rebased https://github.com/mapbox/mapbox-navigation-android/pull/4419 from `main` and can't reproduce consistently locally anymore 🤔 

https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/8865001394225981595/executions/bs.a18096e1a239f8b4

CI didn't reproduce `reroute_completes` `expect_faster_route_alternatives` failures. It reproduced https://github.com/mapbox/mapbox-navigation-android/issues/4429#issuecomment-855772383 which is also failing sometimes in other PRs targeting `main`.

**Comment by mskurydin** [comment]
Can we capture a history recording for the test? 

This would give us the full context and allow to understand the reasons behind the off-route. The initialized state after off-route may mean we are a bit too far from the route (but not too far). My guess - there is a map-matching error and we snap to some edge that is quite far. The SDK takes the location from this enhanced location as the origin for a new route. After the route is set, it takes a few seconds to reach some location on a new route.

**Comment by Guardiola31337** [comment]
Experimented a bit on how to make `reroute_completes` more robust and deterministic in https://github.com/mapbox/mapbox-navigation-android/tree/pg-core-reroute-test-refactor

Current problem:

- We don't know with certainty what is going to be the off-route origin point as we don't know when the `OFF_ROUTE` event is going to be emitted and the re-route requested and handled by MockWebServer. Was experimenting with `omitCoordinates` but test was still flaky (even other tests started to fail randomly). I'm starting to think if it could be an issue with MockWebServer not handling all the requests or if there are some unexpected requests that are not being added to the handler and therefore the expected requests are not handled.

We should refactor these tests and how MockWebServer handles internal requests for these kind of scenarios. Let's use this ticket to keep track of this work.

**Comment by Guardiola31337** [comment]
Noting that `RouteAlternativesTest AssertionError` was addressed by https://github.com/mapbox/mapbox-navigation-android/pull/4527 Going to change OP description to reflect what's this ticket tracking now.

cc @kmadsen

**Comment by Guardiola31337** [comment]
@kmadsen BTW rebased https://github.com/mapbox/mapbox-navigation-android/pull/4419 from `main` after https://github.com/mapbox/mapbox-navigation-android/pull/4527 and test failed again https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/4668431245650952651/executions/bs.6e9713f03e37489e/testcases/3

**Comment by Guardiola31337** [comment]
@kmadsen Another instance of `expect_faster_route_alternatives` test failing https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/8780689655655725505/executions/bs.fd5511d87b59e88f/testcases/3/errors

**Comment by Guardiola31337** [comment]
Noting that `reroute_completes` failed in https://github.com/mapbox/mapbox-navigation-android/pull/4558 https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/8537049470456065458/executions/bs.efc3cbfd1f5101bb/testcases/1/logs

**Comment by Guardiola31337** [comment]
Interesting 🤔 

Run into `verify_history_files_are_recorded_and_readable` test failure https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/6580013920275794138/executions/bs.996e4138806a0416/testcases/2/errors (https://github.com/mapbox/mapbox-navigation-android/pull/4482 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/12577/workflows/661a4eec-4908-4c14-bf88-a6744ae22de2/jobs/51374)

cc @kmadsen
