### ISSUE TITLE
Provide Android SDK wrapper classes around native classes

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4441]
Downstream unit tests require wrapper objects in order to use the native objects. 

For example, after including https://github.com/mapbox/mapbox-navigation-android/pull/4408. Downstream unit tests will run into this `UnsatisfiedLinkError`
```
java.lang.UnsatisfiedLinkError: com.mapbox.common.TileStore.getInstance()Lcom/mapbox/common/TileStore;

	at com.mapbox.common.TileStore.getInstance(Native Method)
	at com.mapbox.navigation.base.internal.tilestore.TileStoreProvider.getDefaultTileStoreInstance(TileStoreProvider.kt:7)
	at com.mapbox.navigation.base.options.RoutingTilesOptions$Builder.<init>(RoutingTilesOptions.kt:115)
	at com.mapbox.******.settings.RoutingTilesOptionsProvider.provide(RoutingTilesOptionsProvider.kt:15)
	at com.mapbox.******.map.presentation.optionproviders.OptionProvidersTest.checkTileStorePathIsTheSame(OptionProvidersTest.kt:67)
...
```

**Comment by kmadsen** [comment]
cc: @korshaknn

**Comment by korshaknn** [comment]
@kmadsen there is a TilestoreProvider wrapper. Mock it when you need.

**Comment by kmadsen** [comment]
OK the solution for testing with `mockk` is to do this.

``` kotlin
    @Before
    fun setup() {
        mockkObject(TileStoreProvider)
        every { TileStoreProvider.getDefaultTileStoreInstance() } returns mockk()
        every { TileStoreProvider.getTileStoreInstance(any()) } returns mockk()
    }

    @After
    fun teardown() {
        unmockkObject(TileStoreProvider)
    }
```
