### ISSUE TITLE
StackOverflowError when canceling animation in the NavigationCamera

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4453]
**Mapbox Navigation SDK version:** v2.0.0-beta.11

```
Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at java.util.HashMap.put(HashMap.java:385)
       at java.util.HashSet.add(HashSet.java:95)
       at dalvik.system.MarmotUtil.Log(MarmotUtil.java:26)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.cancelAnimation(NavigationCamera.java:389)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToIdle(NavigationCamera.java:318)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera$createTransitionListener$1.onAnimationEnd(NavigationCamera.java:434)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.cancelAnimation(NavigationCamera.java:384)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToIdle(NavigationCamera.java:318)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera$createTransitionListener$1.onAnimationEnd(NavigationCamera.java:434)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.cancelAnimation(NavigationCamera.java:384)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToIdle(NavigationCamera.java:318)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera$createTransitionListener$1.onAnimationEnd(NavigationCamera.java:434)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.cancelAnimation(NavigationCamera.java:384)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToIdle(NavigationCamera.java:318)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera$createTransitionListener$1.onAnimationEnd(NavigationCamera.java:434)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.cancelAnimation(NavigationCamera.java:384)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToIdle(NavigationCamera.java:318)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera$createTransitionListener$1.onAnimationEnd(NavigationCamera.java:434)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.cancelAnimation(NavigationCamera.java:384)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToIdle(NavigationCamera.java:318)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera$createTransitionListener$1.onAnimationEnd(NavigationCamera.java:434)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.cancelAnimation(NavigationCamera.java:384)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToIdle(NavigationCamera.java:318)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera$createTransitionListener$1.onAnimationEnd(NavigationCamera.java:434)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.cancelAnimation(NavigationCamera.java:384)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToIdle(NavigationCamera.java:318)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera$createTransitionListener$1.onAnimationEnd(NavigationCamera.java:434)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.cancelAnimation(NavigationCamera.java:384)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToIdle(NavigationCamera.java:318)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera$createTransitionListener$1.onAnimationEnd(NavigationCamera.java:434)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.cancelAnimation(NavigationCamera.java:384)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToIdle(NavigationCamera.java:318)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera$createTransitionListener$1.onAnimationEnd(NavigationCamera.java:434)
       at android.animation.AnimatorSet.cancel(AnimatorSet.java:341)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.cancelAnimation(NavigationCamera.java:384)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.startAnimation(NavigationCamera.java:393)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToOverview(NavigationCamera.java:292)
       at com.mapbox.navigation.ui.maps.camera.NavigationCamera.requestNavigationCameraToOverview$default(NavigationCamera.java:279)
```

**Comment by VitaminPSG** [comment]
Do we have updates regarding this issue? GM app constantly crashing during animation update

**Comment by LukasPaczos** [comment]
@VitaminPSG sorry, no updates just yet. Could you shed a little bit more light on how are you running into this issue? Do you have a reproducible example? Could you give an example of how you are interacting with the `NavigationCamera` or the Map camera in general to trigger this?

**Comment by yuryybk** [comment]
@LukasPaczos pls check the code from the GM Navigation app

https://github.com/mapbox/gm-navigation-app/blob/develop/map/src/main/java/com/mapbox/nav/gm/map/presentation/ui/MapFragment.kt#L594

App crashes when animation is interrupted by another animation. 
From the user perspective, the app crashes when the user selects the destination point with the long-tap, then the user observes the camera transition to Overview mode to see the whole route, and then quickly tap on the "Navigate" button to switch to Active Guidance mode without waiting for the end of the Overview animation.

It is NavigationCamera crash inside, seems nothing related to Maps.
Also, it is reproduced 100% for the described use-case, so I can provide any additional info if required.

**Comment by yuryybk** [comment]
@LukasPaczos did you have a chance to reproduce the issue? do you need any additional info?
