### ISSUE TITLE
ConcurrentModificationException in MapboxRouteLineUtils

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#4483]
**Mapbox Navigation SDK version:** `v2.0.0-beta.13`
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.ArrayList$Itr.next(ArrayList.java:860)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils.getTrafficLineExpression$libnavui_maps_release(MapboxRouteLineUtils.java:895)
       at com.mapbox.navigation.ui.maps.route.line.api.VanishingRouteLine.getTraveledRouteLineExpressions$libnavui_maps_release(VanishingRouteLine.java:173)
       at com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineApi.updateTraveledRouteLine(MapboxRouteLineApi.java:279)
       at com.mapbox.onetap.map.presentation.ui.RouteLineBinder$3.onIndicatorPositionChanged(RouteLineBinder.java:61)
       at com.mapbox.maps.plugin.locationcomponent.LocationComponentPluginImpl$indicatorPositionChangedListener$1.onIndicatorPositionChanged(LocationComponentPluginImpl.java:68)
       at com.mapbox.maps.plugin.locationcomponent.animators.PuckPositionAnimator.updateLayer(PuckPositionAnimator.java:10)
       at com.mapbox.maps.plugin.locationcomponent.animators.PuckPositionAnimator.updateLayer(PuckPositionAnimator.java:6)
       at com.mapbox.maps.plugin.locationcomponent.animators.PuckAnimator$1.onAnimationUpdate(PuckAnimator.java:31)
       at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1566)
       at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1357)
       at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1489)
       at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
       at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
       at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
       at android.view.Choreographer.doCallbacks(Choreographer.java:796)
       at android.view.Choreographer.doFrame(Choreographer.java:727)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7766)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```
cc @cafesilencio

**Comment by zugaldia** [comment]
@cafesilencio Are you looking into this one? I'd like to prioritize it considering it's a release blocker.

**Comment by cafesilencio** [comment]
I have not seen that this issue is reproducible but the changes I made in this PR: https://github.com/mapbox/mapbox-navigation-android/pull/4489/  I think further protect from this kind of error occurring.
