### ISSUE TITLE
Crashed after updating navigation SDK with latest version

### ISSUE THREAD

**Issue by jkpatel1463** [mapbox/mapbox-navigation-android#4496]
Hello there

Here is crashlog after updating navigation SDK. Crashlog and crucial information attached in the issues:

```
Fatal Exception: java.lang.NullPointerException
       at android.content.res.XmlBlock.nativeGetStyleAttribute(XmlBlock.java)
       at android.content.res.XmlBlock.access$1500(XmlBlock.java:41)
       at android.content.res.XmlBlock$Parser.getStyleAttribute(XmlBlock.java:459)
       at android.content.res.Resources$Theme.getExplicitStyle(Resources.java:1778)
       at android.view.View.retrieveExplicitStyle(View.java:6102)
       at android.view.View.<init>(View.java:5241)
       at android.widget.TextView.<init>(TextView.java:974)
       at android.widget.TextView.<init>(TextView.java:968)
       at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:102)
       at com.mapbox.navigation.ui.maneuver.view.MapboxExitText.<init>(MapboxExitText.kt:29)
       at com.mapbox.navigation.ui.maneuver.view.MapboxPrimaryManeuver.render(MapboxPrimaryManeuver.kt:38)
       at com.mapbox.navigation.ui.maneuver.view.MapboxManeuverView.renderPrimaryManeuver(MapboxManeuverView.kt:257)
       at com.mapbox.navigation.ui.maneuver.view.MapboxManeuverView.drawManeuver(MapboxManeuverView.kt:385)
       at com.mapbox.navigation.ui.maneuver.view.MapboxManeuverView.renderManeuver$lambda-3(MapboxManeuverView.kt:110)
       at com.mapbox.navigation.ui.maneuver.view.MapboxManeuverView.lambda$TxE4O8XEjcDdH0V317Tok68T5CM()
       at com.mapbox.navigation.ui.maneuver.view.-$$Lambda$MapboxManeuverView$TxE4O8XEjcDdH0V317Tok68T5CM.run(:4)
       at com.mapbox.bindgen.Expected.onValue(Expected.java:145)
       at com.mapbox.navigation.ui.maneuver.view.MapboxManeuverView.renderManeuver(MapboxManeuverView.kt:109)
       at com.app.activity.AppNavigationActivity.bannerInstructionsObserver$lambda-14$lambda-13(AppNavigationActivity.kt:656)
       at com.app.activity.AppNavigationActivity.lambda$lxC_KQuUxP-PKU_fN8px9lqhDHI()
       at com.app.activity.-$$Lambda$AppNavigationActivity$lxC_KQuUxP-PKU_fN8px9lqhDHI.onManeuver(:2)
       at com.mapbox.navigation.ui.maneuver.api.MapboxManeuverApi$getManeuver$1.invokeSuspend(MapboxManeuverApi.kt:61)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:7590)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

**Android API: Android 10**
**Model:Xiaomi Redmi Note 7S**
**Mapbox Navigation SDK version: Mapbox Navigation SDK 2.0.0-beta.14**

### Steps to trigger behavior
 Here is the link of video for steps. Please take a look at the video:
https://www.dropbox.com/s/6uxte4plsd0m2nh/Screenrecorder-2021-06-14-01-16-28-944.mp4?dl=0

### Expected behavior
-> Example should run without crash

### Actual behavior
-> Example crashed.

**Comment by LukasPaczos** [comment]
cc @abhishek1508 for visibility

**Comment by geografa** [comment]
@jkpatel1463 can you tell us if this is happening just for the top `Turn by Turn` example or others as well? Are you simulating the GPS position on the actual device or using your true position on the device?

**Comment by jkpatel1463** [comment]
can you tell us if this is happening just for the top Turn by Turn example or others as well? Yes, It causes issues in turn by turn navigation. 

Are you simulating the GPS position on the actual device or using your true position on the device?
I didn't understood this questions. Please take a look at video. If you need input, I can send you.

**Comment by jkpatel1463** [comment]
Hello 

Above crash fix in some device, While below device have still crash. We executed same code on different device, Some device has working for same input while below device produce crash for same input, same code. (We have updated Navigation sdk to latest version mentioned by you.) Below, I have attached video and device information:
1. Device model: MI-Redmi Note 7S
2. DeviceOS: Android 10

Video's link is attached in this message. Hope it will help you to identify issues.
https://www.dropbox.com/s/5cgu7nstcwgzxic/Screenrecorder-2021-06-23-15-31-47-715%280%29%20%281%29.mp4?dl=0

Thank you
JK Patel

**Comment by geografa** [comment]
@jkpatel1463 thank you for confirming that this so far is specific to this device. The other issue I wanted to clarify is whether or not the issue was specific to the example you chose from the menu:
![image](https://user-images.githubusercontent.com/134753/124042926-c3632380-d9be-11eb-8306-a67b45d879fc.png)

Or are you able to replicate this with this example: https://docs.mapbox.com/android/beta/navigation/examples/basic/

**Comment by jkpatel1463** [comment]
Hello @geografa 

We do not aware about other example. We do not need those examples. 

About Basic Example:
Our shared video & crash log doesn't enough to get idea about crash?

**Comment by abhishek1508** [comment]
@jkpatel1463 
Thanks for reporting the issue. After looking more into it, I could verify the problem is not in the SDK but it is in the device settings. 

#### Android version crash is happening
- Android 10 and above

#### Reason for crash

##### On emulator Android 9 (API 28)
Go to Device Settings > System > About emulated device > Scroll down and tap on Build Number 10 times > Go back to System > You should now see Developer Options

Go to Developer Options > Scroll down until you find `Enable view attribute inspection` > Switch it off.
Refer the image below
<img src="https://user-images.githubusercontent.com/9770186/133480298-7cd13a02-fe29-4082-844a-2214a8009294.png" width="250" />


##### On device
Go to Device Settings > Find **About Phone** (It should either be inside `System` or directly in Device Settings) > Scroll down and tap on Build Number 10 times > Go back > Go to System > Click on Advanced > You should now see Developer Options. Find `Enable view attribute inspection` and switch it off

_Note: For every device the steps might not be the same, but on a nutshell you need to find the `Build Number` first and `tap on it 10 times`. Once done, you should look for `Developer Options` and switch off `Enable view attribute inspection`._

With this `Enable view attribute inspection` turned **on** the example is crashing, but it is not if I switch it off.

This is not a permanent solution, but meanwhile we figure out how to resolve it, you could use this workaround if you already haven't tried.

/cc @zugaldia @LukasPaczos
