### ISSUE TITLE
Flaky AlternativeRouteSelectionTest

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4510]
https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/8551698089535676672/executions/bs.26c3669f44daf21a

Not to be confused with https://github.com/mapbox/mapbox-navigation-android/issues/4429
Because `RouteAlternativesTest` is a different test

```
snappingClosures=null}, voiceLanguage=en-US}>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)
	at com.mapbox.navigation.instrumentation_tests.ui.routeline.AlternativeRouteSelectionTest$selectAlternateRoute$1$2.onRouteProgressChanged(AlternativeRouteSelectionTest.kt:127)
	at com.mapbox.navigation.core.trip.session.MapboxTripSession.updateRouteProgress(MapboxTripSession.kt:611)
	at com.mapbox.navigation.core.trip.session.MapboxTripSession.access$updateRouteProgress(MapboxTripSession.kt:58)
	at com.mapbox.navigation.core.trip.session.MapboxTripSession$updateDataFromNavigatorStatus$updateNavigatorStatusDataJob$1.invokeSuspend(MapboxTripSession.kt:581)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:148)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:519)
	at androidx.test.espresso.base.UiControllerImpl.loopMainThreadUntilIdle(UiControllerImpl.java:441)
	at androidx.test.espresso.Espresso$1.run(Espresso.java:277)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by kmadsen** [comment]
cc: @cafesilencio would you have an idea what is causing this?

**Comment by cafesilencio** [comment]
I usually just re-run the test.  It seems to occasionally fail in landscape mode. I've never noticed it fail in portrait mode.

**Comment by kmadsen** [comment]
> I usually just re-run the test. It seems to occasionally fail in landscape mode. I've never noticed it fail in portrait mode.

Any idea what is causing it? Ideally we can make it give zero false negatives. I've had a few unexpected issues in the instrumentation tests I've made too, so am wanting to get to the bottom of this one

**Comment by Guardiola31337** [comment]
Run into this one too https://github.com/mapbox/mapbox-navigation-android/issues/4429#issuecomment-855772383

**Comment by Guardiola31337** [comment]
Capturing from https://github.com/mapbox/mapbox-navigation-android/pull/4934#issuecomment-934431362

> @kmadsen look at this `expect_faster_route_alternatives` failure https://console.firebase.google.com/u/1/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/6858594384686128148/executions/bs.3c7d5f111c9ce17d caught in https://github.com/mapbox/mapbox-navigation-android/pull/4942 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/14168/workflows/5a8d3549-5e65-43f7-9d98-6abcdf7604c2/jobs/59701 It seems that https://github.com/mapbox/mapbox-navigation-android/blob/11e5a1303670c07cfe154d302f799ffd5002b8d8/instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/MapboxHistoryTest.kt#L68-L71 was taken from `RouteAlternativesTest` for some reason and 2 `setRoute` events were generated, making the test assertion https://github.com/mapbox/mapbox-navigation-android/blob/11e5a1303670c07cfe154d302f799ffd5002b8d8/instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/core/RouteAlternativesTest.kt#L113 to fail https://github.com/mapbox/mapbox-navigation-android/blob/67b139faead09106662cc916afd105a48e4b2085/instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/idling/RouteAlternativesIdlingResource.kt#L16-L17
>
> We should keep iterating these tests to make them more robust and consistent.

Refs. https://github.com/mapbox/mapbox-navigation-android/pull/4726

Re-opening here.

**Comment by Guardiola31337** [comment]
Probably we should push a relevant location update as part of the `setup` of each test so it gets refreshed on each run.

**Comment by kmadsen** [comment]
Is this test flaky? Or should we discuss "how we want to implement warming-up instrumentation tests GPS coordinate"

**Comment by Guardiola31337** [comment]
> Is this test flaky?

It is indeed.

> look at this `expect_faster_route_alternatives` failure https://console.firebase.google.com/u/1/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/6858594384686128148/executions/bs.3c7d5f111c9ce17d caught in https://github.com/mapbox/mapbox-navigation-android/pull/4942 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/14168/workflows/5a8d3549-5e65-43f7-9d98-6abcdf7604c2/jobs/59701

**Comment by kmadsen** [comment]
Yeah you're right, considering that devices will run multiple tests. The gps system is a state that can influence test to test.

Considering this is an issue for all tests it would be good to require an initialization location from anything using BaseTest
