### ISSUE TITLE
Incompatibility between navigation:ui and mapbox-search

### ISSUE THREAD

**Issue by xerna01** [mapbox/mapbox-navigation-android#4602]
I'm using the navigation ui inside my application with fixed routes so I didn't need search api and everything worked fine.
Now i was trying to use reverse geocoding in another module of the application but when i add the 
`    implementation "com.mapbox.search:mapbox-search-android:1.0.0-beta.15" `  dependency the navigator ui module stop to work.
Instantly when the navigation starts it crashes with the following error:

```
E/MapboxNavNative: User defined HTTP service instance not provided from the module implementation.
    Module: com.mapbox.common.module.okhttp.MapboxOkHttpService@2a87d1e
    but present is: com.mapbox.common.module.okhttp.MapboxOkHttpService@2a87d1e
    Are you calling HttpServiceFactory.setUserDefined() correctly?
E/Mbgl-MapChangeReceiver: Exception in onDidFinishLoadingStyle
    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common14OfflineService16registerObserverERKNSt6__ndk110shared_ptrINS0_22OfflineServiceObserverEEE" referenced by "/data/app/eu.mediator.hmi.cluster2-AYHL7EU1TVk6gOeJyL9xFA==/lib/x86/libnavigator-android.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.mapbox.navigator.NavNativeStaticInitializer$Companion.loadRequiredDependencies(NavNativeStaticInitializer.kt:45)
        at com.mapbox.navigator.NavNativeStaticInitializer.loadRequiredDependencies(Unknown Source:2)
        at com.mapbox.navigator.Navigator.<clinit>(Navigator.java:14)
        at com.mapbox.navigation.navigator.internal.NavigatorLoader.createNavigator(NavigatorLoader.kt:24)
        at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl.create(MapboxNativeNavigatorImpl.kt:64)
        at com.mapbox.navigation.core.NavigationComponentProvider.createNativeNavigator(NavigationComponentProvider.kt:32)
        at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:171)
        at com.mapbox.navigation.ui.NavigationViewModel.initializeNavigation(NavigationViewModel.java:437)
        at com.mapbox.navigation.ui.NavigationViewModel.initialize(NavigationViewModel.java:220)
        at com.mapbox.navigation.ui.NavigationView.initializeNavigation(NavigationView.java:935)
        at com.mapbox.navigation.ui.NavigationView.startNavigation(NavigationView.java:497)
        at eu.mediator.hmi.cluster2.navigator.BlankFragment.onNavigationReady$lambda-2(NavigatorLaunchedFragment.kt:188)
        at eu.mediator.hmi.cluster2.navigator.BlankFragment.lambda$ResbqNSyGHHngWXEf0J8_C3jcOE(Unknown Source:0)
        at eu.mediator.hmi.cluster2.navigator.-$$Lambda$BlankFragment$ResbqNSyGHHngWXEf0J8_C3jcOE.onChanged(Unknown Source:6)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
        at androidx.lifecycle.LiveData.observe(LiveData.java:205)
        at eu.mediator.hmi.cluster2.navigator.BlankFragment.onNavigationReady(NavigatorLaunchedFragment.kt:180)
        at com.mapbox.navigation.ui.NavigationView.updateNavigationReadyListeners(NavigationView.java:701)
        at com.mapbox.navigation.ui.NavigationView.lambda$onMapReady$0$NavigationView(NavigationView.java:261)
        at com.mapbox.navigation.ui.-$$Lambda$NavigationView$cQ4pEaxGsKIc0JZPsHECDoNZqgE.onStyleLoaded(Unknown Source:4)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:963)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:225)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1383)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1166)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common14OfflineService16registerObserverERKNSt6__ndk110shared_ptrINS0_22OfflineServiceObserverEEE" referenced by "/data/app/eu.mediator.hmi.cluster2-AYHL7EU1TVk6gOeJyL9xFA==/lib/x86/libnavigator-android.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at com.mapbox.navigator.NavNativeStaticInitializer$Companion.loadRequiredDependencies(NavNativeStaticInitializer.kt:45)
W/System.err:     at com.mapbox.navigator.NavNativeStaticInitializer.loadRequiredDependencies(Unknown Source:2)
        at com.mapbox.navigator.Navigator.<clinit>(Navigator.java:14)
        at com.mapbox.navigation.navigator.internal.NavigatorLoader.createNavigator(NavigatorLoader.kt:24)
        at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl.create(MapboxNativeNavigatorImpl.kt:64)
        at com.mapbox.navigation.core.NavigationComponentProvider.createNativeNavigator(NavigationComponentProvider.kt:32)
        at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:171)
        at com.mapbox.navigation.ui.NavigationViewModel.initializeNavigation(NavigationViewModel.java:437)
        at com.mapbox.navigation.ui.NavigationViewModel.initialize(NavigationViewModel.java:220)
        at com.mapbox.navigation.ui.NavigationView.initializeNavigation(NavigationView.java:935)
        at com.mapbox.navigation.ui.NavigationView.startNavigation(NavigationView.java:497)
W/System.err:     at eu.mediator.hmi.cluster2.navigator.BlankFragment.onNavigationReady$lambda-2(NavigatorLaunchedFragment.kt:188)
        at eu.mediator.hmi.cluster2.navigator.BlankFragment.lambda$ResbqNSyGHHngWXEf0J8_C3jcOE(Unknown Source:0)
        at eu.mediator.hmi.cluster2.navigator.-$$Lambda$BlankFragment$ResbqNSyGHHngWXEf0J8_C3jcOE.onChanged(Unknown Source:6)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
        at androidx.lifecycle.LiveData.observe(LiveData.java:205)
        at eu.mediator.hmi.cluster2.navigator.BlankFragment.onNavigationReady(NavigatorLaunchedFragment.kt:180)
W/System.err:     at com.mapbox.navigation.ui.NavigationView.updateNavigationReadyListeners(NavigationView.java:701)
        at com.mapbox.navigation.ui.NavigationView.lambda$onMapReady$0$NavigationView(NavigationView.java:261)
        at com.mapbox.navigation.ui.-$$Lambda$NavigationView$cQ4pEaxGsKIc0JZPsHECDoNZqgE.onStyleLoaded(Unknown Source:4)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:963)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:225)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1383)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1166)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
W/System.err:     at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
A/libc: /usr/local/google/buildbot/src/android/ndk-release-r21/external/libcxx/../../external/libcxxabi/src/abort_message.cpp:72: abort_message: assertion "terminating with uncaught exception of type jni::PendingJavaException" failed
    Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 11147 (or.hmi.cluster2), pid 11147 (or.hmi.cluster2)

```

This are the mapbox dependencies I'm using:

```
implementation "com.mapbox.navigation:ui:1.5.1"
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:5.9.0-alpha.1'
implementation "com.mapbox.search:mapbox-search-android:1.0.0-beta.15"
```

**Comment by cafesilencio** [comment]
I"m able to reproduce this. Let me gather some more info and i"ll report back here.

**Comment by cafesilencio** [comment]
There are libraries in common between the search SDK and the navigation SDK. The versions depended on by the search SDK are not compatible with 1.x of the navigation SDK.  I recommend using version 2.x beta of the navigation SDK with the search SDK.

https://docs.mapbox.com/android/beta/navigation/guides/

**Comment by cafesilencio** [comment]
Another option would be to try [this suggestion](https://github.com/mapbox/mapbox-search-android/issues/411#issuecomment-758662774).
