### ISSUE TITLE
Android: NoSuchMethodError

### ISSUE THREAD

**Issue by Danny-James** [mapbox/mapbox-navigation-android#464]
http://crashes.to/s/4c0d0af7ec4

I've now changed my gradle to use the following:

```
// Mapbox Maps SDK
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.3@aar') {
        transitive=true
        exclude module: 'lost'
        exclude module: 'mapbox-java-geojson'
        exclude module: 'mapbox-android-telemetry'
    }
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.0-SNAPSHOT') {
        transitive = true
    }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.0-SNAPSHOT'
    compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.3.0'
```
I was previously using `navigation-ui:0.6.3` & `navigation:0.6.3`

**Error**
```
11-03 12:09:58.312 16222-16222/uk.co.ainscough.routeinfo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: uk.co.ainscough.routeinfo, PID: 16222
                                                                           java.lang.NoSuchMethodError: No virtual method initialize(Landroid/content/Context;Ljava/lang/String;Ljava/lang/String;Lcom/mapbox/services/android/telemetry/location/LocationEngine;)V in class Lcom/mapbox/services/android/telemetry/MapboxTelemetry; or its super classes (declaration of 'com.mapbox.services.android.telemetry.MapboxTelemetry' appears in /data/app/uk.co.ainscough.routeinfo-1HO6yKFrN2HRnrQ-yEs0mw==/split_lib_dependencies_apk.apk!classes2.dex)
                                                                               at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:58)
                                                                               at uk.co.ainscough.routeinfo.ActivityNavigationMap.onCreate(ActivityNavigationMap.java:139)
                                                                               at android.app.Activity.performCreate(Activity.java:7000)
                                                                               at android.app.Activity.performCreate(Activity.java:6991)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                               at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                               at android.os.Looper.loop(Looper.java:164)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

See below my entire Activity - I've used the following as a guide [NavigationViewActivity.java](https://github.com/mapbox/mapbox-navigation-android/blob/master/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/navigationui/NavigationViewActivity.java)

```
package uk.co.ainscough.routeinfo;

// Support Libary Classes
import android.support.design.widget.FloatingActionButton;
import android.support.v4.app.ActivityCompat;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.Toolbar;

import android.app.Service;
import android.content.DialogInterface;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.os.Build;
import android.os.Bundle;
import android.util.Log;

// classes for layout objects
import android.view.MenuItem;
import android.widget.ProgressBar;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedList;
import java.util.List;

// classes needed to initialize map
import com.crashlytics.android.Crashlytics;
import com.crashlytics.android.answers.Answers;
import com.crashlytics.android.answers.ContentViewEvent;
import com.mapbox.geojson.Point;
import com.mapbox.mapboxsdk.Mapbox;
import com.mapbox.mapboxsdk.exceptions.InvalidLatLngBoundsException;
import com.mapbox.mapboxsdk.geometry.LatLngBounds;
import com.mapbox.mapboxsdk.location.LocationSource;
import com.mapbox.mapboxsdk.maps.MapView;

// classes need to plot route on map
import com.mapbox.mapboxsdk.annotations.Icon;
import com.mapbox.mapboxsdk.annotations.IconFactory;
import com.mapbox.mapboxsdk.annotations.MarkerOptions;

// classes needed to launch navigation UI
import android.view.View;
import com.mapbox.services.android.navigation.ui.v5.NavigationLauncher;

// classes needed to add location layer
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;
import android.location.Location;
import android.widget.Toast;

import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.camera.CameraUpdateFactory;
import com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerMode;
import com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin;
import com.mapbox.services.android.location.LostLocationEngine;
import com.mapbox.services.android.telemetry.location.LocationEngine;
import com.mapbox.services.android.telemetry.location.LocationEngineListener;
import com.mapbox.services.android.telemetry.permissions.PermissionsManager;

// classes to calculate a route
import com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute;
import com.mapbox.services.android.navigation.v5.navigation.NavigationRoute;
//import com.mapbox.services.api.directions.v5.DirectionsCriteria;
//import com.mapbox.services.api.directions.v5.models.DirectionsResponse;
//import com.mapbox.services.api.directions.v5.models.DirectionsRoute;
import com.mapbox.directions.v5.DirectionsCriteria;
import com.mapbox.directions.v5.models.DirectionsResponse;
import com.mapbox.directions.v5.models.DirectionsRoute;
import com.mapbox.geojson.LineString;
import com.mapbox.services.commons.models.Position;

// classes to add Traffic
import com.mapbox.mapboxsdk.plugins.traffic.TrafficPlugin;

import static com.mapbox.services.android.telemetry.location.LocationEnginePriority.HIGH_ACCURACY;

import butterknife.BindView;
import io.fabric.sdk.android.Fabric;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;
import timber.log.Timber;


import static com.mapbox.services.Constants.PRECISION_6;

public class ActivityNavigationMap extends AppCompatActivity implements OnMapReadyCallback, LocationEngineListener, Callback<DirectionsResponse>{

    private String TAG = "ainscough.routeinfo";
    private static final int CAMERA_ANIMATION_DURATION = 1000;
    private static final String NAVIGATIONROUTE = "NavigationRouteURL";

    // variables for adding location layer
    private MapboxMap mapboxMap;
    private LocationLayerPlugin locationLayer;
    private LocationEngine locationEngine;

    // variables for TrafficPlugin
    private TrafficPlugin trafficPlugin;

    // variables for calculating and drawing a route
    private Point currentPosition;
    private Point destination;
    private List<String> coOrdinates;
    private DirectionsRoute currentRoute;
    private NavigationMapRoute navigationMapRoute;
    //private MapboxNavigation navigation;
    private String RouteURL;


    @BindView(R.id.mapView)
    MapView mapView;
    private ProgressBar loading;

    private boolean locationFound;
    private boolean requestedLocation;

    @SuppressWarnings({"MissingPermission"})
    @Override
    protected void onRestart() {
        super.onRestart();
        Log.d(TAG, "Activity Restarted: Refresh Location.");

        if (locationEngine != null) {
            locationEngine.requestLocationUpdates();
        }
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Mapbox access token is configured here. This needs to be called either in your application
        // object or in the same activity which contains the mapview.
        Log.d(TAG, "Mapbox.getInstace();");
        Mapbox.getInstance(this, getString(R.string.mapbox_access_token));

        // Create CrashLytics.
        final Fabric fabric = new Fabric.Builder(this)
                .kits(new Crashlytics())
                .debuggable(true)
                .build();
        Fabric.with(fabric);

        // Get Intent Data.
        if (getIntent().hasExtra(NAVIGATIONROUTE)) {
            RouteURL = getIntent().getExtras().getString(NAVIGATIONROUTE);
        }

        if (RouteURL != null) {
            String googleMapsURL = "https://www.google.co.uk/maps/dir/Current+Location/";
            Log.d(TAG, "RouteURL: " + RouteURL);
            RouteURL = RouteURL.replace(googleMapsURL, "");
            Log.d(TAG, "RouteURL Replace: " + RouteURL);
            coOrdinates = new LinkedList<>(Arrays.asList(RouteURL.split("/"))); // Split CoOrdinates Into List.
            String[] destinationCoOrds = coOrdinates.get(coOrdinates.size() - 1).split(","); // Get Destination CoOrdinates From List.
            coOrdinates.remove(coOrdinates.size() - 1); // Remove Destination From List.

            //Set Destination
            destination = Point.fromLngLat(Double.valueOf(destinationCoOrds[0]), Double.valueOf(destinationCoOrds[1]));
            Log.d(TAG, "Set Destination " + destination.toString());

        }


        // This contains the MapView in XML and needs to be called after the access token is configured.
        setContentView(R.layout.activity_navigation_map);
        Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
        setSupportActionBar(toolbar);

        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        // Declare Loading Object.
        loading = (ProgressBar) findViewById(R.id.loading);

        // Create a mapView
        mapView = (MapView) findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);

        // Start Location Engine And Retrieve Current Location.
        if (!PermissionsManager.areLocationPermissionsGranted(this)) {
            Log.d(TAG, "No LOCATION Permission");
            PermissionRequest permissionRequest = new PermissionRequest(getApplicationContext(), this);
            permissionRequest.makePermissionRequest(permissionRequest.REQUEST_LOCATION_PERMISSION);
        } else {
            Log.d(TAG, "mapView.getMapAsync();");
            mapView.getMapAsync(this);
        }

        // Start Navigation Floating Button.
        FloatingActionButton fabStartNavigation = (FloatingActionButton) findViewById(R.id.fabStartNavigation);
        FloatingActionButton fabLocation = (FloatingActionButton) findViewById(R.id.fabLocation);
        fabStartNavigation.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                startNavigation();
            }
        });

        fabLocation.setOnClickListener(new View.OnClickListener() {
            @SuppressWarnings({"MissingPermission"})
            @Override
            public void onClick(View view) {
                //Get Location onDemand.
                Log.d(TAG, "Location FAB Clicked.");
                locationEngine.requestLocationUpdates();
                if (locationEngine.getLastLocation() != null) {
                    Log.d(TAG, "Get Last Location");
                    requestedLocation = true;
                    Location lastLocation = locationEngine.getLastLocation();
                    onLocationChanged(lastLocation);
                }
            }
        });

        // Log CrashLytics Event.
        Answers.getInstance().logContentView(new ContentViewEvent()
                .putContentName("RouteInfo Navigation Map")
                .putContentType("Android Activity")
                .putContentId("ActivityNavigationMap"));
    }

    private void startNavigation() {
        if (currentPosition != null) {
            if (currentRoute != null) {
                String awsPoolID = "eu-west-1_XXXXXXXX"; //Not In Use.
                Log.d(TAG, "Start Navigation UI");
                // Launch Navigation UI.
                NavigationLauncher.startNavigation(ActivityNavigationMap.this, currentRoute, null, false);
            }
        } else {
            // Create Dialog To Allow User To Acknowledge Location Issue.
            new AlertDialog.Builder(this)
                    .setTitle("Location Problem")
                    .setMessage("The application is unable to find your location, please close this dialog and touch the white location icon and try again.")
                    .setCancelable(false)
                    .setPositiveButton("Close", new DialogInterface.OnClickListener() {
                        public void onClick(DialogInterface dialog, int id) {
                            dialog.dismiss();
                        }
                    })
                    .show();
            Log.d(TAG, "Display No Location Dialog.");
        }
    }

    @SuppressWarnings({"MissingPermission"})
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();
        switch (id) {
            case android.R.id.home:
                Log.d(TAG, "Home Button Clicked");
                onBackPressed();
                return true;
            default:
                return super.onOptionsItemSelected(item);
        }
    }

    @SuppressWarnings({"MissingPermission"})
    @Override
    public void onMapReady(MapboxMap map) {

        // Interact with the map using mapboxMap here
        mapboxMap = map;
        initializeMap();
    }

    @SuppressWarnings({"MissingPermission"})
    private void initializeMap() {
        Log.d(TAG, "Initialise Map");

        enableLocationPlugin();
        buildRoute();

        // Setup TrafficPlugin If API Version >= 21.
        // Only Show Traffic On Newer Devices To Prevent Excess Map Processing.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            Log.d(TAG, "Start: Activate Traffic Plugin.");
            trafficPlugin = new TrafficPlugin(mapView, mapboxMap);
            trafficPlugin.setVisibility(true);
            Log.d(TAG, "End: Activate Traffic Plugin.");
        }
    }

    private boolean validRouteResponse(Response<DirectionsResponse> response) {
        return response.body() != null
                && response.body().routes() != null
                && response.body().routes().size() > 0;
    }

    @Override
    public void onResponse(Call<DirectionsResponse> call, Response<DirectionsResponse> response) {
        Log.d(TAG, "Response code: " + response.code());
        if (validRouteResponse(response)) {
            // Place returned route into currentRoute.
            currentRoute = response.body().routes().get(0);

            // Print some info about the route
            Log.d(TAG, "Distance (sec): " + currentRoute.distance());

            if (currentRoute != null) {
                // Display Route Information
                TextView textView_JourneyTime = (TextView) findViewById(R.id.textView_JourneyTime);
                TextView textView_JourneyDistance = (TextView) findViewById(R.id.textView_JourneyDistance);
                TextView textView_JourneySummary = (TextView) findViewById(R.id.textView_JourneySummary);

                textView_JourneyTime.setText(displayTravelTime(currentRoute.duration()));
                textView_JourneyDistance.setText(displayTravelDistance(currentRoute.distance()));
                textView_JourneySummary.setText(currentRoute.legs().get(0).steps().get(0).maneuver().instruction());

                drawRoute(currentRoute);
                boundCameraToRoute();
                hideLoading();
            }
        }
    }

    @Override
    public void onFailure(Call<DirectionsResponse> call, Throwable throwable) {
        Log.e(TAG, "Error: " + throwable.getMessage());
        Timber.e(throwable.getMessage());
    }

    private void buildRoute() {
        // Build Route.
        Log.d(TAG, "buildRoute();");
        Log.d(TAG, "Create navigationRoute");
        NavigationRoute.Builder navigationRoute = NavigationRoute.builder();

        navigationRoute.accessToken(getString(R.string.mapbox_access_token))
                .origin(currentPosition)
                .destination(destination)
                .profile(DirectionsCriteria.PROFILE_DRIVING);

        // Add Waypoints.
        if (coOrdinates.size() > 0) {
            // Set Waypoints.
            for (String x : coOrdinates) {
                String[] coOrds = x.split(",");
                Double lat = Double.valueOf(coOrds[1]);
                Double lon = Double.valueOf(coOrds[0]);
                // Add Waypoint To Route.
                navigationRoute.addWaypoint(Point.fromLngLat(lon, lat));
                Log.d(TAG, "Add Waypoint: " + (Position.fromCoordinates(lat, lon).toString()));
            }
        }
        navigationRoute.build().getRoute(this);

        // Show Loading Spinner.
        loading.setVisibility(View.VISIBLE);
    }

    private void drawRoute(DirectionsRoute route) {

        Log.d(TAG, "Draw Route On MapView.");

        // Check If Existing Route Is Plotted And Remove.
        if (navigationMapRoute != null) {
            Log.d(TAG, "Remove Old Route");
            navigationMapRoute.removeRoute();
        }

        // Display Loading Spinner.
        loading.setVisibility(View.VISIBLE);

        // Draw the route on the map
        Log.d(TAG, "Create NavigationMapRoute();");
        navigationMapRoute = new NavigationMapRoute(null, mapView, this.mapboxMap, R.style.NavigationMapRoute);
        navigationMapRoute.addRoute(currentRoute);

        // Create an Icon object for the marker to use
        Log.d(TAG, "Create Marker Icon");
        IconFactory mIconFactory = IconFactory.getInstance(this);
        Icon iconDestination = mIconFactory.fromResource(R.drawable.green_marker);
        Icon iconOrigin = mIconFactory.fromResource(R.drawable.blue_marker);

        // Add Destination Marker.
        Log.d(TAG, "Draw Destination Marker");
        mapboxMap.addMarker(new MarkerOptions()
                .position(new LatLng(destination.latitude(), destination.longitude()))
                .title("Destination")
                .snippet(getIntent().getExtras().getString("DestinationAddress"))
                .setIcon(iconDestination));

        // Add Origin Marker.
        Log.d(TAG, "Draw Origin Marker");
        String[] OriginCoOrds = coOrdinates.get(0).split(","); // Get Origin CoOrdinates From List.
        mapboxMap.addMarker(new MarkerOptions()
                .position(new LatLng(Double.valueOf(OriginCoOrds[0]), Double.valueOf(OriginCoOrds[1])))
                .title("Origin")
                .setIcon(iconOrigin));
    }


    @SuppressWarnings({"MissingPermission"})
    @Override
    public void onConnected() {
        Log.d(TAG, "requestLocationUpdates();");
        locationEngine.requestLocationUpdates();
    }

    @Override
    public void onLocationChanged(Location location) {
        if (location != null) {
            // Set Current Position.
            currentPosition = Point.fromLngLat(location.getLongitude(), location.getLatitude());
            Log.d(TAG, "Set currentPosition: " + currentPosition.toString());

            // forceLocationUpdate on Location Layer.
            if (locationLayer != null) {
                Log.d(TAG, "forceLocationUpdate");
                locationLayer.forceLocationUpdate(location);
            }

            //locationEngine.removeLocationEngineListener(this);
            onLocationFound(location);
        }
    }

    @SuppressWarnings({"MissingPermission"})
    private void enableLocationPlugin() {

        initializeLocationEngine();

        // Setup LocationLayerPlugin To Show Current Location Icon.
        locationLayer = new LocationLayerPlugin(mapView, mapboxMap, locationEngine);
        locationLayer.setLocationLayerEnabled(LocationLayerMode.COMPASS);
    }

    @SuppressWarnings({"MissingPermission"})
    private void initializeLocationEngine() {
        // Create Location Engine.

        Log.d(TAG, "initLocationEngine()");
        locationEngine = new LocationSource(this);
        locationEngine.setPriority(HIGH_ACCURACY);
        locationEngine.setInterval(0);
        locationEngine.setFastestInterval(1000);
        locationEngine.addLocationEngineListener(this);
        Log.d(TAG, "Activate initLocationEngine()");
        locationEngine.activate();

        Location lastLocation = locationEngine.getLastLocation();
        if (lastLocation != null) {
            onLocationChanged(lastLocation);
            currentPosition = Point.fromLngLat(lastLocation.getLongitude(), lastLocation.getLatitude());
        } else {
            locationEngine.addLocationEngineListener(this);
        }
    }


    private void onLocationFound(Location location) {
        if (requestedLocation) {
            // If User Has Selected Location FAB Animate Camera To Found Location.
            animateCamera(new LatLng(location.getLatitude(), location.getLongitude()));
            requestedLocation = false;
        }
        hideLoading();
    }

    public void boundCameraToRoute() {
        if (currentRoute != null) {
            List<Point> routeCoords = LineString.fromPolyline(currentRoute.geometry(),
                    PRECISION_6).coordinates();
            List<LatLng> bboxPoints = new ArrayList<>();
            for (Point point : routeCoords) {
                bboxPoints.add(new LatLng(point.latitude(), point.longitude()));
            }
            if (bboxPoints.size() > 1) {
                try {
                    LatLngBounds bounds = new LatLngBounds.Builder().includes(bboxPoints).build();
                    animateCameraBbox(bounds, CAMERA_ANIMATION_DURATION, new int[] {50, 500, 50, 335});
                    //animateCameraBbox(bounds, CAMERA_ANIMATION_DURATION, new int[]{125, 125, 125, 250});
                } catch (InvalidLatLngBoundsException exception) {
                    Toast.makeText(this, "Valid route not found.", Toast.LENGTH_SHORT).show();
                }
            }
        }
    }

    private void animateCameraBbox(LatLngBounds bounds, int animationTime, int[] padding) {
        mapboxMap.animateCamera(CameraUpdateFactory.newLatLngBounds(bounds,
                padding[0], padding[1], padding[2], padding[3]), animationTime);
    }


    private void animateCamera(LatLng point) {
        mapboxMap.animateCamera(CameraUpdateFactory.newLatLngZoom(point, 16), CAMERA_ANIMATION_DURATION);
    }

    private void hideLoading() {
        if (loading.getVisibility() == View.VISIBLE) {
            loading.setVisibility(View.INVISIBLE);
        }
    }

    private String displayTravelTime(double travelTime) {
        int seconds;
        int minutes;
        int hours;
        seconds = (int) travelTime;
        hours = seconds / 3600;
        minutes = (seconds % 3600) / 60;
        int seconds_output = (seconds % 3600) % 60;
        return (hours > 0 ? hours + " hr" + ((hours > 1 ? "s " : " ")) : "") + minutes + " min" + (minutes > 1 ? "s" : "");
    }

    private String displayTravelDistance(double travelDistance) {
        double meters;
        meters = travelDistance;

        double inches = (39.370078 * meters);
        double miles = (int) (inches / 63360);
        double feet = (int) (inches - miles * 63360) / 12;
        double inchesRemaining = inches - (miles * 63360 + feet * 12);
        return "(" + miles + " mile" + ((miles > 1 ? "s)" : ")"));
    }

    @Override
    public void onBackPressed() {
        // Create Dialog To Prompt If User Would Like To Go Back To Prevent
        // Accidental Closure Of Navigation Preview.
        AlertDialog.Builder builder = new AlertDialog.Builder(this);
        builder.setMessage("Are you sure you want to exit the map?")
                .setTitle("Exit Navigation?")
                .setCancelable(false)
                .setPositiveButton("Yes", new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int id) {
                        finish();
                    }
                })
                .setNegativeButton("No", new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int id) {
                        dialog.cancel();
                    }
                });
        AlertDialog alert = builder.create();
        alert.show();
    }

    // Add the mapView lifecycle to the activity's lifecycle methods
    @SuppressWarnings({"MissingPermission"})
    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
        if (locationEngine != null) {
            locationEngine.addLocationEngineListener(this);
            if (!locationEngine.isConnected()) {
                locationEngine.activate();
            }
        }
    }

    @SuppressWarnings({"MissingPermission"})
    @Override
    protected void onStart() {
        super.onStart();
        mapView.onStart();
        if (locationLayer != null) {
            locationLayer.onStart();
        }
    }

    @Override
    protected void onStop() {
        super.onStop();
        mapView.onStop();
        if (locationLayer != null) {
            locationLayer.onStop();
        }
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
        if (locationEngine != null) {
            locationEngine.removeLocationEngineListener(this);
        }
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
        if (locationEngine != null) {
            locationEngine.removeLocationUpdates();
            locationEngine.deactivate();
        }
    }

    @Override
    protected void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }


    /**********************************************************
     *   START: CHECK FOR PERMISSION   *
     **********************************************************/

    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        PermissionRequest permissionRequest = new PermissionRequest(this, this);
        permissionRequest.onRequestPermissionsResult(requestCode, permissions, grantResults);

        if (requestCode == PermissionRequest.REQUEST_LOCATION_PERMISSION && grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
            Log.d(TAG, "LOCATION Permission Granted");
            if (ActivityCompat.checkSelfPermission(this, android.Manifest.permission.ACCESS_FINE_LOCATION) == PackageManager.PERMISSION_GRANTED &&
                    ActivityCompat.checkSelfPermission(this, android.Manifest.permission.ACCESS_COARSE_LOCATION) == PackageManager.PERMISSION_GRANTED) {

                mapView.getMapAsync(this);

            }
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        PermissionRequest permissionRequest = new PermissionRequest(this, this);
        permissionRequest.onActivityResult(requestCode, resultCode, data);

        if (requestCode == PermissionRequest.REQUEST_LOCATION_PERMISSION) {
            if (ActivityCompat.checkSelfPermission(this, android.Manifest.permission.ACCESS_FINE_LOCATION) != PackageManager.PERMISSION_GRANTED &&
                    ActivityCompat.checkSelfPermission(this, android.Manifest.permission.ACCESS_COARSE_LOCATION) != PackageManager.PERMISSION_GRANTED) {

                mapView.getMapAsync(this);

            }
        }
    }
}
```

**Comment by Grsmto** [comment]
The lastest commits on master are breaking changes as they have update a dependency (https://github.com/mapbox/mapbox-java) and both this SDK and Mapbox GL have to be updated for it to work.
I think there is nothing you can do apart from waiting for the guys to update Mapbox GL with latest changes of MAS.

**Comment by Danny-James** [comment]
@Grsmto Thanks for the reply. 👍

**Comment by cammace** [comment]
We have reverted the API breaking changes in master inside the map, Mapbox Java, and nav SDKs. LocationEngine related issues should be resolved now.
