### ISSUE TITLE
Replay set route isn't working

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4650]
We just fixed the set route feature here: https://github.com/mapbox/mapbox-navigation-android/pull/4637

But now it won't work after this one: https://github.com/mapbox/mapbox-navigation-android/pull/4526

The crash is currently silent. But I'm will see that it causes this issue https://github.com/mapbox/mapbox-java/issues/1274

We're introducing a new reader and it makes these crashes louder https://github.com/mapbox/mapbox-navigation-android/pull/4601

**Comment by kmadsen** [comment]
cc: @lukasmartinelli @korshaknn

**Comment by kmadsen** [comment]
When using `DirectionsRoute.fromJson(jsonString, "pk.1234")`

When the jsonString is a DirectionsRoute that includes `routeOptions`

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 27755
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.routeOptions.coordinates
        at com.google.gson.Gson.fromJson(Gson.java:944)
        at com.google.gson.Gson.fromJson(Gson.java:1003)
        at com.google.gson.Gson.fromJson(Gson.java:975)
        at com.mapbox.api.directions.v5.models.DirectionsRoute.fromJson(DirectionsRoute.java:220)
```

**Comment by kmadsen** [comment]
When using `DirectionsRoute.fromJson(jsonString)`

When the jsonString is a DirectionsRoute that includes routeOptions and a valid accessToken

```
2021-07-21 11:37:12.544 29522-29522/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 29522
    java.lang.IllegalArgumentException: Provided serialized route contains RouteOptions. Use DirectionsRoute#fromJson(json, accessToken) instead.
        at com.mapbox.api.directions.v5.models.DirectionsRoute.fromJson(DirectionsRoute.java:184)
```

**Comment by kmadsen** [comment]
"coordinates":[[-122.5237429,37.975393],[-122.5231413,37.9750695]]

"coordinates":"-122.5237429,37.975393;-122.5231413,37.9750695"

it seems the new json parser requires this change to coordinates 🤔. Were these manually edited?

**Comment by kmadsen** [comment]
I manually edited the `replay-history-activity.json` with the coordinates changes as seen above. and that is an alternative fix for this issue.

All the old history files we have.. would need to have this change, so another solution moving forward could be to create a script which handles this change

**Comment by kmadsen** [comment]
Resolved by https://github.com/mapbox/mapbox-navigation-android/pull/4601
