### ISSUE TITLE
Please fix error "SecurityException: getDataNetworkTypeForSubscriber" for version 0.42.6 

### ISSUE THREAD

**Issue by Ranafugaz** [mapbox/mapbox-navigation-android#4793]
Please fix the security exception caused by the READ_PHONE_STATE permission for all of us that are using the legacy version  0.42.6 and targeting android 11/12.

The exception happens in:
mapView.onCreate(savedInstanceState);

java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
        at com.mapbox.android.telemetry.TelemetryUtils.obtainCellularNetworkType(TelemetryUtils.java:157)
        at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(PhoneState.java:39)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(TelemetryImpl.java:46)
        at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:277)

**Comment by JasmineMan** [comment]
I confirm that this issue is still present on com.mapbox.mapboxsdk:mapbox-android-sdk:8.6.6 when targeting Android 30 (now it is a requirement). Cannot use the map right now because of the crash:

`    java.lang.SecurityException: getDataNetworkTypeForSubscriber
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
        at android.os.Parcel.createException(Parcel.java:2357)
        at android.os.Parcel.readException(Parcel.java:2340)
        at android.os.Parcel.readException(Parcel.java:2282)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getNetworkTypeForSubscriber(ITelephony.java:8762)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:3021)
        at android.telephony.TelephonyManager.getNetworkType(TelephonyManager.java:2985)
        at com.mapbox.android.telemetry.TelemetryUtils.obtainCellularNetworkType(TelemetryUtils.java:150)
        at com.mapbox.mapboxsdk.module.telemetry.PhoneState.<init>(PhoneState.java:39)
        at com.mapbox.mapboxsdk.module.telemetry.TelemetryImpl.onAppUserTurnstileEvent(TelemetryImpl.java:46)
        at com.mapbox.mapboxsdk.maps.MapView.onCreate(MapView.java:279)
        at com.mapbox.mapboxsdk.maps.SupportMapFragment.onViewCreated(SupportMapFragment.java:112)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
`

Setting a constraing on transitive dependencies as `"com.mapbox.mapboxsdk:mapbox-android-telemetry:6.1.0"` does help, but the real fix will be appretiated.

I saw the exact same telemetry issue being fixed for navigation component here: #3577, but this seems to be having the old telemetry dependency and needs an update.

**Comment by Ranafugaz** [comment]
I have fixed it by adding:

> implementation 'com.mapbox.mapboxsdk:mapbox-android-telemetry:8.1.0'

You can also upgrade the Mapbox SDK to version 8.6.7 (navigation uses 8.5.1), apparently works fine without conflicts.
> implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:8.6.7'
