### ISSUE TITLE
IndexOutOfBoundsException in MapboxRouteLineUtils

### ISSUE THREAD

**Issue by tomaszrybakiewicz** [mapbox/mapbox-navigation-android#4833]
**Android API: 29 (Android 10), 30 (Android 11)**
**Mapbox Navigation SDK version: 2.0.0-rc.1**

Our Crashlytics detected a crash originating from Navigation SDK. 
As of Sep 16 2021,  we only recorded 3 crashes (out of 1.23K installs at 25% rollout).

### Repro steps
Unfortunately we don't have exact repro steps for this crash. We can only assume the app state based on the captured stacktrace.  Judging from it, the crash could have happened either on Directions Selection screen or on Turn-by-turn navigation screen.

To start turn-by-turn navigation in straightaway:
1. Run Straightaway app
2. Add at least one stop
3. Start a route by pressing "Start route"
4. Start navigation by pressing "Navigate"
5. (potential crash point) You should land on Direction Selection screen. From here select proposed route and press GO.
6. (potential crash point) You should start Turn-by-turn navigation session.

Few notes about Straightaway implementation:
- `mapboxNavigation.startTripSession()` is called only on Turn-by-turn navigation screen
- Only first `DirectionsRoute` line is rendered on Turn-by-turn navigation screen
  ```
  // from Turn-by-turn navigation fragment
  private val routesObserver = object : RoutesObserver {
          override fun onRoutesChanged(routes: List<DirectionsRoute>) {
              if (activity == null || routes.isEmpty()) return
  
              try {
                  // MapboxNavigation might load multiple directions on rerouting.
                  // We are only interested in primary directions that are always at index 0.
                  val lines = listOf(RouteLine(routes.first(), null))
                  routeLineAPI.setRoutes(lines, navConsumer)
                  updateCameraToFollowing()
              } catch (e: Throwable) {
                  logW(TAG, "onRoutesChanged: Error updating route line and camera.", e)
              }
          }
      }
  ```
- Directions Select screen renders all DirectionRoute lines.

### Stacktrace from Crashlytics report:

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 980, Size: 980
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils.getRouteLineAnnotationExpressionData$libnavui_maps_release(MapboxRouteLineUtils.java:15)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils$getRouteLineAnnotationExpressionDataFromCache$1.invoke(MapboxRouteLineUtils.java:15)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils$getRouteLineAnnotationExpressionDataFromCache$1.invoke(MapboxRouteLineUtils.java:15)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$CacheResultKey2.invoke(CacheResultUtils.java:1)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$CacheResultHandler.invoke(CacheResultUtils.java:2)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$cacheResult$2.invoke(CacheResultUtils.java:1)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils.calculateRouteLineSegments(MapboxRouteLineUtils.java:1)
       at com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineApi$buildDrawRoutesState$4$segmentsDef$1.invokeSuspend(MapboxRouteLineApi.java:11)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:2)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:86)
       at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:929)
```

**Comment by cafesilencio** [comment]
Were any crashes of this type detected before RC.1?

**Comment by tomaszrybakiewicz** [comment]
@cafesilencio No crashes of this kind were recorded before RC.1 update.
I think we can squeeze in an update to RC.2 with the next release (which is planned for the end of this month). 

For now, let's keep this ticket open and I will update it once we know more.

**Comment by LukasPaczos** [comment]
A similar crash caught with RC.2:
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 100, Size: 100
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils$extractRouteData$1.invoke(MapboxRouteLineUtils.java:528)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils$extractRouteData$1.invoke(MapboxRouteLineUtils.java:548)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$CacheResultKey2.invoke(CacheResultUtils.java:17)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$CacheResultKey2.invoke(CacheResultUtils.java:15)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$CacheResultHandler.invoke(CacheResultUtils.java:50)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$cacheResult$2.invoke(CacheResultUtils.java:38)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils$extractRouteDataWithTrafficAndRoadClassDeDuped$1.invoke(MapboxRouteLineUtils.java:476)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils$extractRouteDataWithTrafficAndRoadClassDeDuped$1.invoke(MapboxRouteLineUtils.java:494)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$CacheResultKey2.invoke(CacheResultUtils.java:17)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$CacheResultKey2.invoke(CacheResultUtils.java:15)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$CacheResultHandler.invoke(CacheResultUtils.java:50)
       at com.mapbox.navigation.ui.maps.util.CacheResultUtils$cacheResult$2.invoke(CacheResultUtils.java:38)
       at com.mapbox.navigation.ui.maps.internal.route.line.MapboxRouteLineUtils.calculateRouteLineSegments(MapboxRouteLineUtils.java:437)
       at com.mapbox.navigation.ui.maps.route.line.api.MapboxRouteLineApi$buildDrawRoutesState$4$segmentsDef$1.invokeSuspend(MapboxRouteLineApi.java:1016)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```
