### ISSUE TITLE
NullPointException in rerouting

### ISSUE THREAD

**Issue by josephquzhou** [mapbox/mapbox-navigation-android#488]
I am using navigation:0.6.3 and navigation-ui:0.6.3

E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: edu.cmu.jqz.joe_test5, PID: 2464
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'long android.location.Location.getTime()' on a null object reference
                                                                         at com.mapbox.services.android.navigation.v5.navigation.NavigationMetricsWrapper.rerouteEvent(NavigationMetricsWrapper.java:101)
                                                                         at com.mapbox.services.android.navigation.v5.navigation.NavigationService.sendRerouteEvent(NavigationService.java:315)
                                                                         at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onLocationChanged(NavigationService.java:202)
                                                                         at com.mapbox.services.android.location.MockLocationEngine$LocationUpdateRunnable.run(MockLocationEngine.java:375)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by danesfeder** [comment]
@josephquzhou This is a known issue we unfortunately released with `0.6.3` - it should be fixed in `0.7.0-SNAPSHOT`

**Comment by danesfeder** [comment]
@josephquzhou We released `0.7.0` which should fix this issue.  Please update to this version and confirm it has been fixed.  Thanks!

**Comment by josephquzhou** [comment]
navigation:0.7.0 depends on com.mapbox.mapboxsdk:mapbox-java-services-directions:3.0.0-SNAPSHOT.
Is it normal?
