### ISSUE TITLE
Crash UninitializedPropertyAccessException: lateinit property feedbackFlowListener

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4890]
**Mapbox Navigation SDK version:** 2.0.0-rc.2.1

### Steps to trigger behavior

I'm pretty sure this crash was hit by me. I just completed a 20 minute ride from SF to Oakland and lost the data. This was not using Android Auto.

https://console.firebase.google.com/u/0/project/tap-android-1c190/crashlytics/app/android:com.mapbox.onetap.app/issues/ea648b9b94d008cfde6370babf8e5777?time=last-seven-days&sessionEventKey=614BC63A031500012AD11071BFE876B1_1589502058642868252

```
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property feedbackFlowListener has not been initialized
       at com.mapbox.navigation.ui.internal.feedback.FeedbackArrivalFragment.dismiss(FeedbackArrivalFragment.java:82)
       at com.mapbox.navigation.ui.internal.feedback.FeedbackArrivalFragment$initListeners$1.onClick(FeedbackArrivalFragment.java:141)
       at android.view.View.performClick(View.java:7448)
       at android.view.View.performClickInternal(View.java:7425)
       at android.view.View.access$3600(View.java:810)
       at android.view.View$PerformClick.run(View.java:28305)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7664)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

cc: @abhishek1508 @cafesilencio @Guardiola31337

**Comment by Guardiola31337** [comment]
https://mapbox.slack.com/archives/CT57PP4TU/p1632388795209000

I also run into this https://console.firebase.google.com/u/1/project/tap-android-1c190/crashlytics/app/android:com.mapbox.onetap.app/issues/ea648b9b94d008cfde6370babf8e5777?time=last-seven-days&sessionEventKey=614BC63A031500012AD11071BFE876B1_1589502058642868252

cc @RingerJK

**Comment by Zayankovsky** [comment]
The crash happens when an activity or application process recreates, while the feedback fragment is showing. It can easily occur, when the app is in background and the system needs to free resources. This can also be triggered locally with the help of `Don't keep activities` setting in `Developer options`. 
Current implementation supports configuration changes very poorly. We can't rely on `retainInstance`, because it only covers a limited set of cases.

**Comment by Guardiola31337** [comment]
This may be fixed by new Feedback UI.
