### ISSUE TITLE
qa-test-app crashes because it's creating multiple instances of MapboxNavigation

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#4891]
I'm working on `AlternativeRouteActivity` so am noticing it here. But I think the issue is on all the Activities

```
     Caused by: java.lang.IllegalStateException: A different MapboxNavigation instance already exists.
    Make sure to destroy it with #onDestroy before creating a new one.
    Also see MapboxNavigationProvider for instance management assistance.
        at com.mapbox.navigation.core.MapboxNavigation.<init>(MapboxNavigation.kt:316)
        at com.mapbox.navigation.qa_test_app.view.AlternativeRouteActivity$mapboxNavigation$2.invoke(AlternativeRouteActivity.kt:84)
        at com.mapbox.navigation.qa_test_app.view.AlternativeRouteActivity$mapboxNavigation$2.invoke(AlternativeRouteActivity.kt:83)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.mapbox.navigation.qa_test_app.view.AlternativeRouteActivity.getMapboxNavigation(AlternativeRouteActivity.kt:83)
        at com.mapbox.navigation.qa_test_app.view.AlternativeRouteActivity.initNavigation(AlternativeRouteActivity.kt:148)
        at com.mapbox.navigation.qa_test_app.view.AlternativeRouteActivity.onCreate(AlternativeRouteActivity.kt:115)
        at android.app.Activity.performCreate(Activity.java:7994)
        at android.app.Activity.performCreate(Activity.java:7978)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
        	... 11 more
```

cc: @abhishek1508

**Comment by abhishek1508** [comment]
We are already doing it for all the examples in the examples repository. But, it's a good callout that this needs to happens to all the examples in the `qa-test-app`.
This brings me to the open verbal dialogue we had just before 2.0.0-RC to remove the `examples` module from this repo in favor of our new examples repository. Where are we that and what are the plans to moving forward with it?

I think we can just do it now given that we are maybe 1-2 weeks away from GA and make it official with GA that we have new example repository.

/cc @LukasPaczos
