### ISSUE TITLE
IndexOutOfBoundsException : getPointsToFrameOnCurrentStep

### ISSUE THREAD

**Issue by Christophe668** [mapbox/mapbox-navigation-android#5033]
**Mapbox Navigation SDK version:** Mapbox Navigation 2.0.0 (GA)

### Steps to trigger behavior

Happening from time to time, not sure yet when it occurs.
Let me know what I can give you to help you reproduce the issue

### Actual behavior

```

    Process: bike.cowboy.app.debug, PID: 17839
    java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.mapbox.navigation.ui.maps.camera.data.ViewportDataSourceProcessor.getPointsToFrameOnCurrentStep(ViewportDataSourceProcessor.kt:189)
        at com.mapbox.navigation.ui.maps.camera.data.MapboxNavigationViewportDataSource.onRouteProgressChanged(MapboxNavigationViewportDataSource.kt:478)
```

**Comment by LukasPaczos** [comment]
@Christophe668 I'd need the JSON this is reproducible on specifically because a request can return many different routes depending on live conditions, traffic, etc.

**Comment by Christophe668** [comment]
Noted, will add some logs to retrieve this easily, thanks!
