### ISSUE TITLE
Possibly flaky instrumentation test not allowed to perform MOCK_LOCATION

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#5116]
**Android API:**
**Mapbox Navigation SDK version:**

Drop-in-ui change that did nothing to core-sdk failed running the instrumentation tests https://github.com/mapbox/mapbox-navigation-android/pull/5086

Looks like this error log was hit https://github.com/mapbox/mapbox-navigation-android/blob/ce8d7844ca26707babfe317bbfd9e95306eb18fe/libtesting-ui/src/main/java/com/mapbox/navigation/testing/ui/MockLocationUpdatesRule.kt#L57

```
11-16 11:28:33.314: I/UsageTrackerFacilitator(24435): Usage tracking disabled
11-16 11:28:33.364: D/TestExecutor(24435): Adding listener androidx.test.internal.runner.listener.LogRunListener
11-16 11:28:33.364: D/TestExecutor(24435): Adding listener androidx.test.orchestrator.instrumentationlistener.OrchestratedInstrumentationListener
11-16 11:28:33.365: D/TestExecutor(24435): Adding listener androidx.test.internal.runner.listener.ActivityFinisherRunListener
11-16 11:28:33.371: I/TestRunner(24435): run started: 1 tests
11-16 11:28:33.503: I/DMAgent(21476): Accessibility state changed to true. Doing device sync.
11-16 11:28:33.520: I/DMAgent(21476): Received request to invoke DeviceManagementService
11-16 11:28:33.533: D/DMAgent(21476): Number of managed accounts: 1
11-16 11:28:33.647: I/DMAgent(21476): Service runs for: 0 accounts
11-16 11:28:34.577: W/MockLocationUpdatesRule(24435): addTestProvider failed
11-16 11:28:34.579: E/TestRunner(24435): failed: com.mapbox.navigation.instrumentation_tests.core.CoreRerouteTest
11-16 11:28:34.579: E/TestRunner(24435): ----- begin exception -----
11-16 11:28:34.582: E/TestRunner(24435): java.lang.SecurityException: com.mapbox.navigation.instrumentation_tests from uid 10098 not allowed to perform MOCK_LOCATION
11-16 11:28:34.582: E/TestRunner(24435): 	at android.os.Parcel.readException(Parcel.java:1620)
11-16 11:28:34.582: E/TestRunner(24435): 	at android.os.Parcel.readException(Parcel.java:1573)
11-16 11:28:34.582: E/TestRunner(24435): 	at android.location.ILocationManager$Stub$Proxy.setTestProviderEnabled(ILocationManager.java:1168)
11-16 11:28:34.582: E/TestRunner(24435): 	at android.location.LocationManager.setTestProviderEnabled(LocationManager.java:1325)
11-16 11:28:34.582: E/TestRunner(24435): 	at com.mapbox.navigation.testing.ui.MockLocationUpdatesRule.before(MockLocationUpdatesRule.kt:59)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runners.Suite.runChild(Suite.java:128)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runners.Suite.runChild(Suite.java:27)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
11-16 11:28:34.582: E/TestRunner(24435): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
11-16 11:28:34.582: E/TestRunner(24435): 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
11-16 11:28:34.582: E/TestRunner(24435): 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
11-16 11:28:34.582: E/TestRunner(24435): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
```

**Comment by kmadsen** [comment]
This started not too long ago

![Screen Shot 2021-11-16 at 12 08 54 PM](https://user-images.githubusercontent.com/3021882/142058143-3827122d-878f-469b-9b8f-5db0acbf01ec.png)

**Comment by kmadsen** [comment]
I sent a support ticket to Firebase, because I'm not sure why this started failing all of the sudden

**Comment by kmadsen** [comment]
Considering this closed because it is green again

![Screen Shot 2021-11-16 at 5 12 57 PM](https://user-images.githubusercontent.com/3021882/142091231-076e35b5-4074-4f26-889f-5be8260cf248.png)

**Comment by kmadsen** [comment]
This issue is not happening 100% of the time, but am still seeing it every once and awhile. I've contacted Firebase support but they have a list of items they need in order to figure out the issue

- Test matrix ID(s) you've gathered for the test(s)
- APK and test APK you've used when running the test
- A short video or test video result of your application
    - This would give us a brief description of what your application is about
- Screenshots of any advanced options/settings that you’ve enabled for the test (if there's any)
- Detailed or step-by-step instructions to reproduce the issue (screenshots would be great)
   - Include selected devices/API version/orientation (Test matrix)

**Comment by VysotskiVadim** [comment]
@kmadsen , since #5164 was merged instrumentation-tests success rate in the main branch became 100% .

![image](https://user-images.githubusercontent.com/6190346/146032662-17e5095f-c512-4bfe-bd1a-6a7414af3ef8.png)

Can we close the issue?

**Comment by kmadsen** [comment]
> since #5164 was merged instrumentation-tests success rate in the main branch became 100% .

🥳 🎂

**Comment by Guardiola31337** [comment]
Speaking of this, it failed again as part of https://github.com/mapbox/mapbox-navigation-android/pull/5272 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/15607/workflows/99433937-a1c6-40f4-996e-2ea145927588/jobs/68224 https://console.firebase.google.com/u/1/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/6130836153988717887/executions/bs.94fdd18ee0b43575/issues 😬 

```
Test run failed to complete. Expected 14 tests, received 13. Time: 159,906 There was 1 failure: 1) com.mapbox.navigation.instrumentation_tests.core.CoreRerouteTest java.lang.SecurityException: com.mapbox.navigation.instrumentation_tests from uid 10097 not allowed to perform MOCK_LOCATION at android.os.Parcel.readException(Parcel.java:1620) at android.os.Parcel.readException(Parcel.java:1573) at android.location.ILocationManager$Stub$Proxy.setTestProviderEnabled(ILocationManager.java:1168) at android.location.LocationManager.setTestProviderEnabled(LocationManager.java:1325) at com.mapbox.navigation.testing.ui.MockLocationUpdatesRule.before(MockLocationUpdatesRule.kt:59) at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50) at org.junit.rules.RunRules.evaluate(RunRules.java:20) at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) at org.junit.runners.ParentRunner.run(ParentRunner.java:413) at org.junit.runners.Suite.runChild(Suite.java:128) at org.junit.runners.Suite.runChild(Suite.java:27) at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) at org.junit.runners.ParentRunner.run(ParentRunner.java:413) at org.junit.runner.JUnitCore.run(JUnitCore.java:137) at org.junit.runner.JUnitCore.run(JUnitCore.java:115) at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56) at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395) at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879) FAILURES!!! Tests found: 14, Tests run: 13, Failures: 1
```

Should we cherry-pick https://github.com/mapbox/mapbox-navigation-android/pull/5164 into the 2.x release branches?

cc @kmadsen @VysotskiVadim

**Comment by VysotskiVadim** [comment]
@Guardiola31337 , I will cherry-pick
