### ISSUE TITLE
java.lang.NullPointerException: Null routes when parsing routes

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#5118]
Caught on Nav SDK `v2.1.0-rc.1` using Nav Native `v79.0.2`.
```
Fatal Exception: java.lang.NullPointerException: Null routes
       at java.util.Objects.requireNonNull(Objects.java:245)
       at com.mapbox.api.directions.v5.models.$AutoValue_DirectionsResponse.<init>(.java:34)
       at com.mapbox.api.directions.v5.models.AutoValue_DirectionsResponse.<init>(AutoValue_DirectionsResponse.java:25)
       at com.mapbox.api.directions.v5.models.AutoValue_DirectionsResponse$GsonTypeAdapter.read(AutoValue_DirectionsResponse.java:182)
       at com.mapbox.api.directions.v5.models.AutoValue_DirectionsResponse$GsonTypeAdapter.read(AutoValue_DirectionsResponse.java:28)
       at com.google.gson.Gson.fromJson(Gson.java:932)
       at com.google.gson.Gson.fromJson(Gson.java:897)
       at com.google.gson.Gson.fromJson(Gson.java:846)
       at com.google.gson.Gson.fromJson(Gson.java:817)
       at com.mapbox.api.directions.v5.models.DirectionsResponse.fromJson(DirectionsResponse.java:164)
       at com.mapbox.navigation.base.internal.utils.DirectionsResponseUtilsKt$parseDirectionsResponse$2.invokeSuspend(DirectionsResponseUtilsKt.java:29)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)
```

@DenisPryt are there situation where the native router could return a route is `null`? Not asking about alternatives on `v80` (which do return `null`s), but routes and alternatives on `v79`.

**Comment by LukasPaczos** [comment]
Closing as a duplicate of https://github.com/mapbox/mapbox-navigation-android/issues/5066.

**Comment by DenisPryt** [comment]
@LukasPaczos alternatives on v79 do not insert nulls to the routeResponse. And as far I know nav-native's router can't return nulls too.
