### ISSUE TITLE
Crash in the firebase robo which plays ReplayHistoryActivity

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#5135]
**Android API:**
**Mapbox Navigation SDK version:** `main` branch

I noticed this here https://github.com/mapbox/mapbox-navigation-android/pull/5132
But it didn't make sense, and it turns out it's on the `main` branch

## Steps to reproduce

1. Start the examples app
1. Start Replay Example
1. Tap PLAY HISTORY button  
1. Tap SELECT HISTORY button
1. Select the Germany Highway
1. Crash

This is the json passed to `parseDirectionsResponse`, crashes because it does not contain a route
``` json
{"message":"should be >= 1","code":"InvalidInput"}
```

```
2021-11-18 15:52:50.645 26379-26432/com.mapbox.navigation.examples E/FirebaseCrashlytics: Tried to write a fatal exception while no session was open.
2021-11-18 15:52:50.647 26379-26379/com.mapbox.navigation.examples E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.navigation.examples, PID: 26379
    java.lang.NullPointerException: Null routes
        at com.mapbox.api.directions.v5.models.$AutoValue_DirectionsResponse.<init>($AutoValue_DirectionsResponse.java:34)
        at com.mapbox.api.directions.v5.models.AutoValue_DirectionsResponse.<init>(AutoValue_DirectionsResponse.java:25)
        at com.mapbox.api.directions.v5.models.AutoValue_DirectionsResponse$GsonTypeAdapter.read(AutoValue_DirectionsResponse.java:182)
        at com.mapbox.api.directions.v5.models.AutoValue_DirectionsResponse$GsonTypeAdapter.read(AutoValue_DirectionsResponse.java:28)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at com.google.gson.Gson.fromJson(Gson.java:817)
        at com.mapbox.api.directions.v5.models.DirectionsResponse.fromJson(DirectionsResponse.java:165)
        at com.mapbox.navigation.base.internal.utils.DirectionsResponseUtilsKt$parseDirectionsResponse$2.invokeSuspend(DirectionsResponseUtils.kt:29)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by kmadsen** [comment]
cc: @LukasPaczos @korshaknn

**Comment by kmadsen** [comment]
> https://api.mapbox.com/directions/v5/mapbox/driving-traffic/8.854003,49.2477319;139.629888,35.6129?access_token={access_token}&geometries=polyline6&alternatives=true&overview=full&steps=true&avoid_maneuver_radius=0&bearings=73.8540268,90;&layers=;&continue_straight=false&annotations=congestion,duration,distance&language=ja&roundabout_exits=false&voice_instructions=true&banner_instructions=true&voice_units=metric&waypoint_names=;日本,%20東京都東京都世田谷区玉川2丁目14番19&waypoint_targets=;

This is where it's coming from

![Screen Shot 2021-11-18 at 4 30 45 PM](https://user-images.githubusercontent.com/3021882/142518331-2a5ee3bd-342d-4bf8-ae7a-638858205edb.png)

**Comment by kmadsen** [comment]
Curious if this is a `RouteOptions.toUrl` issue. So here's the log of RouteOptions.toJson and RouteOptions.toUrl


> 2021-11-18 16:34:56.657 6785-6785/com.mapbox.navigation.examples I/MbxRouterWrapper: getRoute routeJson: {"baseUrl":"https://api.mapbox.com","user":"mapbox","profile":"driving-traffic","coordinates":"139.6502552,35.6414044;139.629888,35.6129","alternatives":true,"language":"ja","bearings":"274.2128601,90;","avoid_maneuver_radius":0,"layers":"0;","continue_straight":false,"roundabout_exits":false,"geometries":"polyline6","overview":"full","steps":true,"annotations":"congestion,duration,distance","voice_instructions":true,"banner_instructions":true,"voice_units":"metric","waypoint_names":";日本, 東京都東京都世田谷区玉川2丁目14番19","waypoint_targets":";"}
2021-11-18 16:34:56.657 6785-6785/com.mapbox.navigation.examples I/MbxRouterWrapper: getRoute routeUrl: https://api.mapbox.com/directions/v5/mapbox/driving-traffic/139.6502552,35.6414044;139.629888,35.6129?access_token=YOUR_ACCESS_TOKEN&geometries=polyline6&alternatives=true&overview=full&steps=true&avoid_maneuver_radius=0&bearings=274.2128601,90;&layers=0;&continue_straight=false&annotations=congestion,duration,distance&language=ja&roundabout_exits=false&voice_instructions=true&banner_instructions=true&voice_units=metric&waypoint_names=;日本,%20東京都東京都世田谷区玉川2丁目14番19&waypoint_targets=;

**Comment by LukasPaczos** [comment]
Resolving this in https://github.com/mapbox/mapbox-navigation-android/pull/5138 particular problem in. There is a bigger problem of a route generation failure being delivered as success (also seen in https://github.com/mapbox/mapbox-navigation-android/issues/5066) that we might need to workaround.

**Comment by LukasPaczos** [comment]
Following up on router failure obfuscation in https://github.com/mapbox/mapbox-navigation-android/pull/5139.

Great catch on this one @kmadsen!
