### ISSUE TITLE
NullPointException with MockLocationEngine in 0.7.0

### ISSUE THREAD

**Issue by josephquzhou** [mapbox/mapbox-navigation-android#519]
@danesfeder Could you help me with this? Thanks!

java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationMetricsWrapper.rerouteEvent(NavigationMetricsWrapper.java:118)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationQueueContainer.sendRerouteEvent(NavigationQueueContainer.java:129)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationQueueContainer.updateRerouteQueue(NavigationQueueContainer.java:175)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationQueueContainer.updateCurrentLocation(NavigationQueueContainer.java:46)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onLocationChanged(NavigationService.java:173)
                                                                           at com.mapbox.services.android.navigation.v5.location.MockLocationEngine$LocationUpdateRunnable.run(MockLocationEngine.java:382)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by josephquzhou** [comment]
@danesfeder This sounds like a bug to me. No matter I do it keeps occurring.

**Comment by josephquzhou** [comment]
@danesfeder @tobrun 
This is what I found in MockLocationEngine.java.

  private class LocationUpdateRunnable implements Runnable {
    @Override
    public void run() {
      // Calculate the next steps points if the list becomes empty
      // so that the mock location continues along the route
      if (points.isEmpty()) {
        calculateStepPoints();
      }

      if (!points.isEmpty()) {
        // Notify of an update
        Location location = mockLocation(points.get(0));
        for (LocationEngineListener listener : locationListeners) {
          listener.onLocationChanged(location);
        }
        points.remove(0);
      } else {
        Location location = getLastLocation();
        for (LocationEngineListener listener : locationListeners) {
          listener.onLocationChanged(location);
        }
      }


Location location = getLastLocation(); So location could be null. And if you pass this to onLocationChanged this is problematic. Am I right?

**Comment by danesfeder** [comment]
@josephquzhou Yeah you're right - queue'd up a PR to fix this:  https://github.com/mapbox/mapbox-navigation-android/pull/523 Thanks for debugging this!
