### ISSUE TITLE
Crash when launching Navigation UI

### ISSUE THREAD

**Issue by deleonAndroid3** [mapbox/mapbox-navigation-android#521]
I get this error whenever I try to launch navigation

> java.lang.NoSuchFieldError: No static field navigationView of type I in class Lcom/mapbox/services/android/navigation/ui/v5/R$id; or its superclasses (declaration of 'com.mapbox.services.android.navigation.ui.v5.R$id' appears in /data/app/com.training.android.undivided-1/split_lib_slice_4_apk.apk)
                                                                                    at com.mapbox.services.android.navigation.ui.v5.NavigationActivity.onCreate(NavigationActivity.java:21)
                                                                                    at android.app.Activity.performCreate(Activity.java:6001)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368)
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:144)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5235)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

My dependencies

> compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.2.0'
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.3@aar')
 { transitive=true }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.1-SNAPSHOT'
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') 
{ transitive = true }

**Comment by tobrun** [comment]
Thank you for the report, could you list your `build.gradle` dependency section?
This looks like a dependency mismatch issue.

**Comment by deleonAndroid3** [comment]
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "com.training.android.undivided"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    jcenter()
    maven { url 'https://maven.fabric.io/public' }
    maven { url "https://maven.google.com" }
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    mavenLocal()
    mavenCentral()
    google()
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile "android.arch.lifecycle:extensions:1.0.0"
    compile "android.arch.persistence.room:runtime:1.0.0"
    annotationProcessor "android.arch.lifecycle:compiler:1.0.0"
    annotationProcessor "android.arch.persistence.room:compiler:1.0.0"


    //MapBox
    compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.2.0'
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.3@aar') { transitive=true }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.1-SNAPSHOT'
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') { transitive = true }

    //ButterKnife
    compile 'com.jakewharton:butterknife:8.8.1'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.8.1'

    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support:support-v4:26.1.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.google.android.gms:play-services-places:11.6.0'
    compile 'com.google.android.gms:play-services-maps:11.6.0'
    compile 'com.google.android.gms:play-services-location:11.6.0'
    compile 'com.android.support:recyclerview-v7:26.1.0'
    compile 'com.android.support:design:26.1.0'
    compile 'com.wang.avi:library:2.1.3'
    compile 'com.roughike:bottom-bar:2.3.1'
    compile 'com.google.code.gson:gson:2.8.1'
    compile 'com.google.firebase:firebase-auth:11.6.0'
    compile 'com.google.android.gms:play-services-auth:11.6.0'
    compile 'com.firebaseui:firebase-ui-auth:1.2.0'
    compile 'jp.wasabeef:blurry:2.1.1'
    testCompile 'junit:junit:4.12'
}
apply plugin: 'com.google.gms.google-services'

```

**Comment by tobrun** [comment]
could you try updating `mapbox-android-sdk` to use 5.2.0 stable?

**Comment by danesfeder** [comment]
Thanks @tobrun! 

@deleonAndroid3 For the navigation UI, you should _only_ need:
```
implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') {
    transitive = true
}
```
This will include the location layer plugin, the map SDK, and the core navigation logic and will prevent any dependencies from getting tangled causing these kinds of errors.  We are working hard to release `0.7.1` ASAP - stay tuned!

**Comment by deleonAndroid3** [comment]
I still get the same issue when I change to `0.7.0` and when I use `5.2.0` I get this error 
```
java.lang.NoClassDefFoundError: com.mapbox.services.android.telemetry.location.LostLocationEngine
at com.mapbox.services.android.telemetry.location.LostLocationEngineFactory.supply(LostLocationEngineFactory.java:17)
at com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:44)
at com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(LocationEngineProvider.java:23)
at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54)
at com.training.android.undivided.NavigationMode.NavigationMode.onCreate(NavigationMode.java:79)
at android.app.Activity.performCreate(Activity.java:6001)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2261)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2368)
at android.app.ActivityThread.access$800(ActivityThread.java:144)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5235)                                                                                  
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

Pointing to this line

>  Mapbox.getInstance(this, getString(R.string.access_token));

**Comment by Danny-James** [comment]
@deleonAndroid3, I believe @danesfeder is saying to remove the following from your gradle configuration

```
//MapBox
    compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.2.0'
    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.3@aar') { transitive=true }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.1-SNAPSHOT'
```

Your gradle will only contain the following

```
//MapBox
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') { 
        transitive = true 
    }
```

The LostLocationEngine I believe has been removed from the Map SDK but has been included in the `0.7.1-SNAPSHOT`

**Comment by deleonAndroid3** [comment]
After removing 
```
compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.2.0'
compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0-beta.3@aar') { transitive=true }
compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.1-SNAPSHOT'
```
I still get the same error 
```
java.lang.NoSuchFieldError: No static field navigationView of type I in class Lcom/mapbox/services/android/navigation/ui/v5/R$id; or its superclasses (declaration of 'com.mapbox.services.android.navigation.ui.v5.R$id' appears in /data/app/com.training.android.undivided-1/split_lib_slice_4_apk.apk)

```
and another one
```
FusedLocationProviderServiceDelegate: Error occurred trying to report a new Locationandroid.os.DeadObjectException
at android.os.BinderProxy.transactNative(Native Method)
at android.os.BinderProxy.transact(Binder.java:496)
at com.mapzen.android.lost.internal.IFusedLocationProviderCallback$Stub$Proxy.onLocationChanged(IFusedLocationProviderCallback.java:129)
at com.mapzen.android.lost.internal.FusedLocationProviderServiceDelegate.reportLocation(FusedLocationProviderServiceDelegate.java:95)
at com.mapzen.android.lost.internal.FusionEngine.onLocationChanged(FusionEngine.java:196)
at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:281)
at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:210)
at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:233)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5235)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by sstolz** [comment]
Hi guyz,

Same problem for me when calling a NavigationLauncher object with startNavigation method (in Kotlin) :

```
val navOptions = NavigationViewOptions.builder()
                                .directionsRoute(currentRoute)
                                .awsPoolId(null)
                                .shouldSimulateRoute(true)

NavigationLauncher.startNavigation(this@NavigationActivity, navOptions.build())
```

The NavigationActivity is launched with a "click me" button in a MainActivity and then the route come from a NavigationRoute.builder() call (that is good because I displayed the route on the map). 

Got only the navigation-ui in 0.7.1-SNAPSHOT as U recommend :

```
dependencies {

    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'

    testImplementation 'junit:junit:4.12'

    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    compile 'org.jetbrains.kotlin:kotlin-stdlib-jre7:1.1.61'

    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') {
        transitive = true
    }

    compile('io.fabric.sdk.android:fabric:1.3.10@aar') {
        transitive = true;
    }
}
```

**Comment by konskons5** [comment]
Launching the Navigation I get: 

FATAL EXCEPTION: main
                                                                     Process: com.klab.klabclient, PID: 30113
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLongitude()' on a null object reference
                                                                         at com.mapbox.services.android.navigation.v5.location.MockLocationEngine.getLastLocation(MockLocationEngine.java:138)
                                                                         at com.mapbox.services.android.navigation.v5.navigation.NavigationService.validLocationUpdate(NavigationService.java:183)
                                                                         at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onLocationChanged(NavigationService.java:170)
                                                                         at com.mapbox.services.android.navigation.v5.location.MockLocationEngine$LocationUpdateRunnable.sendLocationUpdate(MockLocationEngine.java:400)
                                                                         at com.mapbox.services.android.navigation.v5.location.MockLocationEngine$LocationUpdateRunnable.run(MockLocationEngine.java:384)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

with 

    compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0@aar') { transitive=true }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.7.1-SNAPSHOT'
    compile ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') { transitive = true}

**Comment by nileshinfograins** [comment]
yes i'm getting same issue with LostLocationEngine
art: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.services.android.telemetry.location.LostLocationEngine>
AndroidRuntime: FATAL EXCEPTION: main
                                                           Process: com.offerak, PID: 1843
                                                           java.lang.NoClassDefFoundError: com.mapbox.services.android.telemetry.location.LostLocationEngine
                                                               at com.mapbox.services.android.telemetry.location.LostLocationEngineFactory.supply(LostLocationEngineFactory.java:17)
                                                               at com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:44)
                                                               at com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(LocationEngineProvider.java:23)
                                                               at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54)
                                                               at com.offerak.activity.NewMapboxActivity.onCreate(NewMapboxActivity.java:79)
                                                               at android.app.Activity.performCreate(Activity.java:6575)
                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3121)
                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3278)
                                                               at android.app.ActivityThread.access$1000(ActivityThread.java:211)
                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                               at android.os.Looper.loop(Looper.java:145)
                                                               at android.app.ActivityThread.main(ActivityThread.java:6918)
                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                               at java.lang.reflect.Method.invoke(Method.java:372)
                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Successfully bound to service but never got onServiceConnected callback

and my dependencies are :-

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support:support-v13:27.0.2'
    implementation 'com.android.support:design:27.0.2'
    implementation 'com.android.support:cardview-v7:27.0.2'
    implementation 'com.android.support:recyclerview-v7:27.0.2'
    implementation 'com.rengwuxian.materialedittext:library:2.1.4'
    implementation 'com.google.android.gms:play-services-maps:11.6.2'
    implementation 'com.google.android.gms:play-services-location:11.6.2'
    implementation 'com.google.android.gms:play-services-analytics:11.6.2'
    implementation 'com.google.firebase:firebase-messaging:11.6.2'
    implementation 'com.google.android.gms:play-services-analytics:11.6.2'
    implementation 'com.google.maps.android:android-maps-utils:0.5'
    implementation 'com.github.bumptech.glide:glide:3.7.0'
    implementation 'com.soundcloud.android:android-crop:1.0.1@aar'
    implementation 'com.wdullaer:materialdatetimepicker:3.2.2'
    implementation 'com.akexorcist:googledirectionlibrary:1.0.4'
    implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0@aar') {
        transitive = true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.3'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.6.3') {
        transitive = true
    }
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation project(':MaterialDesign')
    implementation project(':TabIndicator')
}

**Comment by nileshinfograins** [comment]
now is downgrade the dependencies and getting this issue when starting navigation :- 

FATAL EXCEPTION: main
                                                             Process: , PID: 27579
                                                             java.lang.ClassCastException: com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin_LifecycleAdapter cannot be cast to android.arch.lifecycle.GeneratedAdapter
                                                                 at android.arch.lifecycle.Lifecycling.createGeneratedAdapter(Lifecycling.java:79)
                                                                 at android.arch.lifecycle.Lifecycling.getCallback(Lifecycling.java:62)
                                                                 at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:346)
                                                                 at android.arch.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:162)
                                                                 at com.mapbox.services.android.navigation.ui.v5.NavigationView.initLifecycleObservers(NavigationView.java:466)
                                                                 at com.mapbox.services.android.navigation.ui.v5.NavigationView.onMapReady(NavigationView.java:168)
                                                                 at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:946)
                                                                 at com.mapbox.mapboxsdk.maps.MapView$MapCallback.access$1000(MapView.java:911)
                                                                 at com.mapbox.mapboxsdk.maps.MapView$MapCallback$1.run(MapView.java:929)
                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:145)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6918)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support:support-v13:27.0.2'
    implementation 'com.android.support:design:27.0.2'
    implementation 'com.android.support:cardview-v7:27.0.2'
    implementation 'com.android.support:recyclerview-v7:27.0.2'
    implementation 'com.rengwuxian.materialedittext:library:2.1.4'
    implementation 'com.google.android.gms:play-services-maps:11.6.2'
    implementation 'com.google.android.gms:play-services-location:11.6.2'
    implementation 'com.google.android.gms:play-services-analytics:11.6.2'
    implementation 'com.google.firebase:firebase-messaging:11.6.2'
    implementation 'com.google.android.gms:play-services-analytics:11.6.2'
    implementation 'com.google.maps.android:android-maps-utils:0.5'
    implementation 'com.github.bumptech.glide:glide:3.7.0'
    implementation 'com.soundcloud.android:android-crop:1.0.1@aar'
    implementation 'com.wdullaer:materialdatetimepicker:3.2.2'
    implementation 'com.akexorcist:googledirectionlibrary:1.0.4'
    implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:5.1.4@aar') {
        transitive = true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.6.3'
    implementation('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.6.3') {
        transitive = true
    }
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation project(':MaterialDesign')
    implementation project(':TabIndicator')
}

**Comment by danesfeder** [comment]
This was a result of upgrading the Navigation UI to 5.2.0 Maps SDK and should be resolved in the latest version of the UI dependency.
