### ISSUE TITLE
Flaky test TripServiceTest.checkNotificationContent(TripServiceTest.kt:38)

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#5223]
https://console.firebase.google.com/u/1/project/mapbox-navigation-android/testlab/histories/bh.15676ee24df688cf/matrices/8770419840010862810/executions/bs.1a5c332da89e972f/testcases/1

```
java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at com.mapbox.navigation.core.trip.service.TripServiceTest.checkNotificationContent(TripServiceTest.kt:38)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
```

**Comment by Guardiola31337** [comment]
This is happening lately on the `Pixel 6, API Level 31` tests e.g. https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.15676ee24df688cf/matrices/6629851720912618809/executions/bs.f42d4999ad7a93d5 https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/18325/workflows/6561b47e-8ce6-4079-ab60-fd2f2e40b8d0/jobs/84973

cc @mapbox/navigation-android
