### ISSUE TITLE
androidx.startup.StartupException when upgrading to 2.2.0-alpha

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#5227]
**Android API:**
**Mapbox Navigation SDK version:** 2.2.0-alpha.2

### Steps to trigger behavior

 1. Bump downstream app to version 2.2.0-alpha.2
 2. Compile and run

This could be specific to our onetap app solution, but I'm assuming if it is there it exists elsewhere.

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.onetap.app, PID: 13223
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common9Scheduler15CreateSequencedENS1_17DestructionPolicyE" referenced by "/data/app/~~lbx0KzjVqgPWM7mkq31LNg==/com.mapbox.onetap.app-b-PnPP8YYDS5Q6weKrfLvg==/base.apk!/lib/arm64-v8a/libnavigator-android.so"...
        at android.app.ActivityThread.installProvider(ActivityThread.java:7426)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6938)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6709)
        at android.app.ActivityThread.access$1500(ActivityThread.java:247)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7838)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common9Scheduler15CreateSequencedENS1_17DestructionPolicyE" referenced by "/data/app/~~lbx0KzjVqgPWM7mkq31LNg==/com.mapbox.onetap.app-b-PnPP8YYDS5Q6weKrfLvg==/base.apk!/lib/arm64-v8a/libnavigator-android.so"...
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:162)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2404)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2374)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7421)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6938) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6709) 
        at android.app.ActivityThread.access$1500(ActivityThread.java:247) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2053) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7838) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common9Scheduler15CreateSequencedENS1_17DestructionPolicyE" referenced by "/data/app/~~lbx0KzjVqgPWM7mkq31LNg==/com.mapbox.onetap.app-b-PnPP8YYDS5Q6weKrfLvg==/base.apk!/lib/arm64-v8a/libnavigator-android.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at com.mapbox.common.loader.MapboxLibraryLoader.load(MapboxLibraryLoader.kt:19)
        at com.mapbox.navigator.MapboxNavigationNativeInitializer.create(MapboxNavigationNativeInitializer.kt:16)
        at com.mapbox.navigator.MapboxNavigationNativeInitializer.create(MapboxNavigationNativeInitializer.kt:10)
```

**Comment by kmadsen** [comment]
Seems related to this one https://github.com/mapbox/mapbox-navigation-android/pull/4027

Which was introduced in 2.2.0-alpha https://github.com/mapbox/mapbox-navigation-android/commit/a554bd10372680908ab61128b877407f57291193

**Comment by LukasPaczos** [comment]
https://github.com/mapbox/mapbox-navigation-android/pull/4027 landed back in February, I doubt it's related.

Maybe this could be caused by the Common SDK version brought in by Search and Nav SDK in the downstream app which are mismatched.

**Comment by kmadsen** [comment]
> Maybe this could be caused by the Common SDK version brought in by Search and Nav SDK in the downstream app which are mismatched.

Yeah that checks out, 1tap and android-auto depend on search. Seems this can be considered blocked until the search upgrade

Common SDK 20.1.1 https://github.com/mapbox/mapbox-search-android/releases/tag/v1.0.0-beta.23
Common SDK 20.1.0 https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.2.0-alpha.1
Common SDK 21.0.0-rc.1 https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.2.0-alpha.1

**Comment by LukasPaczos** [comment]
Thanks for checking :+1: we should be good to close here then, right?
