### ISSUE TITLE
com.mapbox.navigation.ui:1.6.1 crash during configurations change

### ISSUE THREAD

**Issue by Ilya-Gazman-2** [mapbox/mapbox-navigation-android#5287]
**Android API: 29+**
**com.mapbox.navigation.ui:1.6.1**

### Steps to trigger behavior

 1. Create a `com.mapbox.navigation.ui.NavigationView` in a new fragment
 2. Wait for the night, so the device will go into a dark mode(don't listen for configurations changes in the activity)
 3. Call to start navigation after the fragment was recreated

### Expected behavior
No crashing

### Actual behavior
A crash

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.navigation.ui.NavigationViewEventDispatcher.onNavigationFinished()' on a null object reference
        at com.mapbox.navigation.ui.NavigationViewModel$3.onSessionStateChanged(NavigationViewModel.java:531)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.registerStateObserver(MapboxTripSession.kt:309)
        at com.mapbox.navigation.core.MapboxNavigation.registerTripSessionStateObserver(MapboxNavigation.kt:519)
        at com.mapbox.navigation.ui.NavigationViewModel.addNavigationListeners(NavigationViewModel.java:448)
        at com.mapbox.navigation.ui.NavigationViewModel.initializeNavigation(NavigationViewModel.java:438)
        at com.mapbox.navigation.ui.NavigationViewModel.initialize(NavigationViewModel.java:220)
        at com.mapbox.navigation.ui.NavigationView.initializeNavigation(NavigationView.java:935)
        at com.mapbox.navigation.ui.NavigationView.startNavigation(NavigationView.java:497)
```

### Why do I think this is happening?
During fragment recreation, a new view is created before the old view is destroyed. 
After the old view is destroyed it calls to `com.mapbox.navigation.ui.NavigationViewModel.onDestroy`. It sets the `navigationViewEventDispatcher` to `null`.
When the new view calls to `startNavigation` the app is crashing because `navigationViewEventDispatcher` is `null`.

The `NavigationViewModel` is using an activity life cycle, so you should not couple it with the View life cycle. I bet this causes a bunch of other bugs as well.

## A workaround

Before starting navigation, check for this bug and attempt to reinitialize the view

### Check for the bug
```
    fun isNavigationViewEventDispatcherNullBug(): Boolean {
        val navigationViewModel =
            ViewModelProvider(requireActivity()).get(NavigationViewModel::class.java)
        val field = navigationViewModel.javaClass.getDeclaredField("navigationViewEventDispatcher")
        field.isAccessible = true
        return field.get(navigationViewModel) == null
    }
```
### Reinitialize the view
```
    fun reinitializeNavigationView() {
        val methods = NavigationView::class.java.declaredMethods
        methods.filter {
            arrayOf(
                "initializeNavigationEventDispatcher",
                "initializeInstructionListener",
                "initializeSummaryBottomSheet"
            ).contains(it.name)
        }.forEach {
            it.isAccessible = true
            it.invoke(navigationView)
        }
    }
```

**Comment by Zayankovsky** [comment]
@Ilya-Gazman-2 are you sure a new view is created before the old one is destroyed, i.e. `onCreateView` is called before `onDestroyView`? I couldn't reproduce such behavior during a configuration change. Maybe it would help me if you could share a project where this call order can be observed.

**Comment by Ilya-Gazman-2** [comment]
@Zayankovsky you are right, I created a sample project for you and I saw that it's not happening during a configuration change but it does happen during navigation using the Android navigation component. 

Here is an example project I created for you to demonstrate this.

Step 1: Click navigate
Step 2: Click refresh log

![image](https://user-images.githubusercontent.com/83291294/146960393-9740e675-d73a-43fd-b4a2-c4eb30435b3a.png)


Note that this can happen in many scenarios of fragment navigation. 
Also, I wonder what kind of bugs you might get when having multiple instances of the same fragment in the stack. 
You really should not update your ViewModel during the View lifecycle.

**Comment by Zayankovsky** [comment]
Yes, view lifecycles do overlap when navigating between fragments. But that shouldn't happen during configuration change, which was your original question. 
For v1.x it is a known limitation that you can't have multiple `NavigationView`s in a single activity. If you really need multiple `NavigationView`s working in parallel, then I'm afraid you'll have to create a separate activity for each view. For a case of navigating between fragments I suggest to create a shared helper (e.g. a `ViewModel` tied to your activity), that would keep track of a current active `NavigationView`, so that you can destroy it before creating a new one, even if `onDestroyView` for that fragment hasn't been called yet. 
It's unlikely that we will remove this limitation in v1.x, as there are ways around it. For v2.x we are currently rewriting `NavigationView` and are going to move away from using activity lifecycle. You can track this progress in #5162 if you want to.

**Comment by abhishek1508** [comment]
@Ilya-Gazman-2 

Thanks for using the Mapbox Navigation SDK for Android and being a valued customer.

Mapbox will be soon deprecating any support for `v0` and `v1` versions of the SDK. To facilitate this transition we’re launching a new drop-in UI component into `v2`, equivalent to the existing `NavigationView` `v1` in its design goals, however with a more modern and customizable API. 

We plan to launch this new drop-in UI component as a Developer Preview feature in April, as part of the `v2.5` series. Since you are using `NavigationView` with `v1`, we’d love to hear your feedback so that we can incorporate it ahead of a GA release.

If you’re interested in having early access to the upcoming drop-in UI for `v2` and its documentation, drop a comment on this ticket or send an email to abhishek.kejriwal@mapbox.com

/cc @zugaldia @AhmerKhan1
