### ISSUE TITLE
null sessionState.eventLocation() passed to NavigationMetricsWrapper.rerouteEvent

### ISSUE THREAD

**Issue by josephquzhou** [mapbox/mapbox-navigation-android#535]
@danesfeder I noticed that you have done some changes to MockLocationEngine. However I still get the following error.

 java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationMetricsWrapper.rerouteEvent(NavigationMetricsWrapper.java:118)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationQueueContainer.sendRerouteEvent(NavigationQueueContainer.java:129)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationQueueContainer.updateRerouteQueue(NavigationQueueContainer.java:175)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationQueueContainer.updateCurrentLocation(NavigationQueueContainer.java:46)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onLocationChanged(NavigationService.java:173)
                                                                           at com.mapbox.services.android.navigation.v5.location.MockLocationEngine$LocationUpdateRunnable.run(MockLocationEngine.java:382)

The reason for that is because a null sessionState.eventLocation() passed to NavigationMetricsWrapper.rerouteEvent which cannot accept a null location.

Can you please look at it? Thanks!

**Comment by josephquzhou** [comment]
@danesfeder Even with both navigation:0.7.1-SNAPSHOT and navigation-ui:0.7.1-SNAPSHOT I still get the same crash.

**Comment by josephquzhou** [comment]
@danesfeder after some code changes, with both 0.7.1-SNAPSHOT, I get a different error (see below)

com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: Layer mapbox-navigation-route-shield-layer-1 already exists
                                                                           at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddLayer(Native Method)
                                                                           at com.mapbox.mapboxsdk.maps.NativeMapView.addLayerBelow(NativeMapView.java:676)
                                                                           at com.mapbox.mapboxsdk.maps.MapboxMap.addLayerBelow(MapboxMap.java:330)
                                                                           at com.mapbox.services.android.navigation.ui.v5.utils.MapUtils.addLayerToMap(MapUtils.java:63)
                                                                           at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addRouteShieldLayer(NavigationMapRoute.java:464)
                                                                           at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.drawRoutes(NavigationMapRoute.java:333)
                                                                           at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.onProgressChange(NavigationMapRoute.java:696)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:143)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:194)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:83)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by danesfeder** [comment]
@cammace not related to the original issue, but this looks like an issue with the `NavigationMapRoute` - I haven't run into this myself.  Any idea what could be causing an attempt to add the route shield layer twice?

**Comment by Grsmto** [comment]
Hey, just to confirm that the issue of this thread is gone using 0.7.1-SNAPSHOT. 👍

**Comment by josephquzhou** [comment]
@cammace I agreed with Dan that the problem is a new problem which is related to NavigationMapRoute. It happens right after the second time I call NavigationRoute.getRoute() and successfully get a response. Please have a look at it. Basically I got stuck because of this. Thanks!

**Comment by josephquzhou** [comment]
@cammace Also this problem only happens when navigation is running.

**Comment by danesfeder** [comment]
Closing in favor of https://github.com/mapbox/mapbox-navigation-android/issues/543
