### ISSUE TITLE
addVoiceInstructionObserver instrumentation test is failing

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#5364]
**Mapbox Navigation SDK version:** 2.3.0-alpha.1

Some details in this ticket. https://github.com/mapbox/mapbox-navigation-android/pull/5363#issuecomment-1013555221
The issue was also blocking a pull request with no functional change https://github.com/mapbox/mapbox-navigation-android/pull/5103

```
org.junit.ComparisonFailure: expected:<[Head east on Fulton Street, then turn left onto 27th Avenue]> but was:<[In a quarter mile, Turn left onto 27th Avenue.]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at com.mapbox.navigation.instrumentation_tests.ui.navigationview.NavigationViewExternalObserversTests$addVoiceInstructionObserver$1.invoke$lambda-0(NavigationViewExternalObserversTests.kt:95)
at com.mapbox.navigation.instrumentation_tests.ui.navigationview.NavigationViewExternalObserversTests$addVoiceInstructionObserver$1.$r8$lambda$7XPH97LIxfP_zaWHFgAZOSwPbNU(Unknown Source:0)
at com.mapbox.navigation.instrumentation_tests.ui.navigationview.NavigationViewExternalObserversTests$addVoiceInstructionObserver$1$$ExternalSyntheticLambda0.onNewVoiceInstructions(Unknown Source:2)
at com.mapbox.navigation.dropin.NavigationView$observeVoiceInstructions$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:137)
at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt:351)
```

**Comment by kmadsen** [comment]
When this issue is fixed, make sure to re-enable the branch protection rules on `main` to include `instrumentation-tests`
![Screen Shot 2022-01-14 at 4 43 50 PM](https://user-images.githubusercontent.com/3021882/149601942-3475473a-d19a-422e-b7eb-394d011172b8.png)

**Comment by kmadsen** [comment]
Instrumentation tests on `main` have looked good https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android?branch=main&filter=all

Re-enabled the "Require status checks" for `instrumentation-tests`.

Discussing whether this is still a flaky test or if it was resolved by something. Here is another place it was seen a week ago https://github.com/mapbox/mapbox-navigation-android/pull/5356#issuecomment-1011147136

**Comment by kmadsen** [comment]
Closing here because when i opened this issue it was failing every time. Can re-open it as "flaky" if we continue to run into problems
