### ISSUE TITLE
Caused by: java.lang.ClassCastException: Please ensure that the provided Context is a valid LifecycleOwner

### ISSUE THREAD

**Issue by MehdiFal** [mapbox/mapbox-navigation-android#542]
I'm facing something pretty odd. I've included the Libraries successfully etc...

However, when launching a navigation Event, I experience a ~10 seconds delay then a crash with following stacktrace. 

```
AndroidRuntime: FATAL EXCEPTION: main
Process: com.my_app, PID: 30835
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myapp/com.mapbox.services.android.navigation.ui.v5.NavigationActivity}: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6541)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: android.view.InflateException: Binary XML file line #0: Binary XML file line #0: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance0(Native Method)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
    at android.view.LayoutInflater.createView(LayoutInflater.java:647)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
    at com.mapbox.services.android.navigation.ui.v5.NavigationActivity.onCreate(NavigationActivity.java:28)
    at android.app.Activity.performCreate(Activity.java:6975)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
    at android.app.ActivityThread.-wrap11(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6541)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.ClassCastException: Please ensure that the provided Context is a valid LifecycleOwner
    at com.mapbox.services.android.navigation.ui.v5.NavigationView.initNavigationViewObserver(NavigationView.java:393)
    at com.mapbox.services.android.navigation.ui.v5.NavigationView.init(NavigationView.java:320)
    at com.mapbox.services.android.navigation.ui.v5.NavigationView.<init>(NavigationView.java:98)
    at com.mapbox.services.android.navigation.ui.v5.NavigationView.<init>(NavigationView.java:91)
    at java.lang.reflect.Constructor.newInstance0(Native Method) 
    at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
    at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
    at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
    at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
    at com.mapbox.services.android.navigation.ui.v5.NavigationActivity.onCreate(NavigationActivity.java:28) 
    at android.app.Activity.performCreate(Activity.java:6975) 
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
    at android.app.ActivityThread.-wrap11(Unknown Source:0) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
    at android.os.Handler.dispatchMessage(Handler.java:105) 
    at android.os.Looper.loop(Looper.java:164) 
    at android.app.ActivityThread.main(ActivityThread.java:6541) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

Any idea? (I have included the Mapbox Navigatui / ui as project dependencies so I can tweek the code if needed)

**Comment by MehdiFal** [comment]
My bad. It was a mistake from my side.

**Comment by MehdiFal** [comment]
Reopening it as it's still occurring, with the same exact code of the demo project. 
Any thoughts?
Thanks.

**Comment by MehdiFal** [comment]
Hi everyone, 

The trick was to implement the new Arch component `LifecycleOwner` on the activity.

So my activity's code becomes:

```
public class MapboxFullNavigationActivity extends AppCompatActivity implements NavigationViewListener, LifecycleOwner {
	
	private final LifecycleRegistry lifecycleRegistry = new LifecycleRegistry (this);
	
	private NavigationView navigationView;
       
        // .......

        @NonNull
	@Override
	public Lifecycle getLifecycle () {
		return lifecycleRegistry;
	}
```

**Comment by danesfeder** [comment]
@MehdiFal Yeah we require the `Activity` or `Fragment` you use to launch the turn-by-turn UI to be a `LifecycleOwner` - let us know if you run into any other issues and thanks for checking out the SDK!

**Comment by AlexeyIke** [comment]
Hello,
has same error on run navigation from my app: 
Unable to start activity ComponentInfo{ru.vl.map.debug/com.mapbox.services.android.navigation.ui.v5.NavigationActivity 
... Binary XML file line #8: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
... ClassNotFoundException: Didn't find class "android.arch.lifecycle.ViewModelProviders" on path: DexPathList
it happens on using "minifyEnabled true" rule or using multidex app  without minify rule (my app large)
I've add proguard rules:

## Android architecture components: Lifecycle
# LifecycleObserver's empty constructor is considered to be unused by proguard
-keepclassmembers class * implements android.arch.lifecycle.LifecycleObserver {
    <init>(...);
}
# ViewModel's empty constructor is considered to be unused by proguard
-keepclassmembers class * extends android.arch.lifecycle.ViewModel {
    <init>(...);
}
# keep Lifecycle State and Event enums values
-keepclassmembers class android.arch.lifecycle.Lifecycle$State { *; }
-keepclassmembers class android.arch.lifecycle.Lifecycle$Event { *; }
# keep methods annotated with @OnLifecycleEvent even if they seem to be unused
# (Mostly for LiveData.LifecycleBoundObserver.onStateChange(), but who knows)
-keepclassmembers class * {
    @android.arch.lifecycle.OnLifecycleEvent *;
}
But error the same: ClassNotFoundException: Didn't find class "android.arch.lifecycle.ViewModelProviders" on path
Mapbox SDK: 5.2.1
Navigation SDK: 0.8.0
mapboxServicesVersion : 2.2.9

Demo example works well, lately i try to use small project without minify lately

**Comment by josephcrowell** [comment]
The LifeCycleOwner you use needs to be also registered as the ViewTreeLifecycleOwner now.

**Comment by ankiimation** [comment]
> The LifeCycleOwner you use needs to be also registered as the ViewTreeLifecycleOwner now.

thanks, it worked
