### ISSUE TITLE
NavigationMapRoute CannotAddLayerException

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#543]
Capturing from https://github.com/mapbox/mapbox-navigation-android/issues/535#issuecomment-347300581

With `0.7.1-SNAPSHOT`, I get a different error (see below)
```
com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: Layer mapbox-navigation-route-shield-layer-1 already exists
at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddLayer(Native Method)
at com.mapbox.mapboxsdk.maps.NativeMapView.addLayerBelow(NativeMapView.java:676)
at com.mapbox.mapboxsdk.maps.MapboxMap.addLayerBelow(MapboxMap.java:330)
at com.mapbox.services.android.navigation.ui.v5.utils.MapUtils.addLayerToMap(MapUtils.java:63)
at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addRouteShieldLayer(NavigationMapRoute.java:464)
at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.drawRoutes(NavigationMapRoute.java:333)
at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.onProgressChange(NavigationMapRoute.java:696)
at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:143)
at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:194)
at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:83)
at android.os.Handler.handleCallback(Handler.java:751)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6119)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by josephquzhou** [comment]
@cammace Have you got time to have a look at this problem? Thanks！

**Comment by josephquzhou** [comment]
After using the stable release 0.7.1 I still got the exact same error. Please have a look at the issue. Thanks!

**Comment by danesfeder** [comment]
@cammace is this issue just a matter of guarding against trying to add a layer twice with the same Id?

**Comment by josephquzhou** [comment]
It seems that I only have this issue on the mock navigation mode.

**Comment by danesfeder** [comment]
@josephquzhou you're using `NavigationLauncher`?

**Comment by josephquzhou** [comment]
@danesfeder No, I don't use NavigationLauncher, because I have multiple way points. It seems that NavigationLauncher doesn't support way points. 

I use MapboxNavigation.startNavigation with a MockLocationEngine.

**Comment by danesfeder** [comment]
@josephquzhou Yeah not at the moment.  It seems like this could be related to multiple waypoints -  if the second leg is trying to be added to the same layer?

**Comment by josephquzhou** [comment]
@danesfeder Thanks! I think I might have a clue. Let me try to figure it out.

**Comment by josephquzhou** [comment]
@danesfeder No, it doesn't work. I think the problem is related to multiple routes support of NavigationMapRoute, which is added in 0.7.1.  For my app I need to generate new route during navigation automatically with additional way points.

It seems that I have to stay with 0.7.0

**Comment by danesfeder** [comment]
@Guardiola31337 you have been drawing routes with multiple waypoints right?  Can you confirm you have not been seeing this crash?

**Comment by danesfeder** [comment]
Going to go ahead and close this - can re-open if we begin to see this again 👀

**Comment by Guardiola31337** [comment]
Confirming that drawing routes with waypoints I'm not able to 👀 OP's crash.

**Comment by Xgamefactory** [comment]
we have same error after rerouting
using core navigation without NavView ui
```
com.mapbox.mapboxsdk.style.layers.CannotAddLayerException: Layer mapbox-navigation-route-shield-layer-1 already exists
        at com.mapbox.mapboxsdk.maps.NativeMapView.nativeAddLayer(Native Method)
        at com.mapbox.mapboxsdk.maps.NativeMapView.addLayerBelow(NativeMapView.java:676)
        at com.mapbox.mapboxsdk.maps.MapboxMap.addLayerBelow(MapboxMap.java:332)
        at com.mapbox.services.android.navigation.ui.v5.utils.MapUtils.addLayerToMap(MapUtils.java:63)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.addRouteShieldLayer(NavigationMapRoute.java:480)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.drawRoutes(NavigationMapRoute.java:324)
        at com.mapbox.services.android.navigation.ui.v5.route.NavigationMapRoute.onProgressChange(NavigationMapRoute.java:734)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:157)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:114)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:123)
        at android.os.Handler.handleCallback(Handler.java:733)
```

**Comment by saddahussain** [comment]
@Xgamefactory did you find any solution?

**Comment by Xgamefactory** [comment]
@saddahussain no we gave up using mapbox cant rely on such unserious tech support.

**Comment by saddahussain** [comment]
Sad to hear.

**Comment by saddahussain** [comment]
What a shame.
