### ISSUE TITLE
Navigation Activity from Navigation UI

### ISSUE THREAD

**Issue by deleonAndroid3** [mapbox/mapbox-navigation-android#563]
![capture](https://user-images.githubusercontent.com/20215889/33540876-dbf915a0-d907-11e7-9aa6-6667e056bc20.PNG)

```
java.lang.NoSuchFieldError: No static field navigationView of type I in class Lcom/mapbox/services/android/navigation/ui/v5/R$id; or its superclasses (declaration of 'com.mapbox.services.android.navigation.ui.v5.R$id' appears in /data/app/com.training.android.undivided-yRnbKe85lz8t2BV-YADltA==/split_lib_slice_4_apk.apk)
                                                                                  at com.mapbox.services.android.navigation.ui.v5.NavigationActivity.onCreate(NavigationActivity.java:29)
                                                                                  at android.app.Activity.performCreate(Activity.java:6975)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                                                                                  at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                  at android.os.Looper.loop(Looper.java:164)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by danesfeder** [comment]
Hey @deleonAndroid3, which version of the SDK are you adding in your `build.gradle`?  

This view ID should exist: https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/res/layout/activity_navigation.xml#L9

I would suggest a `Clean` --> `Build` to make sure your project is synced with the dependency files.  Thanks!

**Comment by deleonAndroid3** [comment]
```
android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "com.training.android.undivided"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
```

@danesfeder This is what I currently have in my `build.gradle`

**Comment by danesfeder** [comment]
@deleonAndroid3 Sorry, in your project `build.gradle`, where you are adding the dependency for our SDK

**Comment by deleonAndroid3** [comment]
@danesfeder I'm using 

```
 compile('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.7.1-SNAPSHOT') {
        transitive = true
    }
```

**Comment by danesfeder** [comment]
@deleonAndroid3 You need to add the `NavigationView` class to your XML and assign a resource ID - if you haven't done this, the result you are seeing will occur.  

```
<com.mapbox.services.android.navigation.ui.v5.NavigationView
        android:id="@+id/navigationView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        ...
        />
```

**Comment by anujgoel89** [comment]
@deleonAndroid3 make sure you dont name your layout file 'activity_navigation' if yes please rename it.
