### ISSUE TITLE
Instrumentation test failing sometimes

### ISSUE THREAD

**Issue by kmadsen** [mapbox/mapbox-navigation-android#5770]
`verify_history_files_are_recorded_and_readable_with_silent_waypoints`

https://app.circleci.com/pipelines/github/mapbox/mapbox-navigation-android/17897/workflows/44134dc8-7a92-495a-8cd0-ab2cdbc34a9f/jobs/81674

https://console.firebase.google.com/u/0/project/mapbox-navigation-android/testlab/histories/bh.54eb2dd57e959221/matrices/5304873808056687705/executions/bs.7e888e4297528ead

```
05-03 07:16:02.676: E/TestRunner(24075): junit.framework.AssertionFailedError: expected:<-77.031991> but was:<-77.031957>
05-03 07:16:02.676: E/TestRunner(24075): 	at junit.framework.Assert.fail(Assert.java:50)
05-03 07:16:02.676: E/TestRunner(24075): 	at junit.framework.Assert.failNotEquals(Assert.java:287)
05-03 07:16:02.676: E/TestRunner(24075): 	at junit.framework.Assert.assertEquals(Assert.java:102)
05-03 07:16:02.676: E/TestRunner(24075): 	at junit.framework.Assert.assertEquals(Assert.java:109)
05-03 07:16:02.676: E/TestRunner(24075): 	at com.mapbox.navigation.instrumentation_tests.core.MapboxHistoryTest.verifyHistoryEvents(MapboxHistoryTest.kt:246)
05-03 07:16:02.676: E/TestRunner(24075): 	at com.mapbox.navigation.instrumentation_tests.core.MapboxHistoryTest.verify_history_files_are_recorded_and_readable_with_silent_waypoints(MapboxHistoryTest.kt:220)
05-03 07:16:02.676: E/TestRunner(24075): 	at java.lang.reflect.Method.invoke(Native Method)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
05-03 07:16:02.676: E/TestRunner(24075): 	at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
05-03 07:16:02.676: E/TestRunner(24075): 	at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
05-03 07:16:02.676: E/TestRunner(24075): 	at androidx.test.rule.GrantPermissionRule$RequestPermissionStatement.evaluate(GrantPermissionRule.java:134)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
05-03 07:16:02.676: E/TestRunner(24075): 	at com.adevinta.android.barista.rule.cleardata.ClearDatabaseRule$apply$1.evaluate(ClearDatabaseRule.kt:31)
05-03 07:16:02.676: E/TestRunner(24075): 	at com.adevinta.android.barista.rule.cleardata.ClearPreferencesRule$1.evaluate(ClearPreferencesRule.java:26)
05-03 07:16:02.676: E/TestRunner(24075): 	at com.adevinta.android.barista.rule.cleardata.ClearFilesRule$apply$1.evaluate(ClearFilesRule.kt:25)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.Suite.runChild(Suite.java:128)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.Suite.runChild(Suite.java:27)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
05-03 07:16:02.676: E/TestRunner(24075): 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
05-03 07:16:02.676: E/TestRunner(24075): 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
05-03 07:16:02.676: E/TestRunner(24075): 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
05-03 07:16:02.676: E/TestRunner(24075): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
05-03 07:16:02.676: E/TestRunner(24075): ----- end exception -----
```

**Comment by kmadsen** [comment]
> verify_history_files_are_recorded_and_readable_with_silent_waypoints

```
05-03 07:16:02.676: E/TestRunner(24075): junit.framework.AssertionFailedError: expected:<-77.031991> but was:<-77.031957>
05-03 07:16:02.676: E/TestRunner(24075): 	at junit.framework.Assert.fail(Assert.java:50)
05-03 07:16:02.676: E/TestRunner(24075): 	at junit.framework.Assert.failNotEquals(Assert.java:287
```

Sometimes this test fails because of the integration with the initial location. It is expecting the first location to be the origin https://github.com/mapbox/mapbox-navigation-android/blob/9a785a4b8a0d4bf08d3a7b9869b0082c8823e9e0/instrumentation-tests/src/androidTest/java/com/mapbox/navigation/instrumentation_tests/utils/routes/MockRoutesProvider.kt#L21

This is not always, due to the history recorder. The location coordinate is being saved correctly, but the location passed to the history recorder is incorrect
