### ISSUE TITLE
IndexOutOfBoundsException in ViewportDataSourceProcessor.getPointsToFrameOnCurrentStep

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-navigation-android#5783]
Nav SDK: v2.5.0-beta.2

```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 4, Size: 3
       at java.util.ArrayList.get(ArrayList.java:437)
       at com.mapbox.navigation.ui.maps.camera.data.ViewportDataSourceProcessor.getPointsToFrameOnCurrentStep(ViewportDataSourceProcessor.kt:180)
       at com.mapbox.navigation.ui.maps.camera.data.MapboxNavigationViewportDataSource.onRouteProgressChanged(MapboxNavigationViewportDataSource.kt:490)
```

**Comment by LukasPaczos** [comment]
This seems to have happened right after a route was changed.
