### ISSUE TITLE
ArrayIndexOutOfBoundsException when calling MapboxNavigation.startNavigation() to pass an updated route

### ISSUE THREAD

**Issue by safecrossing** [mapbox/mapbox-navigation-android#591]
This is what happened after using 0.7.1. It seems this is related to the changes in MapboxNavigation.startNavigation(). 
    } else {
      // Update telemetry directions route
      navigationTelemetry.updateSessionRoute(directionsRoute);
    }

                                                                       java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
                                                                           at java.util.ArrayList.get(ArrayList.java:413)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationTelemetry.updateLastRerouteEvent(NavigationTelemetry.java:528)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.NavigationTelemetry.updateSessionRoute(NavigationTelemetry.java:226)
                                                                           at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.startNavigation(MapboxNavigation.java:368)
                                                                           at edu.cmu.jqz.joe_test9.MainActivity.onResponse(MainActivity.java:761)
                                                                           at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:159)
                                                                           at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by danesfeder** [comment]
Hey @safecrossing thanks for the report.  #589 just landed to address this.
