### ISSUE TITLE
App crashes on end of navigation if speed is higher than step length

### ISSUE THREAD

**Issue by Grsmto** [mapbox/mapbox-navigation-android#60]
**Platform:** Android 7.1.2
**SDK version:** Latest SNAPSHOT

### Steps to trigger behavior

 1. Open the `RerouteActivity.java`
 2. Set speed of the MockEngine to `60` on [this line](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/app/src/main/java/com/mapbox/services/android/navigation/testapp/activity/RerouteActivity.java#L78)
(2.1. Set destination coordinate to be sure you'll experience the bug: `-87.6910, 41.8542`)
 3. Reach the end of the path and observe crash

I thought this was specific to the mock engine but actually if I'm right this could happen in real life if car is going fast and GPS signal is slow I guess.

### Expected behavior
Navigation should end nicely

### Actual behavior
App crash with an NPE

**Comment by cammace** [comment]
Interesting, thanks for reporting, I'll look more into this over the weekend.

**Comment by Grsmto** [comment]
Ok have a great weekend then :)
I had a closer look to this and I figured out that when the user goes further than the very last step of the route, his location is snapped to the very last coordinate points of the last step, which is normal.
But, when `onLocationChanged` is called on `NavigationEngine`, the final `[RouteProgress](https://github.com/mapbox/mapbox-navigation-android/blob/master/navigation/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/NavigationEngine.java#L85)` object fail to be instantiated because an error occurs on the underlying stack: there is a `TurfMisc.lineSlice()` being called with the same coordinate for both start/end arguments, which generate an error.

Hope this help to identify the bug a bit faster!

**Comment by cammace** [comment]
Was this the crash you were seeing?

```
06-01 11:17:42.688 28987-28987/com.mapbox.services.android.navigation.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                Process: com.mapbox.services.android.navigation.testapp, PID: 28987
                                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Number com.google.gson.JsonElement.getAsNumber()' on a null object reference
                                                                                                    at com.mapbox.services.commons.geojson.Feature.getNumberProperty(Feature.java:231)
                                                                                                    at com.mapbox.services.api.utils.turf.TurfMisc.lineSlice(TurfMisc.java:58)
                                                                                                    at com.mapbox.services.android.navigation.v5.models.RouteStepProgress.<init>(RouteStepProgress.java:46)
                                                                                                    at com.mapbox.services.android.navigation.v5.models.RouteLegProgress.<init>(RouteLegProgress.java:37)
                                                                                                    at com.mapbox.services.android.navigation.v5.RouteProgress.<init>(RouteProgress.java:58)
                                                                                                    at com.mapbox.services.android.navigation.v5.NavigationEngine.onLocationChanged(NavigationEngine.java:85)
                                                                                                    at com.mapbox.services.android.navigation.v5.NavigationService.onLocationChanged(NavigationService.java:237)
                                                                                                    at com.mapbox.services.android.navigation.testapp.activity.MockLocationEngine$LocationUpdateRunnable.run(MockLocationEngine.java:349)
                                                                                                    at android.os.Handler.handleCallback(Handler.java:751)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                                    at android.os.Looper.loop(Looper.java:154)
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

The directions response would sometimes give the last step with only one coordinate. This would cause `TurfMisc.lineSlice()` to fail since the points were identical. I added an if statement checking for this case, fixed up other methods to return correct info in this case, and added a test to confirm the issues fixed. Fix was added to https://github.com/mapbox/mapbox-navigation-android/pull/50

Let me know if this resolves the issue on your end.

**Comment by Grsmto** [comment]
That's exactly that! Good catch! :)
