### ISSUE TITLE
Crash on navigation.getRoute()

### ISSUE THREAD

**Issue by kirtan-inexture** [mapbox/mapbox-navigation-android#622]
While calling getRoute method on navigation instance, I am having following error:

```
onFailure: navigation.getRoute()
   java.lang.IllegalArgumentException: Unexpected char 0x2122 at 27 in User-Agent value: TODO Linux/3.18.88-Reloaded™ (aarch64)
       at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:338)
       at okhttp3.Headers$Builder.add(Headers.java:288)
       at okhttp3.Request$Builder.addHeader(Request.java:177)
       at retrofit2.RequestBuilder.addHeader(RequestBuilder.java:85)
       at retrofit2.ParameterHandler$Header.apply(ParameterHandler.java:79)
       at retrofit2.ServiceMethod.toRequest(ServiceMethod.java:111)
       at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:184)
       at retrofit2.OkHttpCall.enqueue(OkHttpCall.java:91)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.enqueue(ExecutorCallAdapterFactory.java:62)
       at com.mapbox.api.directions.v5.MapboxDirections.enqueueCall(MapboxDirections.java:147)
       at com.mapbox.services.android.navigation.v5.navigation.NavigationRoute.getRoute(NavigationRoute.java:70)
```

Dependecies I am using: 

 ```
 compile ('com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.1@aar'){
        transitive=true
    }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.8.0'
    implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.8.0') {
        transitive = true
    }
```

Android Version: 8.1

**UPDATE:**

It seems device specific. My Custom ROM's kernal name includes unicode "TM" symbol. That is causing crash!

**Comment by danesfeder** [comment]
Thanks for bringing this to us @kirtan-inexture.  @cammace this looks like an issue with with our Android services, but more specifically Retrofit?

**Comment by danesfeder** [comment]
@kirtan-inexture can you check this issue with `0.9.0`?

**Comment by danesfeder** [comment]
This error is occurring in our services library.  I've opened this ticket https://github.com/mapbox/mapbox-java/issues/720
