### ISSUE TITLE
Android crash on construction of PredictiveCacheController.

### ISSUE THREAD

**Issue by kpennacchia** [mapbox/mapbox-navigation-android#6435]
Hello,

I'm trying to implement predictive caching following the [official guide](https://docs.mapbox.com/android/navigation/guides/advanced/offline/), however I am getting a crash immediately on constructing the `PredictiveCacheController`.

I've tried on various different emulators and physical devices, all with the same result. I don't know what I'm missing.

**Android API:** 27, 31
**Mapbox Navigation SDK version:** 2.8.0

For reference, these are all the Mapbox packages I'm using:
```
implementation 'com.mapbox.maps:android:10.8.1'
implementation 'com.mapbox.navigation:android:2.8.0'
implementation 'com.mapbox.mapboxsdk:mapbox-sdk-services:6.8.0'
```

A code snippet which triggers the crash:

```
val predictiveCacheController = PredictiveCacheController(
  PredictiveCacheOptions.Builder()
    .predictiveCacheMapsOptions(
      PredictiveCacheMapsOptions.Builder()
        .predictiveCacheLocationOptions(
          PredictiveCacheLocationOptions.Builder()
            .build()
        )
        .build()
      )
      .predictiveCacheNavigationOptions(
        PredictiveCacheNavigationOptions.Builder()
          .predictiveCacheLocationOptions(
            PredictiveCacheLocationOptions.Builder()
              .build()
            )
            .build()
          )
          .build()
)
```

Even the basic constructor exhibits the same crash.

```
val predictiveCacheController = PredictiveCacheController()
```

This is the relevant stack trace:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.wemakeapps.tourboss, PID: 4255
    java.lang.RuntimeException: Unable to start activity ComponentInfo{net.wemakeapps.tourboss/app.tourboss.GuidedNavigationActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException
        at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl.createNavigationPredictiveCacheController(MapboxNativeNavigatorImpl.kt:403)
        at com.mapbox.navigation.core.internal.PredictiveCache.createNavigationController(PredictiveCache.kt:65)
        at com.mapbox.navigation.ui.maps.PredictiveCacheController.<init>(PredictiveCacheController.kt:132)
        at app.tourboss.GuidedNavigationActivity.onCreate(GuidedNavigationActivity.kt:632)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by foyst** [comment]
+1 I'm also seeing this too

**Android API:** 33
**Mapbox Navigation SDK version:** 2.9.2

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.spiralindex.rusttorome, PID: 31338
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.spiralindex.rusttorome/com.spiralindex.rusttorome.navigation.NavigationActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3676)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException
        at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl.createNavigationPredictiveCacheController(MapboxNativeNavigatorImpl.kt:384)
        at com.mapbox.navigation.core.internal.PredictiveCache.createNavigationController(PredictiveCache.kt:65)
        at com.mapbox.navigation.ui.maps.PredictiveCacheController.<init>(PredictiveCacheController.kt:134)
        at com.mapbox.navigation.ui.maps.PredictiveCacheController.<init>(PredictiveCacheController.kt:115)
        at com.mapbox.navigation.ui.maps.PredictiveCacheController.<init>(PredictiveCacheController.kt:90)
        at com.mapbox.navigation.ui.maps.PredictiveCacheController.<init>(PredictiveCacheController.kt:85)
        at com.test.NavigationActivity$predictiveCacheController$2.invoke(NavigationActivity.kt:318)
        at com.test.NavigationActivity$predictiveCacheController$2.invoke(NavigationActivity.kt:318)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.test.NavigationActivity.getPredictiveCacheController(NavigationActivity.kt:318)
        at com.test.NavigationActivity.onCreate(NavigationActivity.kt:523)
        at android.app.Activity.performCreate(Activity.java:8290)
        at android.app.Activity.performCreate(Activity.java:8269)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by foyst** [comment]
Finally got to the bottom of this (a while ago but late replying to this) - I was accidentally calling PredictiveCacheController.createStyleMapControllers before MapboxNavigationApp.setup, which is what was causing my NPE.

Similar to https://github.com/mapbox/mapbox-navigation-android/issues/3064 I think

**Comment by Guardiola31337** [comment]
@kpennacchia could you double-check if you are calling PredictiveCacheController.createStyleMapControllers before MapboxNavigationApp.setup and see if that's the reason of the crash you're experiencing?

cc @foyst

**Comment by kpennacchia** [comment]
I resolved this by constructing `PredictiveCacheController` after `MapboxMap` had finished loading its style.
