### ISSUE TITLE
Crash appears after ending navigation

### ISSUE THREAD

**Issue by palto-ccadoret** [mapbox/mapbox-navigation-android#651]
Crash appears after ending navigation :

Device:
Samsung Galaxy j5
Android API level: 24

Its seems that you have a synchronization issue on NavigationLifecycleMonitor.

https://github.com/mapbox/mapbox-navigation-android/blob/d4a3ea0eb2ce5be7f3696fa1c6ee2b7589ef2673/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/metrics/NavigationLifecycleMonitor.java#L115 

Stack trace : ```
b.a.c.d: Index: 0, Size: 0
	at b.a.e.b.a$o.a(Functions.java:704)
	at b.a.e.b.a$o.accept(Functions.java:701)
	at b.a.e.d.j.b_(LambdaObserver.java:77)
	at b.a.e.d.j.a_(LambdaObserver.java:67)
	at b.a.e.e.d.r$a.g(ObservableObserveOn.java:200)
	at b.a.e.e.d.r$a.run(ObservableObserveOn.java:252)
	at b.a.a.b.b$b.run(HandlerScheduler.java:109)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6776)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:411)
	at com.mapbox.services.android.navigation.v5.navigation.a.c.a(NavigationLifecycleMonitor.java:114)
	at com.mapbox.services.android.navigation.v5.navigation.a.c.b(NavigationLifecycleMonitor.java:93)
	at com.mapbox.services.android.navigation.v5.navigation.n.j(NavigationTelemetry.java:553)
	at com.mapbox.services.android.navigation.v5.navigation.n.b(NavigationTelemetry.java:217)
	at com.mapbox.services.android.navigation.v5.navigation.d.c(MapboxNavigation.java:393)
	at com.less.line.navigation.NavigationManager.endNavigation(NavigationManager.java:219)
	at com.less.line.navigation.NavigationManager.startNavigation(NavigationManager.java:183)
	at com.less.line.navigation.NavigationLifecycle.onRideTripUpdate(NavigationLifecycle.java:72)
	at com.less.line.navigation.NavigationLifecycle.lambda$start$0$NavigationLifecycle(NavigationLifecycle.java:49)
	at com.less.line.navigation.NavigationLifecycle$$Lambda$1.accept(Unknown Source)
	at b.a.e.d.j.a_(LambdaObserver.java:63)
	... 10 more
```

**Comment by danesfeder** [comment]
Hey @palto-ccadoret, thanks for bringing this to us.  Do you mind providing the version of the SDK you are using?  https://github.com/mapbox/mapbox-navigation-android/pull/625 landed a couple weeks ago, preventing this crash.  We hope to get out `0.8.1` asap which will include this fix.

**Comment by palto-blubek** [comment]
(@palto-ccadoret's teammate here) we are using `0.8.0`.

**Comment by danesfeder** [comment]
@palto-blubek thank you, I'll update this ticket once the `0.9.0` release lands (sorry I was incorrect saying `0.8.1` and updated the comment above).  In the meantime, you can test that this fix works correctly with the `0.8.1-SNAPSHOT`, where the fix is currently implemented.

**Comment by danesfeder** [comment]
Fixed in `0.9.0`
