### ISSUE TITLE
FileSource: Failed to read the storage key

### ISSUE THREAD

**Issue by nafis042** [mapbox/mapbox-navigation-android#660]
I am getting the following error when moving from main to any activity:
01-22 20:42:47.667 11041-11041/com.mapbox.services.android.navigation.testapp E/FileSource: Failed to read the storage key: 

                                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String, boolean)' on a null object reference
                                                                                                at com.mapbox.mapboxsdk.storage.FileSource.getCachePath(FileSource.java:69)
                                                                                                at com.mapbox.mapboxsdk.storage.FileSource.getInstance(FileSource.java:48)
                                                                                                at com.mapbox.mapboxsdk.maps.MapView.onStart(MapView.java:356)
                                                                                                at com.mapbox.services.android.navigation.ui.v5.NavigationView.onStart(NavigationView.java:593)
                                                                                                at com.mapbox.services.android.navigation.ui.v5.NavigationView_LifecycleAdapter.callMethods(NavigationView_LifecycleAdapter.java:25)
                                                                                                at android.arch.lifecycle.SingleGeneratedAdapterObserver.onStateChanged(SingleGeneratedAdapterObserver.java:35)
                                                                                                at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:353)
                                                                                                at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:291)
                                                                                                at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:331)
                                                                                                at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137)
                                                                                                at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123)
                                                                                                at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121)
                                                                                                at android.arch.lifecycle.ReportFragment.onStart(ReportFragment.java:81)
                                                                                                at android.app.Fragment.performStart(Fragment.java:2378)
                                                                                                at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1027)
                                                                                                at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1171)
                                                                                                at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1153)
                                                                                                at android.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:2048)
                                                                                                at android.app.FragmentController.dispatchStart(FragmentController.java:188)
                                                                                                at android.app.Activity.performStart(Activity.java:6935)
                                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2887)
                                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
                                                                                                at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
                                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                                at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

I added read permission but not working

**Comment by danesfeder** [comment]
@nafis042 thanks for bringing this us.  This is from our Maps SDK and shouldn't be fatal.  Many times it shows in the logs after a crash that has happened elsewhere.  Can you confirm this is the only stacktrace in your logs when transitioning activities?  cc @tobrun

**Comment by nafis042** [comment]
below is the full log before the error happened.

01-22 20:42:35.707 11041-11041/com.mapbox.services.android.navigation.testapp D/ContextRelationMgrBrdg: loadKlass() : caller=com.samsung.android.bridge.multiscreen.common.ContextRelationManagerBridge.<clinit>:28 android.app.LoadedApk.makeApplication:840 
01-22 20:42:35.714 11041-11041/com.mapbox.services.android.navigation.testapp I/InstantRun: starting instant run server: is main process
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art: Rejecting re-init on previously-failed class java.lang.Class<com.mapbox.services.android.telemetry.location.GoogleLocationEngine>: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/GoogleApiClient$ConnectionCallbacks;
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at java.util.Map com.mapbox.services.android.telemetry.location.LocationEngineProvider.obtainDefaultLocationEnginesDictionary() (LocationEngineProvider.java:53)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(android.content.Context) (LocationEngineProvider.java:40)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(android.content.Context) (LocationEngineProvider.java:23)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:54)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void com.mapbox.services.android.navigation.testapp.NavigationApplication.onCreate() (NavigationApplication.java:37)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1032)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5885)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1703)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.os.Looper.loop() (Looper.java:154)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6692)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1468)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1358)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.GoogleApiClient$ConnectionCallbacks" on path: DexPathList[[zip file "/data/app/com.mapbox.services.android.navigation.testapp-1/base.apk", zip file "/data/app/com.mapbox.services.android.navigation.testapp-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.mapbox.services.android.navigation.testapp-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.mapbox.services.android.navigation.testapp-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.mapbox.services.android.navigation.testapp-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.mapbox.services.android.navigation.testapp-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.mapbox.services.android.navigation.testapp-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.mapbox.services.android.navigation.testapp-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.mapbox.services.android.navigation.testapp-1/split_lib_slice_6_apk.apk", zip f
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at java.util.Map com.mapbox.services.android.telemetry.location.LocationEngineProvider.obtainDefaultLocationEnginesDictionary() (LocationEngineProvider.java:53)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(android.content.Context) (LocationEngineProvider.java:40)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(android.content.Context) (LocationEngineProvider.java:23)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at com.mapbox.mapboxsdk.Mapbox com.mapbox.mapboxsdk.Mapbox.getInstance(android.content.Context, java.lang.String) (Mapbox.java:54)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void com.mapbox.services.android.navigation.testapp.NavigationApplication.onCreate() (NavigationApplication.java:37)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.app.Instrumentation.callApplicationOnCreate(android.app.Application) (Instrumentation.java:1032)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.app.ActivityThread.handleBindApplication(android.app.ActivityThread$AppBindData) (ActivityThread.java:5885)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.app.ActivityThread.-wrap3(android.app.ActivityThread, android.app.ActivityThread$AppBindData) (ActivityThread.java:-1)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1703)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.os.Looper.loop() (Looper.java:154)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6692)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1468)
01-22 20:42:35.754 11041-11041/com.mapbox.services.android.navigation.testapp I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1358)
01-22 20:42:35.755 11041-11041/com.mapbox.services.android.navigation.testapp V/AndroidLocationEngine: Initializing.
01-22 20:42:35.766 11041-11041/com.mapbox.services.android.navigation.testapp V/MapboxTelemetry: Initializing telemetry.
01-22 20:42:35.799 11041-11041/com.mapbox.services.android.navigation.testapp D/NetworkSecurityConfig: No Network Security Config specified, using platform default
01-22 20:42:35.813 11041-11041/com.mapbox.services.android.navigation.testapp V/MapboxTelemetry: Enabling telemetry.
01-22 20:42:35.833 11041-11041/com.mapbox.services.android.navigation.testapp I/art: Thread[1,tid=11041,Native,Thread*=0x7dae6c7a00,peer=0x760c9530,"main"] recursive attempt to load library "/data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so"
01-22 20:42:35.841 11041-11041/com.mapbox.services.android.navigation.testapp I/art: Thread[1,tid=11041,Native,Thread*=0x7dae6c7a00,peer=0x760c9530,"main"] recursive attempt to load library "/data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so"
01-22 20:42:35.842 11041-11041/com.mapbox.services.android.navigation.testapp I/art: Thread[1,tid=11041,Native,Thread*=0x7dae6c7a00,peer=0x760c9530,"main"] recursive attempt to load library "/data/app/com.mapbox.services.android.navigation.testapp-1/lib/arm64/libmapbox-gl.so"
01-22 20:42:35.985 11041-11041/com.mapbox.services.android.navigation.testapp W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
01-22 20:42:36.209 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.210 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.412 11041-11041/com.mapbox.services.android.navigation.testapp D/InputTransport: Input channel constructed: fd=83
01-22 20:42:36.413 11041-11041/com.mapbox.services.android.navigation.testapp D/ViewRootImpl@4b336f1[MainActivity]: setView = DecorView@a7202d6[MainActivity] touchMode=true
01-22 20:42:36.416 11041-11041/com.mapbox.services.android.navigation.testapp V/TelemetryService: Create event.
01-22 20:42:36.417 11041-11041/com.mapbox.services.android.navigation.testapp V/TelemetryService: Start command event.
01-22 20:42:36.548 11041-11131/com.mapbox.services.android.navigation.testapp I/OpenGLRenderer: Initialized EGL, version 1.4
01-22 20:42:36.548 11041-11131/com.mapbox.services.android.navigation.testapp D/OpenGLRenderer: Swap behavior 1
01-22 20:42:36.551 11041-11131/com.mapbox.services.android.navigation.testapp D/libGLESv1: STS_GLApi : DTS is not allowed for Package : com.mapbox.services.android.navigation.testapp
01-22 20:42:36.554 11041-11131/com.mapbox.services.android.navigation.testapp D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [720x1280]-format:1
01-22 20:42:36.558 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.559 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.570 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.572 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.576 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.578 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.581 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.583 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.586 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.587 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:36.605 11041-11041/com.mapbox.services.android.navigation.testapp W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
01-22 20:42:36.677 11041-11041/com.mapbox.services.android.navigation.testapp D/ViewRootImpl@4b336f1[MainActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 48 - 0, 0) vi=Rect(0, 48 - 0, 0) or=1
01-22 20:42:45.007 11041-11041/com.mapbox.services.android.navigation.testapp D/ViewRootImpl@4b336f1[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 1
01-22 20:42:45.009 11041-11041/com.mapbox.services.android.navigation.testapp V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@aa96fba nm : com.mapbox.services.android.navigation.testapp ic=null
01-22 20:42:45.009 11041-11041/com.mapbox.services.android.navigation.testapp I/InputMethodManager: [IMM] startInputInner - mService.startInputOrWindowGainedFocus
01-22 20:42:45.016 11041-11053/com.mapbox.services.android.navigation.testapp D/InputTransport: Input channel constructed: fd=93
01-22 20:42:45.017 11041-11041/com.mapbox.services.android.navigation.testapp V/InputMethodManager: Starting input: tba=android.view.inputmethod.EditorInfo@e0b6e6b nm : com.mapbox.services.android.navigation.testapp ic=null
01-22 20:42:46.214 11041-11041/com.mapbox.services.android.navigation.testapp V/TelemetryService: Start command event.
01-22 20:42:47.232 11041-11041/com.mapbox.services.android.navigation.testapp D/ViewRootImpl@4b336f1[MainActivity]: ViewPostImeInputStage processPointer 0
01-22 20:42:47.232 11041-11041/com.mapbox.services.android.navigation.testapp W/System: ClassLoader referenced unknown path: /system/framework/QPerformance.jar
01-22 20:42:47.233 11041-11041/com.mapbox.services.android.navigation.testapp E/BoostFramework: BoostFramework() : Exception_1 = java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.Performance" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64]]
01-22 20:42:47.233 11041-11041/com.mapbox.services.android.navigation.testapp V/BoostFramework: BoostFramework() : mPerf = null
01-22 20:42:47.296 11041-11041/com.mapbox.services.android.navigation.testapp D/ViewRootImpl@4b336f1[MainActivity]: ViewPostImeInputStage processPointer 1
01-22 20:42:47.320 11041-11041/com.mapbox.services.android.navigation.testapp D/ViewRootImpl@4b336f1[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0
01-22 20:42:47.425 11041-11041/com.mapbox.services.android.navigation.testapp W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
01-22 20:42:47.495 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:47.519 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:47.520 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:47.521 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:47.558 11041-11041/com.mapbox.services.android.navigation.testapp D/TextView: setTypeface with style : 0
01-22 20:42:47.634 11041-11041/com.mapbox.services.android.navigation.testapp I/TextToSpeech: Sucessfully bound to com.google.android.tts
01-22 20:42:47.656 11041-11041/com.mapbox.services.android.navigation.testapp I/TwilightManager: Could not get last known location. This is probably because the app does not have any location permissions. Falling back to hardcoded sunrise/sunset values.
01-22 20:42:47.663 11041-11041/com.mapbox.services.android.navigation.testapp I/TwilightManager: Could not get last known location. This is probably because the app does not have any location permissions. Falling back to hardcoded sunrise/sunset values.

**Comment by parnishGhodki** [comment]
Can you please tell how this issue is resolved?
