### ISSUE TITLE
Location updates incompatible with Play Services Location v21

### ISSUE THREAD

**Issue by josephcrowell** [mapbox/mapbox-navigation-android#6613]
### Environment

    Android OS version: 10.0-13.0
    Devices affected: All devices that were tested
    Navigation SDK Version: 2.9.1
    Play Services Location: 21.0.1 (com.google.android.gms:play-services-location:21.0.1)

### Observed behavior and steps to reproduce

Display a map view.
### Expected behavior

Receive location updates.
### Notes / preliminary analysis

Version 21.0.0 included a change which makes Mapbox incompatible with it.
I switched back to version 20.0.0 and everything works flawlessly.
Error stacktrace

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: au.com.annon.flutter_mapbox_turn_by_turn_example, PID: 5100
    java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~LUrDO50t6ePm-xRTm3vH6g==/au.com.annon.flutter_mapbox_turn_by_turn_example-yNHFcTLmZOYGNbRyoWw2-Q==/base.apk)
        at com.mapbox.android.core.location.GoogleLocationEngineImpl.requestLocationUpdates(GoogleLocationEngineImpl.java:58)
        at com.mapbox.android.core.location.GoogleLocationEngineImpl.requestLocationUpdates(GoogleLocationEngineImpl.java:26)
        at com.mapbox.android.core.location.LocationEngineProxy.requestLocationUpdates(LocationEngineProxy.java:34)
        at com.mapbox.navigation.core.trip.session.TripSessionLocationEngine.startLocationUpdates(TripSessionLocationEngine.kt:46)
        at com.mapbox.navigation.core.trip.session.MapboxTripSession.start(MapboxTripSession.kt:287)
        at com.mapbox.navigation.core.MapboxNavigation$startSession$1.invoke(MapboxNavigation.kt:1687)
        at com.mapbox.navigation.core.MapboxNavigation.runIfNotDestroyed(MapboxNavigation.kt:1857)
        at com.mapbox.navigation.core.MapboxNavigation.startSession(MapboxNavigation.kt:1686)
        at com.mapbox.navigation.core.MapboxNavigation.startTripSession(MapboxNavigation.kt:600)
        at com.mapbox.navigation.core.MapboxNavigation.startTripSession$default(MapboxNavigation.kt:599)`

Additional links and references

N/A

**Comment by Guardiola31337** [comment]
Hey @josephcrowell thanks for reaching out and reporting your issue.

This seems the same as https://github.com/mapbox/mapbox-navigation-android/issues/6713 could you re-test with the latest version of the SDK when you have a chance? 🙏 

cc @jush

**Comment by josephcrowell** [comment]
Issue persists with 2.9.5. Will try with 2.10.x when I get to work on Monday.

**Comment by josephcrowell** [comment]
Yes it's fixed on 2.10.0-rc1.
