### ISSUE TITLE
NullPointerException in NavigationView causing crash

### ISSUE THREAD

**Issue by briandilley** [mapbox/mapbox-navigation-android#702]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.setCameraTrackingLocation(boolean)' on a null object reference
       at com.mapbox.services.android.navigation.ui.v5.NavigationView.setCameraTrackingEnabled(NavigationView.java:241)
       at com.mapbox.services.android.navigation.ui.v5.NavigationPresenter.onMapScroll(NavigationPresenter.java:31)
       at com.mapbox.services.android.navigation.ui.v5.NavigationView.onScroll(NavigationView.java:225)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector.notifyOnScrollListeners(MapGestureDetector.java:519)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector$GestureListener.onScroll(MapGestureDetector.java:470)
       at android.view.GestureDetector.onTouchEvent(GestureDetector.java:622)
       at android.support.v4.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:480)
       at android.support.v4.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:543)
       at com.mapbox.mapboxsdk.maps.MapGestureDetector.onTouchEvent(MapGestureDetector.java:269)
       at com.mapbox.mapboxsdk.maps.MapView.onTouchEvent(MapView.java:434)
       at android.view.View.dispatchTouchEvent(View.java:9994)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2830)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2501)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2841)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2516)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2838)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3047)
       at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
       at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2799)
       at android.view.View.dispatchPointerEvent(View.java:10229)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5352)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5188)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4628)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4681)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4647)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4789)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4655)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4846)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4628)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4681)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4647)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4655)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4628)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7325)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7203)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7164)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7435)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
       at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(InputEventReceiver.java)
       at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
       at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7399)
       at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7462)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
       at android.view.Choreographer.doCallbacks(Choreographer.java:695)
       at android.view.Choreographer.doFrame(Choreographer.java:625)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7230)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by danesfeder** [comment]
Hey @briandilley thanks for the feedback.  Any context as to when you're seeing this?  And which version of the SDK? Thanks
