### ISSUE TITLE
Android : Resource leaks are happening in DropInUI

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#7166]
Hello Team, I am using mapbox DropInUi in my app and I am seeing some resource leaks when I run the code using strict mode. I suspect this is causing a ANR issues in our app. It is very easy to reproduce this issue.

I have written a dropin navigationview in my xml like below.

      ` <com.mapbox.navigation.dropin.NavigationView
        android:id="@+id/navigationView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:accessToken="@string/mapbox_access_token"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="parent"
        app:layout_constraintTop_toTopOf="parent" />`

And I am sending current location and destination with other criteria's like below.
               
                 mapboxNavigation = MapboxNavigationApp.current()!! 
                 var routeOptions: RouteOptions =
                 RouteOptions.builder()
                .applyDefaultNavigationOptions()
                .language("en")
                .voiceUnits(DirectionsCriteria.METRIC)
                .coordinatesList(listOf(origin, destination))
                .alternatives(true)
                .baseUrl(Constants.BASE_API_URL)
                .user(Constants.MAPBOX_USER)
                .maxHeight(maxHeight)
                .maxWeight(maxWeight)
                .maxWidth(maxWidth)
                .snappingIncludeClosuresList(listOf(true, true))
                .snappingIncludeStaticClosuresList(listOf(true, true))
                .exclude(DirectionsCriteria.EXCLUDE_TOLL)
                .voiceInstructions(true)
                .bannerInstructions(true)
                .continueStraight(true)
                .alternatives(true)
                .annotationsList(annotations)
                .roundaboutExits(true)
                .overview("full")
                .steps(true)
                .build()
               mapboxNavigation.requestRoutes(
                routeOptions, object : NavigationRouterCallback {
                override fun onRoutesReady(
                    routes: List<NavigationRoute>,
                    routerOrigin: RouterOrigin
                ) {
                 binding.navigationView.api.startActiveGuidance(routes)
                 }

                override fun onFailure(
                    reasons: List<RouterFailure>,
                    routeOptions: RouteOptions
                ) {
                    Log.i(TAG, reasons.toString())
                }

                override fun onCanceled(
                    routeOptions: RouteOptions,
                    routerOrigin: RouterOrigin
                ) {
                    Log.i(TAG, routeOptions.toString())
                }
            }`

I am getting the following leaks when I just open the navigation screen.
[File1.txt](https://github.com/mapbox/mapbox-navigation-android/files/11440742/File1.txt)

I am getting the following DiskReadViolation when I start the navigation.
[File2.txt](https://github.com/mapbox/mapbox-navigation-android/files/11440731/File2.txt)

    
**Android API: 32**
**Mapbox Navigation SDK version: com.mapbox.navigation:ui-app:2.13.0-rc.1
com.mapbox.navigation:ui-dropin:2.13.0-rc.1**

### Steps to trigger behavior

 1.Use the strictmode
 2.Open the navigation screen and you can replicate in preview state
 3.Again if you start the navigation, you can see the next set of DiskReadViolation

This is happening with simple layout with dropIn NavigationView and the code to request the routes using maboxNavigation. Is there any leak issue with NavigationRouterCallback? Please check it and let me know how to solve this issue.

**Comment by Sridhar261990** [comment]
In addition to the above findings, please check the below one as well.

   `ANR Input dispatching timed out (Application does not have a focused window)
CameraAnimationsPluginImpl.java:0
(ANR Input dispatching timed out (Application does not have a focused window)
	 at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.getAnchor(CameraAnimationsPluginImpl.java:0)
	 at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.commitChangesRunnable$lambda-0(CameraAnimationsPluginImpl.java:7)
	 at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.$r8$lambda$Q1xLlWoVQ16QyJTQHFZvvXRplO4(CameraAnimationsPluginImpl.java:0)
	 at com.instabug.featuresrequest.ui.base.featureslist.n$$InternalSyntheticLambda$1$c5b2aaf5b5c9fcdc25a61a4840d2ad20a731ca24454780a736406347a2918b1c$0.run$bridge(n.java:0)
	 at android.os.Handler.handleCallback(Handler.java:938)
	 at android.os.Handler.dispatchMessage(Handler.java:99)
	 at android.os.Looper.loopOnce(Looper.java:201)
	 at android.os.Looper.loop(Looper.java:288)
	 at android.app.ActivityThread.main(ActivityThread.java:7916)
	 at java.lang.reflect.Method.invoke(Method.java)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
, 0)`

**Comment by Sridhar261990** [comment]
ANR Input dispatching timed out (Application does not have a focused window)
ObservableExtensionKt.java:0
(ANR Input dispatching timed out (Application does not have a focused window)
	 at com.mapbox.maps.extension.observable.ObservableExtensionKt.nullableLong(ObservableExtensionKt.java:0)
	 at com.mapbox.maps.extension.observable.ObservableExtensionKt.getCameraChangedEventData(ObservableExtensionKt.java:30)
	 at com.mapbox.maps.NativeObserver.notify(NativeObserver.java:174)
	 at com.mapbox.maps.CameraManager.setCamera(CameraManager.java)
	 at com.mapbox.maps.NativeMapImpl.setCamera(NativeMapImpl.java:7)
	 at com.mapbox.maps.MapboxMap.setCamera(MapboxMap.java:15)
	 at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.performMapJump$plugin_animation_publicRelease(CameraAnimationsPluginImpl.java:49)
	 at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.commitChangesRunnable$lambda-0(CameraAnimationsPluginImpl.java:24)
	 at com.mapbox.maps.plugin.animation.CameraAnimationsPluginImpl.$r8$lambda$Q1xLlWoVQ16QyJTQHFZvvXRplO4(CameraAnimationsPluginImpl.java:0)
	 at com.instabug.featuresrequest.ui.base.featureslist.n$$InternalSyntheticLambda$1$c5b2aaf5b5c9fcdc25a61a4840d2ad20a731ca24454780a736406347a2918b1c$0.run$bridge(n.java:0)
	 at android.os.Handler.handleCallback(Handler.java:938)
	 at android.os.Handler.dispatchMessage(Handler.java:99)
	 at android.os.Looper.loopOnce(Looper.java:201)
	 at android.os.Looper.loop(Looper.java:288)
	 at android.app.ActivityThread.main(ActivityThread.java:7916)
	 at java.lang.reflect.Method.invoke(Method.java)
	 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
	 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
, 0)

**Comment by Sridhar261990** [comment]
Hi Mapbox Team, Any updates regarding this ticket?

**Comment by Sridhar261990** [comment]
In addition to the above information, Please check the below issue as well.

main (waiting):tid=1 systid=5475 
#00 pc 0x4def0 libc.so (syscall + 32) (BuildId: 369edc656806aeaf384cbeb8f7a347af)
#01 pc 0x467d84 libart.so (art::Thread::Park(bool, long) + 404) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
#02 pc 0x467688 libart.so (art::Unsafe_park(_JNIEnv*, _jobject*, unsigned char, long) (.__uniq.319429422067363160645159987129209045680) + 160) (BuildId: 12e00d030bcfeb51f978c01791e0cd24)
       at jdk.internal.misc.Unsafe.park(Native method)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
       at com.mapbox.maps.renderer.MapboxRenderThread.onSurfaceDestroyed(MapboxRenderThread.java:36)
       at com.mapbox.maps.renderer.MapboxSurfaceRenderer.surfaceDestroyed(unavailable:4)
       at com.mapbox.maps.renderer.MapboxSurfaceHolderRenderer.surfaceDestroyed(unavailable:5)
       at android.view.SurfaceView.notifySurfaceDestroyed(SurfaceView.java:1972)
       at android.view.SurfaceView.updateSurface(SurfaceView.java:1189)
       at android.view.SurfaceView.setWindowStopped(SurfaceView.java:312)
       at android.view.SurfaceView.surfaceDestroyed(SurfaceView.java:1850)
       at android.view.ViewRootImpl.notifySurfaceDestroyed(ViewRootImpl.java:1935)
       at android.view.ViewRootImpl.setWindowStopped(ViewRootImpl.java:1892)
       at android.view.WindowManagerGlobal.setStoppedState(WindowManagerGlobal.java:661)
       at android.app.Activity.performStop(Activity.java:8275)
       at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5185)
       at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5165)
       at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5230)
       at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2214)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7916)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

**Comment by EricGeiler** [comment]
any traction on this issue we are facing?

**Comment by Sridhar261990** [comment]
Hello @dzinad, Hope you are doing good. Could you please look into this issue and let me know how to solve it?

**Comment by EricGeiler** [comment]
@abhishek1508

**Comment by VysotskiVadim** [comment]
Hello @Sridhar261990 . Thank you for reporting the issues and sorry for the long delay.

I don't see any mistakes in usage of `NavigationView`, the reported issues seem like our bugs. Can you please help me understand the impact the issues have on your application to determine priority? Do you observe performance problems like low FPS because of the mentioned leaks/violations?
I created tickets for them in our internal system:
https://mapbox.atlassian.net/browse/NAVAND-1369, https://mapbox.atlassian.net/browse/NAVAND-1367, you won't be able to access them but I'm leaving links here in order to let other mapboxers quickly find them when they read this issue.

How often do you have mentioned ANR?

**Comment by EricGeiler** [comment]
as of today, about 1/3 of the installed devices are affected by these reported ANRs.

![image](https://github.com/mapbox/mapbox-navigation-android/assets/61550186/070ced19-5cc7-4625-b3d7-d3a0f9945442)

I'd consider this medium to high priority, @Sridhar261990 can shed more light on the impact.  I just know I have users complaining about "freezing" while the SDK is being utilized.  Drivers are power cyclying or force closing to solve the "freeze"

**Comment by Sridhar261990** [comment]
Hello @VysotskiVadim, Thanks for your response. This ANR is happening randomly to the user. As Eric mentioned there are 1/3 drivers are affected. There are some drivers getting this ANR 2 to 4 times a day. Apart from this ANR, Could you also please make sure there is no memory leakage to ensure that will not cause the ANR's? I have not found any low FSP based on my testing. I will also provide you if there is any other ANR issues here. Thanks for looking into this issue.

**Comment by Sridhar261990** [comment]
Hi @VysotskiVadim, Any updates regarding this ticket?

**Comment by EricGeiler** [comment]
Just following up on this ticket, as this seems to be having an impact on our fleet.  Any updates?

**Comment by dzinad** [comment]
Sorry, I'm a bit lost here. So far you've shared:

1. StrictMode violation: reading from disk on the main thread;
2. StrictMode violation: resource leak;
3. Multiple ANR traces that are not connected to p. 1 and 2.

I assume that the actual ANRs are the ones with traces (I see 3 of them: https://github.com/mapbox/mapbox-navigation-android/issues/7166#issuecomment-1548183079, https://github.com/mapbox/mapbox-navigation-android/issues/7166#issuecomment-1542522425, https://github.com/mapbox/mapbox-navigation-android/issues/7166#issuecomment-1542519990)? Is my assumption correct?

**Comment by Sridhar261990** [comment]
Hi @dzinad, You are correct. Those three are the captured ANR's. I thought the point 1 and point 2 regarding the violation may also cause for the ANR issue. So that I have added that reports as well to give you more clear picture. @VysotskiVadim has mentioned that he has created a internal tickets NAVAND-1369 and NAVAND-1367. Please let me know when this will be be fixed.

**Comment by kiryldz** [comment]
@Sridhar261990 couple questions:
1. Do you use several maps or just one? 
2. If you have access to logcat - can you share the logs before ANR happens?
3. Are you able to reproduce locally? 
4. Is this affecting _only_ API 32 (based on ticket description)? What about other Android APIs?

**Comment by Sridhar261990** [comment]
Hi @kiryldz,

I can't reproduce it locally. Actually this anr is not happening for last couple of weeks. We just want to make sure that this issue is resolved. I will close this ticket as of now and update you if this happens again. Thank you!
