### ISSUE TITLE
java.lang.IllegalArgumentException: latitude must not be NaN

### ISSUE THREAD

**Issue by sooniln** [mapbox/mapbox-navigation-android#7193]
Google is observing a variety of different Android app crashes, all with stack traces pointing to the MapBox SDK. One vector of many is Android U devices running the SpotAngels app, which crashes 100% of the time.

All of the crashing apps appear to have similar stack traces within the MapBox SDK.

One representative trace:

```
04-02 17:57:28.096 E AndroidRuntime: FATAL EXCEPTION: main
04-02 17:57:28.096 E AndroidRuntime: Process: com.spotangels.android, PID: 19611
04-02 17:57:28.096 E AndroidRuntime: java.lang.IllegalArgumentException: latitude must not be NaN
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.geometry.LatLng.h(LatLng.java:35)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.e.a(LatLngEvaluator.java:20)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.e.evaluate(LatLngEvaluator.java:5)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.KeyframeSet.getValue(KeyframeSet.java:202)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.PropertyValuesHolder.calculateValue(PropertyValuesHolder.java:1017)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1652)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.ValueAnimator.animateValuesInRange(ValueAnimator.java:1466)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.animateValuesInRange(AnimatorSet.java:1015)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.animateBasedOnPlayTime(AnimatorSet.java:861)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.initChildren(AnimatorSet.java:1154)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1374)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.start(AnimatorSet.java:745)
04-02 17:57:28.096 E AndroidRuntime: 	at android.animation.AnimatorSet.start(AnimatorSet.java:696)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.w.b(MapboxAnimatorSetProvider.java:15)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.i.t(LocationAnimatorCoordinator.java:35)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.i.m(LocationAnimatorCoordinator.java:179)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.k.d0(LocationComponent.java:84)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.k.c0(LocationComponent.java:16)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.k.b(LocationComponent.java:1)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.k$o.a(LocationComponent.java:16)
04-02 17:57:28.096 E AndroidRuntime: 	at com.mapbox.mapboxsdk.location.k$o.onSuccess(LocationComponent.java:3)
04-02 17:57:28.096 E AndroidRuntime: 	at fc.b$a.a(GoogleLocationEngineImpl.java:18)
04-02 17:57:28.096 E AndroidRuntime: 	at fc.b$a.onSuccess(GoogleLocationEngineImpl.java:3)
04-02 17:57:28.096 E AndroidRuntime: 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.0.1:26)
04-02 17:57:28.096 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:958)
04-02 17:57:28.096 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-02 17:57:28.096 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:205)
04-02 17:57:28.096 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:294)
04-02 17:57:28.096 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8174)
04-02 17:57:28.096 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-02 17:57:28.096 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
04-02 17:57:28.096 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
```

After investigation it is our belief that the MapBix is not being passed Location objects with a NaN value from Google Play services, but that this problem originates within MapBox itself somehow.

Users have also anecdotally reported "the app does not crash if I also have Maps open and in navigation/driving mode".

A preliminary avenue of investigation is thus that this may have something to do with MapBox state initialization.

**Comment by sooniln** [comment]
Possibly related to https://github.com/mapbox/mapbox-maps-android/issues/2059.
