### ISSUE TITLE
Error in Android 13(S) can any knows this error how to fix?

### ISSUE THREAD

**Issue by swaggyarun1** [mapbox/mapbox-navigation-android#7230]
implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:9.5.0'
    implementation('com.mapbox.mapboxsdk:mapbox-android-sdk:9.5.0') {
        exclude group: 'group_name', module: 'module_name'
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.42.6'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.42.6'

 E  Exception in onDidFinishLoadingStyle
                                                                                                    java.lang.IllegalArgumentException: com.services.safe4r: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:402)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:672)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:659)
                                                                                                    	at com.mapbox.android.telemetry.AlarmSchedulerFlusher.register(AlarmSchedulerFlusher.java:31)
                                                                                                    	at com.mapbox.android.telemetry.MapboxTelemetry.startAlarm(MapboxTelemetry.java:380)
                                                                                                    	at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry(MapboxTelemetry.java:374)
                                                                                                    	at com.mapbox.android.telemetry.MapboxTelemetry.enable(MapboxTelemetry.java:114)
                                                                                                    	at com.mapbox.services.android.navigation.v5.navigation.NavigationMetricsWrapper.init(NavigationMetricsWrapper.java:30)
                                                                                                    	at com.mapbox.services.android.navigation.v5.navigation.NavigationTelemetry.initialize(NavigationTelemetry.java:124)
                                                                                                    	at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.initializeTelemetry(MapboxNavigation.java:921)
                                                                                                    	at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.initialize(MapboxNavigation.java:891)
                                                                                                    	at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.<init>(MapboxNavigation.java:143)
                                                                                                    	at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.initializeNavigation(NavigationViewModel.java:399)
                                                                                                    	at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.initialize(NavigationViewModel.java:217)
                                                                                                    	at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeNavigation(NavigationView.java:631)
                                                                                                    	at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:394)
                                                                                                    	at com.mapbox.services.android.navigation.ui.v5.MapboxNavigationActivity.onNavigationReady(MapboxNavigationActivity.java:99)
                                                                                                    	at com.mapbox.services.android.navigation.ui.v5.NavigationView$1.onStyleLoaded(NavigationView.java:238)
                                                                                                    	at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:963)
                                                                                                    	at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:225)
                                                                                                    	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1373)
                                                                                                    	at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
                                                                                                    	at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1166)
                                                                                                    	at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                                                    	at android.os.MessageQueue.next(MessageQueue.java:339)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:186)
                                                                                                    	at android.os.Looper.loop(Looper.java:351)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8380)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by igala** [comment]
@swaggyarun1  any luck in solving this issue? i have the same error

**Comment by swaggyarun1** [comment]
@igala not yet still facing this issue

**Comment by DzmitryFomchyn** [comment]
Hi everyone,
Navigation SDK `0.42.6` and Maps SDK `9.5.0` are quite old. I'd recommend updating you dependencies to [Navigation SDK v2](https://docs.mapbox.com/android/navigation/guides/) and [Maps SDK v10](https://docs.mapbox.com/android/maps/guides/)

Migration guides:
- https://docs.mapbox.com/android/navigation/guides/migrate-to-v2/
- https://docs.mapbox.com/android/maps/guides/migrate-to-v10/

**Comment by mochadwi** [comment]
do you have migration to v1 first? @DzmitryFomchyn from 0.42 to v1 also major refactor which I think currently I cannot found the proper documentation for this, if there's official migration docs please let us know 🙏
