### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/android/core/FileUtils after bumping the Android Navigation SDK

### ISSUE THREAD

**Issue by istevanovic99** [mapbox/mapbox-navigation-android#7335]
**Android API:** 33
**Mapbox Navigation SDK version:** 2.14.0

### Steps to trigger behavior

After bumping the Android navigation SDK version, we get crashes when the app starts. This is the log of the crash:

```
FATAL EXCEPTION: MapboxTelemetryExecutor
Process: com.themobilecompany.Onderweg.acc, PID: 8409
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/android/core/FileUtils;
at com.mapbox.android.telemetry.errors.ErrorReporterEngine.sendReports(ErrorReporterEngine.java:48)
at com.mapbox.android.telemetry.errors.ErrorReporterEngine$1.run(ErrorReporterEngine.java:34)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.android.core.FileUtils" on path: DexPathList[[zip file "/data/app/~~eYRvVWrC-PDJJJIB9EhKZg==/com.themobilecompany.Onderweg.acc-O4YaklYo2ruzgEiHQewv9Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~eYRvVWrC-PDJJJIB9EhKZg==/com.themobilecompany.Onderweg.acc-O4YaklYo2ruzgEiHQewv9Q==/lib/arm64, /data/app/~~eYRvVWrC-PDJJJIB9EhKZg==/com.themobilecompany.Onderweg.acc-O4YaklYo2ruzgEiHQewv9Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
at com.mapbox.android.telemetry.errors.ErrorReporterEngine.sendReports(ErrorReporterEngine.java:48) 
at com.mapbox.android.telemetry.errors.ErrorReporterEngine$1.run(ErrorReporterEngine.java:34) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
at java.lang.Thread.run(Thread.java:1012) 
```

Not sure why is this happening, can you help with this?

We are also using these dependencies:
`com.mapbox.search:mapbox-search-android:1.0.0-rc.7`
`com.mapbox.mapboxsdk:mapbox-android-telemetry:8.1.5`

### Expected behavior
App is not crashing.

### Actual behavior
App is crashing.

**Comment by CodingFlex** [comment]
Please how did you fix this issue?
