### ISSUE TITLE
Android - DropInUi Crash issues

### ISSUE THREAD

**Issue by Sridhar261990** [mapbox/mapbox-navigation-android#7468]
Hello Mapbox team,

I am using DropInUI sdk in our app  and I am getting two different crashes.

The below one is first crash happening at least 10 times a day.

Fatal Exception: java.lang.IllegalArgumentException: Parse error at offset 638: Missing a colon after a name of object member.
       at com.mapbox.common.EventsService.sendEvent(SourceFile)
       at com.mapbox.navigation.metrics.MapboxMetricsReporter.addEvent(MapboxMetricsReporter.java:63)
       at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry.sendEvent(MapboxNavigationTelemetry.java:34)
       at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry.createFreeDriveEvent(MapboxNavigationTelemetry.java:49)
       at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry.access$createFreeDriveEvent(MapboxNavigationTelemetry.java)
       at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry$trackFreeDrive$1.invoke(:9)
       at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry$trackFreeDrive$1.invoke(:2)
       at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry.ifTelemetryRunning(MapboxNavigationTelemetry.java:12)
       at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry.trackFreeDrive(MapboxNavigationTelemetry.java:16)
       at com.mapbox.navigation.core.telemetry.MapboxNavigationTelemetry.navigationSessionStateObserver$lambda-2(MapboxNavigationTelemetry.java:74)
       at com.mapbox.navigation.core.trip.session.NavigationSession.setState$libnavigation_core_release(:34)
       at com.mapbox.navigation.core.trip.session.NavigationSession.updateState(:10)
       at com.mapbox.navigation.core.trip.session.NavigationSession.setHasRoutes(:6)
       at com.mapbox.navigation.core.trip.session.NavigationSession.onRoutesChanged(:15)
       at com.mapbox.navigation.core.directions.session.MapboxDirectionsSession.setNavigationRoutesFinished(:85)
       at com.mapbox.navigation.core.MapboxNavigation$internalSetNavigationRoutes$2.invokeSuspend(MapboxNavigation.java:2)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:14)
       at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:47)
       at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:105)
       at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:105)
       at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.java:105)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.java:45)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.java:17)
       at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.java:17)
       at com.mapbox.navigation.navigator.internal.MapboxNativeNavigatorImpl$setRoutes$2$2.run(:12)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:335)
       at android.os.Looper.loopOnce(Looper.java:161)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7916)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

The below one is second crash which happens twice or thrice a day.

Fatal Exception: java.lang.NullPointerException: Missing required view with ID: app.abcourier.ccmobile:id/maneuverView
       at com.mapbox.navigation.dropin.databinding.MapboxManeuverGuidanceLayoutBinding.bind(:32)
       at com.mapbox.navigation.dropin.maneuver.ManeuverViewBinder.bind(:18)
       at com.mapbox.navigation.dropin.maneuver.ManeuverViewBinder.bind(:2)
       at com.mapbox.navigation.ui.base.lifecycle.UICoordinator$onAttached$1$invokeSuspend$$inlined$collect$1.emit(UICoordinator.java:23)
       at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invokeSuspend(FlowKt__Zip.kt:63)
       at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invoke(FlowKt__Zip.kt:20)
       at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invoke(FlowKt__Zip.kt:20)
       at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:258)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:14)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:100)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7916)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:577)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

Please check these error reports and let me know how do we solve this issue. 

**Android API:32**
implementation 'com.mapbox.navigation:ui-app:2.15.1
implementation 'com.mapbox.navigation:ui-dropin:2.15.1'

Currently I don't have the steps to reproduce the issue.

**Comment by Sridhar261990** [comment]
Any update on this issue?

**Comment by EricGeiler** [comment]
Adding more context...

com.mapbox.common.EventsService.sendEvent
java.lang.IllegalArgumentException - Parse error at offset 625: Missing a colon after a name of object member.

We captured the following info, hopefully this assists.

Drv 4880 triggered this issue numerous times this morning.  See below and attached.

![image](https://github.com/mapbox/mapbox-navigation-android/assets/61550186/ad075865-96f7-46cc-a52f-43c626a136d9)
```
2023-08-22 08:35:18: Network_Connection_Type - TYPE_MOBILE - 13
2023-08-22 08:35:19: DirectionsOrderLocation -onRoutesReady -NavigationRoute#id lEhcWFueEYWBbeczyxyO-kvD5IuYqi9162nk2T72c0oJbdmJCcq3bA==_us-east-1#0
2023-08-22 08:35:19: DirectionsOrderLocation -onRoutesReady -DirectionsResponse#uuid lEhcWFueEYWBbeczyxyO-kvD5IuYqi9162nk2T72c0oJbdmJCcq3bA==_us-east-1
2023-08-22 08:35:21: Network_Connection_Type - TYPE_MOBILE - 13
```

![image](https://github.com/mapbox/mapbox-navigation-android/assets/61550186/6892433c-1900-4fef-9a52-76d687d7cda7)
```
2023-08-22 08:35:07: DirectionsOrderLocation -onRoutesReady -NavigationRoute#id bSDzis5dntowz0I2EUhCM5xtj07HeWLZ2RhsBmWrTxVWY1QJYzaXQg==_us-east-1#0
2023-08-22 08:35:07: DirectionsOrderLocation -onRoutesReady -DirectionsResponse#uuid bSDzis5dntowz0I2EUhCM5xtj07HeWLZ2RhsBmWrTxVWY1QJYzaXQg==_us-east-1
```

**Comment by EricGeiler** [comment]
This issue has no longer been present for a while now, please close ticket.

**Comment by rahul-evolution** [comment]
Hello Mapbox team,

I am using below sdk for navigation ::

    implementation "com.mapbox.navigation:copilot:2.16.0"
    implementation "com.mapbox.navigation:ui-app:2.16.0"
    implementation "com.mapbox.navigation:ui-dropin:2.16.0"

but whenever I am try to start navigation on 3rd time, unfortunately app is crash and show below logs

`java.lang.NullPointerException: Missing required view with ID: com.example.naveo:id/maneuverView
                                                                                                    	at com.mapbox.navigation.dropin.databinding.MapboxManeuverGuidanceLayoutBinding.bind(MapboxManeuverGuidanceLayoutBinding.java:60)
                                                                                                    	at com.mapbox.navigation.dropin.maneuver.ManeuverViewBinder.bind(ManeuverViewBinder.kt:27)
                                                                                                    	at com.mapbox.navigation.dropin.maneuver.ManeuverViewBinder.bind(ManeuverViewBinder.kt:16)
                                                                                                    	at com.mapbox.navigation.ui.base.lifecycle.UICoordinator$onAttached$1$invokeSuspend$$inlined$collect$1.emit(Collect.kt:136)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invokeSuspend(Zip.kt:262)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invoke(Unknown Source:13)
                                                                                                    	at kotlinx.coroutines.flow.FlowKt__ZipKt$combine$$inlined$combineUnsafe$FlowKt__ZipKt$1$2.invoke(Unknown Source:6)
                                                                                                    	at kotlinx.coroutines.flow.internal.CombineKt$combineInternal$2.invokeSuspend(Combine.kt:76)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:257)
                                                                                                    	at android.os.Looper.loop(Looper.java:368)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8848)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9f13e8a, Dispatchers.Main]`

can you please provide more guidance or solution for this issue?

**Comment by Mohtashim-Naeem** [comment]
I think this has been solved in new versions. I also faced but by updating dependencies, it worked.
