### ISSUE TITLE
Crash on Android 14 (SDK 34), because a receiver in the MapboxTripNotification class hasn't been declared (non-)exportable

### ISSUE THREAD

**Issue by Daphne-CoffeeIT** [mapbox/mapbox-navigation-android#7487]
**Android API: 34**
**Mapbox Navigation SDK version: tested both on 2.15.1 and 2.16.0-beta.1**

### Steps to trigger behavior

 1. Use drop-in UI
 2. Try to start the MapBox containing activity
 3. App crashes because a receiver within `MapboxTripNotification` isn't declared exportable or non-exportable, which is an [Android 14 requirement](https://developer.android.com/about/versions/14/behavior-changes-14#runtime-receivers-exported)

### Expected behavior
App doesn't crash and navigation starts.

### Actual behavior
A crash with the following stack trace:
```
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4962)
 at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4995)
 at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:57)
 at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
 at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:205)
 at android.os.Looper.loop(Looper.java:294)
 at android.app.ActivityThread.main(ActivityThread.java:8177)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
 Caused by: java.lang.SecurityException: com.grid.application: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
 at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
 at android.os.Parcel.createException(Parcel.java:3041)
 at android.os.Parcel.readException(Parcel.java:3024)
 at android.os.Parcel.readException(Parcel.java:2966)
 at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
 at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
 at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
 at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
 at com.mapbox.navigation.trip.notification.internal.MapboxTripNotification.registerReceiver(MapboxTripNotification.kt:190)
 at com.mapbox.navigation.trip.notification.internal.MapboxTripNotification.onTripSessionStarted(MapboxTripNotification.kt:162)
 at com.mapbox.navigation.core.trip.service.MapboxTripService.startService(MapboxTripService.kt:118)
 at com.mapbox.navigation.core.trip.session.MapboxTripSession.start(MapboxTripSession.kt:331)
 at com.mapbox.navigation.core.MapboxNavigation$startSession$1.invoke(MapboxNavigation.kt:1982)
 at com.mapbox.navigation.core.MapboxNavigation.runIfNotDestroyed(MapboxNavigation.kt:2149)
 at com.mapbox.navigation.core.MapboxNavigation.startSession(MapboxNavigation.kt:1981)
 at com.mapbox.navigation.core.MapboxNavigation.startTripSession(MapboxNavigation.kt:661)
 at com.mapbox.navigation.core.MapboxNavigation.startTripSession$default(MapboxNavigation.kt:660)
 at com.grid.application.presentation.ui.navigation.NavigationActivity$mapboxNavigation$2.onAttached(NavigationActivity.kt:453)
 at com.mapbox.navigation.core.lifecycle.MapboxNavigationOwner.register(MapboxNavigationOwner.kt:49)
 at com.mapbox.navigation.core.lifecycle.MapboxNavigationAppDelegate.registerObserver(MapboxNavigationAppDelegate.kt:55)
 at com.mapbox.navigation.core.lifecycle.MapboxNavigationApp.registerObserver(MapboxNavigationApp.kt:160)
 at com.mapbox.navigation.core.lifecycle.RequireMapboxNavigationDelegate$lifecycleObserver$1.onResume(RequireMapboxNavigation.kt:110)
 at androidx.lifecycle.DefaultLifecycleObserverAdapter.onStateChanged(DefaultLifecycleObserverAdapter.kt:26)
 at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.kt:314)
```

**Comment by Daphne-CoffeeIT** [comment]
It's solved in the latest version of MapBox.
