### ISSUE TITLE
Mapbox crashes when tapping banner while still scrolling

### ISSUE THREAD

**Issue by chooble** [mapbox/mapbox-navigation-android#761]
http://gph.is/2pgV8sV

Bug found in 0.10.0
Still in 0.11.0       
OnePlus 5

error: 
`E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: nl.coffeeit.mototour, PID: 22820
                  java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true android.support.v7.widget.RecyclerView{41ee4c8 VFED..... .......D 0,0-1080,1605 #7f0800c5 app:id/rvInstructions}, adapter:com.mapbox.services.android.navigation.ui.v5.summary.list.InstructionListAdapter@636481, layout:android.support.v7.widget.LinearLayoutManager@fb74926, context:nl.coffeeit.mototour.activities.NavigationActivity@395207e
                      at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:5890)
                      at android.support.v7.widget.RecyclerView$Recycler.recycleView(RecyclerView.java:5834)
                      at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:292)
                      at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                      at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                      at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                      at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                      at android.os.Handler.handleCallback(Handler.java:789)
                      at android.os.Handler.dispatchMessage(Handler.java:98)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6809)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
`

**Comment by danesfeder** [comment]
Hey @chooble thanks for the issue here - looking into the cause of this now 👀
