### ISSUE TITLE
Crash when enableOffRouteDetection is set to false

### ISSUE THREAD

**Issue by skienzl** [mapbox/mapbox-navigation-android#780]
**Bug report:** If you set enableOffRouteDetection to false in MapboxNavigationOptions the crashes if you start navigation. 

Seems like because of this setting no OffRouteDetector is set during the MapboxNavigation init: 
[MapboxNavigation.java](https://github.com/mapbox/mapbox-navigation-android/blob/090cb38532bbe9c5d1ea260b72f92fb6152d4f49/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/MapboxNavigation.java#L158)

Because no engine is set. The following lines throw a NullPointerException: 
[NavigationHelper.java](https://github.com/mapbox/mapbox-navigation-android/blob/c4e928d83e4415dac8397e03c176c2baa6b18c2a/libandroid-navigation/src/main/java/com/mapbox/services/android/navigation/v5/navigation/NavigationHelper.java#L203)

**Logs:** 
`
E/AndroidRuntime: FATAL EXCEPTION: NavThread
                                                                Process: com.app.debug, PID: 572
                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.mapbox.services.android.navigation.v5.offroute.OffRoute.isUserOffRoute(android.location.Location, com.mapbox.services.android.navigation.v5.routeprogress.RouteProgress, com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationOptions)' on a null object reference
                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationHelper.isUserOffRoute(NavigationHelper.java:205)
                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleRequest(NavigationEngine.java:99)
                                                                    at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleMessage(NavigationEngine.java:62)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:65)`

**Comment by danesfeder** [comment]
Hey @skienzl, this looks like a regression in our code.  We will investigate today and get a fix in ASAP.  Thank you for your patience.

**Comment by skienzl** [comment]
Thx @danesfeder  for the quick check. Do you have an estimate when this PR gets merged and released?

**Comment by skienzl** [comment]
@danesfeder really sorry to get on your nerves. but this is an important bug fix for our usecase and as far as i can see the PR is already ready to go and would it be possible to merge it to the snapshot release. thanks in advance and again sorry :/

**Comment by skienzl** [comment]
@danesfeder thank you very much!
