### ISSUE TITLE
NoClassDefFoundError: LostLocationEngine

### ISSUE THREAD

**Issue by P-Zenker** [mapbox/mapbox-navigation-android#791]
Hey,

just upgraded from 0.11.1 to 12.0-SNAPSHOT (and from mapbox-android-sdk:5.5.0 to 6.0.0-beta.4) today:

```
MapboxNavigationOptions navigationOptions = MapboxNavigationOptions.builder()
                .enableNotification(false)
                .snapToRoute(true)
                .userLocationSnapDistance(40.0)
                .build();

MapboxNavigation mapboxNavigation = new MapboxNavigation(context, context.getString(R.string.mapbox_access_token), navigationOptions);
```
```
03-21 11:46:48.890 14574-14574/? W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/services/android/telemetry/location/LostLocationEngine;
03-21 11:46:48.890 14574-14574/? W/System.err:     at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.obtainLocationEngine(MapboxNavigation.java:191)
03-21 11:46:48.890 14574-14574/? W/System.err:     at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.initializeDefaultLocationEngine(MapboxNavigation.java:182)
03-21 11:46:48.890 14574-14574/? W/System.err:     at com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.initialize(MapboxNavigation.java:144)
```

If I revert to mapbox-android-sdk:5.5.0 everything is fine.

**Comment by P-Zenker** [comment]
Well, I just excluded com.mapbox.mapboxsdk and included transitive = true in mapbox-android-navigation

**Comment by mashahbazi** [comment]
what did you mean?
I have same problem but cant solve it
