### ISSUE TITLE
IndexOutOfBoundsException Step Points

### ISSUE THREAD

**Issue by gonzalt03** [mapbox/mapbox-navigation-android#801]
**Android API:** 26
**Mapbox Navigation SDK version:** :0.11.1

### Steps to trigger behavior

 1. Add waypoints
 2. And at the end of the navigation :

```
 java.lang.IndexOutOfBoundsException: Invalid index 5, size is 5
   at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
   at java.util.ArrayList.get(ArrayList.java:308)
   at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.decodeStepPoints(NavigationEngine.java:255)
   at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.advanceStepIndex(NavigationEngine.java:227)
   at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.buildNewRouteProgress(NavigationEngine.java:161)
   at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleRequest(NavigationEngine.java:96)
   at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine.handleMessage(NavigationEngine.java:62)
   at android.os.Handler.dispatchMessage(Handler.java:98)
   at android.os.Looper.loop(Looper.java:158)
   at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by danesfeder** [comment]
Hey @gonzalt03, good catch here.  This was a regression introduced by #773 and we added a fix in #784 (not yet released).  Sorry for the inconvenience here and thank you for your patience and submitting this issue.

**Comment by excapade** [comment]
Hi there,
I am currently building my mobile app and have the same issue as stated by gonzalt03. In reference to #784 which you said was not released, has this fix been released now?

Thanks.

**Comment by FullDeveloper917** [comment]
When is this problem resolved?
