### ISSUE TITLE
IllegalArgumentException thrown using NavigationCamera

### ISSUE THREAD

**Issue by vicobz** [mapbox/mapbox-navigation-android#826]
**Android API:** Oreo 8.0.0

**Mapbox SDK versions:**
`mapbox-android-sdk:5.5.0`
`mapbox-android-plugin-locationlayer:0.4.0`
`mapbox-sdk-services:3.0.1`
`mapbox-sdk-services:3.0.1`
`mapbox-android-navigation:0.12.0`
`mapbox-android-navigation-ui:0.12.0`

### Steps to trigger behavior

Try to use a NavigationCamera object like this:

```mapboxNavigation.setLocationEngine(locationEngine);
      navigationCamera = new NavigationCamera(mapboxMap, mapboxNavigation);
      mapboxNavigation.startNavigation(route);
      navigationCamera.start(route);
      navigationCamera.setCameraTrackingLocation(true);
      locationPlugin.setLocationLayerEnabled(LocationLayerMode.NAVIGATION); 
```

### Expected behavior
The `NavigationCamera` object smoothly handles camera updates.

### Actual behavior

An `IllegalArgumentException` is thrown, leading app to crash:

```
java.lang.IllegalArgumentException: Null duration passed into easeCamera
        at com.mapbox.mapboxsdk.maps.MapboxMap.easeCamera(MapboxMap.java:836)
        at com.mapbox.mapboxsdk.maps.MapboxMap.easeCamera(MapboxMap.java:807)
        at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.easeMapCameraPosition(NavigationCamera.java:191)
        at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.animateCameraFromLocation(NavigationCamera.java:258)
        at com.mapbox.services.android.navigation.ui.v5.camera.NavigationCamera.onProgressChange(NavigationCamera.java:102)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEventDispatcher.onProgressChange(NavigationEventDispatcher.java:156)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onNewRouteProgress(NavigationService.java:117)
        at com.mapbox.services.android.navigation.v5.navigation.NavigationEngine$1.run(NavigationEngine.java:91)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6809)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
 ```

It seems the exception is thrown consistently when `navigationCamera.onProgressChange(location, routeProgress)` is called from `onProgressChange(Location location, RouteProgress routeProgress)` callback.

**Comment by danesfeder** [comment]
Hey @vicobz thanks for the report!  Just some clarification:

> It seems the exception is thrown when `navigationCamera.onProgressChange(location, routeProgress)` is called from `onProgressChange(Location location, RouteProgress routeProgress)` callback

Are you calling `NavigationCamera#onProgressChange` in your own `ProgressChangeListener`? 
```
public void onProgressChange(Location location, RouteProgress routeProgress) {
    navigationCamera.onProgressChange(location, routeProgress);
}
```

Or is that code snippet you posted the only code you have for the camera currently?

**Comment by vicobz** [comment]
Hi @danesfeder, thanks for your quick reply!

Actually yes, I'm calling `NavigationCamera#onProgressChange` in my own `ProgressChangeListener` as you mentioned in your code snippet.

**Comment by danesfeder** [comment]
@vicobz Yeah this is unclear, because `onProgressChange` is `public`, but you actually don't need to call this within your own listener.  After the initial animation finishes (or is cancelled), we add one automatically and start listening to updates within the class itself.  I updated `NavigationCamera` with #828 to make this more clear. 

To fix your code, you should only need to remove the camera listener code.

**Comment by vicobz** [comment]
@danesfeder Thank you for the clarification, I actually thought I was in charge of sending updates to the `NavigationCamera`. I should have read more from the Navigation SDK "internal code", though the `public` attribute of `NavigationCamera#onProgressChange` method can be confusing as you said :)
