### ISSUE TITLE
Cannot initiate walking/cycling. 

### ISSUE THREAD

**Issue by excapade** [mapbox/mapbox-navigation-android#855]
**Android API:**
Using android version 6.0.1. ZTE phone and Samsung.
**Mapbox Navigation SDK version:**
0.12.0

### Steps to trigger behavior. 
For example we press the walking navigation button.
So, we get the start location and end location from the user. We also pass the direction mode as "walking" since thats what selected. We then pass those information of the result based on walking in
![issue](https://user-images.githubusercontent.com/10036883/38645133-96425aca-3da8-11e8-910e-0452b05a53a4.gif)
to mapbox class.
See code below:

public String get_direction_profile() {
        if (tab_position == 0) {
            return DirectionsCriteria.PROFILE_DRIVING_TRAFFIC;
        } else if (tab_position == 1) {
            return DirectionsCriteria.PROFILE_DRIVING_TRAFFIC;
        } else if (tab_position == 2) {
            return DirectionsCriteria.PROFILE_CYCLING;
        } else if (tab_position == 3) {
            return DirectionsCriteria.PROFILE_WALKING;
        }
        return DirectionsCriteria.PROFILE_DRIVING_TRAFFIC;
    }

 1. Based on the selected medium i.e cycling/walking

### Expected behavior
When a user click on the walk or the cycling button, it should take the user to the nav screen and provide directions and so on. This worked in 0.11.0 version.

### Actual behavior
After moving to 0.12.0,  when we initiate the walking feature it gets stuck

**Comment by danesfeder** [comment]
Hey @excapade can you try `0.12.0-SNAPSHOT` and see if your issue is resolved?  I'm pretty sure #829 was the fix needed here.

**Comment by excapade** [comment]
Hi @danesfeder,
We tried running the simulated mode to see if we can produce the issue and we got this error:

W/BindingContextFactory: Failed to complete your request. 
    com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.mapbox.api.directions.v5.models.AutoValue_DirectionsError$GsonTypeAdapter.read(AutoValue_DirectionsError.java:43)
        at com.mapbox.api.directions.v5.models.AutoValue_DirectionsError$GsonTypeAdapter.read(AutoValue_DirectionsError.java:23)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
        at com.mapbox.api.directions.v5.MapboxDirections.errorDidOccur(MapboxDirections.java:190)
        at com.mapbox.api.directions.v5.MapboxDirections.access$000(MapboxDirections.java:60)
        at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:144)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5318)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

this is error i got when i try to initiate cycling navigation its just spinning and not stopping spinning. Just same symptoms as described initially.

We also tried the 0.12.0-SNAPSHOT suggestion but got an error as well

Failed to resolve: com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.12.0-SNAPSHOT
Failed to resolve: com.mapbox.mapboxsdk:mapbox-android-navigation:0.12.0-SNAPSHOT
 
Any other suggestions will be helpful. Since this is the only setback holding us from moving our product to Beta.

Thanks

**Comment by Guardiola31337** [comment]
Hey @excapade 👋 Thank you for the detailed info.

Following you can find installation instructions for `SNAPSHOT`s:

```java
repositories {
    jcenter()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    // ...
}

dependencies {
    // ...
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.12.0-SNAPSHOT'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.12.0-SNAPSHOT'
    // ...
}
```

> Also, are you using `NavigationLauncher`? If so, are you using an origin + destination, or a prefetched route?

☝️ refers to https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#launch-the-navigation-ui so, how are you launching the Navigation UI? Using `NavigationLauncher`?

**Comment by excapade** [comment]
HI @Guardiola31337 I will work on the installation. 
Yes we are using NavigationLauncher. See below:

 compile('com.mapbox.mapboxsdk:mapbox-android-sdk:5.5.1') {
        transitive = true
    }
    compile 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.12.0'
    compile 'com.mapbox.mapboxsdk:mapbox-android-plugin-traffic:0.4.0'
    compile('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.12.0') {
        transitive = true
    }

NavigationRoute.builder()
                    .accessToken(Mapbox.getAccessToken())
                    .origin(origin)
                    .profile(get_direction_profile())
                    .destination(destination)
                    .exclude(is_tollway_include_in_navigation())
                    .build()
                    .getRoute(new Callback() {
                        @Override
                        public void onResponse(Call call, retrofit2.Response response) {
                            try {
                                Log.d(Appkeyutil.Tag, "Response code: " + response.code());
                                if (response.body() == null) {
                                    Log.e(Appkeyutil.Tag, "No routes found, make sure you set the right user and access token.");
                                    return;
                                } else if (response.body().routes().size() < 1) {
                                    Log.e(Appkeyutil.Tag, "No routes found");
                                    return;
                                }
                                String awsPoolId = null;
                                boolean simulateRoute = false;
                                final DirectionsRoute currentRoute = response.body().routes().get(0);
                                **NavigationLauncher**Options navigationLauncherOptions=new NavigationLauncherOptions() {
                                    @Nullable
                                    @Override
                                    public Locale locale() {
                                        return null;
                                    }

                                    @Nullable
                                    @Override
                                    public Integer unitType() {
                                        return null;
                                    }

                                    @Override
                                    public boolean enableOffRouteDetection() {
                                        return false;
                                    }

                                    @Nullable
                                    @Override
                                    public DirectionsRoute directionsRoute() {
                                        return currentRoute;
                                    }

                                    @Nullable
                                    @Override
                                    public String directionsProfile() {
                                        return null;
                                    }

                                    @Nullable
                                    @Override
                                    public Point origin() {
                                        return origin;
                                    }

                                    @Nullable
                                    @Override
                                    public Point destination() {
                                        return destination;
                                    }

                                    @Nullable
                                    @Override
                                    public String awsPoolId() {
                                        return null;
                                    }

                                    @Nullable
                                    @Override
                                    public Integer lightThemeResId() {
                                        return helper.setMapboxTheme(tab_position);
                                    }

                                    @Nullable
                                    @Override
                                    public Integer darkThemeResId() {
                                        return null;
                                    }

                                    @Override
                                    public boolean shouldSimulateRoute() {
                                        return false;
                                    }
                                };
                                **NavigationLauncher.startNavigation(getActivity(),navigationLauncherOptions);**
                            } catch (Exception e) {
                            }
                        }

                        @Override
                        public void onFailure(Call call, Throwable throwable) {
                            //Log.e(Appkeyutil.Tag, "Error: " + throwable.getMessage());
                        }
                    });



// i am using same fragment in different position 
// 1==car
//2 =bus/train
//3= cycling
//4=walking
public String get_direction_profile() {
        if (tab_position == 0) {
            return DirectionsCriteria.PROFILE_DRIVING_TRAFFIC;
        } else if (tab_position == 1) {
            return DirectionsCriteria.PROFILE_DRIVING_TRAFFIC;
        } else if (tab_position == 2) {
            return DirectionsCriteria.PROFILE_CYCLING;
        } else if (tab_position == 3) {
            return DirectionsCriteria.PROFILE_WALKING;
        }
        return "";
    }
 
public String is_tollway_include_in_navigation(){
        if (helper.loadPreferences_boolean(Appkeyword.is_tollway_include_in_navigation)){
            return "";
        }else {
            return com.mapbox.api.directions.v5.DirectionsCriteria.EXCLUDE_TOLL;
        }
    }
Thanks.

**Comment by danesfeder** [comment]
Using:
```    
NavigationLauncherOptions.Builder optionsBuilder = NavigationLauncherOptions.builder()
      .directionsProfile(DirectionsCriteria.PROFILE_CYCLING)
      .origin(currentLocation)
      .destination(destination);

    NavigationLauncher.startNavigation(this, optionsBuilder.build());
```


I was able to launch the UI successfully - maybe it's an issue with the `Point`s you are passing in.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8434572/38697129-176eb236-3e5f-11e8-98ef-083ec64daeae.gif)

**Comment by excapade** [comment]
HI @danesfeder, thanks, i will go through and try your suggestion.

Thanks.

**Comment by excapade** [comment]
hi @danesfeder @Guardiola31337 ,
We successfully have SNAPSHOT working and in some mobile devices launching cycling and walking per your NavitionLauncherOptions works, but not on others.
Devices:
Device launch navigation successfuuly:
MOTO G3  android version 6.0
Nexus 5    android version 6.0

issue device:
VIVO Y51L  android version 5.0.2
ZTE Z981 android version 6.0


 Here is the error code:

W/BindingContextFactory: Failed to complete your request. 
    com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1568)
        at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1409)
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:593)
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
        at com.mapbox.api.directions.v5.models.AutoValue_DirectionsError$GsonTypeAdapter.read(AutoValue_DirectionsError.java:43)
        at com.mapbox.api.directions.v5.models.AutoValue_DirectionsError$GsonTypeAdapter.read(AutoValue_DirectionsError.java:23)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
        at com.mapbox.api.directions.v5.MapboxDirections.errorDidOccur(MapboxDirections.java:190)
        at com.mapbox.api.directions.v5.MapboxDirections.access$000(MapboxDirections.java:60)
        at com.mapbox.api.directions.v5.MapboxDirections$1.onResponse(MapboxDirections.java:144)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5318)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

thanks

**Comment by excapade** [comment]
Hi,
We found the issue. we had toll way enabled for all the navigation mode and once we disable it for cycling and walking it all worked. 
Thanks again for your feedback and support.

**Comment by bluckThakkar** [comment]
Hello,
Thanks a lot to @danesfeder   for your answer its helpful to did my task easily,

could you please help to find out realtime distance & duration from NavigationLauncherOptions /navigationView.

It will be great help for me 

Thanks in Advance
