### ISSUE TITLE
ExceptionInitializerError crash

### ISSUE THREAD

**Issue by vladgheorghe** [mapbox/mapbox-navigation-android#901]
Sometimes the app crashes randomly with the following stracktrace

```
 Process: ro.ascendnet.android.startaxi.taximetrist, PID: 4001
                                                                                         java.lang.ExceptionInInitializerError
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30)
                                                                                             at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49)
                                                                                             at ro.ascendnet.android.startaxi.taximetrist.core.Driver.onCreate(Driver.java:34)
                                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120)
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747)
                                                                                             at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                             at android.os.Looper.loop(Looper.java:164)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6501)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                                          Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=ro.ascendnet.android.startaxi.taximetrist/com.mapbox.android.telemetry.TelemetryService }: app is in background uid UidRecord{4f69d22 u0a197 SVC  idle change:idle|uncached procs:1 seq(0,0,0)}
                                                                                             at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
                                                                                             at android.app.ContextImpl.startService(ContextImpl.java:1477)
                                                                                             at android.content.ContextWrapper.startService(ContextWrapper.java:650)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.startLocation(MapboxTelemetry.java:490)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetryService(MapboxTelemetry.java:226)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.optLocationIn(MapboxTelemetry.java:197)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.startTelemetry(MapboxTelemetry.java:461)
                                                                                             at com.mapbox.android.telemetry.MapboxTelemetry.enable(MapboxTelemetry.java:136)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:25)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.<init>(Telemetry.java:10)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.<clinit>(Telemetry.java:42)
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry$TelemetryHolder.access$000(Telemetry.java:41) 
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.obtainTelemetry(Telemetry.java:46) 
                                                                                             at com.mapbox.mapboxsdk.maps.Telemetry.initialize(Telemetry.java:30) 
                                                                                             at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:49) 
                                                                                             at ro.ascendnet.android.startaxi.taximetrist.core.Driver.onCreate(Driver.java:34) 
                                                                                             at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1120) 
                                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5747) 
                                                                                             at android.app.ActivityThread.-wrap1(Unknown Source:0) 
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                             at android.os.Looper.loop(Looper.java:164) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6501) 
                                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                                             at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

**Comment by danesfeder** [comment]
Hey @vladgheorghe, thanks for the feedback here. 

@Guardiola31337 @electrostat can either of you take a look at this when you have a chance?

**Comment by Guardiola31337** [comment]
Thanks for reporting this issue @vladgheorghe 
Following up in https://github.com/mapbox/mapbox-events-android/issues/129.

cc @electrostat @danesfeder
