### ISSUE TITLE
NullReferenceException in NavigationService

### ISSUE THREAD

**Issue by richjhart** [mapbox/mapbox-navigation-android#915]
**Android API:** Android 8.1
**Mapbox Navigation SDK version:** Navigation Library 0.13.0

### Steps to trigger behavior

At this stage, unsure what triggered it, but I've seen it more than once. It might be if startNavigation() is never called (in which case the service will never set the mapboxNavigation object)

### Actual behavior

```
05-04 11:12:56.372 2401-2401/com.bynd.looper E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bynd.looper, PID: 2401
    java.lang.RuntimeException: Unable to stop service com.mapbox.services.android.navigation.v5.navigation.NavigationService@bf2966d: java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationOptions com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.options()' on a null object reference
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3735)
        at android.app.ActivityThread.-wrap30(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1741)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.mapbox.services.android.navigation.v5.navigation.MapboxNavigationOptions com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.options()' on a null object reference
        at com.mapbox.services.android.navigation.v5.navigation.NavigationService.onDestroy(NavigationService.java:85)
        at android.app.ActivityThread.handleStopService(ActivityThread.java:3718)
        at android.app.ActivityThread.-wrap30(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1741) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6682) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 
```

**Comment by Guardiola31337** [comment]
Hey @richjhart 👋 thanks for reaching out and report your issue.

Could you add some more information for reproducing the `NullPointerException` (minimal example) or any other specifics around your test setup? Do you have some more information on used device? If there is any sample or pseudo code you can provide that would be really helpful.
