### ISSUE TITLE
MapboxSpeechPlayer NullPointerException File#getPath() 

### ISSUE THREAD

**Issue by danesfeder** [mapbox/mapbox-navigation-android#921]
```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String java.io.File.getPath()' on a null object reference
com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.playInstruction (MapboxSpeechPlayer.java:168)
com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.playInstructionIfUpNext (MapboxSpeechPlayer.java:264)
com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer.access$300 (MapboxSpeechPlayer.java:29)
com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer$4.onFinishedDownloading (MapboxSpeechPlayer.java:249)
com.mapbox.services.android.navigation.ui.v5.voice.InstructionDownloadTask.onPostExecute (InstructionDownloadTask.java:76)
com.mapbox.services.android.navigation.ui.v5.voice.InstructionDownloadTask.onPostExecute (InstructionDownloadTask.java:13)
```

**Comment by Guardiola31337** [comment]
Run into a related crash 💥

```
05-14 16:32:19.997 17780-17780/com.mapbox.services.android.navigation.testapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                Process: com.mapbox.services.android.navigation.testapp, PID: 17780
                                                                                                java.lang.NullPointerException
                                                                                                    at java.util.concurrent.ConcurrentLinkedQueue.checkNotNull(ConcurrentLinkedQueue.java:773)
                                                                                                    at java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:295)
                                                                                                    at java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:265)
                                                                                                    at com.mapbox.services.android.navigation.ui.v5.voice.MapboxSpeechPlayer$4.onFinishedDownloading(MapboxSpeechPlayer.java:250)
                                                                                                    at com.mapbox.services.android.navigation.ui.v5.voice.InstructionDownloadTask.onPostExecute(InstructionDownloadTask.java:76)
                                                                                                    at com.mapbox.services.android.navigation.ui.v5.voice.InstructionDownloadTask.onPostExecute(InstructionDownloadTask.java:13)
                                                                                                    at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                                                    at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                                                    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                    at android.os.Looper.loop(Looper.java:135)
                                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)
05-14 16:32:20.019 18185-18185/? E/PlayCommon: [1] MetalogHelper.<init>: Failed to restore PlayMetalog
05-14 16:32:20.019 18185-18185/? E/PlayCommon: [1] MetalogHelper.<init>: Failed to restore LogsUploadAttempt
```

`master`
Moto X (2nd gen) - Android 5.0

cc @devotaaabel
