### ISSUE TITLE
NPE in night mode in OnMapChangedListener: Attempt to invoke virtual method '...addProgressChangeListener' on a null object reference

### ISSUE THREAD

**Issue by wbearand** [mapbox/mapbox-navigation-android#956]
I am using a modified version of the WaypointNavigationActivity of the mapbox-navigation-android samples, and i see abovementioned NPE if i start a navigation at night after a fresh app start. The navigationview is then not fully loaded. Cancelling and retrying works though without NPE. Also everything works as expected if navigation is started during the day / "with day styling". 

Mapbox Navigation SDK version: 0.13.0

LOG:

E/NativeMapView: Exception in MapView.OnMapChangedListener
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.addProgressChangeListener(com.mapbox.services.android.navigation.v5.routeprogress.ProgressChangeListener)' on a null object reference
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewEventDispatcher.assignProgressChangeListner(NavigationViewEventDispatcher.java:140)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewEventDispatcher.initializeListeners(NavigationViewEventDispatcher.java:38)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initNavigationListeners(NavigationView.java:570)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:376)
        at com...........................ui.WaypointNavigationActivity.onNavigationReady(WaypointNavigationActivity.java:184)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView$1.onStyleLoaded(NavigationView.java:226)
        at com.mapbox.mapboxsdk.maps.MapboxMap$1.onMapChanged(MapboxMap.java:988)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:873)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by Guardiola31337** [comment]
Hey @wbearand 👋 thanks for reaching out and report your problem.

I guess this should be fixed now (https://github.com/mapbox/mapbox-navigation-android/pull/946 landed last week) and it'll be available in the next release. In the meantime, could you please retest this using `0.14.0-SNAPSHOT` and report back if it's still an issue?

Following you can find installation instructions for `SNAPSHOT`s:

```java
repositories {
    jcenter()
    maven { url "http://oss.sonatype.org/content/repositories/snapshots/" }
    // ...
}

dependencies {
    // ...
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.14.0-SNAPSHOT'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.14.0-SNAPSHOT'
    // ...
}
```

> I am using a modified version of the WaypointNavigationActivity of the mapbox-navigation-android samples

BTW, do you mind sharing a snippet of your `WaypointNavigationActivity` version giving us insight into your implementation?

**Comment by danesfeder** [comment]
Thanks for bringing this to us @wbearand - confirming that this should be fixed with #946.  Please feel free to re-open if you still experience this issue.

**Comment by wbearand** [comment]
Tried it now with the 0.14.0 snapshot, seems to be fixed now as you suspected!

In my version of the WaypointNavigationActivity, i did not change much, just added TextToSpeech and tried to add custom voice instruction (which of course is not optimal because it is not in the same queue as the "real" instructions => might overlap).

**Comment by Guardiola31337** [comment]
@wbearand 
> Tried it now with the 0.14.0 snapshot, seems to be fixed now as you suspected!

Glad to hear, thanks for the update!
