### ISSUE TITLE
Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView

### ISSUE THREAD

**Issue by franshua** [mapbox/mapbox-navigation-android#966]
Updated from 0.12.0 to 0.13.0 version and changed only minimal code:

`  @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setTheme(R.style.Theme_AppCompat_NoActionBar);
        setContentView(R.layout.activity_navigation);
        Mapbox.getInstance(this, getString(R.string.mapbox_api_key));

        mNavigationView = findViewById(R.id.navigationView);
        mNavigationView.onCreate(savedInstanceState);
        mNavigationView.initialize(this);
    }`

Logcat:

`05-23 16:58:56.975 28618-28618/com.app.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.dev, PID: 28618
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.dev/com.app.navigator.DirectionsNavigator}: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3255)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
        at android.app.ActivityThread.access$1100(ActivityThread.java:222)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7230)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: android.view.InflateException: Binary XML file line #8: Binary XML file line #8: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
        at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.app.navigator.DirectionsNavigator.onCreate(DirectionsNavigator.java:32)
        at android.app.Activity.performCreate(Activity.java:6877)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208)`

**Android API: 23
**Mapbox Navigation SDK version: 0.13.0

### Steps to trigger behavior

 1. Only open Activity and setContentView throws the exception

**Comment by danesfeder** [comment]
Hey @franshua, it looks like from your code snippet you are setting your access token after inflating the `NavigationView`.  Because the `NavigationView` uses a `MapView` and initializes it behind the scenes, this needs to be set before `setContentView`

I reproduced the same scenario and saw this at the end of my stacktrace:
```
Using MapView requires setting a valid access token. Use Mapbox.getInstance(Context context, String accessToken) to provide one. 
    Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
    More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
        at com.mapbox.mapboxsdk.Mapbox.validateMapbox(Mapbox.java:77)
        at com.mapbox.mapboxsdk.Mapbox.getAccessToken(Mapbox.java:67)
        at com.mapbox.services.android.navigation.ui.v5.NavigationViewModel.<init>(NavigationViewModel.java:76)
```

Thanks for checking out the SDK!

**Comment by Jamali-MohammadReza** [comment]
I have same problem and not solved by your point

**Comment by Ambi1709** [comment]
2021-06-12 14:57:34.899 11651-11651/com.harman.predictivemap D/AndroidRuntime: Shutting down VM
2021-06-12 14:57:34.900 11651-11651/com.harman.predictivemap E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.harman.predictivemap, PID: 11651
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.harman.predictivemap/com.harman.predictivemap.Navigation}: android.view.InflateException: Binary XML file line #14 in com.harman.predictivemap:layout/activity_main2: Binary XML file line #14 in com.harman.predictivemap:layout/activity_main2: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #14 in com.harman.predictivemap:layout/activity_main2: Binary XML file line #14 in com.harman.predictivemap:layout/activity_main2: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
     Caused by: android.view.InflateException: Binary XML file line #14 in com.harman.predictivemap:layout/activity_main2: Error inflating class com.mapbox.services.android.navigation.ui.v5.NavigationView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.harman.predictivemap.Navigation.onCreate(Navigation.java:59)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2021-06-12 14:57:34.901 11651-11651/com.harman.predictivemap E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #24 in com.harman.predictivemap:layout/navigation_view_layout: Binary XML file line #24 in com.harman.predictivemap:layout/navigation_view_layout: Error inflating class com.mapbox.services.android.navigation.ui.v5.summary.SummaryBottomSheet
     Caused by: android.view.InflateException: Binary XML file line #24 in com.harman.predictivemap:layout/navigation_view_layout: Error inflating class com.mapbox.services.android.navigation.ui.v5.summary.SummaryBottomSheet
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at android.view.View.inflate(View.java:25757)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeView(NavigationView.java:510)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.<init>(NavigationView.java:106)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.<init>(NavigationView.java:100)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.harman.predictivemap.Navigation.onCreate(Navigation.java:59)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2021-06-12 14:57:34.901 11651-11651/com.harman.predictivemap E/AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #8 in com.harman.predictivemap:layout/summary_bottomsheet_layout: Binary XML file line #2 in com.harman.predictivemap:layout/summary_peek_layout: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #2 in com.harman.predictivemap:layout/summary_peek_layout: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1233)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1263)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1119)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at android.view.View.inflate(View.java:25757)
        at com.mapbox.services.android.navigation.ui.v5.summary.SummaryBottomSheet.initialize(SummaryBottomSheet.java:193)
        at com.mapbox.services.android.navigation.ui.v5.summary.SummaryBottomSheet.<init>(SummaryBottomSheet.java:63)
        at com.mapbox.services.android.navigation.ui.v5.summary.SummaryBottomSheet.<init>(SummaryBottomSheet.java:58)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at android.view.View.inflate(View.java:25757)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.initializeView(NavigationView.java:510)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.<init>(NavigationView.java:106)
        at com.mapbox.services.android.navigation.ui.v5.NavigationView.<init>(NavigationView.java:100)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
        at com.harman.predictivemap.Navigation.onCreate(Navigation.java:59)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
2021-06-12 14:57:34.901 11651-11651/com.harman.predictivemap E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x7f030242 a=-1}
        at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:996)
        at android.content.res.TypedArray.getDrawable(TypedArray.java:980)
        at android.view.View.<init>(View.java:5269)
        at android.view.ViewGroup.<init>(ViewGroup.java:675)
        at android.view.ViewGroup.<init>(ViewGroup.java:671)
        at android.view.ViewGroup.<init>(ViewGroup.java:667)
        at androidx.constraintlayout.widget.ConstraintLayout.<init>(ConstraintLayout.java:568)
        	... 61 more

**Comment by Ambi1709** [comment]
Facing same issue, any one found the solution to this?

**Comment by franshua** [comment]
> Facing same issue, any one found the solution to this?

Sorry I cannot help you, I resolved this with @danesfeder comment.

**Comment by franshua** [comment]
> Facing same issue, any one found the solution to this?

Sorry I cannot help you, I resolved this with @danesfeder comment.
