### ISSUE TITLE
NullPointer on screen rotation

### ISSUE THREAD

**Issue by kozyr** [mapbox/mapbox-navigation-android#978]
**Android API:**
27
 
**Mapbox Navigation SDK version:**
0.13

### Steps to trigger behavior

 1. Load embedded NavigationView via initialize() call
 2. On callback, start navigation with a route and a progress listener
```
        NavigationViewOptions.Builder options = NavigationViewOptions.builder();
        options.navigationListener(this);
        options.directionsRoute(myRoute);
        options.shouldSimulateRoute(false);
        options.directionsProfile("driving");
        options.routeListener(this);
        options.navigationOptions(MapboxNavigationOptions.builder()
                .locale(Locale.US)
                .enableNotification(false)
                .build());
        options.progressChangeListener(this);

        navigationView.startNavigation(options.build());
```
 3. Rotate the screen right after, which results in this NullPointer

```
                      java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.services.android.navigation.v5.navigation.MapboxNavigation.addProgressChangeListener(com.mapbox.services.android.navigation.v5.routeprogress.ProgressChangeListener)' on a null object reference
                          at com.mapbox.services.android.navigation.ui.v5.NavigationViewEventDispatcher.assignProgressChangeListner(NavigationViewEventDispatcher.java:140)
                          at com.mapbox.services.android.navigation.ui.v5.NavigationViewEventDispatcher.initializeListeners(NavigationViewEventDispatcher.java:38)
                          at com.mapbox.services.android.navigation.ui.v5.NavigationView.initNavigationListeners(NavigationView.java:570)
                          at com.mapbox.services.android.navigation.ui.v5.NavigationView.startNavigation(NavigationView.java:376)
```

**Comment by kozyr** [comment]
Fixed the issue by updating to 0.14.0-SNAPSHOT. I also saw the warning about mapbox location layer missing which seemed to be resolved in the latest commits. Any word on when 0.14 will come out?
