### ISSUE TITLE
Fatal Exception

### ISSUE THREAD

**Issue by gmorenope** [mapbox/mapbox-navigation-android#998]
Hi, I follow this exmple:

https://www.mapbox.com/help/android-navigation-sdk/

All is ok until I push the button Start Navigation, In debug console I get this error:

E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NoSuchFieldError: com.mapbox.services.android.navigation.ui.v5.R$id.navigationView
                      at com.mapbox.services.android.navigation.ui.v5.NavigationActivity.onCreate(NavigationActivity.java:38)
                      at android.app.Activity.performCreate(Activity.java:5326)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2225)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2316)
                      at android.app.ActivityThread.access$700(ActivityThread.java:158)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1296)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:176)
                      at android.app.ActivityThread.main(ActivityThread.java:5365)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                      at dalvik.system.NativeStart.main(Native Method)
 
This is my build.gradle file:

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.example.gabi.mapboxnavigation"
        minSdkVersion 17
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}
repositories {
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.1'
    implementation 'com.android.support:design:27.1.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-locationlayer:0.5.3'

    implementation ('com.mapbox.mapboxsdk:mapbox-android-sdk:6.1.3@aar') {
        transitive=true
    }
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation:0.13.0'
    implementation ('com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.13.0') {
        transitive = true
    }
}

Thank you

**Android API:**
**Mapbox Navigation SDK version:**

### Steps to trigger behavior

 1.
 2.
 3.

### Expected behavior
Start navigation
### Actual behavior
Stop app and error message in debug console

**Comment by danesfeder** [comment]
Hey @gmorenope, can you rename the `Activity` you created in this example (`NavigationActivity`) to something like `MyNavigationActivity`?  Does this help?

**Comment by gmorenope** [comment]
Hi @danesfeder, yes, it was the solution, thanks you very much!
